package com.tencent.mobileqq.app;

import android.os.Environment;
import com.tencent.common.app.BaseApplicationImpl;
import java.io.File;

public abstract interface AppConstants
{
  public static final long A = 9984L;
  public static final long B = 9983L;
  public static final String B = "sc.account.info.update";
  public static final long C = 9982L;
  public static final String C = "mobileQQi";
  public static final long D = 9981L;
  public static final String D = "statistic";
  public static final long E = 9980L;
  public static final String E = "share";
  public static final long F = 9979L;
  public static final String F = "screen_shot";
  public static final long G = 1000L;
  public static final String G = "history_chat_msg_search_key";
  public static final long H = 2592000000L;
  public static final String H = "free_call";
  public static final long I = 160L;
  public static final String I = "aio_plus_panel_red_point";
  public static final long J = 19922944L;
  public static final String J = "troop_new_guid";
  public static final long K = 19922944L;
  public static final String K = "local_html";
  public static final long L = 4294967295L;
  public static final String L = String.valueOf(2068467417L);
  public static final String M = String.valueOf(9990L);
  public static final String N = String.valueOf(9991L);
  public static final String O = String.valueOf(9992L);
  public static final String P = String.valueOf(9993L);
  public static final String Q = String.valueOf(9994L);
  public static final String R = String.valueOf(9995L);
  public static final String S = String.valueOf(9996L);
  public static final String T = String.valueOf(9997L);
  public static final String U = String.valueOf(9998L);
  public static final String V = String.valueOf(9999L);
  public static final String W = String.valueOf(10000L);
  public static final String X = String.valueOf(9989L);
  public static final String Y = String.valueOf(9988L);
  public static final String Z = String.valueOf(9987L);
  public static final String aA;
  public static final String aB;
  public static final String aC;
  public static final String aD;
  public static final String aE = "head/_hd/";
  public static final String aF = "head/_thd/";
  public static final String aG = ".emotionsm/";
  public static final String aH = ".emoQFace/";
  public static final String aI = ".pendant/";
  public static final String aJ;
  public static final String aK;
  public static final String aL;
  public static final String aM;
  public static final String aN;
  public static final String aO;
  public static final String aP;
  public static final String aQ;
  public static final int aR = -1001;
  public static final String aR = "custom_background/";
  public static final int aS = -1002;
  public static final String aS = "diskcache";
  public static final int aT = -1003;
  public static final String aT;
  public static final int aU = -1004;
  public static final String aU;
  public static final int aV = -1005;
  public static final String aV;
  public static final int aW = -1006;
  public static final String aW;
  public static final int aX = -1007;
  public static final String aX = "QQThemePkg";
  public static final int aY = -1;
  public static final String aY;
  public static final int aZ = -1008;
  public static final String aZ;
  public static final String aa = String.valueOf(9986L);
  public static final String ab = String.valueOf(9985L);
  public static final String ac = String.valueOf(9984L);
  public static final String ad = String.valueOf(9983L);
  public static final String ae = String.valueOf(9982L);
  public static final String af = String.valueOf(9981L);
  public static final String ag = String.valueOf(9980L);
  public static final String ah = String.valueOf(9979L);
  public static final String ai = "mobileqq.service";
  public static final String aj = "qcenter.service";
  public static final String ak = "/data/media/";
  public static final String al = Environment.getExternalStorageDirectory().getAbsolutePath();
  public static final String am = "/mnt/extSdCard/";
  public static final String an = al + "/Tencent/MobileQQi/";
  public static final String ao = an + "log/";
  public static final String ap = al + "/Tencent/QQi_Images/";
  public static final String aq = al + "/Tencent/QQi_Favorite/";
  public static final String ar = al + "/Tencent/QQi_Collection/";
  public static final String as = al + "/Tencent/QQifile_recv/";
  public static final String at = al + "/Tencent/QQifile_recv/.thumbnails/";
  public static final String au = al + "/Tencent/QQifile_recv/.tmp/";
  public static final String av = al + "/Tencent/QQifile_recv/.trooptmp/";
  public static final String aw = al + "/Tencent/QQi_Secretfile/";
  public static final String ax = "/sdcard/Android/data/com.tencent.mobileqqi/files/";
  public static final String ay;
  public static final String az = "head/";
  public static final String bA = "notifcation_taget";
  public static final String bB = "qqsetting_sharedpref";
  public static final String bC = "qqsetting_notify_icon_key";
  public static final String bD = "qqsetting_auto_receive_pic_key";
  public static final String bE = "qqsetting_auto_receive_magic_face_key";
  public static final String bF = "qqsetting_receivemsg_whenexit_key";
  public static final String bG = "qqsetting_lock_screen_whenexit_key";
  public static final String bH = "qqsetting_notify_showcontent_key";
  public static final String bI = "qqsetting_nodisturb_mode_key";
  public static final String bJ = "qqsetting_notify_blncontrol_key";
  public static final String bK = "qqsetting_notify_myfeedpush_key";
  public static final String bL = "qqsetting_musicgene_canshow_key";
  public static final String bM = "qqsetting_musicgene_exist_key";
  public static final String bN = "qqsetting_bothonline_key";
  public static final String bO = "qqsetting_security_scan_key";
  public static final String bP = "qqsetting_notify_soundtype_key";
  public static final String bQ = "qqsetting_screenshot_key";
  public static final String bR = "qqsetting_enter_sendmsg_key";
  public static final String bS = "qqsetting_all_contacts_key";
  public static final String bT = "qqsetting_msg_lockscreen_key";
  public static final String bU = "picCu";
  public static final String bV = "picCd";
  public static final String bW = "picGu";
  public static final String bX = "picGd";
  public static final String bY = "picDu";
  public static final String bZ = "picDd";
  public static final int ba = 0;
  public static final String ba;
  public static final int bb = 1;
  public static final String bb;
  public static final int bc = 2;
  public static final String bc;
  public static final int bd = 500;
  public static final String bd = "QQThemePkgConfig.xml";
  public static final int be = 1;
  public static final String be;
  public static final int bf = 2;
  public static final String bf;
  public static final int bg = 40;
  public static final String bg = "mobileqq_theme";
  public static final int bh = 90;
  public static final String bh = "using_theme_res";
  public static final int bi = 20;
  public static final String bi = ".emtion_urldrawable";
  public static final int bj = 5;
  public static final String bj = "uniform_background.jpg";
  public static final int bk = 5;
  public static final String bk;
  public static final int bl = 4;
  public static final String bl;
  public static final int bm = 3;
  public static final String bm;
  public static final String bn = "mobileqq.web";
  public static final String bo = "http://maps.google.com/maps?q=";
  public static final String bp;
  public static final String bq;
  public static final String br;
  public static final String bs = "none";
  public static final String bt = "null";
  public static final String bu = "chat_backgournd_nickname_color.";
  public static final String bv = "2010741172";
  public static final String bw = "raw_photo";
  public static final String bx = "raw_photo_4_test";
  public static final String by = "plugin_is_show_mengban";
  public static final String bz = "start_from_notification";
  public static final boolean c = false;
  public static final String ca = "pttCu";
  public static final String cb = "pttCd";
  public static final String cc = "pttGu";
  public static final String cd = "pttGd";
  public static final String ce = "pttDu";
  public static final String cf = "pttDd";
  public static final String cg = "qzPicd";
  public static final String ch = "qzPicu";
  public static final String ci = "qzEmod";
  public static final String cj = "qzFsPicd";
  public static final String ck = "qzCvPicd";
  public static final String cl = "qzBigPicd";
  public static final String cm = "qzSignPicd";
  public static final String cn = "saPicbd";
  public static final String co = "10000512";
  public static final boolean d = false;
  public static final long e = 9223372036854775805L;
  public static final long f = 9223372036854775806L;
  public static final long g = 1752794996L;
  public static final long h = 2927565187L;
  public static final long i = 1787740092L;
  public static final long j = 2068467417L;
  public static final long k = 10000L;
  public static final long l = 9999L;
  public static final long m = 9998L;
  public static final long n = 9997L;
  public static final long o = 9996L;
  public static final long p = 9995L;
  public static final long q = 9994L;
  public static final long r = 9993L;
  public static final long s = 9992L;
  public static final long t = 9991L;
  public static final long u = 9990L;
  public static final long v = 9989L;
  public static final long w = 9988L;
  public static final long x = 9987L;
  public static final long y = 9986L;
  public static final long z = 9985L;
  
  static
  {
    if (BaseApplicationImpl.a().doesHasSDCardPermission()) {}
    for (String str = an;; str = "/sdcard/Android/data/com.tencent.mobileqqi/files/Tencent/MobileQQ/")
    {
      ay = str;
      aA = ay + "head/";
      aB = an + "head/";
      aC = aA + "_hd/";
      aD = aA + "_thd/";
      aJ = ay + ".emotionsm/";
      aK = ay + ".emoQFace/";
      aL = ay + ".pendant/";
      aM = an + "foward_urldrawable/";
      aN = an + ".billd_urldrawable/";
      aO = an + ".map_roam/";
      aP = an + "head/" + "_SSOhd/";
      aQ = an + "location/";
      aT = an + "system_background/";
      aU = aT + "QQPicConfig.xml";
      aV = aT + "thumbnail/";
      aW = aT + "resource/";
      aY = an + "theme_pkg/";
      aZ = aY + "QQThemePkg" + "/";
      ba = aZ + "QQThemePkgConfig.xml";
      bb = aZ + "QQThemePkgTempConfig.xml";
      bc = aZ + "QQThemePkgOldConfig.xml";
      be = aZ + "cover/";
      bf = aZ + "pkg/";
      bk = an + "card/";
      bl = an + "card/starfans/";
      bm = an + "data/";
      bp = an + "troop/activity/";
      bq = an + "photo/watermark_temp.jpg";
      br = an + "sharefile/";
      return;
    }
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqqi\classes.jar
 * Qualified Name:     com.tencent.mobileqq.app.AppConstants
 * JD-Core Version:    0.7.0.1
 */