package com.tencent.moai.mailsdk.protocol.auth;

public class NtlmFlag
{
  public static int NTLMSSP_NEGOTIATE_128;
  public static int NTLMSSP_NEGOTIATE_56 = -2147483648;
  public static int NTLMSSP_NEGOTIATE_ALWAYS_SIGN;
  public static int NTLMSSP_NEGOTIATE_DATAGRAM_STYLE;
  public static int NTLMSSP_NEGOTIATE_KEY_EXCH;
  public static int NTLMSSP_NEGOTIATE_LM_KEY;
  public static int NTLMSSP_NEGOTIATE_LOCAL_CALL;
  public static int NTLMSSP_NEGOTIATE_NETWARE;
  public static int NTLMSSP_NEGOTIATE_NTLM;
  public static int NTLMSSP_NEGOTIATE_NTLM2;
  public static int NTLMSSP_NEGOTIATE_OEM;
  public static int NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED;
  public static int NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED;
  public static int NTLMSSP_NEGOTIATE_SEAL;
  public static int NTLMSSP_NEGOTIATE_SIGN;
  public static int NTLMSSP_NEGOTIATE_TARGET_INFO;
  public static int NTLMSSP_NEGOTIATE_UNICODE = 1;
  public static int NTLMSSP_REQUEST_ACCEPT_RESPONSE;
  public static int NTLMSSP_REQUEST_INIT_RESPONSE;
  public static int NTLMSSP_REQUEST_NON_NT_SESSION_KEY;
  public static int NTLMSSP_REQUEST_TARGET;
  public static int NTLMSSP_TARGET_TYPE_DOMAIN;
  public static int NTLMSSP_TARGET_TYPE_SERVER;
  public static int NTLMSSP_TARGET_TYPE_SHARE;
  
  static
  {
    NTLMSSP_NEGOTIATE_OEM = 2;
    NTLMSSP_REQUEST_TARGET = 4;
    NTLMSSP_NEGOTIATE_SIGN = 16;
    NTLMSSP_NEGOTIATE_SEAL = 32;
    NTLMSSP_NEGOTIATE_DATAGRAM_STYLE = 64;
    NTLMSSP_NEGOTIATE_LM_KEY = 128;
    NTLMSSP_NEGOTIATE_NETWARE = 256;
    NTLMSSP_NEGOTIATE_NTLM = 512;
    NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED = 4096;
    NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED = 8192;
    NTLMSSP_NEGOTIATE_LOCAL_CALL = 16384;
    NTLMSSP_NEGOTIATE_ALWAYS_SIGN = 32768;
    NTLMSSP_TARGET_TYPE_DOMAIN = 65536;
    NTLMSSP_TARGET_TYPE_SERVER = 131072;
    NTLMSSP_TARGET_TYPE_SHARE = 262144;
    NTLMSSP_NEGOTIATE_NTLM2 = 524288;
    NTLMSSP_REQUEST_INIT_RESPONSE = 1048576;
    NTLMSSP_REQUEST_ACCEPT_RESPONSE = 2097152;
    NTLMSSP_REQUEST_NON_NT_SESSION_KEY = 4194304;
    NTLMSSP_NEGOTIATE_TARGET_INFO = 8388608;
    NTLMSSP_NEGOTIATE_128 = 536870912;
    NTLMSSP_NEGOTIATE_KEY_EXCH = 1073741824;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.tim\classes7.jar
 * Qualified Name:     com.tencent.moai.mailsdk.protocol.auth.NtlmFlag
 * JD-Core Version:    0.7.0.1
 */