package com.tencent.mobileqq.banner;

public class BannerTypeCollections
{
  public static final int A;
  public static final int B;
  public static final int C;
  public static final int D;
  public static final int E;
  public static final int F;
  public static final int G;
  public static final int H;
  public static final int I;
  public static final int J;
  public static final int K;
  public static final int L;
  public static final int M;
  public static final int N;
  public static final int O;
  public static final int P;
  public static final int Q;
  private static int R = 1;
  public static final int a;
  public static final int b;
  public static final int c;
  public static final int d;
  public static final int e;
  public static final int f;
  public static final int g;
  public static final int h;
  public static final int i;
  public static final int j;
  public static final int k;
  public static final int l;
  public static final int m;
  public static final int n;
  public static final int o;
  public static final int p;
  public static final int q;
  public static final int r;
  public static final int s;
  public static final int t;
  public static final int u;
  public static final int v;
  public static final int w;
  public static final int x;
  public static final int y;
  public static final int z;
  
  static
  {
    int i1 = R;
    R = i1 + 1;
    a = i1;
    i1 = R;
    R = i1 + 1;
    b = i1;
    i1 = R;
    R = i1 + 1;
    c = i1;
    i1 = R;
    R = i1 + 1;
    d = i1;
    i1 = R;
    R = i1 + 1;
    e = i1;
    i1 = R;
    R = i1 + 1;
    f = i1;
    i1 = R;
    R = i1 + 1;
    g = i1;
    i1 = R;
    R = i1 + 1;
    h = i1;
    i1 = R;
    R = i1 + 1;
    i = i1;
    i1 = R;
    R = i1 + 1;
    j = i1;
    i1 = R;
    R = i1 + 1;
    k = i1;
    i1 = R;
    R = i1 + 1;
    l = i1;
    i1 = R;
    R = i1 + 1;
    m = i1;
    i1 = R;
    R = i1 + 1;
    n = i1;
    i1 = R;
    R = i1 + 1;
    o = i1;
    i1 = R;
    R = i1 + 1;
    p = i1;
    i1 = R;
    R = i1 + 1;
    q = i1;
    i1 = R;
    R = i1 + 1;
    r = i1;
    i1 = R;
    R = i1 + 1;
    s = i1;
    i1 = R;
    R = i1 + 1;
    t = i1;
    i1 = R;
    R = i1 + 1;
    u = i1;
    i1 = R;
    R = i1 + 1;
    v = i1;
    i1 = R;
    R = i1 + 1;
    w = i1;
    i1 = R;
    R = i1 + 1;
    x = i1;
    i1 = R;
    R = i1 + 1;
    y = i1;
    i1 = R;
    R = i1 + 1;
    z = i1;
    i1 = R;
    R = i1 + 1;
    A = i1;
    i1 = R;
    R = i1 + 1;
    B = i1;
    i1 = R;
    R = i1 + 1;
    C = i1;
    i1 = R;
    R = i1 + 1;
    D = i1;
    i1 = R;
    R = i1 + 1;
    E = i1;
    i1 = R;
    R = i1 + 1;
    F = i1;
    i1 = R;
    R = i1 + 1;
    G = i1;
    i1 = R;
    R = i1 + 1;
    H = i1;
    i1 = R;
    R = i1 + 1;
    I = i1;
    i1 = R;
    R = i1 + 1;
    J = i1;
    i1 = R;
    R = i1 + 1;
    K = i1;
    i1 = R;
    R = i1 + 1;
    L = i1;
    i1 = R;
    R = i1 + 1;
    M = i1;
    i1 = R;
    R = i1 + 1;
    N = i1;
    i1 = R;
    R = i1 + 1;
    O = i1;
    i1 = R;
    R = i1 + 1;
    P = i1;
    i1 = R;
    R = i1 + 1;
    Q = i1;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes5.jar
 * Qualified Name:     com.tencent.mobileqq.banner.BannerTypeCollections
 * JD-Core Version:    0.7.0.1
 */