package com.tencent.mobileqq.vfs;

import com.tencent.mobileqq.app.AppConstants;
import java.io.File;
import java.util.HashSet;

public class VFSSourcePathConfig
{
  public static final HashSet<String> a = new HashSet();
  public static final HashSet<String> b = new HashSet();
  public static final String c;
  public static final String d;
  public static String e;
  public static final String[] f;
  
  static
  {
    Object localObject1 = new StringBuilder();
    ((StringBuilder)localObject1).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject1).append("chatpic");
    ((StringBuilder)localObject1).append(File.separator);
    c = ((StringBuilder)localObject1).toString();
    localObject1 = new StringBuilder();
    ((StringBuilder)localObject1).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject1).append("vasSplashAD/");
    d = ((StringBuilder)localObject1).toString();
    localObject1 = new StringBuilder();
    ((StringBuilder)localObject1).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject1).append("ptt");
    ((StringBuilder)localObject1).append(File.separator);
    e = ((StringBuilder)localObject1).toString();
    localObject1 = b;
    Object localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(File.separator);
    ((StringBuilder)localObject2).append("flashchat");
    ((StringBuilder)localObject2).append(File.separator);
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    b.add(AppConstants.SDCARD_POKE);
    b.add(AppConstants.SDCARD_NEW_POKE);
    b.add(AppConstants.SDCARD_PE);
    b.add(AppConstants.SDCARD_PATH_EMOJIS);
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/tencent/MobileQQ/.troop/pic_effects/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".troop/enter_effects/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".gift/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("qav/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("new_ptv_template/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("ptv_template/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("funcall/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("pddata/prd/av_redpacket/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("pddata/prd/early");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("hotimage/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("pddata/vas/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".profilecard/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("head/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".hiboom_font/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".font_info/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".font_effect/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".pendant/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".vaspoke/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("system_background/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".CorlorNick/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("custom_background/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".starHead/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("rbt/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".vipicon/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("webso/offline/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".readInjoy/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    b.add(d);
    b.add(AppConstants.SDCARD_SHORTVIDEO_SAVE);
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/Tencent/ReaderZone/style/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/Tencent/ReaderZone/font/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".apollo/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("DoutuRes");
    ((StringBuilder)localObject2).append(File.separator);
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/tencent/TMAssistantSDK/Download/com.tencent.mobileqq");
    ((StringBuilder)localObject2).append(File.separator);
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/tencent/MobileQQ/pddata/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/tencent/MobileQQ/pddata/APP/offline/html5/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/tencent/MobileQQ/pddata/APP/offline/tmp/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = b;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/tencent/MobileQQ/ShareScreenShots");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = a;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("diskcache");
    ((StringBuilder)localObject2).append(File.separator);
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    a.add(c);
    localObject1 = a;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("photo/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = a;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("thumb/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = a;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append("shortvideo");
    ((StringBuilder)localObject2).append(File.separator);
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    a.add(e);
    a.add(AppConstants.SUBSCRIBE_DRAFT);
    a.add(AppConstants.SUBSCRIBE_DRAFT_SIMPLE);
    localObject1 = a;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/Tencent/QQfile_recv/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    a.add(AppConstants.SDCARD_HOMEWORK_AUDIO);
    a.add(AppConstants.SDCARD_HOMEWORK_ATTACH);
    localObject1 = a;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".Rock");
    ((StringBuilder)localObject2).append(File.separator);
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = a;
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject2).append("/Tencent/QQ_Collection/");
    ((HashSet)localObject1).add(((StringBuilder)localObject2).toString());
    localObject1 = new StringBuilder();
    ((StringBuilder)localObject1).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject1).append("keyword_emotion");
    localObject1 = ((StringBuilder)localObject1).toString();
    localObject2 = new StringBuilder();
    ((StringBuilder)localObject2).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject2).append(".sticker_recommended_pics");
    localObject2 = ((StringBuilder)localObject2).toString();
    Object localObject3 = new StringBuilder();
    ((StringBuilder)localObject3).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject3).append("/Tencent/QQ_CameraEmo");
    localObject3 = ((StringBuilder)localObject3).toString();
    Object localObject4 = new StringBuilder();
    ((StringBuilder)localObject4).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject4).append(".diy");
    localObject4 = ((StringBuilder)localObject4).toString();
    Object localObject5 = new StringBuilder();
    ((StringBuilder)localObject5).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject5).append("Scribble");
    localObject5 = ((StringBuilder)localObject5).toString();
    Object localObject6 = new StringBuilder();
    ((StringBuilder)localObject6).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject6).append(".emotionsm");
    localObject6 = ((StringBuilder)localObject6).toString();
    Object localObject7 = new StringBuilder();
    ((StringBuilder)localObject7).append(AppConstants.SDCARD_ROOT);
    ((StringBuilder)localObject7).append("/Tencent/QQ_Favorite");
    localObject7 = ((StringBuilder)localObject7).toString();
    Object localObject8 = new StringBuilder();
    ((StringBuilder)localObject8).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject8).append("hotpic");
    localObject8 = ((StringBuilder)localObject8).toString();
    Object localObject9 = new StringBuilder();
    ((StringBuilder)localObject9).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject9).append("hugeimagecache");
    localObject9 = ((StringBuilder)localObject9).toString();
    Object localObject10 = new StringBuilder();
    ((StringBuilder)localObject10).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject10).append("ArkApp");
    localObject10 = ((StringBuilder)localObject10).toString();
    Object localObject11 = new StringBuilder();
    ((StringBuilder)localObject11).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject11).append("zhitu");
    localObject11 = ((StringBuilder)localObject11).toString();
    Object localObject12 = new StringBuilder();
    ((StringBuilder)localObject12).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject12).append("msgbackup");
    localObject12 = ((StringBuilder)localObject12).toString();
    Object localObject13 = new StringBuilder();
    ((StringBuilder)localObject13).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject13).append("qqmusic");
    localObject13 = ((StringBuilder)localObject13).toString();
    Object localObject14 = new StringBuilder();
    ((StringBuilder)localObject14).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject14).append("aio_long_shot");
    localObject14 = ((StringBuilder)localObject14).toString();
    Object localObject15 = new StringBuilder();
    ((StringBuilder)localObject15).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject15).append("tim_theme_aio");
    localObject15 = ((StringBuilder)localObject15).toString();
    Object localObject16 = new StringBuilder();
    ((StringBuilder)localObject16).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject16).append("qim_theme_aio");
    localObject16 = ((StringBuilder)localObject16).toString();
    Object localObject17 = new StringBuilder();
    ((StringBuilder)localObject17).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject17).append("nativemem");
    localObject17 = ((StringBuilder)localObject17).toString();
    Object localObject18 = new StringBuilder();
    ((StringBuilder)localObject18).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject18).append("pddata/prd/ar_promotion");
    localObject18 = ((StringBuilder)localObject18).toString();
    Object localObject19 = new StringBuilder();
    ((StringBuilder)localObject19).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject19).append("pddata/app/offline/html5");
    localObject19 = ((StringBuilder)localObject19).toString();
    Object localObject20 = new StringBuilder();
    ((StringBuilder)localObject20).append(AppConstants.SDCARD_PATH);
    ((StringBuilder)localObject20).append("iar");
    localObject20 = ((StringBuilder)localObject20).toString();
    StringBuilder localStringBuilder = new StringBuilder();
    localStringBuilder.append(AppConstants.SDCARD_ROOT);
    localStringBuilder.append("/AVReportCenter");
    f = new String[] { localObject1, localObject2, localObject3, localObject4, localObject5, localObject6, localObject7, localObject8, localObject9, localObject10, localObject11, localObject12, localObject13, localObject14, localObject15, localObject16, localObject17, localObject18, localObject19, localObject20, localStringBuilder.toString() };
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes12.jar
 * Qualified Name:     com.tencent.mobileqq.vfs.VFSSourcePathConfig
 * JD-Core Version:    0.7.0.1
 */