package com.tencent.mobileqq.service.troop;

public class TroopNotificationConstants
{
  public static final int A;
  public static final int B;
  public static final int C;
  public static final int D;
  public static final int E;
  public static final int F;
  public static final int G;
  public static final int H;
  public static final int I;
  public static final int J;
  public static final int K;
  public static final int L;
  public static final int M;
  public static final int N;
  public static final int O;
  public static final int P;
  public static final int Q;
  public static final int R;
  public static final int S;
  public static final int T;
  public static final int U;
  public static final int V;
  public static final int W;
  public static final int X;
  public static final int Y;
  public static final int Z;
  public static final int a;
  public static final int aA;
  public static final int aB;
  public static final int aC;
  public static final int aD;
  public static final int aE;
  public static final int aF;
  public static final int aG;
  public static final int aH;
  public static final int aI;
  public static final int aJ;
  public static final int aK;
  public static final int aL;
  public static final int aM;
  public static final int aN;
  public static final int aO;
  public static final int aP;
  public static final int aQ;
  public static final int aR;
  public static final int aS;
  public static final int aT;
  public static final int aU;
  public static final int aV;
  public static final int aW;
  public static final int aX;
  public static final int aY;
  public static final int aZ;
  public static final int aa;
  public static final int ab;
  public static final int ac;
  public static final int ad;
  public static final int ae;
  public static final int af;
  public static final int ag;
  public static final int ah;
  public static final int ai;
  public static final int aj;
  public static final int ak;
  public static final int al;
  public static final int am;
  public static final int an;
  public static final int ao;
  public static final int ap;
  public static final int aq;
  public static final int ar;
  public static final int as;
  public static final int at;
  public static final int au;
  public static final int av;
  public static final int aw;
  public static final int ax;
  public static final int ay;
  public static final int az;
  public static final int b;
  public static final int bA;
  public static final int bB;
  public static final int bC;
  public static final int bD;
  public static final int bE;
  public static final int bF;
  public static final int bG;
  public static final int bH;
  public static final int bI;
  public static final int bJ;
  public static final int bK;
  public static final int bL;
  public static final int bM;
  public static final int bN;
  public static final int bO;
  public static final int bP;
  public static final int bQ;
  public static final int bR;
  public static final int bS;
  public static final int bT;
  public static final int bU;
  public static final int bV;
  public static final int bW;
  public static final int bX;
  public static final int bY;
  public static final int bZ;
  public static final int ba;
  public static final int bb;
  public static final int bc;
  public static final int bd;
  public static final int be;
  public static final int bf;
  public static final int bg;
  public static final int bh;
  public static final int bi;
  public static final int bj;
  public static final int bk;
  public static final int bl;
  public static final int bm;
  public static final int bn;
  public static final int bo;
  public static final int bp;
  public static final int bq;
  public static final int br;
  public static final int bs;
  public static final int bt;
  public static final int bu;
  public static final int bv;
  public static final int bw;
  public static final int bx;
  public static final int by;
  public static final int bz;
  public static final int c;
  public static final int ca;
  public static final int cb;
  public static final int cc;
  public static final int cd;
  public static final int ce;
  public static final int cf;
  public static final int cg;
  public static final int ch;
  public static final int ci;
  public static final int cj;
  public static final int ck;
  public static final int cl;
  public static final int cm;
  public static final int cn;
  public static final int co;
  public static final int cp;
  public static final int cq;
  public static final int cr;
  private static int cs = 0;
  public static final int d;
  public static final int e;
  public static final int f;
  public static final int g;
  public static final int h;
  public static final int i;
  public static final int j;
  public static final int k;
  public static final int l;
  public static final int m;
  public static final int n;
  public static final int o;
  public static final int p;
  public static final int q;
  public static final int r;
  public static final int s;
  public static final int t;
  public static final int u;
  public static final int v;
  public static final int w;
  public static final int x;
  public static final int y;
  public static final int z;
  
  static
  {
    int i1 = cs;
    cs = i1 + 1;
    a = i1;
    i1 = cs;
    cs = i1 + 1;
    b = i1;
    i1 = cs;
    cs = i1 + 1;
    c = i1;
    i1 = cs;
    cs = i1 + 1;
    d = i1;
    i1 = cs;
    cs = i1 + 1;
    e = i1;
    i1 = cs;
    cs = i1 + 1;
    f = i1;
    i1 = cs;
    cs = i1 + 1;
    g = i1;
    i1 = cs;
    cs = i1 + 1;
    h = i1;
    i1 = cs;
    cs = i1 + 1;
    i = i1;
    i1 = cs;
    cs = i1 + 1;
    j = i1;
    i1 = cs;
    cs = i1 + 1;
    k = i1;
    i1 = cs;
    cs = i1 + 1;
    l = i1;
    i1 = cs;
    cs = i1 + 1;
    m = i1;
    i1 = cs;
    cs = i1 + 1;
    n = i1;
    i1 = cs;
    cs = i1 + 1;
    o = i1;
    i1 = cs;
    cs = i1 + 1;
    p = i1;
    i1 = cs;
    cs = i1 + 1;
    q = i1;
    i1 = cs;
    cs = i1 + 1;
    r = i1;
    i1 = cs;
    cs = i1 + 1;
    s = i1;
    i1 = cs;
    cs = i1 + 1;
    t = i1;
    i1 = cs;
    cs = i1 + 1;
    u = i1;
    i1 = cs;
    cs = i1 + 1;
    v = i1;
    i1 = cs;
    cs = i1 + 1;
    w = i1;
    i1 = cs;
    cs = i1 + 1;
    x = i1;
    i1 = cs;
    cs = i1 + 1;
    y = i1;
    i1 = cs;
    cs = i1 + 1;
    z = i1;
    i1 = cs;
    cs = i1 + 1;
    A = i1;
    i1 = cs;
    cs = i1 + 1;
    B = i1;
    i1 = cs;
    cs = i1 + 1;
    C = i1;
    i1 = cs;
    cs = i1 + 1;
    D = i1;
    i1 = cs;
    cs = i1 + 1;
    E = i1;
    i1 = cs;
    cs = i1 + 1;
    F = i1;
    i1 = cs;
    cs = i1 + 1;
    G = i1;
    i1 = cs;
    cs = i1 + 1;
    H = i1;
    i1 = cs;
    cs = i1 + 1;
    I = i1;
    i1 = cs;
    cs = i1 + 1;
    J = i1;
    i1 = cs;
    cs = i1 + 1;
    K = i1;
    i1 = cs;
    cs = i1 + 1;
    L = i1;
    i1 = cs;
    cs = i1 + 1;
    M = i1;
    i1 = cs;
    cs = i1 + 1;
    N = i1;
    i1 = cs;
    cs = i1 + 1;
    O = i1;
    i1 = cs;
    cs = i1 + 1;
    P = i1;
    i1 = cs;
    cs = i1 + 1;
    Q = i1;
    i1 = cs;
    cs = i1 + 1;
    R = i1;
    i1 = cs;
    cs = i1 + 1;
    S = i1;
    i1 = cs;
    cs = i1 + 1;
    T = i1;
    i1 = cs;
    cs = i1 + 1;
    U = i1;
    i1 = cs;
    cs = i1 + 1;
    V = i1;
    i1 = cs;
    cs = i1 + 1;
    W = i1;
    i1 = cs;
    cs = i1 + 1;
    X = i1;
    i1 = cs;
    cs = i1 + 1;
    Y = i1;
    i1 = cs;
    cs = i1 + 1;
    Z = i1;
    i1 = cs;
    cs = i1 + 1;
    aa = i1;
    i1 = cs;
    cs = i1 + 1;
    ab = i1;
    i1 = cs;
    cs = i1 + 1;
    ac = i1;
    i1 = cs;
    cs = i1 + 1;
    ad = i1;
    i1 = cs;
    cs = i1 + 1;
    ae = i1;
    i1 = cs;
    cs = i1 + 1;
    af = i1;
    i1 = cs;
    cs = i1 + 1;
    ag = i1;
    i1 = cs;
    cs = i1 + 1;
    ah = i1;
    i1 = cs;
    cs = i1 + 1;
    ai = i1;
    i1 = cs;
    cs = i1 + 1;
    aj = i1;
    i1 = cs;
    cs = i1 + 1;
    ak = i1;
    i1 = cs;
    cs = i1 + 1;
    al = i1;
    i1 = cs;
    cs = i1 + 1;
    am = i1;
    i1 = cs;
    cs = i1 + 1;
    an = i1;
    i1 = cs;
    cs = i1 + 1;
    ao = i1;
    i1 = cs;
    cs = i1 + 1;
    ap = i1;
    i1 = cs;
    cs = i1 + 1;
    aq = i1;
    i1 = cs;
    cs = i1 + 1;
    ar = i1;
    i1 = cs;
    cs = i1 + 1;
    as = i1;
    i1 = cs;
    cs = i1 + 1;
    at = i1;
    i1 = cs;
    cs = i1 + 1;
    au = i1;
    i1 = cs;
    cs = i1 + 1;
    av = i1;
    i1 = cs;
    cs = i1 + 1;
    aw = i1;
    i1 = cs;
    cs = i1 + 1;
    ax = i1;
    i1 = cs;
    cs = i1 + 1;
    ay = i1;
    i1 = cs;
    cs = i1 + 1;
    az = i1;
    i1 = cs;
    cs = i1 + 1;
    aA = i1;
    i1 = cs;
    cs = i1 + 1;
    aB = i1;
    i1 = cs;
    cs = i1 + 1;
    aC = i1;
    i1 = cs;
    cs = i1 + 1;
    aD = i1;
    i1 = cs;
    cs = i1 + 1;
    aE = i1;
    i1 = cs;
    cs = i1 + 1;
    aF = i1;
    i1 = cs;
    cs = i1 + 1;
    aG = i1;
    i1 = cs;
    cs = i1 + 1;
    aH = i1;
    i1 = cs;
    cs = i1 + 1;
    aI = i1;
    i1 = cs;
    cs = i1 + 1;
    aJ = i1;
    i1 = cs;
    cs = i1 + 1;
    aK = i1;
    i1 = cs;
    cs = i1 + 1;
    aL = i1;
    i1 = cs;
    cs = i1 + 1;
    aM = i1;
    i1 = cs;
    cs = i1 + 1;
    aN = i1;
    i1 = cs;
    cs = i1 + 1;
    aO = i1;
    i1 = cs;
    cs = i1 + 1;
    aP = i1;
    i1 = cs;
    cs = i1 + 1;
    aQ = i1;
    i1 = cs;
    cs = i1 + 1;
    aR = i1;
    i1 = cs;
    cs = i1 + 1;
    aS = i1;
    i1 = cs;
    cs = i1 + 1;
    aT = i1;
    i1 = cs;
    cs = i1 + 1;
    aU = i1;
    i1 = cs;
    cs = i1 + 1;
    aV = i1;
    i1 = cs;
    cs = i1 + 1;
    aW = i1;
    i1 = cs;
    cs = i1 + 1;
    aX = i1;
    i1 = cs;
    cs = i1 + 1;
    aY = i1;
    i1 = cs;
    cs = i1 + 1;
    aZ = i1;
    i1 = cs;
    cs = i1 + 1;
    ba = i1;
    i1 = cs;
    cs = i1 + 1;
    bb = i1;
    i1 = cs;
    cs = i1 + 1;
    bc = i1;
    i1 = cs;
    cs = i1 + 1;
    bd = i1;
    i1 = cs;
    cs = i1 + 1;
    be = i1;
    i1 = cs;
    cs = i1 + 1;
    bf = i1;
    i1 = cs;
    cs = i1 + 1;
    bg = i1;
    i1 = cs;
    cs = i1 + 1;
    bh = i1;
    i1 = cs;
    cs = i1 + 1;
    bi = i1;
    i1 = cs;
    cs = i1 + 1;
    bj = i1;
    i1 = cs;
    cs = i1 + 1;
    bk = i1;
    i1 = cs;
    cs = i1 + 1;
    bl = i1;
    i1 = cs;
    cs = i1 + 1;
    bm = i1;
    i1 = cs;
    cs = i1 + 1;
    bn = i1;
    i1 = cs;
    cs = i1 + 1;
    bo = i1;
    i1 = cs;
    cs = i1 + 1;
    bp = i1;
    i1 = cs;
    cs = i1 + 1;
    bq = i1;
    i1 = cs;
    cs = i1 + 1;
    br = i1;
    i1 = cs;
    cs = i1 + 1;
    bs = i1;
    i1 = cs;
    cs = i1 + 1;
    bt = i1;
    i1 = cs;
    cs = i1 + 1;
    bu = i1;
    i1 = cs;
    cs = i1 + 1;
    bv = i1;
    i1 = cs;
    cs = i1 + 1;
    bw = i1;
    i1 = cs;
    cs = i1 + 1;
    bx = i1;
    i1 = cs;
    cs = i1 + 1;
    by = i1;
    i1 = cs;
    cs = i1 + 1;
    bz = i1;
    i1 = cs;
    cs = i1 + 1;
    bA = i1;
    i1 = cs;
    cs = i1 + 1;
    bB = i1;
    i1 = cs;
    cs = i1 + 1;
    bC = i1;
    i1 = cs;
    cs = i1 + 1;
    bD = i1;
    i1 = cs;
    cs = i1 + 1;
    bE = i1;
    i1 = cs;
    cs = i1 + 1;
    bF = i1;
    i1 = cs;
    cs = i1 + 1;
    bG = i1;
    i1 = cs;
    cs = i1 + 1;
    bH = i1;
    i1 = cs;
    cs = i1 + 1;
    bI = i1;
    i1 = cs;
    cs = i1 + 1;
    bJ = i1;
    i1 = cs;
    cs = i1 + 1;
    bK = i1;
    i1 = cs;
    cs = i1 + 1;
    bL = i1;
    i1 = cs;
    cs = i1 + 1;
    bM = i1;
    i1 = cs;
    cs = i1 + 1;
    bN = i1;
    i1 = cs;
    cs = i1 + 1;
    bO = i1;
    i1 = cs;
    cs = i1 + 1;
    bP = i1;
    i1 = cs;
    cs = i1 + 1;
    bQ = i1;
    i1 = cs;
    cs = i1 + 1;
    bR = i1;
    i1 = cs;
    cs = i1 + 1;
    bS = i1;
    i1 = cs;
    cs = i1 + 1;
    bT = i1;
    i1 = cs;
    cs = i1 + 1;
    bU = i1;
    i1 = cs;
    cs = i1 + 1;
    bV = i1;
    i1 = cs;
    cs = i1 + 1;
    bW = i1;
    i1 = cs;
    cs = i1 + 1;
    bX = i1;
    i1 = cs;
    cs = i1 + 1;
    bY = i1;
    i1 = cs;
    cs = i1 + 1;
    bZ = i1;
    i1 = cs;
    cs = i1 + 1;
    ca = i1;
    i1 = cs;
    cs = i1 + 1;
    cb = i1;
    i1 = cs;
    cs = i1 + 1;
    cc = i1;
    i1 = cs;
    cs = i1 + 1;
    cd = i1;
    i1 = cs;
    cs = i1 + 1;
    ce = i1;
    i1 = cs;
    cs = i1 + 1;
    cf = i1;
    i1 = cs;
    cs = i1 + 1;
    cg = i1;
    i1 = cs;
    cs = i1 + 1;
    ch = i1;
    i1 = cs;
    cs = i1 + 1;
    ci = i1;
    i1 = cs;
    cs = i1 + 1;
    cj = i1;
    i1 = cs;
    cs = i1 + 1;
    ck = i1;
    i1 = cs;
    cs = i1 + 1;
    cl = i1;
    i1 = cs;
    cs = i1 + 1;
    cm = i1;
    i1 = cs;
    cs = i1 + 1;
    cn = i1;
    i1 = cs;
    cs = i1 + 1;
    co = i1;
    i1 = cs;
    cs = i1 + 1;
    cp = i1;
    i1 = cs;
    cs = i1 + 1;
    cq = i1;
    i1 = cs;
    cs = i1 + 1;
    cr = i1;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes.jar
 * Qualified Name:     com.tencent.mobileqq.service.troop.TroopNotificationConstants
 * JD-Core Version:    0.7.0.1
 */