package com.tencent.aelight.camera.ae.download;

import com.tencent.mobileqq.shortvideo.ShortVideoResourceManager.SVConfigItem;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;

public class AELocalConfig
{
  public static final List<ShortVideoResourceManager.SVConfigItem> a = ;
  
  private static List<ShortVideoResourceManager.SVConfigItem> a()
  {
    LinkedList localLinkedList = new LinkedList();
    ShortVideoResourceManager.SVConfigItem localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_short_filter_8817002";
    localSVConfigItem.arm_url = "https://down.qq.com/shadow_qqcamera/Android/res/ae_base_res_1.0.9.zip";
    localSVConfigItem.armv7a_url = "https://down.qq.com/shadow_qqcamera/Android/res/ae_base_res_1.0.9.zip";
    localSVConfigItem.x86_url = "https://down.qq.com/shadow_qqcamera/Android/res/ae_base_res_1.0.9.zipp";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "a943cd1507fd829de3d2334a04879576";
    localSVConfigItem.armv7a_md5 = "a943cd1507fd829de3d2334a04879576";
    localSVConfigItem.x86_md5 = "a943cd1507fd829de3d2334a04879576";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_base_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_basic_2.6.0.23.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_basic_2.6.0.23.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_basic_2.6.0.23.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "feb5d156d841a835fefef675f9fc2493";
    localSVConfigItem.armv7a_md5 = "feb5d156d841a835fefef675f9fc2493";
    localSVConfigItem.x86_md5 = "feb5d156d841a835fefef675f9fc2493";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_hand_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_hand_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_hand_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_hand_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "b32f333a4b11240b8f5ed72f2cf4a7d1";
    localSVConfigItem.armv7a_md5 = "b32f333a4b11240b8f5ed72f2cf4a7d1";
    localSVConfigItem.x86_md5 = "b32f333a4b11240b8f5ed72f2cf4a7d1";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_gender_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_gender_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_gender_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_gender_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "658c3fe4d30ff6e544a698606930d9fd";
    localSVConfigItem.armv7a_md5 = "658c3fe4d30ff6e544a698606930d9fd";
    localSVConfigItem.x86_md5 = "658c3fe4d30ff6e544a698606930d9fd";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_cat_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_cat_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_cat_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_cat_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "ed82ccc9f1ab5bff53444bce75860517";
    localSVConfigItem.armv7a_md5 = "ed82ccc9f1ab5bff53444bce75860517";
    localSVConfigItem.x86_md5 = "ed82ccc9f1ab5bff53444bce75860517";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_depth_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_depth_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_depth_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_depth_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "f83414bb6dd7a9abaab3df6c95a7f8f2";
    localSVConfigItem.armv7a_md5 = "f83414bb6dd7a9abaab3df6c95a7f8f2";
    localSVConfigItem.x86_md5 = "f83414bb6dd7a9abaab3df6c95a7f8f2";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_age_8817002";
    localSVConfigItem.arm_url = "https://down.qq.com/shadow_qqcamera/Android/res/light-sdk_age_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://down.qq.com/shadow_qqcamera/Android/res/light-sdk_age_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://down.qq.com/shadow_qqcamera/Android/res/light-sdk_age_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "ecc924da592ec46a802e9b0e01c62359";
    localSVConfigItem.armv7a_md5 = "ecc924da592ec46a802e9b0e01c62359";
    localSVConfigItem.x86_md5 = "ecc924da592ec46a802e9b0e01c62359";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_seg_hair_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_segment_hair_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_segment_hair_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_segment_hair_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "4edf08972c31d771aa3a405511f498ae";
    localSVConfigItem.armv7a_md5 = "4edf08972c31d771aa3a405511f498ae";
    localSVConfigItem.x86_md5 = "4edf08972c31d771aa3a405511f498ae";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_seg_sky_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_segment_sky_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_segment_sky_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_segment_sky_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "8df1109d4543e61c1f54c4699ee8f553";
    localSVConfigItem.armv7a_md5 = "8df1109d4543e61c1f54c4699ee8f553";
    localSVConfigItem.x86_md5 = "8df1109d4543e61c1f54c4699ee8f553";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_seg_head_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_segment_head_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_segment_head_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_segment_head_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "c8fab6dbe339ffeb7f2c4d290c6ffef6";
    localSVConfigItem.armv7a_md5 = "c8fab6dbe339ffeb7f2c4d290c6ffef6";
    localSVConfigItem.x86_md5 = "c8fab6dbe339ffeb7f2c4d290c6ffef6";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_ace3d_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_ace3d_for_qq_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_ace3d_for_qq_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_ace3d_for_qq_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "7c35a56de439fada1c0902ce9f67f37f";
    localSVConfigItem.armv7a_md5 = "7c35a56de439fada1c0902ce9f67f37f";
    localSVConfigItem.x86_md5 = "7c35a56de439fada1c0902ce9f67f37f";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_3dmm_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_3dmm_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_3dmm_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_3dmm_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "1e0fa2ae8f29116026f700c0ba47d11d";
    localSVConfigItem.armv7a_md5 = "1e0fa2ae8f29116026f700c0ba47d11d";
    localSVConfigItem.x86_md5 = "1e0fa2ae8f29116026f700c0ba47d11d";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_scene_8817002";
    StringBuilder localStringBuilder = new StringBuilder();
    localStringBuilder.append("https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_scene_classify_bundle_");
    localStringBuilder.append("2.6.0.6");
    localStringBuilder.append(".zip");
    localSVConfigItem.arm_url = localStringBuilder.toString();
    localStringBuilder = new StringBuilder();
    localStringBuilder.append("https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_scene_classify_bundle_");
    localStringBuilder.append("2.6.0.6");
    localStringBuilder.append(".zip");
    localSVConfigItem.armv7a_url = localStringBuilder.toString();
    localStringBuilder = new StringBuilder();
    localStringBuilder.append("https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_scene_classify_bundle_");
    localStringBuilder.append("2.6.0.6");
    localStringBuilder.append(".zip");
    localSVConfigItem.x86_url = localStringBuilder.toString();
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "06db13f88ec1de82f46df6c0a4338dfd";
    localSVConfigItem.armv7a_md5 = "06db13f88ec1de82f46df6c0a4338dfd";
    localSVConfigItem.x86_md5 = "06db13f88ec1de82f46df6c0a4338dfd";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_gaze_8817002";
    localStringBuilder = new StringBuilder();
    localStringBuilder.append("https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_gaze_estimate_bundle_");
    localStringBuilder.append("2.6.0.6");
    localStringBuilder.append(".zip");
    localSVConfigItem.arm_url = localStringBuilder.toString();
    localStringBuilder = new StringBuilder();
    localStringBuilder.append("https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_gaze_estimate_bundle_");
    localStringBuilder.append("2.6.0.6");
    localStringBuilder.append(".zip");
    localSVConfigItem.armv7a_url = localStringBuilder.toString();
    localStringBuilder = new StringBuilder();
    localStringBuilder.append("https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_gaze_estimate_bundle_");
    localStringBuilder.append("2.6.0.6");
    localStringBuilder.append(".zip");
    localSVConfigItem.x86_url = localStringBuilder.toString();
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "91415b5dd3171f341ecbeaaf6f56f591";
    localSVConfigItem.armv7a_md5 = "91415b5dd3171f341ecbeaaf6f56f591";
    localSVConfigItem.x86_md5 = "91415b5dd3171f341ecbeaaf6f56f591";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_emotion_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_emotion_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_emotion_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_emotion_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "8c563397365a640893a0f0e6c814d5e7";
    localSVConfigItem.armv7a_md5 = "8c563397365a640893a0f0e6c814d5e7";
    localSVConfigItem.x86_md5 = "8c563397365a640893a0f0e6c814d5e7";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_body_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_body_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_body_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_body_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "4b68cfd150951cafd1a09d693d095494";
    localSVConfigItem.armv7a_md5 = "4b68cfd150951cafd1a09d693d095494";
    localSVConfigItem.x86_md5 = "4b68cfd150951cafd1a09d693d095494";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    localSVConfigItem = new ShortVideoResourceManager.SVConfigItem();
    localSVConfigItem.name = "new_qq_android_native_light_bundle_driver_body_3d_8817002";
    localSVConfigItem.arm_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_body_3d_bundle_2.6.0.6.zip";
    localSVConfigItem.armv7a_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_body_3d_bundle_2.6.0.6.zip";
    localSVConfigItem.x86_url = "https://downv6.qq.com/shadow_qqcamera/Android/res/light-sdk_body_3d_bundle_2.6.0.6.zip";
    localSVConfigItem.arm64v8a_url = "TODO";
    localSVConfigItem.arm_md5 = "2b6b304a5f2b1265ccfda2336fbe6aba";
    localSVConfigItem.armv7a_md5 = "2b6b304a5f2b1265ccfda2336fbe6aba";
    localSVConfigItem.x86_md5 = "2b6b304a5f2b1265ccfda2336fbe6aba";
    localSVConfigItem.arm64v8a_md5 = "TODO";
    localSVConfigItem.versionCode = 8817;
    localSVConfigItem.predownload = false;
    localLinkedList.add(localSVConfigItem);
    return Collections.unmodifiableList(localLinkedList);
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes19.jar
 * Qualified Name:     com.tencent.aelight.camera.ae.download.AELocalConfig
 * JD-Core Version:    0.7.0.1
 */