package com.tencent.mm.compatible.deviceinfo;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.sdk.platformtools.Log;

public final class k
{
  public int lTS;
  public int lTT;
  public int lTU;
  public int lTV;
  public int lTW;
  public int lTX;
  public int lTY;
  public int lTZ;
  public int lUA;
  public int lUB;
  public int lUC;
  public int lUD;
  public int lUE;
  public int lUF;
  public int lUG;
  public int lUH;
  public int lUI;
  public int lUJ;
  public int lUK;
  public int lUL;
  public int lUM;
  public int lUN;
  public int lUO;
  public int lUP;
  public int lUQ;
  public int lUR;
  public int lUS;
  public int lUT;
  public int lUU;
  public int lUV;
  public int lUW;
  public int lUX;
  public int lUY;
  public String lUZ;
  public boolean lUa;
  public int lUb;
  public int lUc;
  public int lUd;
  public int lUe;
  public int lUf;
  public int lUg;
  public int lUh;
  public int lUi;
  public int lUj;
  public int lUk;
  public int lUl;
  public int lUm;
  public int lUn;
  public int lUo;
  public int lUp;
  public int lUq;
  public int lUr;
  public int lUs;
  public int lUt;
  public double lUu;
  public int lUv;
  public int lUw;
  public int lUx;
  public int lUy;
  public int lUz;
  public String lVa;
  public String lVb;
  public String lVc;
  public String lVd;
  public String lVe;
  public String lVf;
  public String lVg;
  public String lVh;
  public String lVi;
  public String lVj;
  public String lVk;
  public String lVl;
  public int lVm;
  public int lVn;
  public int lVo;
  public int lVp;
  public int lVq;
  public int lVr;
  public int lVs;
  public int lVt;
  
  public k()
  {
    AppMethodBeat.i(155654);
    this.lTS = -1;
    this.lTT = -1;
    this.lTU = -1;
    this.lTV = -1;
    this.lTW = -1;
    this.lTX = -1;
    this.lTY = -1;
    this.lTZ = -1;
    this.lUa = false;
    this.lUb = -1;
    this.lUc = -1;
    this.lUd = -1;
    this.lUe = -1;
    this.lUf = -1;
    this.lUg = -1;
    this.lUh = -1;
    this.lUi = -1;
    this.lUj = -1;
    this.lUk = -1;
    this.lUl = -1;
    this.lUm = -1;
    this.lUn = -1;
    this.lUo = -1;
    this.lUp = -1;
    this.lUq = -1;
    this.lUr = -1;
    this.lUs = -1;
    this.lUt = -1;
    this.lUu = -1.0D;
    this.lUv = -1;
    this.lUw = -1;
    this.lUx = -1;
    this.lUy = -1;
    this.lUz = -1;
    this.lUA = -1;
    this.lUB = -1;
    this.lUC = -1;
    this.lUD = -1;
    this.lUE = -1;
    this.lUF = -1;
    this.lUG = -1;
    this.lUH = -1;
    this.lUI = -1;
    this.lUJ = -1;
    this.lUK = -1;
    this.lUL = -1;
    this.lUM = -1;
    this.lUN = -1;
    this.lUO = -1;
    this.lUP = -1;
    this.lUQ = -1;
    this.lUR = -1;
    this.lUS = -1;
    this.lUT = -1;
    this.lUU = -1;
    this.lUV = -1;
    this.lUW = -1;
    this.lUX = -1;
    this.lUY = -1;
    this.lUZ = null;
    this.lVa = null;
    this.lVb = null;
    this.lVc = null;
    this.lVd = null;
    this.lVe = null;
    this.lVf = null;
    this.lVg = null;
    this.lVh = null;
    this.lVi = null;
    this.lVj = null;
    this.lVk = null;
    this.lVl = null;
    this.lVm = -1;
    this.lVn = 2;
    this.lVo = 1;
    this.lVp = 1;
    this.lVq = -1;
    this.lVr = -1;
    this.lVs = -1;
    this.lVt = -1;
    reset();
    AppMethodBeat.o(155654);
  }
  
  public final void aQ()
  {
    AppMethodBeat.i(155655);
    Log.d("MicroMsg.CommonInfo", "js " + this.lTS);
    Log.d("MicroMsg.CommonInfo", "stopBluetoothInBR " + this.lTT);
    Log.d("MicroMsg.CommonInfo", "stopBluetoothInBU " + this.lTU);
    Log.d("MicroMsg.CommonInfo", "setBluetoothScoOn " + this.lTW);
    Log.d("MicroMsg.CommonInfo", "startBluetoothSco " + this.lTV);
    Log.d("MicroMsg.CommonInfo", "voiceSearchFastMode " + this.lTX);
    Log.d("MicroMsg.CommonInfo", "pcmReadMode " + this.lTZ);
    Log.d("MicroMsg.CommonInfo", "pcmBufferRate " + this.lTY);
    Log.d("MicroMsg.CommonInfo", "audioPrePro " + this.lUc);
    Log.d("MicroMsg.CommonInfo", "voicemsgfd " + this.lUd);
    Log.d("MicroMsg.CommonInfo", "htcvoicemode " + this.lUe);
    Log.d("MicroMsg.CommonInfo", "samsungvoicemode " + this.lUf);
    Log.d("MicroMsg.CommonInfo", "speexBufferRate " + this.lUg);
    Log.d("MicroMsg.CommonInfo", "linespe " + this.lUh);
    Log.d("MicroMsg.CommonInfo", "fixspan " + this.lUs);
    Log.d("MicroMsg.CommonInfo", "extvideo " + this.lUi);
    Log.d("MicroMsg.CommonInfo", "extvideosam " + this.lUj);
    Log.d("MicroMsg.CommonInfo", "sysvideodegree " + this.lUk);
    Log.d("MicroMsg.CommonInfo", "mmnotify " + this.lUn);
    Log.d("MicroMsg.CommonInfo", "extsharevcard " + this.lUm);
    Log.d("MicroMsg.CommonInfo", "audioformat " + this.lUo);
    Log.d("MicroMsg.CommonInfo", "qrcam " + this.lUp);
    Log.d("MicroMsg.CommonInfo", "mBase " + this.lUZ);
    Log.d("MicroMsg.CommonInfo", "mPackageInfo " + this.lVa);
    Log.d("MicroMsg.CommonInfo", "mClassLoader " + this.lVb);
    Log.d("MicroMsg.CommonInfo", "mResources " + this.lVc);
    Log.d("MicroMsg.CommonInfo", "sysvideofp " + this.lUq);
    Log.d("MicroMsg.CommonInfo", "extstoragedir " + this.lVd);
    Log.d("MicroMsg.CommonInfo", "extpubdir " + this.lVe);
    Log.d("MicroMsg.CommonInfo", "extdatadir " + this.lVf);
    Log.d("MicroMsg.CommonInfo", "extrootdir " + this.lVg);
    Log.d("MicroMsg.CommonInfo", "extstoragestate " + this.lVh);
    Log.d("MicroMsg.CommonInfo", "extcachedir " + this.lVi);
    Log.d("MicroMsg.CommonInfo", "extvideoplayer " + this.lUr);
    Log.d("MicroMsg.CommonInfo", "loadDrawable " + this.lVj);
    Log.d("MicroMsg.CommonInfo", "loadXmlResourceParser " + this.lVk);
    Log.d("MicroMsg.CommonInfo", "voipAudioPrePro " + this.lUG);
    Log.d("MicroMsg.CommonInfo", "voipAudioPreProNS " + this.lUH);
    Log.d("MicroMsg.CommonInfo", "voipAudioPreProAEC " + this.lUI);
    Log.d("MicroMsg.CommonInfo", "voipAudioPreProAGC " + this.lUJ);
    Log.d("MicroMsg.CommonInfo", "sight full screen type " + this.lVl);
    Log.d("MicroMsg.CommonInfo", "checkSightDraftMd5 " + this.lVn);
    Log.d("MicroMsg.CommonInfo", "swipeBackConfig " + this.lVo);
    Log.d("MicroMsg.CommonInfo", "qrCodeZoom " + this.lUt);
    Log.d("MicroMsg.CommonInfo", "hevcTransCodeMediaCodec" + this.lVr);
    Log.i("MicroMsg.CommonInfo", "videoSupportHevcDecode" + this.lVs);
    Log.i("MicroMsg.CommonInfo", "groupRSCap" + this.lUF);
    AppMethodBeat.o(155655);
  }
  
  public final void reset()
  {
    this.lTS = -1;
    this.lTT = -1;
    this.lTU = -1;
    this.lTV = -1;
    this.lTW = -1;
    this.lTX = -1;
    this.lTZ = -1;
    this.lTY = -1;
    this.lUc = -1;
    this.lUd = -1;
    this.lUe = -1;
    this.lUf = -1;
    this.lUa = false;
    this.lUb = -1;
    this.lUg = -1;
    this.lUh = -1;
    this.lUi = -1;
    this.lUj = -1;
    this.lUk = -1;
    this.lUn = -1;
    this.lUm = -1;
    this.lUo = -1;
    this.lUp = -1;
    this.lUl = -1;
    this.lUo = -1;
    this.lUp = -1;
    this.lUs = -1;
    this.lUG = -1;
    this.lUH = -1;
    this.lUI = -1;
    this.lUJ = -1;
    this.lUX = -1;
    this.lUY = -1;
    this.lUZ = null;
    this.lVa = null;
    this.lVb = null;
    this.lVc = null;
    this.lUq = -1;
    this.lVd = null;
    this.lVe = null;
    this.lVf = null;
    this.lVg = null;
    this.lVh = null;
    this.lVi = null;
    this.lUr = -1;
    this.lVj = null;
    this.lVk = null;
    this.lVl = null;
    this.lVm = -1;
    this.lVn = 2;
    this.lVo = 1;
    this.lVp = 1;
    this.lUt = -1;
    this.lVr = -1;
    this.lVs = -1;
    this.lUF = -1;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes9.jar
 * Qualified Name:     com.tencent.mm.compatible.deviceinfo.k
 * JD-Core Version:    0.7.0.1
 */