package com.tencent.mm.vfs;

import com.tencent.matrix.trace.core.AppMethodBeat;

final class t
{
  private static final String[] agAa = { "${accountSalt}/image", "${accountSalt}/favorite", "${accountSalt}/oneday", "${accountSalt}/emoji", "${accountSalt}/voice2", "wxacache", "${accountSalt}/bizimg", "${accountSalt}/package", "wxanewfiles", "${accountSalt}/video", "wxafiles", "${accountSalt}/textstatus", "CheckResUpdate", "xlog", "vusericon", "Download", "card", "${accountSalt}/mailapp", "${accountSalt}/taskbar", "${accountSalt}/recbiz", "Game", "mapsdk", "wallet", "recovery", "${accountSalt}/image2", "${accountSalt}/image2", ".tmp", "${accountSalt}/music", "${accountSalt}/record", "${accountSalt}/attachment", "wagamefiles", "wallet_images", "crash", "${accountSalt}/scanner", "${accountSalt}/openim", "${accountSalt}/favoffline", "FailMsgFileCache", "facedir", "SQLTrace", "hilive", "hbstoryvideo", "${accountSalt}/openapi", "${accountSalt}/boots", "${accountSalt}/story", "${accountSalt}/remark", "${accountSalt}/dbback", "game", "${accountSalt}/gamelife", "${accountSalt}/gamelife/avatar", "wallet/images", "exdevice", "${accountSalt}/shakemusic", "wxvideocache", "mail", "${accountSalt}/multitask", "taxi_icon", "avatar", "browser", "${accountSalt}/selectrecord", "${accountSalt}/live", "fts", "AudioRecord", "${accountSalt}/videovideoCompressTmpThumb", "${accountSalt}/subvideo", "wepkg", "${accountSalt}/draft", "${accountSalt}/audio", "${accountSalt}/videovideoCompressTmp", "${accountSalt}", "Handler", "${accountSalt}/bizmsg", "ThumbVideoCache", "${accountSalt}/voice", "WebviewCache", "temp_video_cache", "${accountSalt}/ProcessDetect", "diskcache", "wxvideotmp", "wenote", "${accountSalt}/sfs", "video", "imagecache", "Diagnostic", "egg_spring", "${accountSalt}/patmsg", "appbrand", "music", "wxauto", "wvtemp", "${accountSalt}/cdn", "${accountSalt}/secdata", "ClickFlow", "trace", "webcompt", "${accountSalt}/LuckyMoney", "${accountSalt}/game", "${accountSalt}/syncFile", "ProcessDetector", "WebCanvasPkg", "download", "last_avatar_dir", "regioncode", "webview_tmpl", "${accountSalt}/appbrand", "${accountSalt}/normsg", "${accountSalt}/wenote", ".planCache", "CheckResUpdate_1", "CronetCache", "configlist", "jscache", "jsengine", "surface", "mmslot", "tmpScanLicense", "webservice", "CDNTemp", "test_writable", "xlogtest_writable", "mars_mock" };
  private static final String[] agAb = { "${accountSalt}/finder", "${accountSalt}/sns", "${accountSalt}/openapi_cache", "sns_ad_landingpages", "Cache", "${accountSalt}/aimodel", "imgcache", "videocache", "${accountSalt}/bizcache", "MixAudio", "${accountSalt}/webcanvascache", "${accountSalt}/brandicon", "${accountSalt}/recordPlugin", "BigFile", "image", "${accountSalt}/backupRecover", "share", "TMAssistantSDK", "ThumbVideoCache", "matrix_resource", "temp", "Diagnostic", "MicroMsg", "playable", "tt_tmpl_pkg", "wxacomplaint", "wxacache", "hprofs", "mars_mock", "ipxx_diag" };
  private static final String[] agzY = { "app_xwalk_*", "app_webview_com_tencent_mm*", "app_hws_webview_com_tencent_mm*", "files", "cache", "scan_goods", "shared_prefs", "app_xwalkplugin", "databases", "appbrand", "face_detect", "app_font", "app_tbs", ".auth_cache", "app_xwalkconfig", "app_turingdfp", "tinker", "app_turingfd", "tinker_temp", "extqbar", "app_tbs_common_share", "app_sslcache", "app_tbs_64", "app_qmsp", "cert", "app_x5webview", "app_webview", "no_backup", "app_execdir", "app_midasplugins", "app_midaslib_1", "lib", "huaweiks", "ilink", "xweb_lock", "app_dynamic_jar_output", "app_midaslib_0", "app_turingsmi", "code_cache", "openvoice", "app_.patch", "app_midasodex", "wc_tinker_dir", "app_expose", "app_icon_assets", "app_aimodel", "app_txsdklog", "fileshost", "shaders", "app_turingmm", "app_filelock", "app_recovery_lib", "app_tencentMapTemp", "app_flutter", "app_ringtone", "app_vibrate", "app_voip", "app_debugtbs", "app_exp_assets", "_hwclone", "app_TBSqmsp", "PluginInfo", ".magic_cache", "app_plugins", "oat", "app_dex", "dumptextures", "ex_libs", "Flyme_Clone", "voice_split_joint", "app_videoDexOutput", "Micrcrsgappbrand", "app_databases", "app_patch_res", "app_unlzma", "AssetsLibs", "app_one_time", "app_shoot_res", "filesm", "MicroMsg", "MicroMsg/${account}", "MicroMsg/WebNetFile" };
  private static final String[] agzZ = { "webview_com_tencent_mm*", "old_org.chromium.android_webview*", "old_com.tencent.mm.xweb*", "websearch", "WebView", "org.chromium.xwalk", "mv_video", "wakelock", "wordBank", "LocalCache", "fts", "webprefetch", "webprefetch/resource", "TPReportCache_key", "oneday", "temp", "webprefetch/manifest", "webprefetch/content", "xnn", "com.tencent.mm.xweb", "topstory", "org.chromium.android_webview", "sticker", "beacon_volley", "box_temp", "appbrand", "cpsafe", "HttpCache", "image_search_temp", "image_search_temp", "mux", "recovery", "customcache", "WebNetFile", "imagecache", "MixAudio", "Data", "flutter", "tencent", ".db", "libCachedImageData", "oat", "webviewCacheChromium", "TextStatus" };
  
  static void f(k.a parama)
  {
    AppMethodBeat.i(238318);
    parama.a("data-root", new WhiteListFileSystem(new NativeFileSystem("${data}"), agzY)).qg("${data}", "data-root");
    parama.a("data-cache", new WhiteListFileSystem(new NativeFileSystem("${dataCache}"), agzZ)).qg("${dataCache}", "data-cache");
    parama.a("ext-mm", new WhiteListFileSystem(new MigrationFileSystem(new NativeFileSystem("${extData}/MicroMsg"), new Object[] { new NativeFileSystem("${storage}/tencent/MicroMsg") }), agAa)).qg("${extData}/MicroMsg", "ext-mm").qg("${storage}/tencent/MicroMsg", "ext-mm");
    parama.a("ext-cache", new WhiteListFileSystem(new NativeFileSystem("${extCache}"), agAb)).qg("${extCache}", "ext-cache");
    AppMethodBeat.o(238318);
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes7.jar
 * Qualified Name:     com.tencent.mm.vfs.t
 * JD-Core Version:    0.7.0.1
 */