package com.tencent.mm.f.b.a;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.report.a;
import com.tencent.mm.sdk.platformtools.Util;
import java.util.Arrays;

public final class ae
  extends a
{
  private int ggM;
  private long ggN;
  private long ggO;
  private long ggP;
  private long ggQ;
  private long ggR;
  private long ggS;
  private long ggT;
  private long ggU;
  private String ggV;
  private long ggW;
  private String ggX;
  private long ggY;
  private long ggZ;
  private long ghA;
  private long ghB;
  private long ghC;
  private long ghD;
  private long ghE;
  private long ghF;
  private long ghG;
  private int ghH;
  private String ghI;
  private long ghJ;
  private String ghK;
  private long ghL;
  private String ghM;
  private long ghN;
  private String ghO;
  private long ghP;
  private long ghQ;
  private long ghR;
  private long ghS;
  private long gha;
  private long ghb;
  private long ghc;
  private long ghd;
  private long ghe;
  private long ghf;
  private long ghg;
  private long ghh;
  private long ghi;
  private long ghj;
  private long ghk;
  private String ghl;
  private long ghm;
  private long ghn;
  private long gho;
  private long ghp;
  private long ghq;
  private long ghr;
  private long ghs;
  private long ght;
  private long ghu;
  private long ghv;
  private long ghw;
  private long ghx;
  private long ghy;
  private long ghz;
  
  public ae()
  {
    this.ggM = 0;
    this.ggN = 0L;
    this.ggO = 0L;
    this.ggP = 0L;
    this.ggQ = 0L;
    this.ggR = 0L;
    this.ggS = 0L;
    this.ggT = 0L;
    this.ggU = 0L;
    this.ggV = "";
    this.ggW = 0L;
    this.ggX = "";
    this.ggY = 0L;
    this.ggZ = 0L;
    this.gha = 0L;
    this.ghb = 0L;
    this.ghc = 0L;
    this.ghd = 0L;
    this.ghe = 0L;
    this.ghf = 0L;
    this.ghg = 0L;
    this.ghh = 0L;
    this.ghi = 0L;
    this.ghj = 0L;
    this.ghk = 0L;
    this.ghl = "";
    this.ghm = 0L;
    this.ghn = 0L;
    this.gho = 0L;
    this.ghp = 0L;
    this.ghq = 0L;
    this.ghr = 0L;
    this.ghs = 0L;
    this.ght = 0L;
    this.ghu = 0L;
    this.ghv = 0L;
    this.ghw = 0L;
    this.ghx = 0L;
    this.ghy = 0L;
    this.ghz = 0L;
    this.ghA = 0L;
    this.ghB = 0L;
    this.ghC = 0L;
    this.ghD = 0L;
    this.ghE = 0L;
    this.ghF = 0L;
    this.ghG = 0L;
    this.ghH = 0;
    this.ghI = "";
    this.ghJ = 0L;
    this.ghK = "";
    this.ghL = 0L;
    this.ghM = "";
    this.ghN = 0L;
    this.ghO = "";
    this.ghP = 0L;
    this.ghQ = 0L;
    this.ghR = 0L;
    this.ghS = 0L;
  }
  
  public ae(String paramString)
  {
    AppMethodBeat.i(149900);
    this.ggM = 0;
    this.ggN = 0L;
    this.ggO = 0L;
    this.ggP = 0L;
    this.ggQ = 0L;
    this.ggR = 0L;
    this.ggS = 0L;
    this.ggT = 0L;
    this.ggU = 0L;
    this.ggV = "";
    this.ggW = 0L;
    this.ggX = "";
    this.ggY = 0L;
    this.ggZ = 0L;
    this.gha = 0L;
    this.ghb = 0L;
    this.ghc = 0L;
    this.ghd = 0L;
    this.ghe = 0L;
    this.ghf = 0L;
    this.ghg = 0L;
    this.ghh = 0L;
    this.ghi = 0L;
    this.ghj = 0L;
    this.ghk = 0L;
    this.ghl = "";
    this.ghm = 0L;
    this.ghn = 0L;
    this.gho = 0L;
    this.ghp = 0L;
    this.ghq = 0L;
    this.ghr = 0L;
    this.ghs = 0L;
    this.ght = 0L;
    this.ghu = 0L;
    this.ghv = 0L;
    this.ghw = 0L;
    this.ghx = 0L;
    this.ghy = 0L;
    this.ghz = 0L;
    this.ghA = 0L;
    this.ghB = 0L;
    this.ghC = 0L;
    this.ghD = 0L;
    this.ghE = 0L;
    this.ghF = 0L;
    this.ghG = 0L;
    this.ghH = 0;
    this.ghI = "";
    this.ghJ = 0L;
    this.ghK = "";
    this.ghL = 0L;
    this.ghM = "";
    this.ghN = 0L;
    this.ghO = "";
    this.ghP = 0L;
    this.ghQ = 0L;
    this.ghR = 0L;
    this.ghS = 0L;
    if (paramString != null)
    {
      paramString = paramString.split(",");
      if (paramString != null)
      {
        if (paramString.length >= 59) {
          break label1088;
        }
        String[] arrayOfString = new String[59];
        Arrays.fill(arrayOfString, 0, 59, "");
        System.arraycopy(paramString, 0, arrayOfString, 0, paramString.length);
        paramString = arrayOfString;
      }
    }
    label1088:
    for (;;)
    {
      this.ggM = Util.getInt(paramString[0], 0);
      this.ggN = Util.getLong(paramString[1], 0L);
      this.ggO = Util.getLong(paramString[2], 0L);
      this.ggP = Util.getLong(paramString[3], 0L);
      this.ggQ = Util.getLong(paramString[4], 0L);
      this.ggR = Util.getLong(paramString[5], 0L);
      this.ggS = Util.getLong(paramString[6], 0L);
      this.ggT = Util.getLong(paramString[7], 0L);
      this.ggU = Util.getLong(paramString[8], 0L);
      this.ggV = z("SvrIP", paramString[9], true);
      this.ggW = Util.getLong(paramString[10], 0L);
      this.ggX = z("FileKey", paramString[11], true);
      this.ggY = Util.getLong(paramString[12], 0L);
      this.ggZ = Util.getLong(paramString[13], 0L);
      this.gha = Util.getLong(paramString[14], 0L);
      this.ghb = Util.getLong(paramString[15], 0L);
      this.ghc = Util.getLong(paramString[16], 0L);
      this.ghd = Util.getLong(paramString[17], 0L);
      this.ghe = Util.getLong(paramString[18], 0L);
      this.ghf = Util.getLong(paramString[19], 0L);
      this.ghg = Util.getLong(paramString[20], 0L);
      this.ghh = Util.getLong(paramString[21], 0L);
      this.ghi = Util.getLong(paramString[22], 0L);
      this.ghj = Util.getLong(paramString[23], 0L);
      this.ghk = Util.getLong(paramString[24], 0L);
      this.ghl = z("UUID", paramString[25], true);
      this.ghm = Util.getLong(paramString[26], 0L);
      this.ghn = Util.getLong(paramString[27], 0L);
      this.gho = Util.getLong(paramString[28], 0L);
      this.ghp = Util.getLong(paramString[29], 0L);
      this.ghq = Util.getLong(paramString[30], 0L);
      this.ghr = Util.getLong(paramString[31], 0L);
      this.ghs = Util.getLong(paramString[32], 0L);
      this.ght = Util.getLong(paramString[33], 0L);
      this.ghu = Util.getLong(paramString[34], 0L);
      this.ghv = Util.getLong(paramString[35], 0L);
      this.ghw = Util.getLong(paramString[36], 0L);
      this.ghx = Util.getLong(paramString[37], 0L);
      this.ghy = Util.getLong(paramString[38], 0L);
      this.ghz = Util.getLong(paramString[39], 0L);
      this.ghA = Util.getLong(paramString[40], 0L);
      this.ghB = Util.getLong(paramString[41], 0L);
      this.ghC = Util.getLong(paramString[42], 0L);
      this.ghD = Util.getLong(paramString[43], 0L);
      this.ghE = Util.getLong(paramString[44], 0L);
      this.ghF = Util.getLong(paramString[45], 0L);
      this.ghG = Util.getLong(paramString[46], 0L);
      this.ghH = Util.getInt(paramString[47], 0);
      this.ghI = z("UsedIp1", paramString[48], true);
      this.ghJ = Util.getLong(paramString[49], 0L);
      this.ghK = z("UsedIp2", paramString[50], true);
      this.ghL = Util.getLong(paramString[51], 0L);
      this.ghM = z("UsedIp3", paramString[52], true);
      this.ghN = Util.getLong(paramString[53], 0L);
      this.ghO = z("UsedIp4", paramString[54], true);
      this.ghP = Util.getLong(paramString[55], 0L);
      this.ghQ = Util.getLong(paramString[56], 0L);
      this.ghR = Util.getLong(paramString[57], 0L);
      this.ghS = Util.getLong(paramString[58], 0L);
      AppMethodBeat.o(149900);
      return;
    }
  }
  
  public final String agH()
  {
    AppMethodBeat.i(149901);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append(this.ggM);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggN);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggO);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggP);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggQ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggR);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggS);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggT);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggU);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggW);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggX);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggY);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ggZ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.gha);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghb);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghc);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghd);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghe);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghf);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghg);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghh);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghi);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghj);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghk);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghl);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghm);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghn);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.gho);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghp);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghq);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghr);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghs);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ght);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghu);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghv);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghw);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghx);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghy);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghz);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghB);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghC);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghD);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghE);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghF);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghG);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghH);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghI);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghJ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghL);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghM);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghN);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghO);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghP);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghQ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghR);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ghS);
    localObject = ((StringBuffer)localObject).toString();
    aWW((String)localObject);
    AppMethodBeat.o(149901);
    return localObject;
  }
  
  public final String agI()
  {
    AppMethodBeat.i(149902);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append("CientErrNo:").append(this.ggM);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpType:").append(this.ggN);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpStartTs:").append(this.ggO);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpEndTs:").append(this.ggP);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("NetType:").append(this.ggQ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileType:").append(this.ggR);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileSize:").append(this.ggS);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNErrNo:").append(this.ggT);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNOpType:").append(this.ggU);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SvrIP:").append(this.ggV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IPCount:").append(this.ggW);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileKey:").append(this.ggX);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SliceCount:").append(this.ggY);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransportSize:").append(this.ggZ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnTotalCost:").append(this.gha);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnTryTimes:").append(this.ghb);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNTransfStartTs:").append(this.ghc);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNTransfEndTs:").append(this.ghd);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsHitCache:").append(this.ghe);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CompressPicLevel:").append(this.ghf);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SrcFileSize:").append(this.ghg);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ImgSource:").append(this.ghh);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ResolutionX:").append(this.ghi);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ResolutionY:").append(this.ghj);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ReportCode:").append(this.ghk);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UUID:").append(this.ghl);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ETLTime:").append(this.ghm);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PTLTime:").append(this.ghn);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ETLSize:").append(this.gho);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PTLSize:").append(this.ghp);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SkeyFailCount:").append(this.ghq);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SKeyTimeoutCount:").append(this.ghr);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectCount:").append(this.ghs);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectTotalMS:").append(this.ght);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectAvgMS:").append(this.ghu);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectVarianceMS:").append(this.ghv);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectMinMS:").append(this.ghw);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectMaxMS:").append(this.ghx);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforCount:").append(this.ghy);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforTotalMS:").append(this.ghz);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforAvgMS:").append(this.ghA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforVarianceMS:").append(this.ghB);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforMinMS:").append(this.ghC);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforMaxMS:").append(this.ghD);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsProgressiveJPEG:").append(this.ghE);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("WaitSec:").append(this.ghF);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LastPort:").append(this.ghG);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnErrorCode:").append(this.ghH);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp1:").append(this.ghI);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort1:").append(this.ghJ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp2:").append(this.ghK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort2:").append(this.ghL);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp3:").append(this.ghM);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort3:").append(this.ghN);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp4:").append(this.ghO);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort4:").append(this.ghP);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogCreateTime:").append(this.ghQ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogReportTime:").append(this.ghR);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogReportSvrTime:").append(this.ghS);
    localObject = ((StringBuffer)localObject).toString();
    AppMethodBeat.o(149902);
    return localObject;
  }
  
  public final int getId()
  {
    return 10421;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes10.jar
 * Qualified Name:     com.tencent.mm.f.b.a.ae
 * JD-Core Version:    0.7.0.1
 */