package com.tencent.biz.pubaccount.readinjoy.common;

import com.tencent.biz.pubaccount.readinjoy.view.proteus.virtualview.common.ImageCommon;
import com.tencent.biz.pubaccount.readinjoy.view.proteus.virtualview.common.StringCommon;

public class ProteusSettingUtil
{
  public static boolean a = true;
  
  static
  {
    b();
  }
  
  public static void a() {}
  
  public static boolean a()
  {
    return a;
  }
  
  public static void b()
  {
    c();
    d();
  }
  
  private static void c()
  {
    StringCommon.registerId("cmd_dislike_click", 1001);
    StringCommon.registerId("cmd_like_click", 1002);
    StringCommon.registerId("cmd_comment_click", 1003);
    StringCommon.registerId("cmd_biu_click", 1004);
    StringCommon.registerId("cmd_topic_recommend_header_click", 1005);
    StringCommon.registerId("cmd_hot_question_header_click", 1034);
    StringCommon.registerId("cmd_follow_click", 1006);
    StringCommon.registerId("cmd_summary_click", 1007);
    StringCommon.registerId("cmd_article_wrapper_click", 1008);
    StringCommon.registerId("setArticleModel:", 1009);
    StringCommon.registerId("cmd_jump_wrapper_click", 1010);
    StringCommon.registerId("loadQQAvatar:", 1011);
    StringCommon.registerId("cmd_social_header_follow_click", 1012);
    StringCommon.registerId("cmd_topic_capsule_click", 1013);
    StringCommon.registerId("cmd_super_topic_click", 1014);
    StringCommon.registerId("cmd_read_article_click", 1015);
    StringCommon.registerId("cmd_answer_capsule_click", 1016);
    StringCommon.registerId("setCommentContent:", 1017);
    StringCommon.registerId("setCommentAllLink:", 1018);
    StringCommon.registerId("cmd_social_header_wrapper_click", 1019);
    StringCommon.registerId("cmd_users_comment_click", 1020);
    StringCommon.registerId("cmd_social_data_like_click", 1021);
    StringCommon.registerId("cmd_social_data_biu_click", 1022);
    StringCommon.registerId("cmd_avatar_click", 1023);
    StringCommon.registerId("cmd_follow_button_click", 1024);
    StringCommon.registerId("cmd_pack_bottom_click", 1026);
    StringCommon.registerId("cmd_users_comment_edit_click", 1025);
    StringCommon.registerId("cmd_friends_biu_click", 1027);
    StringCommon.registerId("cmd_account_card_click", 1028);
    StringCommon.registerId("setArticleInfo", 1029);
    StringCommon.registerId("cmd_large_video_activity_wrapper_click", 1030);
    StringCommon.registerId("setLocation:", 1031);
    StringCommon.registerId("cmd_jump_channel_bar_click", 1032);
    StringCommon.registerId("cmd_super_topic_button_click", 1033);
    StringCommon.registerId("setFeedsModel", 1035);
    StringCommon.registerId("cmd_social_header_folder_click", 1036);
    StringCommon.registerId("cmd_social_bottom_click", 1037);
    StringCommon.registerId("setFeedsModel:", 1042);
    StringCommon.registerId("cmd_large_img_click", 1043);
    StringCommon.registerId("cmd_large_video_click", 1044);
    StringCommon.registerId("cmd_privacy_capsule_click", 1038);
    StringCommon.registerId("cmd_url_click_card_report", 1039);
    StringCommon.registerId("cmd_do_nothing", 1040);
    StringCommon.registerId("cmd_url_click_no_card_report", 1041);
    StringCommon.registerId("cmd_ugc_ad_click", 1045);
    StringCommon.registerId("cmd_gallery_comment_click", 1046);
    StringCommon.registerId("cmd_gallery_share_click", 1047);
    StringCommon.registerId("progressStyle:", 1054);
    StringCommon.registerId("setDownloadBtnStyle:", 1055);
    StringCommon.registerId("cmd_comment_reply_click", 1056);
    StringCommon.registerId("cmd_comment_dot_click", 1057);
    StringCommon.registerId("defaultImage", 1058);
    StringCommon.registerId("setCommentModel:", 1059);
    StringCommon.registerId("cmd_comment_delete_click", 1060);
    StringCommon.registerId("cmd_expose_comment_click", 1061);
    StringCommon.registerId("cmd_comment_content_click", 1062);
    StringCommon.registerId("cmd_operation_click", 1063);
    StringCommon.registerId("setAwesomeCommentInfo:", 1064);
    StringCommon.registerId("cmd_header_medal_click", 1065);
    StringCommon.registerId("cmd_community_capsule_click", 1066);
    StringCommon.registerId("cmd_awesome_click", 1067);
    StringCommon.registerId("setRightMarginString:", 1068);
    StringCommon.registerId("showAdIconBorder:", 1069);
    StringCommon.registerId("setArticleModels:", 1070);
    StringCommon.registerId("cmd_native_detail_ad_negative_click", 1071);
    StringCommon.registerId("cmd_operation_banner_click", 1073);
    StringCommon.registerId("cmd_choose_comment_type_click", 1074);
    StringCommon.registerId("cmd_daily_festival_title_click", 1075);
    StringCommon.registerId("loadAvatarByUin:", 1076);
    StringCommon.registerId("loadAvatarByUrl:", 1077);
    StringCommon.registerId("setLiveStatusUrl:", 1079);
    StringCommon.registerId("setRingUrl:", 1078);
    StringCommon.registerId("cmd_expose_subcommment_one", 1080);
    StringCommon.registerId("cmd_expose_subcommment_two", 1081);
    StringCommon.registerId("cmd_native_inner_ad_cover_click", 1088);
    StringCommon.registerId("cmd_native_inner_ad_title_click", 1089);
    StringCommon.registerId("cmd_native_inner_ad_button_click", 1090);
    StringCommon.registerId("cmd_native_inner_game_button_click", 1176);
    StringCommon.registerId("cmd_native_inner_ad_icon_click", 1091);
    StringCommon.registerId("cmd_native_inner_ad_source_click", 1092);
    StringCommon.registerId("cmd_native_inner_ad_nothing_click", 1093);
    StringCommon.registerId("cmd_diversion_click", 1094);
    StringCommon.registerId("cmd_comment_media_click", 1095);
    StringCommon.registerId("cmd_guide_jump_clicked", 1096);
    StringCommon.registerId("cmd_guide_dismiss_clicked", 1097);
    StringCommon.registerId("cmd_url_click_partner_header_report", 1098);
    StringCommon.registerId("cmd_family_comment_icon_click", 1156);
    StringCommon.registerId("cmd_native_detail_ad_triple_pic_click", 1105);
    StringCommon.registerId("cmd_share_click", 1157);
    StringCommon.registerId("cmd_write_comment_click", 1158);
    StringCommon.registerId("cmd_collect_click", 1159);
    StringCommon.registerId("cmd_article_video_click", 1160);
    StringCommon.registerId("cmd_article_image_click", 1161);
    StringCommon.registerId("cmd_family_close_click", 1162);
    StringCommon.registerId("cmd_article_link_click", 1173);
    StringCommon.registerId("cmd_like_biu_fusion_click", 1172);
    StringCommon.registerId("setAdLocationStyle:", 1084);
    StringCommon.registerId("cmd_location_click", 1085);
    StringCommon.registerId("setRightImage:", 1086);
    StringCommon.registerId("setImagePadding:", 1087);
    StringCommon.registerId("setLineSpace:", 1083);
    StringCommon.registerId("setCornerUrls:", 1082);
    StringCommon.registerId("setEmotionFontSizeString:", 1191);
    StringCommon.registerId("setEmotionFontColorString:", 1192);
    StringCommon.registerId("setEmotionLineSpaceString:", 1193);
    StringCommon.registerId("setEmotionLinkColorString:", 1194);
    StringCommon.registerId("ad_title_click_in_recommend", 1099);
    StringCommon.registerId("ad_Text_click", 1100);
    StringCommon.registerId("ad_name_click_in_recommend", 1101);
    StringCommon.registerId("ad_nothing_click_in_recommend", 1102);
    StringCommon.registerId("ad_img_click", 1103);
    StringCommon.registerId("ad_download_area_click", 1104);
    StringCommon.registerId("cmd_ad_tags_click", 1195);
    StringCommon.registerId("cmd_color_icon_click", 1197);
    StringCommon.registerId("cmd_large_image_bubble_click", 1196);
    StringCommon.registerId("cmd_ad_education_advertisers_icon_click", 1199);
    StringCommon.registerId("cmd_ad_education_teacher_name_click", 1200);
    StringCommon.registerId("cmd_ad_small_game_more_click", 1120);
    StringCommon.registerId("cmd_ad_small_game1_click", 1113);
    StringCommon.registerId("cmd_ad_small_game2_click", 1114);
    StringCommon.registerId("cmd_ad_small_game3_click", 1115);
    StringCommon.registerId("cmd_ad_small_game_follow_btn_click", 1117);
    StringCommon.registerId("cmd_ad_small_game_follow_area_click", 1118);
    StringCommon.registerId("cmd_ad_small_game_default_click", 1119);
    StringCommon.registerId("cmd_ad_small_game_cell_click", 1116);
    StringCommon.registerId("ad_title_click_in_detail", 1121);
    StringCommon.registerId("ad_name_click_in_detail", 1122);
    StringCommon.registerId("ad_img_click_in_detail", 1123);
    StringCommon.registerId("ad_nothing_click_in_detail", 1126);
    StringCommon.registerId("ad_button_click_in_detail", 1124);
    StringCommon.registerId("ad_text_click_in_detail", 1125);
    StringCommon.registerId("ad_banner_author_icon_click", 1127);
    StringCommon.registerId("cmd_operation_pk_left_click", 1106);
    StringCommon.registerId("cmd_operation_pk_right_click", 1107);
    StringCommon.registerId("ad_pk_title_click", 1108);
    StringCommon.registerId("ad_pk_operate_click", 1109);
    StringCommon.registerId("ad_pk_root_click", 1110);
    StringCommon.registerId("ad_pk_btn_left_click", 1111);
    StringCommon.registerId("ad_pk_btn_right_click", 1112);
    StringCommon.registerId("cmd_ad_tag_click", 1181);
    StringCommon.registerId("ad_time_area_click", 1182);
    StringCommon.registerId("ad_name_click_in_comment", 1183);
    StringCommon.registerId("ad_item_click_in_comment", 1184);
    StringCommon.registerId("cmd_overscroll_jump_action", 1127);
    StringCommon.registerId("cmd_url_click_left_card_report", 1130);
    StringCommon.registerId("cmd_url_click_right_card_report", 1131);
    StringCommon.registerId("column_entrances_click", 1132);
    StringCommon.registerId("cmd_page_close", 1133);
    StringCommon.registerId("cmd_share_icon_click", 1134);
    StringCommon.registerId("setEdgeDragString:", 1048);
    StringCommon.registerId("setScrollJumpUrl:", 1049);
    StringCommon.registerId("setScrollTypeString:", 1050);
    StringCommon.registerId("setScrollIndicatorString:", 1051);
    StringCommon.registerId("setScrollIndicatorString:colors:", 1128);
    StringCommon.registerId("setScrollIndicatorSizeType:width:height:radius:interval:marginBottom:", 1129);
    StringCommon.registerId("setScrollBounceString:", 1052);
    StringCommon.registerId("setScrollInsetLeft:right:top:bottom:", 1053);
    StringCommon.registerId("setScrollInfiniteRoll:", 1136);
    StringCommon.registerId("setAutoRollTime:", 1135);
    StringCommon.registerId("setEdgeDragBackgroundColorString:", 1137);
    StringCommon.registerId("setEdgeDragArrowPath:", 1138);
    StringCommon.registerId("setEdgeDragHeight:type:", 1139);
    StringCommon.registerId("setEdgeDragCenterY:type:", 1140);
    StringCommon.registerId("setVideoId:", 1143);
    StringCommon.registerId("setShouldRepeat:", 1144);
    StringCommon.registerId("setShouldMute:", 1145);
    StringCommon.registerId("setCoverImageUrl:", 1142);
    StringCommon.registerId("setMediaUrl:", 1141);
    StringCommon.registerId("setVideoScaleType:", 1146);
    StringCommon.registerId("setPlayIconWidth:height:", 1147);
    StringCommon.registerId("setPlayIconUrl:", 1148);
    StringCommon.registerId("setPlayIconVisible:", 1149);
    StringCommon.registerId("setVideoId:busiType:", 1150);
    StringCommon.registerId("setPlayMode:", 1151);
    StringCommon.registerId("setGifUrl:", 1154);
    StringCommon.registerId("setGifCoverUrl:", 1163);
    StringCommon.registerId("setNeedGifUrl:", 1155);
    StringCommon.registerId("setReportPlayDuration:", 1152);
    StringCommon.registerId("setAutoPlayMode:", 1153);
    StringCommon.registerId("cmd_double_video_left_account_container_click", 1164);
    StringCommon.registerId("cmd_double_video_right_account_container_click", 1165);
    StringCommon.registerId("cmd_double_video_left_account_icon_click", 1166);
    StringCommon.registerId("cmd_double_video_right_account_icon_click", 1167);
    StringCommon.registerId("setAnimationUrl:", 1168);
    StringCommon.registerId("cmd_cover_click", 1169);
    StringCommon.registerId("cmd_zhitiao_guide_click", 1170);
    StringCommon.registerId("cmd_zhitiao_tips_click", 1171);
    StringCommon.registerId("pgc_video_jump_url", 1175);
    StringCommon.registerId("pgc_video_content_audio_click", 1174);
    StringCommon.registerId("setProgressData:", 1177);
    StringCommon.registerId("setPreBlankNum:", 1176);
    StringCommon.registerId("setPreAccountUin:", 1177);
    StringCommon.registerId("showCommentText:", 1178);
    StringCommon.registerId("cmd_image_container_click", 1179);
    StringCommon.registerId("cmd_column_capsule_click", 1180);
    StringCommon.registerId("cmd_native_detail_ad_click", 1185);
    StringCommon.registerId("cmd_id_area_right_of_img_click", 1186);
    StringCommon.registerId("cmd_native_info_status_click", 1187);
    StringCommon.registerId("cmd_native_id_view_app", 1188);
    StringCommon.registerId("cmd_biu_ad_dislike_click", 1189);
    StringCommon.registerId("cmd_biu_ad_download_click", 1190);
    StringCommon.registerId("cmd_right_dislike_click", 1198);
    StringCommon.registerId("cmd_watch_later_click", 1201);
    StringCommon.registerId("cmd_pack_container_click", 1202);
    StringCommon.registerId("cmd_pack_avatar_click", 1204);
    StringCommon.registerId("cmd_pack_follow_click", 1203);
  }
  
  private static void d()
  {
    ImageCommon.registerDrawable("mengceng.png", 2130841953);
    ImageCommon.registerDrawable("pa_video_play.png", 2130843459);
    ImageCommon.registerDrawable("rij_play_icon", 2130843459);
    ImageCommon.registerDrawable("qq_readinjoy_gallery_count", 2130846214);
    ImageCommon.registerDrawable("ReadInJoy/qq_readinjoy_gallery_count.png", 2130846214);
    ImageCommon.registerDrawable("public_account_video_profile", 2130843210);
    ImageCommon.registerDrawable("public_account_small_video_mengceng", 2130841930);
    ImageCommon.registerDrawable("like_normal", 2130846733);
    ImageCommon.registerDrawable("like_active", 2130846730);
    ImageCommon.registerDrawable("comment", 2130846728);
    ImageCommon.registerDrawable("comment_active", 2130846728);
    ImageCommon.registerDrawable("biu_icon", 2130842947);
    ImageCommon.registerDrawable("share_icon", 2130843205);
    ImageCommon.registerDrawable("biu_icon_active", 2130842947);
    ImageCommon.registerDrawable("green_v.png", 2130843088);
    ImageCommon.registerDrawable("feeds_dislike", 2130843251);
    ImageCommon.registerDrawable("topic_pre_image", 2130843116);
    ImageCommon.registerDrawable("topic_arrow_image", 2130843228);
    ImageCommon.registerDrawable("small_video_play_icon", 2130843210);
    ImageCommon.registerDrawable("readinjoy_star_postmark.png", 2130849900);
    ImageCommon.registerDrawable("qqreadinjoy_kandian_down_arrow.png", 2130846729);
    ImageCommon.registerDrawable("Base_Blue", 2130842938);
    ImageCommon.registerDrawable("Base_Grey", 2130842939);
    ImageCommon.registerDrawable("NativeArticleHeaderFollowed", 2130843095);
    ImageCommon.registerDrawable("follow_info_avator_mask", 2130842934);
    ImageCommon.registerDrawable("NativeArticleHeaderUnfollowed", 2130843246);
    ImageCommon.registerDrawable("plus", 2130843166);
    ImageCommon.registerDrawable("1pixel", 2130842890);
    ImageCommon.registerDrawable("feedback_more", 2130843074);
    ImageCommon.registerDrawable("free_netflow_icon", 2130843096);
    ImageCommon.registerDrawable("img_book_right", 2130842952);
    ImageCommon.registerDrawable("readinjoy_right_arrow.png", 2130849861);
    ImageCommon.registerDrawable("social_header_fold", 2130843173);
    ImageCommon.registerDrawable("readinjoy_privacy_vis_some.png", 2130843259);
    ImageCommon.registerDrawable("readinjoy_privacy_vis_self.png", 2130843136);
    ImageCommon.registerDrawable("rij_collection_arrow", 2130849862);
    ImageCommon.registerDrawable("feeds_dislike_grey", 2130849789);
    ImageCommon.registerDrawable("rij_comment_3dot", 2130841824);
    ImageCommon.registerDrawable("rij_comment_type_choose", 2130849764);
    ImageCommon.registerDrawable("readinjoy_comment_type_choose_highlight", 2130849765);
    ImageCommon.registerDrawable("rij_icon_notify", 2130849804);
    ImageCommon.registerDrawable("rij_comment_v", 2130849766);
    ImageCommon.registerDrawable("rij_comment_avatar_borders", 2130849748);
    ImageCommon.registerDrawable("comment_gray", 2130843277);
    ImageCommon.registerDrawable("like_normal_gray", 2130843134);
    ImageCommon.registerDrawable("like_active_gray", 2130846730);
    ImageCommon.registerDrawable("biu_icon_gray", 2130843272);
    ImageCommon.registerDrawable("pa_video_more_feeds_maintab", 2130841958);
    ImageCommon.registerDrawable("native_ad_download", 2130840263);
    ImageCommon.registerDrawable("native_ad_open", 2130840265);
    ImageCommon.registerDrawable("default_comment_avatar", 2130841899);
    ImageCommon.registerDrawable("awsome_postmark", 2130841866);
    ImageCommon.registerDrawable("video_play_icon", 2130843379);
    ImageCommon.registerDrawable("ReadInJoy/small_video_play_icon.png", 2130843210);
    ImageCommon.registerResource("ReadInJoy/Mask.png", 2130849808);
    ImageCommon.registerDrawable("feeds_native_detail_ad", 2130843150);
    ImageCommon.registerDrawable("feeds_native_detail_ad_arrow", 2130843263);
    ImageCommon.registerDrawable("feeds_native_mask", 2130843263);
    ImageCommon.registerResource("right_arrow_white", 2130843183);
    ImageCommon.registerResource("weather_refresh_white", 2130843414);
    ImageCommon.registerResource("ReadInJoy/brief_content_icon.png", 2130842953);
    ImageCommon.registerDrawable("mengceng_60.png", 2130841948);
    ImageCommon.registerDrawable("readinjoy_comment_guide_close", 2130849754);
    ImageCommon.registerDrawable("readinjoy_comment_guide_big_bg", 2130849753);
    ImageCommon.registerDrawable("share_close.png", 2130840475);
    ImageCommon.registerDrawable("ReadInJoy/ic_share.png", 2130841804);
    ImageCommon.registerDrawable("rij_multi_video_column_arrow", 2130849809);
    ImageCommon.registerDrawable("rij_multi_video_column_play", 2130843459);
    ImageCommon.registerDrawable("rij_multi_video_column_play_s", 2130849811);
    ImageCommon.registerDrawable("ReadInJoy/small_video_play_icon.png", 2130849811);
    ImageCommon.registerDrawable("edge_drag_arrow_black", 2130843489);
    ImageCommon.registerDrawable("edge_drag_arrow_white", 2130843490);
    ImageCommon.registerDrawable("NativeArticleCollectionEnable", 2130841829);
    ImageCommon.registerDrawable("NativeArticleCollectionDisable", 2130841843);
    ImageCommon.registerDrawable("NativeArticleLikeEnable", 2130841850);
    ImageCommon.registerDrawable("NativeArticleLikeDisable", 2130841845);
    ImageCommon.registerDrawable("NativeArticleShare_gray", 2130843152);
    ImageCommon.registerDrawable("NativeArticleDislike_gray", 2130841832);
    ImageCommon.registerDrawable("NativeArticleWriteComment", 2130843422);
    ImageCommon.registerDrawable("NativeArticleComment", 2130841830);
    ImageCommon.registerDrawable("NativeArticleBiu", 2130841828);
    ImageCommon.registerDrawable("biu_comment_icon", 2130842944);
    ImageCommon.registerDrawable("share_bottom_icon", 2130843204);
    ImageCommon.registerDrawable("iconarrow", 2130843185);
    ImageCommon.registerDrawable("msg_bg_card", 2130842872);
    ImageCommon.registerDrawable("video_feed_bottom_controller_bg", 2130841953);
    ImageCommon.registerDrawable("ReadInJoy/video_play_icon.png", 2130843464);
    ImageCommon.registerDrawable("NativeArticleHasBiu", 2130841838);
    ImageCommon.registerDrawable("NativeArticleBiu", 2130841828);
    ImageCommon.registerDrawable("poly_topic", 2130843230);
    ImageCommon.registerDrawable("poly_gallery", 2130846214);
    ImageCommon.registerDrawable("poly_article", 2130842926);
    ImageCommon.registerDrawable("ReadInJoy/rij_play_icon.png", 2130843459);
    ImageCommon.registerDrawable("video_audio_mute", 2130843267);
    ImageCommon.registerDrawable("video_audio_speak", 2130843268);
    ImageCommon.registerDrawable("biu_comment", 2130841872);
    ImageCommon.registerDrawable("biu_comment_like_normal", 2130842946);
    ImageCommon.registerDrawable("biu_comment_like_active", 2130842945);
    ImageCommon.registerDrawable("readinjoy_column_icon", 2130849745);
    ImageCommon.registerDrawable("readinjoy_column_arrow", 2130842984);
    ImageCommon.registerDrawable("readinjoy_column_icon_white", 2130849746);
    ImageCommon.registerDrawable("more_image_icon.png", 2130843139);
    ImageCommon.registerDrawable("column_icon.png", 2130842986);
    ImageCommon.registerDrawable("column_arrow.png", 2130842984);
    ImageCommon.registerDrawable("rij_play_icon.png", 2130843459);
    ImageCommon.registerDrawable("rij_hot_comment_title_icon", 2130849801);
    ImageCommon.registerDrawable("rij_new_comment_title_icon", 2130849812);
    ImageCommon.registerDrawable("rij_comment_menu_hot_icon", 2130849757);
    ImageCommon.registerDrawable("rij_comment_menu_new_icon", 2130849758);
    ImageCommon.registerDrawable("rij_comment_sticky_icon", 2130849763);
    ImageCommon.registerDrawable("article_no_img", 2130846215);
    ImageCommon.registerDrawable("rij_commentBiu_backgroundColor", 2130849749);
    ImageCommon.registerDrawable("social_bottom_style_a_share", 2130841931);
    ImageCommon.registerDrawable("social_bottom_style_a_comment", 2130841932);
    ImageCommon.registerDrawable("dislike_img", 2130843251);
    ImageCommon.registerDrawable("social_bottom_style_a_like_active", 2130841935);
    ImageCommon.registerDrawable("social_bottom_style_a_like", 2130841934);
    ImageCommon.registerDrawable("watch_later", 2130841916);
    ImageCommon.registerDrawable("watch_later_active", 2130841917);
    ImageCommon.registerDrawable("watch_later_white", 2130841919);
    ImageCommon.registerDrawable("watch_later_active_white", 2130841918);
    ImageCommon.registerDrawable("follow_bg", 2130849996);
    ImageCommon.registerDrawable("unfollow_bg", 2130849997);
    ImageCommon.registerDrawable("dislike_right_bottom", 2130849779);
    ImageCommon.registerDrawable("dislike_x", 2130849780);
    ImageCommon.registerDrawable("unfollow_bg", 2130849790);
    ImageCommon.registerDrawable("follow_bg", 2130849794);
    ImageCommon.registerDrawable("follow_bg_white", 2130849795);
    ImageCommon.registerDrawable("readinjoy_ad_small_game", 2130849716);
    ImageCommon.registerDrawable("readinjoy_comment_author_tag", 2130849747);
    ImageCommon.registerDrawable("readinjoy_comment_follow_tag", 2130849752);
    ImageCommon.registerDrawable("left_top_round_corner", 2130843132);
    ImageCommon.registerDrawable("left_bottom_round_corner", 2130843131);
    ImageCommon.registerDrawable("right_top_round_corner", 2130843186);
    ImageCommon.registerDrawable("right_bottom_round_corner", 2130843184);
    ImageCommon.registerDrawable("feeds_dislike_light", 2130843252);
    ImageCommon.registerDrawable("comment_icon_white", 2130843211);
    ImageCommon.registerDrawable("rij_hot_search_arrow", 2130849998);
    ImageCommon.registerDrawable("rij_comment_topic_icon", 2130843022);
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes3.jar
 * Qualified Name:     com.tencent.biz.pubaccount.readinjoy.common.ProteusSettingUtil
 * JD-Core Version:    0.7.0.1
 */