package com.tencent.mm.g.b.a;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.report.a;
import com.tencent.mm.sdk.platformtools.bt;
import java.util.Arrays;

public final class h
  extends a
{
  private int dFK;
  private long dFL;
  private long dFM;
  private long dFN;
  private long dFO;
  private long dFP;
  private long dFQ;
  private long dFR;
  private long dFS;
  private String dFT;
  private long dFU;
  private String dFV;
  private long dFW;
  private long dFX;
  private long dFY;
  private long dFZ;
  private long dGA;
  private long dGB;
  private long dGC;
  private long dGD;
  private long dGE;
  private int dGF;
  private String dGG;
  private long dGH;
  private String dGI;
  private long dGJ;
  private String dGK;
  private long dGL;
  private String dGM;
  private long dGN;
  private long dGO;
  private long dGP;
  private long dGQ;
  private long dGa;
  private long dGb;
  private long dGc;
  private long dGd;
  private long dGe;
  private long dGf;
  private long dGg;
  private long dGh;
  private long dGi;
  private String dGj;
  private long dGk;
  private long dGl;
  private long dGm;
  private long dGn;
  private long dGo;
  private long dGp;
  private long dGq;
  private long dGr;
  private long dGs;
  private long dGt;
  private long dGu;
  private long dGv;
  private long dGw;
  private long dGx;
  private long dGy;
  private long dGz;
  
  public h()
  {
    this.dFK = 0;
    this.dFL = 0L;
    this.dFM = 0L;
    this.dFN = 0L;
    this.dFO = 0L;
    this.dFP = 0L;
    this.dFQ = 0L;
    this.dFR = 0L;
    this.dFS = 0L;
    this.dFT = "";
    this.dFU = 0L;
    this.dFV = "";
    this.dFW = 0L;
    this.dFX = 0L;
    this.dFY = 0L;
    this.dFZ = 0L;
    this.dGa = 0L;
    this.dGb = 0L;
    this.dGc = 0L;
    this.dGd = 0L;
    this.dGe = 0L;
    this.dGf = 0L;
    this.dGg = 0L;
    this.dGh = 0L;
    this.dGi = 0L;
    this.dGj = "";
    this.dGk = 0L;
    this.dGl = 0L;
    this.dGm = 0L;
    this.dGn = 0L;
    this.dGo = 0L;
    this.dGp = 0L;
    this.dGq = 0L;
    this.dGr = 0L;
    this.dGs = 0L;
    this.dGt = 0L;
    this.dGu = 0L;
    this.dGv = 0L;
    this.dGw = 0L;
    this.dGx = 0L;
    this.dGy = 0L;
    this.dGz = 0L;
    this.dGA = 0L;
    this.dGB = 0L;
    this.dGC = 0L;
    this.dGD = 0L;
    this.dGE = 0L;
    this.dGF = 0;
    this.dGG = "";
    this.dGH = 0L;
    this.dGI = "";
    this.dGJ = 0L;
    this.dGK = "";
    this.dGL = 0L;
    this.dGM = "";
    this.dGN = 0L;
    this.dGO = 0L;
    this.dGP = 0L;
    this.dGQ = 0L;
  }
  
  public h(String paramString)
  {
    AppMethodBeat.i(149900);
    this.dFK = 0;
    this.dFL = 0L;
    this.dFM = 0L;
    this.dFN = 0L;
    this.dFO = 0L;
    this.dFP = 0L;
    this.dFQ = 0L;
    this.dFR = 0L;
    this.dFS = 0L;
    this.dFT = "";
    this.dFU = 0L;
    this.dFV = "";
    this.dFW = 0L;
    this.dFX = 0L;
    this.dFY = 0L;
    this.dFZ = 0L;
    this.dGa = 0L;
    this.dGb = 0L;
    this.dGc = 0L;
    this.dGd = 0L;
    this.dGe = 0L;
    this.dGf = 0L;
    this.dGg = 0L;
    this.dGh = 0L;
    this.dGi = 0L;
    this.dGj = "";
    this.dGk = 0L;
    this.dGl = 0L;
    this.dGm = 0L;
    this.dGn = 0L;
    this.dGo = 0L;
    this.dGp = 0L;
    this.dGq = 0L;
    this.dGr = 0L;
    this.dGs = 0L;
    this.dGt = 0L;
    this.dGu = 0L;
    this.dGv = 0L;
    this.dGw = 0L;
    this.dGx = 0L;
    this.dGy = 0L;
    this.dGz = 0L;
    this.dGA = 0L;
    this.dGB = 0L;
    this.dGC = 0L;
    this.dGD = 0L;
    this.dGE = 0L;
    this.dGF = 0;
    this.dGG = "";
    this.dGH = 0L;
    this.dGI = "";
    this.dGJ = 0L;
    this.dGK = "";
    this.dGL = 0L;
    this.dGM = "";
    this.dGN = 0L;
    this.dGO = 0L;
    this.dGP = 0L;
    this.dGQ = 0L;
    if (paramString != null)
    {
      paramString = paramString.split(",");
      if (paramString != null)
      {
        if (paramString.length >= 59) {
          break label1088;
        }
        String[] arrayOfString = new String[59];
        Arrays.fill(arrayOfString, 0, 59, "");
        System.arraycopy(paramString, 0, arrayOfString, 0, paramString.length);
        paramString = arrayOfString;
      }
    }
    label1088:
    for (;;)
    {
      this.dFK = bt.getInt(paramString[0], 0);
      this.dFL = bt.getLong(paramString[1], 0L);
      this.dFM = bt.getLong(paramString[2], 0L);
      this.dFN = bt.getLong(paramString[3], 0L);
      this.dFO = bt.getLong(paramString[4], 0L);
      this.dFP = bt.getLong(paramString[5], 0L);
      this.dFQ = bt.getLong(paramString[6], 0L);
      this.dFR = bt.getLong(paramString[7], 0L);
      this.dFS = bt.getLong(paramString[8], 0L);
      this.dFT = t("SvrIP", paramString[9], true);
      this.dFU = bt.getLong(paramString[10], 0L);
      this.dFV = t("FileKey", paramString[11], true);
      this.dFW = bt.getLong(paramString[12], 0L);
      this.dFX = bt.getLong(paramString[13], 0L);
      this.dFY = bt.getLong(paramString[14], 0L);
      this.dFZ = bt.getLong(paramString[15], 0L);
      this.dGa = bt.getLong(paramString[16], 0L);
      this.dGb = bt.getLong(paramString[17], 0L);
      this.dGc = bt.getLong(paramString[18], 0L);
      this.dGd = bt.getLong(paramString[19], 0L);
      this.dGe = bt.getLong(paramString[20], 0L);
      this.dGf = bt.getLong(paramString[21], 0L);
      this.dGg = bt.getLong(paramString[22], 0L);
      this.dGh = bt.getLong(paramString[23], 0L);
      this.dGi = bt.getLong(paramString[24], 0L);
      this.dGj = t("UUID", paramString[25], true);
      this.dGk = bt.getLong(paramString[26], 0L);
      this.dGl = bt.getLong(paramString[27], 0L);
      this.dGm = bt.getLong(paramString[28], 0L);
      this.dGn = bt.getLong(paramString[29], 0L);
      this.dGo = bt.getLong(paramString[30], 0L);
      this.dGp = bt.getLong(paramString[31], 0L);
      this.dGq = bt.getLong(paramString[32], 0L);
      this.dGr = bt.getLong(paramString[33], 0L);
      this.dGs = bt.getLong(paramString[34], 0L);
      this.dGt = bt.getLong(paramString[35], 0L);
      this.dGu = bt.getLong(paramString[36], 0L);
      this.dGv = bt.getLong(paramString[37], 0L);
      this.dGw = bt.getLong(paramString[38], 0L);
      this.dGx = bt.getLong(paramString[39], 0L);
      this.dGy = bt.getLong(paramString[40], 0L);
      this.dGz = bt.getLong(paramString[41], 0L);
      this.dGA = bt.getLong(paramString[42], 0L);
      this.dGB = bt.getLong(paramString[43], 0L);
      this.dGC = bt.getLong(paramString[44], 0L);
      this.dGD = bt.getLong(paramString[45], 0L);
      this.dGE = bt.getLong(paramString[46], 0L);
      this.dGF = bt.getInt(paramString[47], 0);
      this.dGG = t("UsedIp1", paramString[48], true);
      this.dGH = bt.getLong(paramString[49], 0L);
      this.dGI = t("UsedIp2", paramString[50], true);
      this.dGJ = bt.getLong(paramString[51], 0L);
      this.dGK = t("UsedIp3", paramString[52], true);
      this.dGL = bt.getLong(paramString[53], 0L);
      this.dGM = t("UsedIp4", paramString[54], true);
      this.dGN = bt.getLong(paramString[55], 0L);
      this.dGO = bt.getLong(paramString[56], 0L);
      this.dGP = bt.getLong(paramString[57], 0L);
      this.dGQ = bt.getLong(paramString[58], 0L);
      AppMethodBeat.o(149900);
      return;
    }
  }
  
  public final String PV()
  {
    AppMethodBeat.i(149901);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append(this.dFK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFL);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFM);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFN);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFO);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFP);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFQ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFR);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFS);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFT);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFU);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFW);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFX);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFY);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dFZ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGa);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGb);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGc);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGd);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGe);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGf);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGg);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGh);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGi);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGj);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGk);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGl);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGm);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGn);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGo);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGp);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGq);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGr);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGs);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGt);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGu);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGv);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGw);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGx);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGy);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGz);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGB);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGC);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGD);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGE);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGF);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGG);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGH);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGI);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGJ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGL);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGM);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGN);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGO);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGP);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dGQ);
    localObject = ((StringBuffer)localObject).toString();
    ams((String)localObject);
    AppMethodBeat.o(149901);
    return localObject;
  }
  
  public final String PW()
  {
    AppMethodBeat.i(149902);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append("CientErrNo:").append(this.dFK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpType:").append(this.dFL);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpStartTs:").append(this.dFM);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpEndTs:").append(this.dFN);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("NetType:").append(this.dFO);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileType:").append(this.dFP);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileSize:").append(this.dFQ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNErrNo:").append(this.dFR);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNOpType:").append(this.dFS);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SvrIP:").append(this.dFT);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IPCount:").append(this.dFU);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileKey:").append(this.dFV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SliceCount:").append(this.dFW);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransportSize:").append(this.dFX);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnTotalCost:").append(this.dFY);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnTryTimes:").append(this.dFZ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNTransfStartTs:").append(this.dGa);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNTransfEndTs:").append(this.dGb);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsHitCache:").append(this.dGc);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CompressPicLevel:").append(this.dGd);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SrcFileSize:").append(this.dGe);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ImgSource:").append(this.dGf);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ResolutionX:").append(this.dGg);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ResolutionY:").append(this.dGh);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ReportCode:").append(this.dGi);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UUID:").append(this.dGj);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ETLTime:").append(this.dGk);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PTLTime:").append(this.dGl);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ETLSize:").append(this.dGm);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PTLSize:").append(this.dGn);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SkeyFailCount:").append(this.dGo);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SKeyTimeoutCount:").append(this.dGp);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectCount:").append(this.dGq);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectTotalMS:").append(this.dGr);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectAvgMS:").append(this.dGs);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectVarianceMS:").append(this.dGt);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectMinMS:").append(this.dGu);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectMaxMS:").append(this.dGv);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforCount:").append(this.dGw);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforTotalMS:").append(this.dGx);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforAvgMS:").append(this.dGy);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforVarianceMS:").append(this.dGz);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforMinMS:").append(this.dGA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforMaxMS:").append(this.dGB);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsProgressiveJPEG:").append(this.dGC);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("WaitSec:").append(this.dGD);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LastPort:").append(this.dGE);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnErrorCode:").append(this.dGF);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp1:").append(this.dGG);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort1:").append(this.dGH);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp2:").append(this.dGI);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort2:").append(this.dGJ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp3:").append(this.dGK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort3:").append(this.dGL);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp4:").append(this.dGM);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort4:").append(this.dGN);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogCreateTime:").append(this.dGO);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogReportTime:").append(this.dGP);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogReportSvrTime:").append(this.dGQ);
    localObject = ((StringBuffer)localObject).toString();
    AppMethodBeat.o(149902);
    return localObject;
  }
  
  public final int getId()
  {
    return 10421;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes3.jar
 * Qualified Name:     com.tencent.mm.g.b.a.h
 * JD-Core Version:    0.7.0.1
 */