package com.tencent.mm.g.b.a;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.report.a;
import com.tencent.mm.sdk.platformtools.bs;
import java.util.Arrays;

public final class h
  extends a
{
  private long dDA;
  private long dDB;
  private long dDC;
  private long dDD;
  private long dDE;
  private long dDF;
  private String dDG;
  private long dDH;
  private String dDI;
  private long dDJ;
  private long dDK;
  private long dDL;
  private long dDM;
  private long dDN;
  private long dDO;
  private long dDP;
  private long dDQ;
  private long dDR;
  private long dDS;
  private long dDT;
  private long dDU;
  private long dDV;
  private String dDW;
  private long dDX;
  private long dDY;
  private long dDZ;
  private int dDx;
  private long dDy;
  private long dDz;
  private long dEA;
  private long dEB;
  private long dEC;
  private long dED;
  private long dEa;
  private long dEb;
  private long dEc;
  private long dEd;
  private long dEe;
  private long dEf;
  private long dEg;
  private long dEh;
  private long dEi;
  private long dEj;
  private long dEk;
  private long dEl;
  private long dEm;
  private long dEn;
  private long dEo;
  private long dEp;
  private long dEq;
  private long dEr;
  private int dEs;
  private String dEt;
  private long dEu;
  private String dEv;
  private long dEw;
  private String dEx;
  private long dEy;
  private String dEz;
  
  public h()
  {
    this.dDx = 0;
    this.dDy = 0L;
    this.dDz = 0L;
    this.dDA = 0L;
    this.dDB = 0L;
    this.dDC = 0L;
    this.dDD = 0L;
    this.dDE = 0L;
    this.dDF = 0L;
    this.dDG = "";
    this.dDH = 0L;
    this.dDI = "";
    this.dDJ = 0L;
    this.dDK = 0L;
    this.dDL = 0L;
    this.dDM = 0L;
    this.dDN = 0L;
    this.dDO = 0L;
    this.dDP = 0L;
    this.dDQ = 0L;
    this.dDR = 0L;
    this.dDS = 0L;
    this.dDT = 0L;
    this.dDU = 0L;
    this.dDV = 0L;
    this.dDW = "";
    this.dDX = 0L;
    this.dDY = 0L;
    this.dDZ = 0L;
    this.dEa = 0L;
    this.dEb = 0L;
    this.dEc = 0L;
    this.dEd = 0L;
    this.dEe = 0L;
    this.dEf = 0L;
    this.dEg = 0L;
    this.dEh = 0L;
    this.dEi = 0L;
    this.dEj = 0L;
    this.dEk = 0L;
    this.dEl = 0L;
    this.dEm = 0L;
    this.dEn = 0L;
    this.dEo = 0L;
    this.dEp = 0L;
    this.dEq = 0L;
    this.dEr = 0L;
    this.dEs = 0;
    this.dEt = "";
    this.dEu = 0L;
    this.dEv = "";
    this.dEw = 0L;
    this.dEx = "";
    this.dEy = 0L;
    this.dEz = "";
    this.dEA = 0L;
    this.dEB = 0L;
    this.dEC = 0L;
    this.dED = 0L;
  }
  
  public h(String paramString)
  {
    AppMethodBeat.i(149900);
    this.dDx = 0;
    this.dDy = 0L;
    this.dDz = 0L;
    this.dDA = 0L;
    this.dDB = 0L;
    this.dDC = 0L;
    this.dDD = 0L;
    this.dDE = 0L;
    this.dDF = 0L;
    this.dDG = "";
    this.dDH = 0L;
    this.dDI = "";
    this.dDJ = 0L;
    this.dDK = 0L;
    this.dDL = 0L;
    this.dDM = 0L;
    this.dDN = 0L;
    this.dDO = 0L;
    this.dDP = 0L;
    this.dDQ = 0L;
    this.dDR = 0L;
    this.dDS = 0L;
    this.dDT = 0L;
    this.dDU = 0L;
    this.dDV = 0L;
    this.dDW = "";
    this.dDX = 0L;
    this.dDY = 0L;
    this.dDZ = 0L;
    this.dEa = 0L;
    this.dEb = 0L;
    this.dEc = 0L;
    this.dEd = 0L;
    this.dEe = 0L;
    this.dEf = 0L;
    this.dEg = 0L;
    this.dEh = 0L;
    this.dEi = 0L;
    this.dEj = 0L;
    this.dEk = 0L;
    this.dEl = 0L;
    this.dEm = 0L;
    this.dEn = 0L;
    this.dEo = 0L;
    this.dEp = 0L;
    this.dEq = 0L;
    this.dEr = 0L;
    this.dEs = 0;
    this.dEt = "";
    this.dEu = 0L;
    this.dEv = "";
    this.dEw = 0L;
    this.dEx = "";
    this.dEy = 0L;
    this.dEz = "";
    this.dEA = 0L;
    this.dEB = 0L;
    this.dEC = 0L;
    this.dED = 0L;
    if (paramString != null)
    {
      paramString = paramString.split(",");
      if (paramString != null)
      {
        if (paramString.length >= 59) {
          break label1088;
        }
        String[] arrayOfString = new String[59];
        Arrays.fill(arrayOfString, 0, 59, "");
        System.arraycopy(paramString, 0, arrayOfString, 0, paramString.length);
        paramString = arrayOfString;
      }
    }
    label1088:
    for (;;)
    {
      this.dDx = bs.getInt(paramString[0], 0);
      this.dDy = bs.getLong(paramString[1], 0L);
      this.dDz = bs.getLong(paramString[2], 0L);
      this.dDA = bs.getLong(paramString[3], 0L);
      this.dDB = bs.getLong(paramString[4], 0L);
      this.dDC = bs.getLong(paramString[5], 0L);
      this.dDD = bs.getLong(paramString[6], 0L);
      this.dDE = bs.getLong(paramString[7], 0L);
      this.dDF = bs.getLong(paramString[8], 0L);
      this.dDG = t("SvrIP", paramString[9], true);
      this.dDH = bs.getLong(paramString[10], 0L);
      this.dDI = t("FileKey", paramString[11], true);
      this.dDJ = bs.getLong(paramString[12], 0L);
      this.dDK = bs.getLong(paramString[13], 0L);
      this.dDL = bs.getLong(paramString[14], 0L);
      this.dDM = bs.getLong(paramString[15], 0L);
      this.dDN = bs.getLong(paramString[16], 0L);
      this.dDO = bs.getLong(paramString[17], 0L);
      this.dDP = bs.getLong(paramString[18], 0L);
      this.dDQ = bs.getLong(paramString[19], 0L);
      this.dDR = bs.getLong(paramString[20], 0L);
      this.dDS = bs.getLong(paramString[21], 0L);
      this.dDT = bs.getLong(paramString[22], 0L);
      this.dDU = bs.getLong(paramString[23], 0L);
      this.dDV = bs.getLong(paramString[24], 0L);
      this.dDW = t("UUID", paramString[25], true);
      this.dDX = bs.getLong(paramString[26], 0L);
      this.dDY = bs.getLong(paramString[27], 0L);
      this.dDZ = bs.getLong(paramString[28], 0L);
      this.dEa = bs.getLong(paramString[29], 0L);
      this.dEb = bs.getLong(paramString[30], 0L);
      this.dEc = bs.getLong(paramString[31], 0L);
      this.dEd = bs.getLong(paramString[32], 0L);
      this.dEe = bs.getLong(paramString[33], 0L);
      this.dEf = bs.getLong(paramString[34], 0L);
      this.dEg = bs.getLong(paramString[35], 0L);
      this.dEh = bs.getLong(paramString[36], 0L);
      this.dEi = bs.getLong(paramString[37], 0L);
      this.dEj = bs.getLong(paramString[38], 0L);
      this.dEk = bs.getLong(paramString[39], 0L);
      this.dEl = bs.getLong(paramString[40], 0L);
      this.dEm = bs.getLong(paramString[41], 0L);
      this.dEn = bs.getLong(paramString[42], 0L);
      this.dEo = bs.getLong(paramString[43], 0L);
      this.dEp = bs.getLong(paramString[44], 0L);
      this.dEq = bs.getLong(paramString[45], 0L);
      this.dEr = bs.getLong(paramString[46], 0L);
      this.dEs = bs.getInt(paramString[47], 0);
      this.dEt = t("UsedIp1", paramString[48], true);
      this.dEu = bs.getLong(paramString[49], 0L);
      this.dEv = t("UsedIp2", paramString[50], true);
      this.dEw = bs.getLong(paramString[51], 0L);
      this.dEx = t("UsedIp3", paramString[52], true);
      this.dEy = bs.getLong(paramString[53], 0L);
      this.dEz = t("UsedIp4", paramString[54], true);
      this.dEA = bs.getLong(paramString[55], 0L);
      this.dEB = bs.getLong(paramString[56], 0L);
      this.dEC = bs.getLong(paramString[57], 0L);
      this.dED = bs.getLong(paramString[58], 0L);
      AppMethodBeat.o(149900);
      return;
    }
  }
  
  public final String PR()
  {
    AppMethodBeat.i(149901);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append(this.dDx);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDy);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDz);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDB);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDC);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDD);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDE);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDF);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDG);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDH);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDI);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDJ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDL);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDM);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDN);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDO);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDP);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDQ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDR);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDS);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDT);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDU);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDW);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDX);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDY);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dDZ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEa);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEb);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEc);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEd);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEe);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEf);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEg);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEh);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEi);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEj);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEk);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEl);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEm);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEn);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEo);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEp);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEq);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEr);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEs);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEt);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEu);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEv);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEw);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEx);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEy);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEz);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEB);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dEC);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.dED);
    localObject = ((StringBuffer)localObject).toString();
    arz((String)localObject);
    AppMethodBeat.o(149901);
    return localObject;
  }
  
  public final String PS()
  {
    AppMethodBeat.i(149902);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append("CientErrNo:").append(this.dDx);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpType:").append(this.dDy);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpStartTs:").append(this.dDz);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpEndTs:").append(this.dDA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("NetType:").append(this.dDB);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileType:").append(this.dDC);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileSize:").append(this.dDD);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNErrNo:").append(this.dDE);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNOpType:").append(this.dDF);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SvrIP:").append(this.dDG);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IPCount:").append(this.dDH);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileKey:").append(this.dDI);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SliceCount:").append(this.dDJ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransportSize:").append(this.dDK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnTotalCost:").append(this.dDL);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnTryTimes:").append(this.dDM);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNTransfStartTs:").append(this.dDN);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNTransfEndTs:").append(this.dDO);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsHitCache:").append(this.dDP);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CompressPicLevel:").append(this.dDQ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SrcFileSize:").append(this.dDR);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ImgSource:").append(this.dDS);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ResolutionX:").append(this.dDT);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ResolutionY:").append(this.dDU);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ReportCode:").append(this.dDV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UUID:").append(this.dDW);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ETLTime:").append(this.dDX);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PTLTime:").append(this.dDY);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ETLSize:").append(this.dDZ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PTLSize:").append(this.dEa);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SkeyFailCount:").append(this.dEb);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SKeyTimeoutCount:").append(this.dEc);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectCount:").append(this.dEd);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectTotalMS:").append(this.dEe);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectAvgMS:").append(this.dEf);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectVarianceMS:").append(this.dEg);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectMinMS:").append(this.dEh);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectMaxMS:").append(this.dEi);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforCount:").append(this.dEj);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforTotalMS:").append(this.dEk);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforAvgMS:").append(this.dEl);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforVarianceMS:").append(this.dEm);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforMinMS:").append(this.dEn);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforMaxMS:").append(this.dEo);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsProgressiveJPEG:").append(this.dEp);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("WaitSec:").append(this.dEq);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LastPort:").append(this.dEr);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnErrorCode:").append(this.dEs);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp1:").append(this.dEt);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort1:").append(this.dEu);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp2:").append(this.dEv);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort2:").append(this.dEw);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp3:").append(this.dEx);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort3:").append(this.dEy);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp4:").append(this.dEz);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort4:").append(this.dEA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogCreateTime:").append(this.dEB);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogReportTime:").append(this.dEC);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogReportSvrTime:").append(this.dED);
    localObject = ((StringBuffer)localObject).toString();
    AppMethodBeat.o(149902);
    return localObject;
  }
  
  public final int getId()
  {
    return 10421;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes7.jar
 * Qualified Name:     com.tencent.mm.g.b.a.h
 * JD-Core Version:    0.7.0.1
 */