package com.tencent.mm.sensitive.business;

import android.content.Context;
import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.sdk.platformtools.MMApplicationContext;
import com.tencent.mm.sensitive.d.a;
import com.tencent.mm.sensitive.d.c;
import com.tencent.mm.sensitive.j.c;
import com.tencent.mm.sensitive.j.d;
import java.util.HashMap;
import java.util.Map;
import kotlin.Metadata;
import kotlin.a.p;
import kotlin.ah;
import kotlin.g.b.s;

@Metadata(d1={""}, d2={"Lcom/tencent/mm/sensitive/business/PermissionBusinessConfig;", "", "()V", "BUSINESS_NAME_MAP", "Ljava/util/HashMap;", "", "Lkotlin/collections/HashMap;", "getBUSINESS_NAME_MAP", "()Ljava/util/HashMap;", "PERMISSION_MAP", "Lcom/tencent/mm/sensitive/IPluginSensitive$PERMISSION;", "getPERMISSION_MAP", "PERMISSION_NAME_MAP", "getPERMISSION_NAME_MAP", "permissionBusinessConfigMap", "Lcom/tencent/mm/sensitive/business/PermissionBusinessConfig$PermissionConfigItem;", "getPermissionBusinessConfigMap", "BusinessConfigItem", "PermissionConfigItem", "sensitive_release"}, k=1, mv={1, 5, 1}, xi=48)
public final class a
{
  public static final a acuK;
  private static final HashMap<d.c, a.b> acuL;
  private static final HashMap<String, d.c> acuM;
  private static final HashMap<String, String> acuN;
  private static final HashMap<String, String> acuO;
  
  static
  {
    AppMethodBeat.i(241103);
    acuK = new a();
    Object localObject1 = new HashMap();
    acuL = (HashMap)localObject1;
    Object localObject2 = (Map)localObject1;
    Object localObject3 = d.c.actu;
    Object localObject4 = new a.b();
    ((a.b)localObject4).acuT = Integer.valueOf(j.d.setting_permission_first_dialog_location_default_desc);
    ((a.b)localObject4).acuU = Integer.valueOf(j.c.icons_outlined_location);
    ((Map)((a.b)localObject4).acuV).put(d.a.acsJ, new a.a(j.d.setting_permission_location_chatting_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsK, new a.a(j.d.setting_permission_location_radar_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsL, new a.a(j.d.setting_permission_location_face2face_group_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsM, new a.a(j.d.setting_permission_location_sns_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsN, new a.a(j.d.setting_permission_location_finder_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, p.listOf("com.tencent.mm.plugin.finder.ui.FinderHomeAffinityUI"), 4));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsO, new a.a(j.d.setting_permission_location_live_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsP, new a.a(j.d.setting_permission_location_scan_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsQ, new a.a(j.d.setting_permission_location_shake_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsR, new a.a(j.d.setting_permission_location_story_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsS, new a.a(j.d.setting_permission_location_search_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsT, new a.a(j.d.setting_permission_location_nearby_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsU, new a.a(j.d.setting_permission_location_game_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsW, new a.a(j.d.setting_permission_location_mine_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsX, new a.a(j.d.setting_permission_location_status_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsY, new a.a(j.d.setting_permission_location_fav_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, p.listOf(new String[] { "com.tencent.mm.plugin.finder.feed.ui.FinderLiveVisitorWithoutAffinityUI", "com.tencent.mm.plugin.finder.feed.ui.FinderLiveAnchorWithoutAffinityUI" }), 4));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsZ, new a.a(j.d.setting_permission_location_card_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actc, new a.a(j.d.setting_permission_location_wifi_info_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actd, new a.a(j.d.setting_permission_location_pay_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 8));
    ((Map)((a.b)localObject4).acuV).put(d.a.actn, new a.a(j.d.setting_permission_location_wechatout_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actp, new a.a(-1, -1, false, null, 8));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsV, new a.a(j.d.setting_permission_location_nearby_appbrand_switch_desc, j.d.setting_permission_first_dialog_location_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actr, new a.a(j.d.setting_permission_location_olympic_torch_switch_desc, -1, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acte, new a.a(-1, -1, false, p.listOf(".ui.chatting.ChattingBizView"), 4));
    ah localah = ah.aiuX;
    ((Map)localObject2).put(localObject3, localObject4);
    localObject2 = (Map)localObject1;
    localObject3 = d.c.actv;
    localObject4 = new a.b();
    ((a.b)localObject4).acuT = Integer.valueOf(j.d.setting_permission_first_dialog_contact_default_desc);
    ((a.b)localObject4).acuU = Integer.valueOf(j.c.icons_outlined_contacts);
    ((Map)((a.b)localObject4).acuV).put(d.a.actl, new a.a(j.d.setting_permission_contact_add_contact_switch_desc, -1, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsW, new a.a(j.d.setting_permission_contact_mine_switch_desc, -1, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actn, new a.a(j.d.setting_permission_contact_wechatout_switch_desc, -1, false, null, 12));
    localah = ah.aiuX;
    ((Map)localObject2).put(localObject3, localObject4);
    localObject2 = (Map)localObject1;
    localObject3 = d.c.actw;
    localObject4 = new a.b();
    ((a.b)localObject4).acuT = Integer.valueOf(j.d.setting_permission_first_dialog_storage_default_desc);
    ((a.b)localObject4).acuU = Integer.valueOf(j.c.icons_outlined_folder);
    ((Map)((a.b)localObject4).acuV).put(d.a.acsJ, new a.a(j.d.setting_permission_storage_chatting_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actm, new a.a(j.d.setting_permission_storage_contact_remark_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsM, new a.a(j.d.setting_permission_storage_sns_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsN, new a.a(j.d.setting_permission_storage_finder_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsO, new a.a(j.d.setting_permission_storage_live_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsP, new a.a(j.d.setting_permission_storage_scan_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsQ, new a.a(j.d.setting_permission_storage_shake_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsW, new a.a(j.d.setting_permission_storage_mine_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsX, new a.a(j.d.setting_permission_storage_status_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsY, new a.a(j.d.setting_permission_storage_fav_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acta, new a.a(j.d.setting_permission_storage_musicplayer_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acth, new a.a(j.d.setting_permission_storage_emoji_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acti, new a.a(j.d.setting_permission_storage_sport_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actj, new a.a(j.d.setting_permission_storage_mail_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acto, new a.a(j.d.setting_permission_storage_savefile_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actd, new a.a(-1, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 8));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsU, new a.a(j.d.setting_permission_storage_game_switch_desc, j.d.setting_permission_first_dialog_storage_default_desc_suffix, false, null, 12));
    localah = ah.aiuX;
    ((Map)localObject2).put(localObject3, localObject4);
    localObject2 = (Map)localObject1;
    localObject3 = d.c.actx;
    localObject4 = new a.b();
    ((a.b)localObject4).acuT = Integer.valueOf(j.d.setting_permission_first_dialog_camera_default_desc);
    ((a.b)localObject4).acuU = Integer.valueOf(j.c.icons_outlined_camera);
    ((Map)((a.b)localObject4).acuV).put(d.a.acsJ, new a.a(j.d.setting_permission_camera_chatting_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsM, new a.a(j.d.setting_permission_camera_sns_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsN, new a.a(j.d.setting_permission_camera_finder_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsO, new a.a(j.d.setting_permission_camera_live_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsP, new a.a(j.d.setting_permission_camera_scan_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsS, new a.a(j.d.setting_permission_camera_search_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsQ, new a.a(j.d.setting_permission_camera_shake_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsW, new a.a(j.d.setting_permission_camera_mine_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsX, new a.a(j.d.setting_permission_camera_status_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsY, new a.a(j.d.setting_permission_camera_fav_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acta, new a.a(j.d.setting_permission_camera_musicplayer_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acth, new a.a(j.d.setting_permission_camera_emoji_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acti, new a.a(j.d.setting_permission_camera_sport_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actj, new a.a(j.d.setting_permission_camera_mail_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actp, new a.a(-1, -1, false, null, 8));
    ((Map)((a.b)localObject4).acuV).put(d.a.actd, new a.a(-1, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 8));
    ((Map)((a.b)localObject4).acuV).put(d.a.actm, new a.a(j.d.setting_permission_camera_contact_remark_switch_desc, j.d.setting_permission_first_dialog_camera_default_desc_suffix, false, null, 12));
    localah = ah.aiuX;
    ((Map)localObject2).put(localObject3, localObject4);
    localObject2 = (Map)localObject1;
    localObject3 = d.c.acty;
    localObject4 = new a.b();
    ((a.b)localObject4).acuT = Integer.valueOf(j.d.setting_permission_first_dialog_microphone_default_desc);
    ((a.b)localObject4).acuU = Integer.valueOf(j.c.icons_outlined_mike);
    ((Map)((a.b)localObject4).acuV).put(d.a.acsJ, new a.a(j.d.setting_permission_microphone_chatting_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsM, new a.a(j.d.setting_permission_microphone_sns_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsN, new a.a(j.d.setting_permission_microphone_finder_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsO, new a.a(j.d.setting_permission_microphone_live_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsS, new a.a(j.d.setting_permission_microphone_search_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsQ, new a.a(j.d.setting_permission_microphone_shake_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsX, new a.a(j.d.setting_permission_microphone_status_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsY, new a.a(j.d.setting_permission_microphone_fav_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acta, new a.a(j.d.setting_permission_microphone_musicplayer_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actj, new a.a(j.d.setting_permission_microphone_mail_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.actk, new a.a(j.d.setting_permission_microphone_voiceprint_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acsU, new a.a(j.d.setting_permission_microphone_voiceprint_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    ((Map)((a.b)localObject4).acuV).put(d.a.acth, new a.a(j.d.setting_permission_microphone_emoji_switch_desc, j.d.setting_permission_first_dialog_microphone_default_desc_suffix, false, null, 12));
    localah = ah.aiuX;
    ((Map)localObject2).put(localObject3, localObject4);
    localObject2 = (Map)localObject1;
    localObject3 = d.c.actA;
    localObject4 = new a.b();
    ((a.b)localObject4).acuT = Integer.valueOf(j.d.setting_permission_first_dialog_healthy_default_desc);
    ((a.b)localObject4).acuU = Integer.valueOf(j.c.icons_outlined_sports);
    ((Map)((a.b)localObject4).acuV).put(d.a.acti, new a.a(j.d.setting_permission_healthy_sport_switch_desc, -1, false, null, 12));
    localah = ah.aiuX;
    ((Map)localObject2).put(localObject3, localObject4);
    localObject1 = (Map)localObject1;
    localObject2 = d.c.actB;
    localObject3 = new a.b();
    ((a.b)localObject3).acuT = Integer.valueOf(j.d.setting_permission_first_dialog_overlay_default_desc);
    ((a.b)localObject3).acuU = Integer.valueOf(j.c.icons_outlined_mini_window);
    ((Map)((a.b)localObject3).acuV).put(d.a.acsJ, new a.a(j.d.setting_permission_overlay_chatting_switch_desc, -1, false, null, 12));
    ((Map)((a.b)localObject3).acuV).put(d.a.acsN, new a.a(j.d.setting_permission_overlay_finder_switch_desc, -1, false, null, 12));
    ((Map)((a.b)localObject3).acuV).put(d.a.acsO, new a.a(j.d.setting_permission_overlay_live_switch_desc, -1, false, null, 12));
    ((Map)((a.b)localObject3).acuV).put(d.a.acsU, new a.a(j.d.setting_permission_overlay_game_switch_desc, -1, false, null, 12));
    ((Map)((a.b)localObject3).acuV).put(d.a.acta, new a.a(j.d.setting_permission_overlay_musicplayer_switch_desc, -1, false, null, 12));
    ((Map)((a.b)localObject3).acuV).put(d.a.actf, new a.a(-1, -1, false, null, 8));
    ((Map)((a.b)localObject3).acuV).put(d.a.acsY, new a.a(j.d.setting_permission_overlay_fav_switch_desc, -1, false, null, 8));
    localObject4 = ah.aiuX;
    ((Map)localObject1).put(localObject2, localObject3);
    localObject1 = ah.aiuX;
    localObject1 = new HashMap();
    ((Map)localObject1).put("android.permission.ACCESS_COARSE_LOCATION", d.c.actu);
    ((Map)localObject1).put("android.permission.ACCESS_FINE_LOCATION", d.c.actu);
    ((Map)localObject1).put("android.permission.ACCESS_COARSE_LOCATION", d.c.actu);
    ((Map)localObject1).put("android.permission.READ_CONTACTS", d.c.actv);
    ((Map)localObject1).put("android.permission.WRITE_CONTACTS", d.c.actv);
    ((Map)localObject1).put("android.permission.READ_EXTERNAL_STORAGE", d.c.actw);
    ((Map)localObject1).put("android.permission.WRITE_EXTERNAL_STORAGE", d.c.actw);
    ((Map)localObject1).put("android.permission.CAMERA", d.c.actx);
    ((Map)localObject1).put("android.permission.RECORD_AUDIO", d.c.acty);
    ((Map)localObject1).put("android.permission.ACTIVITY_RECOGNITION", d.c.actA);
    localObject2 = ah.aiuX;
    acuM = (HashMap)localObject1;
    localObject1 = new HashMap();
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_location);
    s.s(localObject3, "getContext().getString(R…ings_permission_location)");
    ((Map)localObject2).put("location", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_contract);
    s.s(localObject3, "getContext().getString(R…ings_permission_contract)");
    ((Map)localObject2).put("contact", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_storage);
    s.s(localObject3, "getContext().getString(R…tings_permission_storage)");
    ((Map)localObject2).put("storage", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_camera);
    s.s(localObject3, "getContext().getString(R…ttings_permission_camera)");
    ((Map)localObject2).put("camera", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_microphone);
    s.s(localObject3, "getContext().getString(R…gs_permission_microphone)");
    ((Map)localObject2).put("microphone", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_bluetooth);
    s.s(localObject3, "getContext().getString(R…ngs_permission_bluetooth)");
    ((Map)localObject2).put("bluetooth", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_healthy);
    s.s(localObject3, "getContext().getString(R…tings_permission_healthy)");
    ((Map)localObject2).put("healthy", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_overlay);
    s.s(localObject3, "getContext().getString(R…tings_permission_overlay)");
    ((Map)localObject2).put("overlay", localObject3);
    localObject2 = ah.aiuX;
    acuN = (HashMap)localObject1;
    localObject1 = new HashMap();
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_chatting);
    s.s(localObject3, "getContext().getString(R…ission_business_chatting)");
    ((Map)localObject2).put("chatting", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_radar);
    s.s(localObject3, "getContext()\n           …ermission_business_radar)");
    ((Map)localObject2).put("radar", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_face2face_group);
    s.s(localObject3, "getContext()\n           …business_face2face_group)");
    ((Map)localObject2).put("face2face_group", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_sns);
    s.s(localObject3, "getContext()\n           …_permission_business_sns)");
    ((Map)localObject2).put("sns", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_finder);
    s.s(localObject3, "getContext()\n           …rmission_business_finder)");
    ((Map)localObject2).put("finder", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_finder_live);
    s.s(localObject3, "getContext()\n           …ion_business_finder_live)");
    ((Map)localObject2).put("live", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_scan);
    s.s(localObject3, "getContext()\n           …permission_business_scan)");
    ((Map)localObject2).put("scan", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_shake);
    s.s(localObject3, "getContext()\n           …ermission_business_shake)");
    ((Map)localObject2).put("shake", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_story);
    s.s(localObject3, "getContext()\n           …ermission_business_story)");
    ((Map)localObject2).put("story", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_search);
    s.s(localObject3, "getContext()\n           …rmission_business_search)");
    ((Map)localObject2).put("search", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_nearby);
    s.s(localObject3, "getContext()\n           …rmission_business_nearby)");
    ((Map)localObject2).put("nearby", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_game);
    s.s(localObject3, "getContext()\n           …permission_business_game)");
    ((Map)localObject2).put("game", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_appbrand);
    s.s(localObject3, "getContext()\n           …ission_business_appbrand)");
    ((Map)localObject2).put("nearby_appbrand", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_mine);
    s.s(localObject3, "getContext()\n           …permission_business_mine)");
    ((Map)localObject2).put("mine", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_status);
    s.s(localObject3, "getContext()\n           …rmission_business_status)");
    ((Map)localObject2).put("status", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_fav);
    s.s(localObject3, "getContext()\n           …_permission_business_fav)");
    ((Map)localObject2).put("fav", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_card);
    s.s(localObject3, "getContext()\n           …permission_business_card)");
    ((Map)localObject2).put("card", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_musicplayer);
    s.s(localObject3, "getContext()\n           …ion_business_musicplayer)");
    ((Map)localObject2).put("musicplayer", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_net_check);
    s.s(localObject3, "getContext()\n           …ssion_business_net_check)");
    ((Map)localObject2).put("net_check", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_wifi_info);
    s.s(localObject3, "getContext()\n           …ssion_business_wifi_info)");
    ((Map)localObject2).put("wifi_info", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_contact);
    s.s(localObject3, "getContext()\n           …mission_business_contact)");
    ((Map)localObject2).put("contact", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_emoji);
    s.s(localObject3, "getContext()\n           …ermission_business_emoji)");
    ((Map)localObject2).put("emoji", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_sport);
    s.s(localObject3, "getContext()\n           …ermission_business_sport)");
    ((Map)localObject2).put("sport", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_mail);
    s.s(localObject3, "getContext()\n           …permission_business_mail)");
    ((Map)localObject2).put("mail", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_voiceprint);
    s.s(localObject3, "getContext()\n           …sion_business_voiceprint)");
    ((Map)localObject2).put("voiceprint", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_add_contact);
    s.s(localObject3, "getContext()\n           …ion_business_add_contact)");
    ((Map)localObject2).put("add_contact", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_contact_remark);
    s.s(localObject3, "getContext()\n           …_business_contact_remark)");
    ((Map)localObject2).put("contact_remark", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_wechatout);
    s.s(localObject3, "getContext()\n           …ssion_business_wechatout)");
    ((Map)localObject2).put("wechatout", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_savefile);
    s.s(localObject3, "getContext()\n           …ission_business_savefile)");
    ((Map)localObject2).put("savefile", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_webview);
    s.s(localObject3, "getContext()\n           …mission_business_webview)");
    ((Map)localObject2).put("webview", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_pay);
    s.s(localObject3, "getContext()\n           …_permission_business_pay)");
    ((Map)localObject2).put("pay", localObject3);
    localObject2 = (Map)localObject1;
    localObject3 = MMApplicationContext.getContext().getString(j.d.settings_permission_business_appbrand_outher);
    s.s(localObject3, "getContext()\n           …business_appbrand_outher)");
    ((Map)localObject2).put("appbrand", localObject3);
    localObject2 = ah.aiuX;
    acuO = (HashMap)localObject1;
    AppMethodBeat.o(241103);
  }
  
  public static HashMap<d.c, a.b> iUa()
  {
    return acuL;
  }
  
  public static HashMap<String, d.c> iUb()
  {
    return acuM;
  }
  
  public static HashMap<String, String> iUc()
  {
    return acuN;
  }
  
  public static HashMap<String, String> iUd()
  {
    return acuO;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes12.jar
 * Qualified Name:     com.tencent.mm.sensitive.business.a
 * JD-Core Version:    0.7.0.1
 */