package com.tencent.mm.util;

import com.tencent.matrix.trace.core.AppMethodBeat;

public enum b$a
{
  static
  {
    AppMethodBeat.i(233997);
    agpn = new a("RepairerGroup_Main", 0);
    agpo = new a("RepairerGroup_Tools", 1);
    agpp = new a("RepairerGroup_Compose", 2);
    agpq = new a("RepairerGroup_ResetConfig", 3);
    agpr = new a("RepairerGroup_PushNewXml", 4);
    agps = new a("RepairerGroup_PushNewMsg", 5);
    agpt = new a("RepairerGroup_ResDownload", 6);
    agpu = new a("RepairerGroup_Finder", 7);
    agpv = new a("RepairerGroup_Global", 8);
    agpw = new a("RepairerGroup_FTS", 9);
    agpx = new a("RepairerGroup_WebSearch", 10);
    agpy = new a("RepairerGroup_WebSearchVersion", 11);
    agpz = new a("RepairerGroup_Mv", 12);
    agpA = new a("RepairerGroup_MvH5", 13);
    agpB = new a("RepairerGroup_TextStatus", 14);
    agpC = new a("RepairerGroup_Chat", 15);
    agpD = new a("RepairerGroup_Updater", 16);
    agpE = new a("RepairerGroup_TopStory", 17);
    agpF = new a("RepairerGroup_Camera", 18);
    agpG = new a("RepairerGroup_WeSport", 19);
    agpH = new a("RepairerGroup_VoIP", 20);
    agpI = new a("RepairerGroup_Sns", 21);
    agpJ = new a("RepairerGroup_Media", 22);
    agpK = new a("RepairerGroup_ListFolder", 23);
    agpL = new a("RepairerGroup_Login", 24);
    agpM = new a("RepairerGroup_XLog", 25);
    agpN = new a("RepairerGroup_Mvvm", 26);
    agpO = new a("RepairerGroup_Demo", 27);
    agpP = new a("RepairerGroup_DemoKeyboardChange", 28);
    agpQ = new a("RepairerGroup_DemoKeyboardEmojiInputPanel", 29);
    agpR = new a("RepairerGroup_DemoSetTextStatus", 30);
    agpS = new a("RepairerGroup_DemoPullDownWidget", 31);
    agpT = new a("RepairerGroup_DemoAnimation", 32);
    agpU = new a("RepairerGroup_DemoDB", 33);
    agpV = new a("RepairerGroup_DemoDRAGCOMPONENT", 34);
    agpW = new a("RepairerGroup_DemoLiveDB", 35);
    agpX = new a("RepairerGroup_DemoLiveDB2", 36);
    agpY = new a("RepairerGroup_DemoLiveMainDB", 37);
    agpZ = new a("RepairerGroup_DemoAccessibility", 38);
    agqa = new a("RepairerGroup_DemoStateCenter", 39);
    agqb = new a("RepairerGroup_DemoXmlToJson", 40);
    agqc = new a("RepairerGroup_DemoRefreshLayout", 41);
    agqd = new a("RepairerGroup_Pay", 42);
    agqe = new a("RepairerGroup_PayLuckyMoney", 43);
    agqf = new a("RepairerGroup_PayReport", 44);
    agqg = new a("RepairerGroup_Recovery", 45);
    agqh = new a("RepairerGroup_AutoAccessibility", 46);
    agqi = new a("RepairerGroup_Separation", 47);
    agqj = new a("RepairerGroup_NewContactLabel", 48);
    agqk = new a("RepairerGroup_DemoApkDiffZipUpdate", 49);
    agql = new a("RepairerGroup_SettingFont", 50);
    agqm = new a("RepairerGroup_StartActivity", 51);
    agqn = new a("RepairerGroup_Maas", 52);
    agqo = new a("RepairerGroup_Egg", 53);
    agqp = new a("RepairerConfig_Inner_Version_Int", 54);
    agqq = new a("RepairerConfig_Inner_TopKey_String", 55);
    agqr = new a("RepairerConfig_Global_MsgDebug_Int", 56);
    agqs = new a("RepairerConfig_Global_ApplyResource_Int", 57);
    agqt = new a("RepairerConfig_Global_EditText_Int", 58);
    agqu = new a("RepairerConfig_Global_ToastActivityName_Int", 59);
    agqv = new a("RepairerConfig_Global_UseCamera2_Int", 60);
    agqw = new a("RepairerConfig_Global_BounceSwitch_Int", 61);
    agqx = new a("RepairerConfig_Global_PullDownLog_Int", 62);
    agqy = new a("RepairerConfig_Global_PullDownParamSetting_Int", 63);
    agqz = new a("RepairerConfig_Global_VasSwitch_Int", 64);
    agqA = new a("RepairerConfig_Global_ContactInfo_Int", 65);
    agqB = new a("RepairerConfig_Global_CloseImgSendSafeMode_Int", 66);
    agqC = new a("RepairerConfig_Global_NewImgCdnDownload_Int", 67);
    agqD = new a("RepairerConfig_Global_PlaySoundEnableThumbPlayer_Int", 68);
    agqE = new a("RepairerConfig_Global_RecentForwardFirst_Int", 69);
    agqF = new a("RepairerConfig_Global_RecentForwardSecond_Int", 70);
    agqG = new a("RepairerConfig_Global_MsgSendAnimDuration_Int", 71);
    agqH = new a("RepairerConfig_Global_TransInWriteTipsShow_Int", 72);
    agqI = new a("RepairerConfig_Global_TransInWriteMaxLine_Int", 73);
    agqJ = new a("RepairerConfig_Global_MinProcessEnableGotoTemplate_Int", 74);
    agqK = new a("RepairerConfig_Global_NOTALLOWNEWSYNC_Int", 75);
    agqL = new a("RepairerConfig_Global_WarmUpFlutterEngineAtStartup_Int", 76);
    agqM = new a("RepairerConfig_WebSearch_PreloadWebView_Int", 77);
    agqN = new a("RepairerConfig_WebSearch_TopStoryPreRequest_Int", 78);
    agqO = new a("RepairerConfig_WebSearch_TopStoryLogTrace_Int", 79);
    agqP = new a("RepairerConfig_WebSearch_EmojiSearch_Int", 80);
    agqQ = new a("RepairerConfig_Global_UseNewPermissionDialog_Int", 81);
    agqR = new a("RepairerConfig_Mv_ChattingRoom_Int", 82);
    agqS = new a("RepairerConfig_Mv_CardDownLevel_Int", 83);
    agqT = new a("RepairerConfig_Mv_SupportQQPlayer_Int", 84);
    agqU = new a("RepairerConfig_Mv_UseNetworkDataPlay_Int", 85);
    agqV = new a("RepairerConfig_Mv_EnableFlexMode_Int", 86);
    agqW = new a("RepairerConfig_Music_UrlCacheMaxInterval_Int", 87);
    agqX = new a("RepairerConfig_Mv_H5SHIELDQQMusic_Int", 88);
    agqY = new a("RepairerConfig_Mv_H5SHIELDNetEaseCloud_Int", 89);
    agqZ = new a("RepairerConfig_Mv_H5SHIELDKuGou_Int", 90);
    agra = new a("RepairerConfig_Mv_H5SHIELDKuWo_Int", 91);
    agrb = new a("RepairerConfig_Mv_SendMusicInChat_Int", 92);
    agrc = new a("RepairerConfig_Mv_SendOriginVideo_Int", 93);
    agrd = new a("RepairerConfig_Chat_ConvBoxGuide_Int", 94);
    agre = new a("RepairerConfig_Chat_ConvBoxOpen_Int", 95);
    agrf = new a("RepairerConfig_Chat_VoiceContinuePlayTimeout_Int", 96);
    agrg = new a("RepairerConfig_TextStatus_SnsFeedFuIcon_Int", 97);
    agrh = new a("RepairerConfig_TextStatus_SnsCommentAndLikeIcon_Int", 98);
    agri = new a("RepairerConfig_TextStatus_UsePreviewMiniApp_Int", 99);
    agrj = new a("RepairerConfig_TextStatus_UseOldIconStrategy_Int", 100);
    agrk = new a("RepairerConfig_TextStatus_EntrySwitch_Int", 101);
    agrl = new a("RepairerConfig_TextStatus_ConvSmileyPanelSwitch_Int", 102);
    agrm = new a("RepairerConfig_TextStatus_SkipSelectorSwitch_Int", 103);
    agrn = new a("RepairerConfig_TextStatus_SetTextStatusFromWeRun_Int", 104);
    agro = new a("RepairerConfig_TextStatus_NewTextStatusSquareSwitch_Int", 105);
    agrp = new a("RepairerConfig_TextStatus_NewTextStatusSquareFakeData_Int", 106);
    agrq = new a("RepairerConfig_Recovery_ExerciseTimerRatio_Int", 107);
    agrr = new a("RepairerConfig_AutoAccessibility_AccForcedEnable_Int", 108);
    agrs = new a("RepairerConfig_AutoAccessibility_CallbackRealtime_Int", 109);
    agrt = new a("RepairerConfig_AutoAccessibility_ExpandEnable_Int", 110);
    agru = new a("RepairerConfig_AutoAccessibility_NodeCacheEnable_Int", 111);
    agrv = new a("RepairerConfig_Media_CaptureHevc_Int", 112);
    agrw = new a("RepairerConfig_Media_RemuxHevc_Int", 113);
    agrx = new a("RepairerConfig_Media_ImportVideoRemuxHevc_Int", 114);
    agry = new a("RepairerConfig_Media_ImportVideoUseComposition_Int", 115);
    agrz = new a("RepairerConfig_Media_AvcEncodeHard_Int", 116);
    agrA = new a("RepairerConfig_Camera_Config_Int", 117);
    agrB = new a("RepairerConfig_Camera_Debug_Int", 118);
    agrC = new a("RepairerConfig_Camera1_Preview_Int", 119);
    agrD = new a("RepairerConfig_Camera_Instance_Int", 120);
    agrE = new a("RepairerConfig_Camerax_Picture_Int", 121);
    agrF = new a("RepairerConfig_Camera_Performance_Int", 122);
    agrG = new a("RepairerConfig_MediaParallel_SaveVideo_Int", 123);
    agrH = new a("RepairerConfig_MediaParallel_NotSupport_Int", 124);
    agrI = new a("RepairerConfig_Media_EnableVCodecEncode_Int", 125);
    agrJ = new a("RepairerConfig_Media_CaptureCropCameraTexture_Int", 126);
    agrK = new a("RepairerConfig_Media_CaptureSoft_Int", 127);
    agrL = new a("RepairerConfig_Media_CleanFile_Int", 128);
    agrM = new a("RepairerConfig_Updater_CloseAutoPatch_Int", 129);
    agrN = new a("RepairerConfig_Updater_OpenNewUpdater_Int", 130);
    agrO = new a("RepairerConfig_Updater_TinkerBaseId_String", 131);
    agrP = new a("RepairerConfig_Updater_HdiffMOCKOLDAPK_Int", 132);
    agrQ = new a("RepairerConfig_Updater_HdiffMOCKPATCHPATH_Int", 133);
    agrR = new a("RepairerConfig_Updater_DISABLEALPHA_Int", 134);
    agrS = new a("RepairerConfig_TopStory_CopyVideoToSDCard_Int", 135);
    agrT = new a("RepairerConfig_Mvvm_OpenFlag_Int", 136);
    agrU = new a("RepairerConfig_Mvvm_SelectConversationFlag_Int", 137);
    agrV = new a("RepairerConfig_Mvvm_SendCardFlag_Int", 138);
    agrW = new a("RepairerConfig_Mvvm_CreateChatroomFlag_Int", 139);
    agrX = new a("RepairerConfig_Mvvm_AddressUIFlag_Int", 140);
    agrY = new a("RepairerConfig_Login_ExDeviceLoginSpam_String", 141);
    agrZ = new a("RepairerConfig_Maas_ShowMainEntry_Int", 142);
    agsa = new a("RepairerConfig_Maas_ShowEventEntry_Int", 143);
    agsb = new a("RepairerConfig_Maas_ShowCreationSameEntry_Int", 144);
    agsc = new a("RepairerConfig_Maas_ShowFeedCreationSameEntry_Int", 145);
    agsd = new a("RepairerConfig_Maas_QuickCreation_Int", 146);
    agse = new a("RepairerConfig_Maas_32BitEntry_Int", 147);
    agsf = new a("RepairerConfig_Maas_MinApiLevel_Int", 148);
    agsg = new a("RepairerConfig_Maas_DisableAiAnalysis_Int", 149);
    agsh = new a("RepairerConfig_Maas_DisableVideoTranscodeOpt_Int", 150);
    agsi = new a("RepairerConfig_Maas_DisableVideoTranscodeDimenLimit_Int", 151);
    agsj = new a("RepairerConfig_Maas_SnsExportVideoBitrate_Int", 152);
    agsk = new a("RepairerConfig_Maas_SnsExportVideoDimension_Int", 153);
    agsl = new a("RepairerConfig_Maas_SnsShowPostMainEntry_Int", 154);
    agsm = new a("RepairerConfig_Maas_SnsShowCreateSameEntry_Int", 155);
    agsn = new a("RepairerConfig_Maas_SnsSpringStrategy_Int", 156);
    agso = new a("RepairerConfig_Maas_SnsSpringOfflineStrategy_Int", 157);
    agsp = new a("RepairerConfig_Maas_PreprocTimeoutLimit_Int", 158);
    agsq = new a("RepairerConfig_Maas_FinderFallBack_Int", 159);
    agsr = new a("RepairerConfig_Maas_RecordTemplateEnable_Int", 160);
    agss = new a("RepairerConfig_Maas_RecordTemplateFollow_Int", 161);
    agst = new a("RepairerConfig_Maas_RecordTemplateTransfer_Int", 162);
    agsu = new a("RepairerConfig_Maas_RecordTemplateEvent_Int", 163);
    agsv = new a("RepairerConfig_Egg_PreviewMiniApp_Int", 164);
    agsw = new a("RepairerConfig_Special_FavConfig_String", 165);
    agsx = new a("RepairerConfig_Pay_KindaConfigEnable_Int", 166);
    agsy = new a("RepairerConfig_Pay_LuckyMoneyEnvelopeFirstGuide_Int", 167);
    agsz = new a("RepairerConfig_Pay_LuckyMoneyEnvelopePreviewVideo_Int", 168);
    agsA = new a("RepairerConfig_Pay_YSFDebugEnv_Int", 169);
    agsB = new a("RepairerConfig_Pay_UseBiometricPrompt_Int", 170);
    agsC = new a("RepairerConfig_VOIP_ShowDebugInfo_Int", 171);
    agsD = new a("RepairerConfig_VOIP_CameraAsyncRelease_Int", 172);
    agsE = new a("RepairerConfig_VOIP_UIFrameWork_Int", 173);
    agsF = new a("RepairerConfig_VOIP_RenderFunc_Int", 174);
    agsG = new a("RepairerConfig_VOIP_EncoderDataSource_Int", 175);
    agsH = new a("RepairerConfig_VOIP_FaceBeautyParams_Int", 176);
    agsI = new a("RepairerConfig_VOIP_CameraFrameWork_Int", 177);
    agsJ = new a("RepairerConfig_VOIP_ForceHardEncode_Int", 178);
    agsK = new a("RepairerConfig_VOIP_ExternalDeviceUseRing_Int", 179);
    agsL = new a("RepairerConfig_VOIP_SetModeWhileRing_Int", 180);
    agsM = new a("RepairerConfig_VOIP_RingChannelGrantPermission_Int", 181);
    agsN = new a("RepairerConfig_VOIP_UseSurfaceEncode_Int", 182);
    agsO = new a("RepairerConfig_VOIP_UseSoftwareEncode_Int", 183);
    agsP = new a("RepairerConfig_Ringtone_ForbiddenUse_Int", 184);
    agsQ = new a("RepairerConfig_VOIP_OPTGLCONTEXT_Int", 185);
    agsR = new a("RepairerConfig_Ringtone_CallingUseVoiceCall_Int", 186);
    agsS = new a("RepairerConfig_Ringtone_FunnyVibrate_Int", 187);
    agsT = new a("RepairerConfig_VOIP_UseDebugSvr_Int", 188);
    agsU = new a("RepairerConfig_Ringtone_ShowAppMsgAfterVoIP_Int", 189);
    agsV = new a("RepairerConfig_FTS_FTSHotSearch_Int", 190);
    agsW = new a[] { agpn, agpo, agpp, agpq, agpr, agps, agpt, agpu, agpv, agpw, agpx, agpy, agpz, agpA, agpB, agpC, agpD, agpE, agpF, agpG, agpH, agpI, agpJ, agpK, agpL, agpM, agpN, agpO, agpP, agpQ, agpR, agpS, agpT, agpU, agpV, agpW, agpX, agpY, agpZ, agqa, agqb, agqc, agqd, agqe, agqf, agqg, agqh, agqi, agqj, agqk, agql, agqm, agqn, agqo, agqp, agqq, agqr, agqs, agqt, agqu, agqv, agqw, agqx, agqy, agqz, agqA, agqB, agqC, agqD, agqE, agqF, agqG, agqH, agqI, agqJ, agqK, agqL, agqM, agqN, agqO, agqP, agqQ, agqR, agqS, agqT, agqU, agqV, agqW, agqX, agqY, agqZ, agra, agrb, agrc, agrd, agre, agrf, agrg, agrh, agri, agrj, agrk, agrl, agrm, agrn, agro, agrp, agrq, agrr, agrs, agrt, agru, agrv, agrw, agrx, agry, agrz, agrA, agrB, agrC, agrD, agrE, agrF, agrG, agrH, agrI, agrJ, agrK, agrL, agrM, agrN, agrO, agrP, agrQ, agrR, agrS, agrT, agrU, agrV, agrW, agrX, agrY, agrZ, agsa, agsb, agsc, agsd, agse, agsf, agsg, agsh, agsi, agsj, agsk, agsl, agsm, agsn, agso, agsp, agsq, agsr, agss, agst, agsu, agsv, agsw, agsx, agsy, agsz, agsA, agsB, agsC, agsD, agsE, agsF, agsG, agsH, agsI, agsJ, agsK, agsL, agsM, agsN, agsO, agsP, agsQ, agsR, agsS, agsT, agsU, agsV };
    AppMethodBeat.o(233997);
  }
  
  private b$a() {}
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes12.jar
 * Qualified Name:     com.tencent.mm.util.b.a
 * JD-Core Version:    0.7.0.1
 */