package com.tencent.mm.storage;

import android.content.Context;
import android.util.SparseArray;
import com.tencent.mm.compatible.util.e;
import com.tencent.mm.sdk.a.b;
import com.tencent.mm.sdk.platformtools.ae;
import com.tencent.mm.sdk.platformtools.bk;
import com.tencent.mm.sdk.platformtools.y;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import junit.framework.Assert;

public final class ac
{
  public static String dOP = e.dOP;
  public static final String unx = ae.getContext().getFilesDir() + "/xlog";
  
  static
  {
    if (b.cqk()) {
      Assert.assertTrue(ctX());
    }
  }
  
  private static final String aaQ(String paramString)
  {
    int j = -1;
    String[] arrayOfString = paramString.split("_");
    if ((arrayOfString == null) || (arrayOfString.length < 4))
    {
      if (arrayOfString == null) {}
      for (;;)
      {
        y.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: key:%s split by '_'  fileds len too short : %d , at least 4", new Object[] { paramString, Integer.valueOf(j) });
        return null;
        j = arrayOfString.length;
      }
    }
    int i = 0;
    while (i < arrayOfString.length)
    {
      if ((arrayOfString[i] == null) || (arrayOfString[i].length() <= 0))
      {
        y.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: name:%s , [%s] too short ( <1 ) ", new Object[] { paramString, arrayOfString[i] });
        return null;
      }
      i += 1;
    }
    int k = arrayOfString.length - 1;
    String str2 = arrayOfString[k];
    i = k;
    String str1 = str2;
    if (str2.equals("SYNC"))
    {
      i = k - 1;
      str1 = arrayOfString[i];
    }
    if (i < 3) {
      if (arrayOfString != null) {
        break label267;
      }
    }
    for (;;)
    {
      y.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: name:%s split by '_'  fileds len too short : %d , at least 3", new Object[] { paramString, Integer.valueOf(j) });
      if ((str1.equals("INT")) || (str1.equals("LONG")) || (str1.equals("STRING")) || (str1.equals("BOOLEAN")) || (str1.equals("FLOAT")) || (str1.equals("DOUBLE"))) {
        break;
      }
      y.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: name[%s], invalid type:%s ", new Object[] { paramString, str1 });
      return null;
      label267:
      j = i;
    }
    return paramString.substring(0, paramString.lastIndexOf(str1) - 1);
  }
  
  private static final boolean ctX()
  {
    Field[] arrayOfField = ac.class.getDeclaredFields();
    SparseArray localSparseArray = new SparseArray();
    int i = 0;
    for (;;)
    {
      if (i >= arrayOfField.length) {
        break label210;
      }
      Field localField = arrayOfField[i];
      if ((Modifier.isStatic(localField.getModifiers())) && ((localField.getName().startsWith("USERINFO_")) || (localField.getName().startsWith("NEW_BANDAGE_")) || (localField.getName().startsWith("DYNAMIC_CONFIG_"))) && (localField.getType().toString().equals("int"))) {}
      try
      {
        int j = localField.getInt(null);
        if (localSparseArray.get(j, null) != null)
        {
          y.e("MicroMsg.ConstantsStorage", "%s and %s has same value(0x%05X)!!!", new Object[] { localSparseArray.get(j), localField.getName(), Integer.valueOf(j) });
          return false;
        }
        localSparseArray.put(j, localField.getName());
      }
      catch (IllegalArgumentException localIllegalArgumentException)
      {
        for (;;)
        {
          y.e("MicroMsg.ConstantsStorage", "exception:%s", new Object[] { bk.j(localIllegalArgumentException) });
        }
      }
      catch (IllegalAccessException localIllegalAccessException)
      {
        for (;;)
        {
          y.e("MicroMsg.ConstantsStorage", "exception:%s", new Object[] { bk.j(localIllegalAccessException) });
        }
      }
      i += 1;
    }
    label210:
    if (localSparseArray.size() > 511)
    {
      y.e("MicroMsg.ConstantsStorage", "constants values size(%d) is over the limit(%d)!!!", new Object[] { Integer.valueOf(localSparseArray.size()), Integer.valueOf(511) });
      return false;
    }
    y.i("MicroMsg.ConstantsStorage", "checkDuplicateUserInfo values size: %d", new Object[] { Integer.valueOf(localSparseArray.size()) });
    return ctY();
  }
  
  private static final boolean ctY()
  {
    ArrayList localArrayList = new ArrayList(a.values().length);
    a[] arrayOfa = a.values();
    int j = arrayOfa.length;
    int i = 0;
    while (i < j)
    {
      Object localObject = arrayOfa[i];
      if ((localObject == null) || (((a)localObject).name() == null)) {
        y.e("MicroMsg.ConstantsStorage", "BusinessInfoKey check error: info is null!!!");
      }
      do
      {
        return false;
        localObject = aaQ(((a)localObject).name());
      } while (bk.bl((String)localObject));
      if (localArrayList.contains(localObject))
      {
        y.e("MicroMsg.ConstantsStorage", "BusinessInfoKey check error: redefinition of [%s] which already defined!", new Object[] { localObject });
        return false;
      }
      localArrayList.add(localObject);
      i += 1;
    }
    return true;
  }
  
  public static enum a
  {
    static
    {
      unA = new a("USERINFO_UPDATE_UPDATE_FLAG_LONG", 2);
      unB = new a("USERINFO_UPDATE_UPDATE_VERION_LONG", 3);
      unC = new a("USERINFO_UPDATE_UPDATE_TIME_LONG", 4);
      unD = new a("USERINFO_WALLET_OFFLINE_IEMI_STRING_SYNC", 5);
      unE = new a("USERINFO_WALLET_OFFLINE_CODE_VER_STRING", 6);
      unF = new a("USERINFO_SHAKE_CARD_ENTRANCE_OPEN_BOOLEAN_SYNC", 7);
      unG = new a("USERINFO_SHAKE_CARD_ENTRANCE_BEGIN_TIME_INT_SYNC", 8);
      unH = new a("USERINFO_SHAKE_CARD_ENTRANCE_END_TIME_INT_SYNC", 9);
      unI = new a("USERINFO_SHAKE_CARD_ENTRANCE_NAME_STRING_SYNC", 10);
      unJ = new a("USERINFO_SHAKE_CARD_FLOW_CONTROL_LEVEL_MIN_INT_SYNC", 11);
      unK = new a("USERINFO_SHAKE_CARD_FLOW_CONTROL_LEVEL_MAX_INT_SYNC", 12);
      unL = new a("USERINFO_SHAKE_CARD_ENTRANCE_TIP_STRING_SYNC", 13);
      unM = new a("USERINFO_SHAKE_CARD_ACTIVITY_TYPE_INT_SYNC", 14);
      unN = new a("USERINFO_SHAKE_CARD_ENTRANCE_RED_DOT_ID_STRING_SYNC", 15);
      unO = new a("USERINFO_SHAKE_CARD_ENTRANCE_RED_DOT_DESC_STRING_SYNC", 16);
      unP = new a("USERINFO_SHAKE_CARD_ENTRANCE_RED_DOT_TEXT_STRING_SYNC", 17);
      unQ = new a("USERINFO_SHAKE_CARD_TAB_RED_DOT_ID_STRING_SYNC", 18);
      unR = new a("USERINFO_SHAKE_CARD_TAB_RED_DOT_DESC_STRING_SYNC", 19);
      unS = new a("USERINFO_GAME_SEARCH_LIST_UPDATE_TIME_LONG", 20);
      unT = new a("USERINFO_GAME_GLOBAL_CONFIG_UPDATE_TIME_LONG", 21);
      unU = new a("USERINFO_MINIGAME_SEARCH_LIST_UPDATE_TIME_LONG", 22);
      unV = new a("USERINFO_EMOJI_BACKUP_OVERSIZE_BOOLEAN", 23);
      unW = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_UPLODD_LONG", 24);
      unX = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_DOWNLOAD_LONG", 25);
      unY = new a("USERINFO_EMOJI_RECOVER_CUSTOM_EMOJI_BOOLEAN", 26);
      unZ = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_UPLODD_FINISH_BOOLEAN", 27);
      uoa = new a("USERINFO_EMOJI_STORE_LAST_REFRESH_TIME_LONG", 28);
      uob = new a("USERINFO_EMOJI_STORE_RECOMMEND_LAST_UPDATE_TIME_LONG", 29);
      uoc = new a("USERINFO_EMOJI_STORE_NEW_ORIGINAL_BOOLEAN", 30);
      uod = new a("USERINFO_EMOJI_SYNC_CUSTOM_EMOJI_BATCH_DOWNLOAD_BOOLEAN", 31);
      uoe = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_NEW_PANEL_BOOLEAN", 32);
      uof = new a("USERINFO_EMOJI_STORE_NEW_DESIGNER_EMOJI_BOOLEAN", 33);
      uog = new a("USERINFO_EMOJI_LAST_BATCH_EMOJI_DOWNLOAD_TIME_2_LONG", 34);
      uoh = new a("USERINFO_EMOJI_CLEAN_TEMP_FILE_TASK_LONG", 35);
      uoi = new a("USERINFO_EMOJI_ENCODE_EMOJI_FILE_TASK_LONG", 36);
      uoj = new a("USERINFO_EMOJI_REPORT_CUSTOM_EMOJI_COUNT_LONG", 37);
      uok = new a("USERINFO_EMOJI_REWARD_TIP_ENABLE_BOOLEAN", 38);
      uol = new a("USERINFO_EMOJI_CUREENT_VERSION_INT", 39);
      uom = new a("USERINFO_EMOJI_UPDATE_EMOJI_GROUP_COUNT_BOOLEAN", 40);
      uon = new a("USERINFO_EMOJI_NEW_EMOJI_INT", 41);
      uoo = new a("USERINFO_EMOJI_NEW_PANEL_INT", 42);
      uop = new a("USERINFO_EMOJI_NEW_SUGGEST_INT", 43);
      uoq = new a("USERINFO_EMOJI_EGG_INT", 44);
      uor = new a("USERINFO_EMOJI_NEW_PANEL_NAME_STRING", 45);
      uos = new a("USERINFO_LUCKY_MONEY_NEWYEAR_SWITCH_INT_SYNC", 46);
      uot = new a("USERINFO_LUCKY_MONEY_NEWYEAR_LOCAL_SWITCH_INT", 47);
      uou = new a("USERINFO_VOICEPRINT_MORE_TAB_DOT_SHOW_BOOLEAN", 48);
      uov = new a("USERFINO_VOICEPRINT_SETTING_DOT_SHOW_BOOLEAN", 49);
      uow = new a("USERINFO_VOICEPRINT_SETTING_ACCOUNT_INFO_DOT_SHOW_BOOLEAN", 50);
      uox = new a("USERINFO_VOICEPRINT_SETTING_ACCOUNT_INFO_NEW_SHOW_BOOLEAN", 51);
      uoy = new a("USERINFO_REPORTNETTYPE_SEQ_LONG", 52);
      uoz = new a("USERINFO_REPORTNETTYPE_LASTREPORT_LONG", 53);
      uoA = new a("USERINFO_SELFINFO_SMALLIMGURL_STRING", 54);
      uoB = new a("USERINFO_SELFINFO_GETPROFILE_TIME_LONG", 55);
      uoC = new a("USERINFO_WALLET_BALANCE_NOTICE_STRING", 56);
      uoD = new a("USERINFO_WALLET_FETCH_NOTICE_STRING", 57);
      uoE = new a("USERINFO_WALLET_SUPPORT_BANK_WORD_STRING", 58);
      uoF = new a("USERINFO_NEED_TO_UPDATE_CONVERSATION_TIME_DIVIDER_LONG", 59);
      uoG = new a("USERINFO_EXPOSE_GETEXPOSESCENE_TIME_LONG", 60);
      uoH = new a("USERINFO_WXPHONE_PB_COUNT_INT", 61);
      uoI = new a("USERINFO_MALL_INDEX_HAS_SHOWN_FTF_NOTICE_BOOLEAN", 62);
      uoJ = new a("USERINFO_PHONE_RECHARGE_CLOSED_BANNER_STRING", 63);
      uoK = new a("USERINFO_QQMAIL_UNREAD_COUNT_INT", 64);
      uoL = new a("USERINFO_AUTOGETBIG_IMG_MAX_LONG", 65);
      uoM = new a("USERINFO_AUTOGETBIG_IMG_CURRENT_LONG", 66);
      uoN = new a("USERINFO_AUTOGETBIG_IMG_CURRENT_DATE_LONG", 67);
      uoO = new a("USERINFO_SHAKE_KV_STAT_BLUETOOTH_POWER_STATE_TIME_LONG", 68);
      uoP = new a("USERINFO_SHAKE_TV_LATITUDE_STRING", 69);
      uoQ = new a("USERINFO_SHAKE_TV_LONGTITUDE_STRING", 70);
      uoR = new a("NEW_BANDAGE_DATASOURCE_NEW_CARD_REDDOT_WORDING_STRING_SYNC", 71);
      uoS = new a("NEW_BANDAGE_DATASOURCE_NEW_CARD_ICON_STRING_SYNC", 72);
      uoT = new a("NEW_BANDAGE_WATCHER_SETTING_CARD_ENTRY_REDDOT_WORDING_STRING_SYNC", 73);
      uoU = new a("NEW_BANDAGE_WATCHER_SETTING_CARD_ENTRY_ICON_STRING_SYNC", 74);
      uoV = new a("USERINFO_CARDLAYOUT_TESTDATA_STRING", 75);
      uoW = new a("USERINFO_CARD_LAYOUT_BUF_DATA_STRING_SYNC", 76);
      uoX = new a("USERINFO_CARD_REDOT_WORDING_STRING_SYNC", 77);
      uoY = new a("USERINFO_CARD_REDOT_END_TIME_INT_SYNC", 78);
      uoZ = new a("USERINFO_CARD_REDOT_BUFF_STRING_SYNC", 79);
      upa = new a("USERINFO_CARD_REDOT_ICON_URL_STRING_SYNC", 80);
      upb = new a("USERINFO_CARD_MSG_TIPS_TITLE_STRING_SYNC", 81);
      upc = new a("USERINFO_CARD_MSG_TIPS_ICON_URL_STRING_SYNC", 82);
      upd = new a("USERINFO_CARD_GET_LAYOUT_SCENE_INT_SYNC", 83);
      upe = new a("USERINFO_CARD_GET_LAYOUT_JSON_STRING_SYNC", 84);
      upf = new a("USERINFO_CARD_SHARECARD_LAYOUT_JSON_STRING_SYNC", 85);
      upg = new a("USERINFO_CARD_REQUENCE_LONG_SYNC", 86);
      uph = new a("USERINFO_CARD_IS_SHARE_CARD_ENTRANCE_OPEN_INT_SYNC", 87);
      upi = new a("USERINFO_CARD_IS_SHOW_SHARE_CARD_TIP_INT_SYNC", 88);
      upj = new a("USERINFO_CARD_IS_SHOW_SHARE_CARD_ENTRANCE_TIP_INT_SYNC", 89);
      upk = new a("USERINFO_CARD_IS_SHOW_MEMBERSHIP_TIP_INT_SYNC", 90);
      upl = new a("USERINFO_CARD_SHARE_LIST_CLEAR_TIME_INT_SYNC", 91);
      upm = new a("USERINFO_CARD_SHOW_WARNING_CARD_IDS_STRING_SYNC", 92);
      upn = new a("USERINFO_CARD_HAS_UPDATE_CARD_TYPE_INT_SYNC", 93);
      upo = new a("USERINFO_CARD_MSG_CARD_ID_STRING_SYNC", 94);
      upp = new a("USERINFO_CARD_MSG_NEED_CHECK_BOOLEAN_SYNC", 95);
      upq = new a("USERINFO_CARD_HOME_PAGE_LIST_STRING_SYNC", 96);
      upr = new a("USERINFO_CARD_HOME_PAGE_SECOND_ENTRANCE_STRING_SYNC", 97);
      ups = new a("USERINFO_CARD_HOME_PAGE_CARD_NUM_INT_SYNC", 98);
      upt = new a("USERINFO_CARD_HOME_PAGE_HAS_LOAD_NEW_ENTRANCE_BOOLEAN_SYNC", 99);
      upu = new a("USERINFO_POSITION_REMIND_MSG_TIP_IN_BOOLEAN", 100);
      upv = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_BOOLEAN_SYNC", 101);
      upw = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_HWFPMANAGER_BOOLEAN_SYNC", 102);
      upx = new a("USERINFO_WALLET_FINGERPRINT_SWITCH_IS_NOT_NEW_BOOLEAN_SYNC", 103);
      upy = new a("USERINFO_FINGER_PRINT_IS_OPEN_BOOLEAN_SYNC", 104);
      upz = new a("USERINFO_FINGER_PRINT_IS_SO_LOAD_SUCCESS_BOOLEAN_SYNC", 105);
      upA = new a("USERINFO_FINGER_PRINT_IS_FORCE_PWD_MODE_BOOLEAN_SYNC", 106);
      upB = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_IN_TRANSPARENT_BOOLEAN_SYNC", 107);
      upC = new a("USERINFO_FINGER_PRINT_IS_SO_LOADLIBRARY_SUCCESS_BOOLEAN_SYNC", 108);
      upD = new a("USERINFO_FINGER_PRINT_IS_FIRST_SHOWN_BOOLEAN_SYNC", 109);
      upE = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_IN_TRANSPARENT_NEW_BOOLEAN_SYNC", 110);
      upF = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_COUNT_INT_SYNC", 111);
      upG = new a("USERINFO_FINGER_PRINT_LAST_IS_SEVERE_ERROR_BOOLEAN_SYNC", 112);
      upH = new a("USERINFO_ABTEST_SERVER_TIMESTAMP_INT", 113);
      upI = new a("USERINFO_ABTEST_LAST_UPDATE_TIME_LONG", 114);
      upJ = new a("USERINFO_ABTEST_UPDATE_TIME_INTERVAL_INT", 115);
      upK = new a("USERINFO_NFC_CPU_CARD_CONFIG_STRING", 116);
      upL = new a("USERINFO_BIND_MOBILE_XML_TIP_BOOLEAN", 117);
      upM = new a("USERINFO_BIND_MOBILE_XML_FORCE_BIND_BOOLEAN", 118);
      upN = new a("USERINFO_BIND_MOBILE_XML_WORDING_STRING", 119);
      upO = new a("USERINFO_BIZ_ATTR_SYNC_OPEN_FLAG_INT", 120);
      upP = new a("USERINFO_NFC_OPEN_SWITCH_INT_SYNC", 121);
      upQ = new a("USERINFO_NFC_OPEN_DEFAULT_SWITCH_INT_SYNC", 122);
      upR = new a("BUSINESS_SNS_ADLOG_FREQUENCY_INT", 123);
      upS = new a("BUSINESS_SNS_ADLOG_CNTTIME_INT", 124);
      upT = new a("USERINFO_NFC_OPEN_SWITCH_WORDING_STRING_SYNC", 125);
      upU = new a("USERINFO_SNS_OPEN_UPLOAD_DRAFT_MEDIA_STRING_SYNC", 126);
      upV = new a("USERINFO_SNS_OPEN_UPLOAD_NEWTEXT_DRAFT_STRING_SYNC", 127);
      upW = new a("USERINFO_SNS_OPEN_UPLOAD_DRAFT_LAST_SESSIONID_STRING", 128);
      upX = new a("USERINFO_SNS_OPEN_UPLOAD_WEISHI_BOOLEAN_SYNC", 129);
      upY = new a("USERINFO_SNS_OPEN_SHOW_WEISHI_BOOLEAN_SYNC", 130);
      upZ = new a("USERINFO_IPCALL_COUNTRY_CODE_RESTRCTION_INT", 131);
      uqa = new a("USERINFO_IPCALL_COUNTRY_CODE_LASTUPDATE_TIME_LONG", 132);
      uqb = new a("USERINFO_IPCALL_FIRST_IN_BOOLEAN", 133);
      uqc = new a("USERINFO_IPCALL_ADDRESS_LASTREPORT_TIME_LONG", 134);
      uqd = new a("USERINFO_IPCALL_ADDRESS_GETMFRIEND_LASTUPDATE_TIME_LONG", 135);
      uqe = new a("USERINFO_IPCALL_ADDRESS_GETLOCATION_LASTUPDATE_TIME_LONG", 136);
      uqf = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_SHOW_REDDOT_BOOLEAN", 137);
      uqg = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_SHOW_REDDOT_TYPE_INT", 138);
      uqh = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_STRING", 139);
      uqi = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_ACTIVITY_STRING", 140);
      uqj = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_ACTIVITY_CLEAR_TYPE_INT", 141);
      uqk = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_ACTIVITY_TYPE_VERSION_INT", 142);
      uql = new a("USERFINO_IPCALL_RECHARGE_STRING", 143);
      uqm = new a("USERINFO_IPCALL_RECHARGE_SHOW_REDDOT_BOOLEAN", 144);
      uqn = new a("USERINFO_IPCALL_PACKAGE_PURCHASE_STRING", 145);
      uqo = new a("USERINFO_IPCALL_EXCHANGE_RECORD_SHOW_REDDOT_BOOLEAN", 146);
      uqp = new a("USERFINO_IPCALL_HAS_ENTRY_BOOLEAN", 147);
      uqq = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_INT", 148);
      uqr = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_WORDING_STRING", 149);
      uqs = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_NEWXML_BOOLEAN", 150);
      uqt = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_TYPE_INT", 151);
      uqu = new a("USERINFO_IPCALL_MSG_CENTER_SHOW_REDDOT_BOOLEAN", 152);
      uqv = new a("USERFINO_IPCALL_MSG_CENTER_SHOW_REDDOT_TYPE_INT", 153);
      uqw = new a("USERFINO_IPCALL_REDDOT_RECHARGE_VERSION_INT", 154);
      uqx = new a("USERFINO_IPCALL_SHOW_FROM_VOIP_LAST_TIME_LONG", 155);
      uqy = new a("USERFINO_IPCALL_SHOW_FROM_VOIP_TIME_COUNT_INT", 156);
      uqz = new a("USERFINO_FAV_HAS_DB_DATATOTALLENGTH_BOOLEAN", 157);
      uqA = new a("USERFINO_FAV_USED_CAPACITY_LONG", 158);
      uqB = new a("USERFINO_FAV_TOTAL_CAPACITY_LONG", 159);
      uqC = new a("USERFINO_FAV_IS_FULL_BOOLEAN", 160);
      uqD = new a("USERFINO_IPCALL_SHOW_FEEDBACK_LAST_TIME_LONG", 161);
      uqE = new a("USERFINO_IPCALL_SHOW_FEEDBACK_TIME_COUNT_INT", 162);
      uqF = new a("USERFINO_IPCALL_HAS_ACTIVITY_BOOLEAN", 163);
      uqG = new a("USERFINO_IPCALL_ACTIVITY_STRING", 164);
      uqH = new a("USERINFO_SUBMENU_SHOW_TIT_BOOLEAN", 165);
      uqI = new a("USERINFO_PROFILE_WEIDIANINFO_STRING", 166);
      uqJ = new a("GAME_DISCOVERY_ENTRANCE_MSGID_LONG_SYNC", 167);
      uqK = new a("GAME_INDEX_BUBBLE_MSGID_LONG_SYNC", 168);
      uqL = new a("GAME_MSG_ENTRANCE_MSGID_LONG_SYNC", 169);
      uqM = new a("GAME_GIFT_ENTRANCE_MSGID_LONG_SYNC", 170);
      uqN = new a("GAME_INDEX_FLOATLAYER_MSGID_LONG_SYNC", 171);
      uqO = new a("USERINFO_WELCOMEMSG_CONTENT_STRING", 172);
      uqP = new a("USERINFO_WELCOMEMSG_EXT_LASTTIME_LONG", 173);
      uqQ = new a("USERINFO_WELCOMEMSG_EXT_SHOWCOUNT_LONG", 174);
      uqR = new a("USERINFO_RES_DOWNLOADER_CHECK_RES_UPDATE_INTERVAL_LONG", 175);
      uqS = new a("USERINFO_RES_DOWNLOADER_CHECK_RESUME_INTERVAL_LONG", 176);
      uqT = new a("USERINFO_LOAN_ENTRANCE_RED_POINT_INT", 177);
      uqU = new a("USERINFO_WEBVIEW_CLEAR_HOST_COOKIES_INTERVAL_LONG", 178);
      uqV = new a("USERINFO_IBEACON_PUSH_SHOP_ID_LONG", 179);
      uqW = new a("USERINFO_IBEACON_PUSH_CHANNEL_OPEN_METHOD_INT", 180);
      uqX = new a("USERINFO_IBEACON_PUSH_CHANNEL_OPEN_TIME_LONG", 181);
      uqY = new a("USERINFO_IBEACON_SHAKE_TAB_DISPLAY_INT", 182);
      uqZ = new a("USERINFO_IBEACON_SHAKE_IS_RANGING_INTERFACE_BOOLEAN", 183);
      ura = new a("USERINFO_IBEACON_PUSH_BEACONINFO_STRING", 184);
      urb = new a("USERINFO_IBEACON_PUSH_LAST_BEACONINFO_STRING", 185);
      urc = new a("USERINFO_IBEACON_PUSH_IS_OPEN_BOOLEAN", 186);
      urd = new a("USERINFO_IBEACON_PUSH_OPEN_TIEMSTAMP_LONG", 187);
      ure = new a("USERINFO_IBEACON_PUSH_IS_IN_SHAKEUI_BOOLEAN", 188);
      urf = new a("USERINFO_IBEACON_SHAKE_TAB_IS_BLUETOOTH_RESIDENT_BOOLEAN", 189);
      urg = new a("USERINFO_IBEACON_SHAKE_TAB_IS_CITY_RESIDENT_BOOLEAN", 190);
      urh = new a("USERINFO_IBEACON_SHAKE_TAB_IS_UIN_RESIDENT_INT", 191);
      urj = new a("USERINFO_IBEACON_SHAKE_TAB_RESIDENT_GATED_LAUNCH_INT", 192);
      urk = new a("USERINFO_PROFILE_WEIDIANINFO_ALERT_INT", 193);
      urm = new a("USERINFO_LAST_LOCATION_STRING", 194);
      urn = new a("USERINFO_LAST_F2F_INVITE_TIME_LONG", 195);
      uro = new a("USERINFO_F2F_DELAY_TIME_LONG", 196);
      urp = new a("USERINFO_MALL_INDEX_TYPE_NAME_LIST_STRING_SYNC", 197);
      urq = new a("USERINFO_MALL_THIRD_PARTY_DISCLAIMER_STRING", 198);
      urr = new a("USERINFO_SHAKE_TV_ACCURACY_STRING", 199);
      urs = new a("USERINFO_IPCALL_ACCOUNT_CACHE_STRING", 200);
      urt = new a("USERINFO_SET_CAN_WEBVIEW_CACHE_DOWNLOAD_BOOLEAN", 201);
      uru = new a("USERINFO_SET_CAN_WEBVIEW_CACHE_PRE_PUSH_DOWNLOAD_BOOLEAN", 202);
      urv = new a("USERINFO_WEBVIEW_CACHE_CLEANUP_INTERVAL_LONG", 203);
      urw = new a("USERINFO_TRICK_SOTER_BOOLEAN", 204);
      urx = new a("USERINFO_CLEANUI_QQMGRINFO_STRING", 205);
      ury = new a("USERINFO_POSITION_AT_CHATRECORD_FIRST_IN_BOOLEAN", 206);
      urz = new a("USERINFO_POSITION_INVOKE_EDIT_TIP_IN_BOOLEAN", 207);
      urA = new a("USERINFO_HAD_SHOW_WALLET_MULTI_WALLET_GUIDE_BOOLEAN", 208);
      urB = new a("USERINFO_WALLET_BULLETIN_GET_TIME_LONG", 209);
      urC = new a("USERINFO_WALLET_BULLETIN_UPDATE_INTERVAL_LONG", 210);
      urD = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRL_STRING_SYNC", 211);
      urE = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_TIP_STRING_SYNC", 212);
      urF = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKFINDMORE_STRING_SYNC", 213);
      urG = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKCAMERA_STRING_SYNC", 214);
      urH = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKFULLSCREEN_STRING_SYNC", 215);
      urI = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYOPEN_BOOLEAN_SYNC", 216);
      urJ = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCTRLHASSHOW_BOOLEAN_SYNC", 217);
      urK = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCOUNT_INT_SYNC", 218);
      urL = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCOUNT2_INT_SYNC", 219);
      urM = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKPOST_STRING_SYNC", 220);
      urN = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKGOLDCAMERATIP_STRING_SYNC", 221);
      urO = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_TIPMARKCAMERATIP_STRING_SYNC", 222);
      urP = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_LEVELCTRL_STRING_SYNC", 223);
      urQ = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_FLOW_CONTROL_CACHEBUFFER_STRING", 224);
      urR = new a("USERINFO_NEWYEAR_2016_ACCEPT_CARD_ITEM_BUFFER_STRING_SYNC", 225);
      urS = new a("USERINFO_NEWYEAR_2016_HONGBAO_IS_OPEN_SNS_PAY_INT_SYNC", 226);
      urT = new a("USERINFO_NEWYEAR_2016_HONGBAO_CAN_OPEN_SNS_PAY_INT_SYNC", 227);
      urU = new a("USERINFO_NEWYEAR_2016_HONGBAO_IS_WHITE_USER_INT_SYNC", 228);
      urV = new a("USERINFO_NEWYEAR_2016_HONGBAO_OPEN_SNS_PAY_TITLE_STRING_SYNC", 229);
      urW = new a("USERINFO_NEWYEAR_2016_HONGBAO_OPEN_SNS_PAY_WORDING_STRING_SYNC", 230);
      urX = new a("USERINFO_NEWYEAR_2016_HONGBAO_SET_SNS_PAY_TITLE_STRING_SYNC", 231);
      urY = new a("USERINFO_NEWYEAR_2016_HONGBAO_SET_SNS_PAY_WORDING_STRING_SYNC", 232);
      urZ = new a("USERINFO_NEWYEAR_2016_HONGBAO_HAS_SHOW_SNS_PAY_GUIDE_DIALOG_BOOLEAN_SYNC", 233);
      usa = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_PATH_STRING_SYNC", 234);
      usb = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_ID_STRING_SYNC", 235);
      usc = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_AES_KEY_STRING_SYNC", 236);
      usd = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_LENGTH_INT_SYNC", 237);
      use = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_PRESTRAIN_FLAG_INT_SYNC", 238);
      usf = new a("USERINFO_FINGERPRINT_RETRY_TIME_INT_SYNC", 239);
      usg = new a("USERINFO_FINGERPRINT_LAST_FREEZE_TIME_LONG_SYNC", 240);
      ush = new a("USERINFO_OVER_SEA_DOWNLOAD_X5_HAS_NOTIFY_BOOLEAN_SYNC", 241);
      usi = new a("USERINFO_WALLET_PAY_DEDUCT_IS_NEW_BOOLEAN_SYNC", 242);
      usj = new a("USERINFO_WALLET_FETCH_CHARGE_TIP_DIALOG_BOOLEAN_SYNC", 243);
      usk = new a("USERINFO_WALLET_PREF_INFO_CACHE_TIME_LONG_SYNC", 244);
      usl = new a("USERINFO_WALLET_PREF_INFO_EXPIRES_INT_SYNC", 245);
      usm = new a("USERINFO_WALLET_BANKCARD_DETAIL_URL_STRING_SYNC", 246);
      usn = new a("USERINFO_WALLET_BANKCARD_DETAIL_URL_TIMESTAMP_LONG_SYNC", 247);
      uso = new a("USERINFO_WALLET_REALNAME_SWITCH_WORDING_STRING_SYNC", 248);
      usp = new a("USERINFO_WALLET_REALNAME_DISCLAIMER_QUERY_EXPIRED_TIME_LONG_SYNC", 249);
      usq = new a("USERINFO_WALLET_DISCLAIMER_NEED_AGERR_INT_SYNC", 250);
      usr = new a("USERINFO_WALLET_REALNAME_URL_STRING_SYNC", 251);
      uss = new a("USERINFO_WALLET_LBS_REPORT_DIALOG_SHOW_TIME_LONG_SYNC", 252);
      ust = new a("USERINFO_WALLET_LBS_REPORT_CONFIG_STRING_SYNC", 253);
      usu = new a("USERINFO_WALLET_LBS_REPORT_DIALOG_TITLE_STRING_SYNC", 254);
      usv = new a("USERINFO_WALLET_LBS_REPORT_DIALOG_CONTENT_STRING_SYNC", 255);
      usw = new a("USERINFO_WALLET_RELEAY_NAME_TIP_CONTENT_STRING_SYNC", 256);
      usx = new a("USERINFO_WALLET_RELEAY_NAME_BALANCE_CONTENT_STRING_SYNC", 257);
      usy = new a("USERINFO_WALLET_DEDUCT_SELECT_WORDING_STRING", 258);
      usz = new a("USERINFO_WALLET_DEDUCT_CHANGE_WORDING_STRING", 259);
      usA = new a("USERINFO_WALLET_DEDUCT_FORGET_URL_STRING", 260);
      usB = new a("USERINFO_MINIQB_SUPPORT_FILE_TYPE_STRING_SYNC", 261);
      usC = new a("USERINFO_FACE_DETECTION_ENROLLED_BOOLEAN_SYNC", 262);
      usD = new a("USERINFO_WALLET_MALLINDEX_OSDATA_TYPE_STRING_SYNC", 263);
      usE = new a("USERINFO_WALLET_REGION_TYPE_INT_SYNC", 264);
      usF = new a("USERINFO_RECHARGE_SHOW_REMIND_BOOLEAN", 265);
      usG = new a("USERINFO_APP_BRAND_PUBLIC_LIB_UPDATE_NEXT_TIME_SEC_LONG", 266);
      usH = new a("USERINFO_APP_BRAND_PUBLIC_LIB_USERNAME_STRING", 267);
      usI = new a("USERINFO_APP_BRAND_PUBLIC_LIB_APPID_STRING", 268);
      usJ = new a("USERINFO_APP_BRAND_PRUNE_PKG_NEXT_TIME_SEC_LONG", 269);
      usK = new a("USERINFO_APP_BRAND_USAGE_RECORD_SYNC_NEXT_TIME_SEC_LONG", 270);
      usL = new a("USERINFO_APP_BRAND_COLLECTION_LIST_FETCH_NEXT_TIME_SEC_LONG", 271);
      usM = new a("USERINFO_APP_BRAND_USAGE_RECORD_HAS_FAVORITE_BOOLEAN", 272);
      usN = new a("USERINFO_APP_BRAND_USAGE_RECORD_HAS_HISTORY_BOOLEAN", 273);
      usO = new a("USERINFO_APP_BRAND_SHOW_HISTORY_COUNT_BOOLEAN", 274);
      usP = new a("USERINFO_APP_BRAND_HISTORY_HAS_MORE_BOOLEAN", 275);
      usQ = new a("USERINFO_APP_BRAND_HISTORY_LIST_PAGING_LAST_SERVER_MIN_UPDATE_TIME_LONG", 276);
      usR = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_END_TIME_SECOND_LONG", 277);
      usS = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_MSG_ID_STRING", 278);
      usT = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_PUSH_TIME_LONG", 279);
      usU = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_SHOWTYPE_INT", 280);
      usV = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_REASON_INT", 281);
      usW = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_TIPS_STRING", 282);
      usX = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_HAS_REPORTED_SEE_RED_DOT_BOOLEAN", 283);
      usY = new a("USERINFO_APP_BRAND_ENTRANCE_SHOW_NEW_BOOLEAN", 284);
      usZ = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_MSG_ID_STRING", 285);
      uta = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_END_TIME_SECOND_LONG", 286);
      utb = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_LAST_TIME_SECOND_LONG", 287);
      utc = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_FREQUENCY_SECOND_LONG", 288);
      utd = new a("USERINFO_APP_BRAND_ENTRANCE_SHOW_RED_DOT_ONCE_BOOLEAN", 289);
      ute = new a("USERINFO_APP_BRAND_ENTRANCE_HAS_SEEN_NEARBY_SHOWCASE_BOOLEAN_SYNC", 290);
      utf = new a("USERINFO_APP_BRAND_CHATTING_BANNER_INFO_STRING_SYNC", 291);
      utg = new a("USERINFO_APP_BRAND_SEARCH_SHOW_OUT_DAILY_SYNC_LAST_TIME_SECOND_LONG", 292);
      uth = new a("USERINFO_APP_BRAND_RECENT_BAR_HAS_BEEN_REVEALED_BY_FIRST_APP_LAUNCH_BOOLEAN", 293);
      uti = new a("USERINFO_APP_BRAND_COLLECTION_RECORD_TABLE_UPGRADE_ISSUE_DONE_BOOLEAN", 294);
      utj = new a("APPBRAND_PREDOWNLOAD_CGI_PULL_LAST_TIME_IN_SECOND_LONG", 295);
      utk = new a("APPBRAND_PREDOWNLOAD_DONE_USAGE_USERNAME_DUPLICATE_BEFORE_BOOLEAN_SYNC", 296);
      utl = new a("APPBRAND_SHORTCUT_URL_UPGRADE_FIXED_BOOLEAN_SYNC", 297);
      utm = new a("APPBRAND_TBS_CHECK_INSTALL_LAST_TIME_IN_SECOND_LONG", 298);
      utn = new a("APPBRAND_BLOCK_QRCODE_PREFIX_STRING_SYNC", 299);
      uto = new a("USERINFO_EXT_SPORT_PKGNAME_STRING", 300);
      utp = new a("USERINFO_SENSE_WHERE_LOCATION_STRING", 301);
      utq = new a("USERINFO_LAST_GET_SENSE_WHERE_LOCATION_LONG", 302);
      utr = new a("USERINFO_LAST_START_SENSE_WHERE_LONG", 303);
      uts = new a("USERINFO_REPORT_SD_STATUS_TIME_LONG", 304);
      utt = new a("USERINFO_REPORT_HARDCODER_TIME_LONG", 305);
      utu = new a("USERINFO_ADDRESS_HAS_SHOW_DISCLAIMER_DIALOG_BOOLEAN_SYNC", 306);
      utv = new a("USERINFO_INVOICE_HAS_SHOW_DISCLAIMER_DIALOG_BOOLEAN_SYNC", 307);
      utw = new a("USERINFO_ONLINE_VIDEO_INT", 308);
      utx = new a("USERINFO_ADDRESS_HAS_SHOW_WALLETOFFLINE_DIALOG_BOOLEAN_SYNC", 309);
      uty = new a("USERINFO_SERVICE_NOTIFY_MESSAGE_NOTICE_BOOLEAN_SYNC", 310);
      utz = new a("USERINFO_WXA_CUSTOM_SESSION_MESSAGE_NOTICE_BOOLEAN_SYNC", 311);
      utA = new a("USERINFO_WALLETDIGITAL_CERT_CRT_STRING_SYNC", 312);
      utB = new a("USERINFO_WALLETDIGITAL_CERT_NO_STRING_SYNC", 313);
      utC = new a("USERINFO_WALLETDIGITAL_CERT_SHOW_INT_SYNC", 314);
      utD = new a("USERINFO_ADDRESS_HAS_SHOW_WALLETOFFLINE2_DIALOG_BOOLEAN_SYNC", 315);
      utE = new a("USERINFO_AA_MAX_PAYER_NUM_INT", 316);
      utF = new a("USERINFO_AA_MAX_RECEIVER_NUM_INT", 317);
      utG = new a("USERINFO_AA_MAX_TOTAL_USER_NUM_INT", 318);
      utH = new a("USERINFO_AA_MAX_TOTAL_AMOUNT_LONG", 319);
      utI = new a("USERINFO_AA_MAX_PER_AMOUNT_LONG", 320);
      utJ = new a("USERINFO_APP_BRAND_FAILED_FORMID_STRING", 321);
      utK = new a("USERINFO_LOCAL_SIGHT_RECODER_INT_SYNC", 322);
      utL = new a("USERINFO_LOCAL_SIGHT_ENCODEINSEND_INT_SYNC", 323);
      utM = new a("USERINFO_LOCAL_SIGHT_PREWVIEWSIZE_INT_SYNC", 324);
      utN = new a("USERINFO_LOCAL_SIGHT_BITRATE_INT_SYNC", 325);
      utO = new a("USERINFO_LOCAL_SIGHT_DEBUGINFO_INT_SYNC", 326);
      utP = new a("USERINFO_LOCAL_SIGHT_SET_SHUTTER_SOUND_INT_SYNC", 327);
      utQ = new a("USERINFO_LOCAL_SIGHT_CROP_INT_SYNC", 328);
      utR = new a("USERINFO_LOCAL_SIGHT_OPENOLDSIGHT_INT_SYNC", 329);
      utS = new a("USERINFO_LOCAL_SIGHT_SETTING_PRESET_INT_SYNC", 330);
      utT = new a("USERINFO_LOCAL_SIGHT_THREADCOUNT_INT_SYNC", 331);
      utU = new a("USERINFO_LOCAL_SIGHT_REALSCALE_INT_SYNC", 332);
      utV = new a("USERINFO_LOCAL_SIGHT_FOCUS_INT_SYNC", 333);
      utW = new a("USERINFO_LOCAL_SIGHT_FFMMPEGCUT_INT_SYNC", 334);
      utX = new a("USERINFO_LOCAL_SIGHT_COMPRESS_TO_SINGLE_CHANNEL_INT_SYNC", 335);
      utY = new a("USERINFO_LOCAL_SIGHT_CLIP_PREVIEW_MEDIA_PLAYER_INT_SYNC", 336);
      utZ = new a("USERINFO_LOCAL_SIGHT_AUDIO_RECORDER_TYPE_INT_SYNC", 337);
      uua = new a("USERINFO_MMSIGHT_MEDIACODEC_COLORFORMAT_INT", 338);
      uub = new a("USERINFO_WECHAT_DB_REPORT_LAST_TIME_LONG", 339);
      uuc = new a("USERINFO_CLOG_SAMPLING_REFRESH_TIME_LONG", 340);
      uud = new a("USERINFO_AVATAR_LAST_MIGRATION_FINISH_LONG", 341);
      uue = new a("USERINFO_WECHAT_FILE_SCAN_LAST_TIME_LONG", 342);
      uuf = new a("USERINFO_WECHAT_FILE_SCAN_INTERVAL_LONG", 343);
      uug = new a("USERINFO_WECHAT_FILE_SCAN_WAIT_TIME_LONG", 344);
      uuh = new a("USERINFO_INSTALL_FIRST_TIME_LONG", 345);
      uui = new a("USERINFO_INSTALL_FIRST_CLIENT_VERSION_INT", 346);
      uuj = new a("USERINFO_INSTALL_LAST_REPORT_TIME_LONG", 347);
      uuk = new a("USERINFO_MSG_SYNCHRONIZE_BOOLEAN", 348);
      uul = new a("USERINFO_LOGIN_EXT_DEVICE_INFO_INT", 349);
      uum = new a("USERINFO_BACKUP_PC_BACKUPING_BOOLEAN", 350);
      uun = new a("USERINFO_BACKUP_PC_RECOVERING_BOOLEAN", 351);
      uuo = new a("USERINFO_BACKUP_PC_MERGERING_BOOLEAN", 352);
      uup = new a("USERINFO_BACKUP_MOVE_BACKUPING_BOOLEAN", 353);
      uuq = new a("USERINFO_BACKUP_MOVE_RECOVERING_BOOLEAN", 354);
      uur = new a("USERINFO_BACKUP_MOVE_MERGERING_BOOLEAN", 355);
      uus = new a("USERINFO_BACKUP_OLD_RECORDS_BOOLEAN", 356);
      uut = new a("USERINFO_WECHAT_BACKUP_CHAT_SIZE_CALCULATE_LAST_TIME_LONG", 357);
      uuu = new a("USERINFO_WECHAT_BACKUP_CHAT_SIZE_CALCULATE_INTERVAL_LONG", 358);
      uuv = new a("USERINFO_WECHAT_BACKUP_CHAT_SIZE_CALCULATE_WAIT_TIME_LONG", 359);
      uuw = new a("USERINFO_DELAY_TRANSFER_CONFIRM_WORDING_STRING", 360);
      uux = new a("USERINFO_DELAY_TRANSFER_SWITCH_WORDING_STRING", 361);
      uuy = new a("USERINFO_DELAY_TRANSFER_REMIND_WORDING_STRING", 362);
      uuz = new a("USERINFO_DELAY_TRANSFER_EXPIRE_TIME_LONG", 363);
      uuA = new a("USERINFO_DELAY_TRANSFER_DESC_URL_STRING", 364);
      uuB = new a("USERINFO_DELAY_TRANSFER_DESC_URL_FLAG_INT", 365);
      uuC = new a("USERINFO_DELAY_TRANSFER_SHOW_SWITCH_FLAG_INT", 366);
      uuD = new a("USERINFO_WEIXIN_MUL_TERMINAL_AUTOSYNC_BOOLEAN", 367);
      uuE = new a("USERINFO_WEIXIN_CAMERA_STATE_INT", 368);
      uuF = new a("USERINFO_WEIXIN_CAMERASAVEIMAGE_STATE_BOOLEAN", 369);
      uuG = new a("USERINFO_WEIXIN_CAMERASAVEVIDEO_STATE_BOOLEAN", 370);
      uuH = new a("USERINFO_WALLET_REMITTANCE_STRING_SYNC", 371);
      uuI = new a("USERINFO_WALLET_HONGBAO_STRING_SYNC", 372);
      uuJ = new a("USERINFO_WEBVIEW_KEEP_STRING_SYNC", 373);
      uuK = new a("USERINFO_WEBVIEW_KEEP_LAST_PAGE_STRING_SYNC", 374);
      uuL = new a("USERINFO_WEBVIEW_KEEP_LAST_PAGE_TITLE_STRING_SYNC", 375);
      uuM = new a("USERINFO_F2F_RING_TONE_STRING", 376);
      uuN = new a("USERINFO_WXA_SEARCH_INPUT_HINT_LANG_STRING_SYNC", 377);
      uuO = new a("USERINFO_WXA_SEARCH_INPUT_HINT_CONTENT_STRING_SYNC", 378);
      uuP = new a("USERINFO_WXA_SEARCH_INPUT_HINT_CONTENT_ID_STRING_SYNC", 379);
      uuQ = new a("USERINFO_WXA_SEARCH_INPUT_HINT_UPDATE_TIME_LONG_SYNC", 380);
      uuR = new a("USERINFO_SHAKE_NEWYEAR_COOKIE_STRING", 381);
      uuS = new a("USERINFO_SNS_RECENT_LIMITED_ID_LONG_SYNC", 382);
      uuT = new a("USERINFO_VIDEO_NEED_RESET_EXTRACTOR_BOOLEAN", 383);
      uuU = new a("USERINFO_MALL_NEWS_MARKED_STRING_SYNC", 384);
      uuV = new a("USERINFO_LAUNCH_APP_NOT_ASK_PKG_STRING", 385);
      uuW = new a("USERINFO_WEBVIEW_KEEP_TOP_SCENE_INT_SYNC", 386);
      uuX = new a("USERINFO_SNS_INTRODUCE_SETTING_DISPLAY_BOOLEAN_SYNC", 387);
      uuY = new a("USERINFO_FACE_SHOW_TUTORIAL_BOOLEAN_SYNC", 388);
      uuZ = new a("USERINFO_HEAVY_USER_FLAG_LONG", 389);
      uva = new a("USERINFO_HEAVY_USER_REPORT_TIME_LONG", 390);
      uvb = new a("USERINFO_HEAVY_USER_REPORT_TYPE_SD_FILE_SIZE_LONG", 391);
      uvc = new a("USERINFO_HEAVY_USER_REPORT_TYPE_SD_FILE_RATIO_LONG", 392);
      uvd = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_SIZE_LONG", 393);
      uve = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_MESSAGE_LONG", 394);
      uvf = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_CONVERSATION_LONG", 395);
      uvg = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_CONTACT_LONG", 396);
      uvh = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_CHATROOM_LONG", 397);
      uvi = new a("USERINFO_HEAVY_USER_REPORT_TYPE_FAV_DB_SIZE_LONG", 398);
      uvj = new a("USERINFO_MM_LVFETIME_REPORT_PID_INT", 399);
      uvk = new a("USERINFO_MM_LVFETIME_REPORT_LIFETIME_LONG", 400);
      uvl = new a("USERINFO_MM_LVFETIME_REPORT_MEMORY_PSS_INT", 401);
      uvm = new a("USERINFO_X264_VERSION_INT", 402);
      uvn = new a("USERINFO_SETTING_RECENT_RED_DOT_ID_INT", 403);
      uvo = new a("USERINFO_MY_RED_DOT_WILL_SHOW_ID_INT", 404);
      uvp = new a("USERINFO_MY_RED_DOT_DID_SHOW_ID_INT", 405);
      uvq = new a("USERINFO_SETTING_RED_DOT_WILL_SHOW_ID_INT", 406);
      uvr = new a("USERINFO_SETTING_RED_DOT_DID_SHOW_ID_INT", 407);
      uvs = new a("USERINFO_PRIVATY_RED_DOT_WILL_SHOW_ID_INT", 408);
      uvt = new a("USERINFO_PRIVATY_RED_DOT_DID_SHOW_ID_INT", 409);
      uvu = new a("USERINFO_RECENT_RED_DOT_WILL_SHOW_ID_INT", 410);
      uvv = new a("USERINFO_RECENT_RED_DOT_DID_SHOW_ID_INT", 411);
      uvw = new a("USERINFO_WEIXIN_ENABLEFPSTOOL_STATE_BOOLEAN", 412);
      uvx = new a("USERINFO_CONTINUE_TEST_SCAN_TIME_INT", 413);
      uvy = new a("USERINFO_ABOUT_INVOICE_ENTRANCE_BOOLEAN", 414);
      uvz = new a("USERINFO_MUSIO_LAST_SCAN_MUSIC_PIECE_FILE_TIME_LONG", 415);
      uvA = new a("USERINFO_MUSIO_LAST_SCAN_MUSIC_FILE_TIME_LONG", 416);
      uvB = new a("USERINFO_MUSIC_PLAYER_SWITCH_FLAG_INT_SYNC", 417);
      uvC = new a("USERINFO_MUSIC_SUPPORT_PLAYER_FLAG_SEQUENCE_LONG_SYNC", 418);
      uvD = new a("USERINFO_MUSIC_RREMOVE_PLAYING_AUDIO_PLAYER_GROUP_COUNT_INT_SYNC", 419);
      uvE = new a("USERINFO_MUSIC_SHOW_AUDIO_TOAST_BOOLEAN_SYNC", 420);
      uvF = new a("USERINFO_WEB_SEARCH_CONFIG_ZH_CN_STRING", 421);
      uvG = new a("USERINFO_WEB_SEARCH_CONFIG_ZH_TW_STRING", 422);
      uvH = new a("USERINFO_WEB_SEARCH_CONFIG_ZH_HK_STRING", 423);
      uvI = new a("USERINFO_WEB_SEARCH_CONFIG_EN_STRING", 424);
      uvJ = new a("USERINFO_WEB_SEARCH_CONFIG_AR_STRING", 425);
      uvK = new a("USERINFO_WEB_SEARCH_CONFIG_DE_STRING", 426);
      uvL = new a("USERINFO_WEB_SEARCH_CONFIG_DE_DE_STRING", 427);
      uvM = new a("USERINFO_WEB_SEARCH_CONFIG_ES_STRING", 428);
      uvN = new a("USERINFO_WEB_SEARCH_CONFIG_FR_STRING", 429);
      uvO = new a("USERINFO_WEB_SEARCH_CONFIG_HE_STRING", 430);
      uvP = new a("USERINFO_WEB_SEARCH_CONFIG_HI_STRING", 431);
      uvQ = new a("USERINFO_WEB_SEARCH_CONFIG_ID_STRING", 432);
      uvR = new a("USERINFO_WEB_SEARCH_CONFIG_IN_STRING", 433);
      uvS = new a("USERINFO_WEB_SEARCH_CONFIG_IT_STRING", 434);
      uvT = new a("USERINFO_WEB_SEARCH_CONFIG_IW_STRING", 435);
      uvU = new a("USERINFO_WEB_SEARCH_CONFIG_JA_STRING", 436);
      uvV = new a("USERINFO_WEB_SEARCH_CONFIG_KO_STRING", 437);
      uvW = new a("USERINFO_WEB_SEARCH_CONFIG_LO_STRING", 438);
      uvX = new a("USERINFO_WEB_SEARCH_CONFIG_MS_STRING", 439);
      uvY = new a("USERINFO_WEB_SEARCH_CONFIG_MY_STRING", 440);
      uvZ = new a("USERINFO_WEB_SEARCH_CONFIG_PL_STRING", 441);
      uwa = new a("USERINFO_WEB_SEARCH_CONFIG_PT_STRING", 442);
      uwb = new a("USERINFO_WEB_SEARCH_CONFIG_RU_STRING", 443);
      uwc = new a("USERINFO_WEB_SEARCH_CONFIG_TH_STRING", 444);
      uwd = new a("USERINFO_WEB_SEARCH_CONFIG_TR_STRING", 445);
      uwe = new a("USERINFO_WEB_SEARCH_CONFIG_VI_STRING", 446);
      uwf = new a("USERINFO_CLIENT_SERVER_DIFF_TIME_LONG", 447);
      uwg = new a("USERINFO_CLIENT_SERVER_TIME_LONG", 448);
      uwh = new a("USERINFO_CLIENT_SERVER_ELAPSED_TIME_LONG", 449);
      uwi = new a("USERINFO_MSG_DELAY_STAT_STRING", 450);
      uwj = new a("USERINFO_SET_SUPPORT_WX_CODE_BOOLEAN", 451);
      uwk = new a("USERINFO_TENCENT_MAP_COUNT_INT", 452);
      uwl = new a("USERINFO_CROWDTEST_CLIENT_VERSION_INT", 453);
      uwm = new a("USERINFO_CROWDTEST_APPLY_EXPIRE_LONG", 454);
      uwn = new a("USERINFO_CROWDTEST_APPLY_LINK_STRING", 455);
      uwo = new a("USERINFO_CROWDTEST_FEEDBACK_LINK_STRING", 456);
      uwp = new a("USERINFO_SETTING_PLUGIN_SWITCH_REDDOT_INT", 457);
      uwq = new a("USERINFO_SETTING_PLUGIN_SWITCH_NAMES_STRING", 458);
      uwr = new a("USERINFO_BACKGROUND_CALC_TIME_LONG", 459);
      uws = new a("USERINFO_WELAB_LAST_UPDATE_TIME_LONG", 460);
      uwt = new a("USERINFO_WELAB_UPDATE_TIME_INTERVAL_INT", 461);
      uwu = new a("USERINFO_WELAB_SERVER_TIMESTAMP_INT", 462);
      uwv = new a("USERINFO_WELAB_REDPOINT_STRING", 463);
      uww = new a("USERINFO_WELAB_APP_REDPOINT_STRING", 464);
      uwx = new a("USERINFO_WENOTE_KEEP_TOP_DATA_STRING_SYNC", 465);
      uwy = new a("BUSINESS_OFFLINE_GETMSG_INTERVAL_INT", 466);
      uwz = new a("BUSINESS_OFFLINE_GETMSG_ACK_KEY_STRING", 467);
      uwA = new a("BUSINESS_OFFLINE_GETMSG_MAX_POS_TIME_INT", 468);
      uwB = new a("USERINFO_WALLET_HK_PAY_URL_STRING", 469);
      uwC = new a("USERINFO_SUPPORT_HEVC_VIDEO_INT", 470);
      uwD = new a("USERINFO_HAD_PRELOAD_SIZE_LONG", 471);
      uwE = new a("USERINFO_HAD_PRELOAD_TIME_LONG", 472);
      uwF = new a("USERINFO_C2C_HAD_PRELOAD_COUNT_INT", 473);
      uwG = new a("USERINFO_SNS_HAD_PRELOAD_COUNT_INT", 474);
      uwH = new a("USERINFO_CHATTING_MONITOR_MAIN_WORDING_STRING_SYNC", 475);
      uwI = new a("USERINFO_CHATTING_MONITOR_MAIN_URL_STRING_SYNC", 476);
      uwJ = new a("USERINFO_CHATTING_MONITOR_MAIN_INTERVAL_LONG_SYNC", 477);
      uwK = new a("USERINFO_CHATTING_MONITOR_MAIN_CLOSABLE_BOOLEAN_SYNC", 478);
      uwL = new a("USERINFO_CHATTING_MONITOR_MAIN_AUTOTRIGGER_BOOLEAN_SYNC", 479);
      uwM = new a("USERINFO_CHATTING_BANNER_CLOSED_BOOLEAN_SYNC", 480);
      uwN = new a("USERINFO_MAIN_MONITOR_MAIN_WORDING_STRING_SYNC", 481);
      uwO = new a("USERINFO_MAIN_MONITOR_MAIN_URL_STRING_SYNC", 482);
      uwP = new a("USERINFO_MAIN_MONITOR_MAIN_INTERVAL_LONG_SYNC", 483);
      uwQ = new a("USERINFO_MAIN_MONITOR_MAIN_CLOSABLE_BOOLEAN_SYNC", 484);
      uwR = new a("USERINFO_MAIN_MONITOR_MAIN_AUTOTRIGGER_BOOLEAN_SYNC", 485);
      uwS = new a("USERINFO_MAIN_BANNER_CLOSED_BOOLEAN_SYNC", 486);
      uwT = new a("USERINFO_MONITOR_BANNER_MSG_COME_TIME_TICKS_LONG_SYNC", 487);
      uwU = new a("USERINFO_MONITOR_IS_TRIGGERED_BOOLEAN_SYNC", 488);
      uwV = new a("USERINFO_RECENT_LAUNCH_AA_GROUP_STRING_SYNC", 489);
      uwW = new a("USERINFO_WALLET_ENTRY_REDDOT_PUSH_DATE_LONG_SYNC", 490);
      uwX = new a("USERINFO_WALLET_INDEX_MAIDAN_STRING_SYNC", 491);
      uwY = new a("USERINFO_LQT_WALLET_RED_DOT_WORDING_STRING", 492);
      uwZ = new a("USERINFO_LQT_WALLET_RED_DOT_INT", 493);
      uxa = new a("USERINFO_LQT_BALANCE_RED_DOT_INT", 494);
      uxb = new a("USERINFO_LQT_LINK_RED_DOT_INT", 495);
      uxc = new a("USERINFO_LQB_MALL_ENTRY_RED_DOT_INT", 496);
      uxd = new a("USERINFO_WEPKG_CHECK_DOWNLOAD_TIME_LONG", 497);
      uxe = new a("USERINFO_WEPKG_FRONT_TRIGGER_DOWNLOAD_TIME_LONG", 498);
      uxf = new a("USERINFO_WEPKG_ENTRANCE_TRIGGER_DOWNLOAD_TIME_LONG", 499);
      uxg = new a("USERINFO_GAME_SILENT_DOWNLOAD_TIME_LONG", 500);
      uxh = new a("USERINFO_FTS_MASTER_DB_VERISON_INT_SYNC", 501);
      uxi = new a("USERINFO_FTS_MASTER_DB_CORRUPT_REBUILD_TIME_INT_SYNC", 502);
      uxj = new a("USERINFO_TINKER_BOOTS_CHECK_LAST_TIME_LONG", 503);
      uxk = new a("BUSINESS_OFFLINE_GETMSG_REQ_KEY_STRING", 504);
      uxl = new a("BUSINESS_OFFLINE_GETMSG_PAYMSG_TYPE_INT", 505);
      uxm = new a("BUSINESS_OFFLINE_GETMSG_TRANS_ID_STRING", 506);
      uxn = new a("USERINFO_FTS_DISCOVERY_RED_ID_INT", 507);
      uxo = new a("USERINFO_FTS_DISCOVERY_RED_XML_STRING", 508);
      uxp = new a("NEW_BANDAGE_DATASOURCE_WALLET_MORE_TAB_STRING_SYNC", 509);
      uxq = new a("NEW_BANDAGE_DATASOURCE_WALLET_BANKCARD_STRING_SYNC", 510);
      uxr = new a("NEW_BANDAGE_WATCHER_WALLET_COMMON_STRING_SYNC", 511);
      uxs = new a("USERINFO_WALLET_MORE_TAB_REDDOT_WORDING_STRING_SYNC", 512);
      uxt = new a("USERINFO_WALLET_BANKCARD_SERIAL_STRING_SYNC", 513);
      uxu = new a("USERINFO_CALC_WX_SCAN_STEP_INT", 514);
      uxv = new a("USERINFO_CALC_WX_SCAN_CURR_MSGID2_LONG", 515);
      uxw = new a("USERINFO_CALC_WX_SCAN_MAX_MSGID2_LONG", 516);
      uxx = new a("USERINFO_CALC_WX_SCAN_REPORT_TIME_LONG", 517);
      uxy = new a("USERINFO_CALC_WX_SCAN_START_TIME_LONG", 518);
      uxz = new a("USERINFO_CALC_WX_SCAN_FINISH_TIME_LONG", 519);
      uxA = new a("USERINFO_CALC_WX_SCAN_SHOW_FILE_INT", 520);
      uxB = new a("USERINFO_WALLET_F2F_COLLECT_PAY_URL_STRING_SYNC", 521);
      uxC = new a("USERINFO_WALLET_F2F_COLLECT_TRUE_NAME_STRING_SYNC", 522);
      uxD = new a("USERINFO_WALLET_F2F_COLLECT_BOTTOM_MENU_STRING_SYNC", 523);
      uxE = new a("USERINFO_WALLET_F2F_COLLECT_BOTTOM_LEFT_ICON_URL_STRING_SYNC", 524);
      uxF = new a("USERINFO_WALLET_F2F_COLLECT_UPRIGHT_MENU_STRING_SYNC", 525);
      uxG = new a("USERINFO_WALLET_BIND_CARD_MENU_STRING_SYNC", 526);
      uxH = new a("USERINFO_WALLET_FACING_REDDOT_WORDING_STRING_SYNC", 527);
      uxI = new a("USERINFO_HARDWARE_LAST_UPLOAD_TICKS_LONG_SYNC", 528);
      uxJ = new a("USERINFO_WALLET_LQT_OPEN_FLAG_INT_SYNC", 529);
      uxK = new a("USERINFO_WALLET_LQT_ENTRY_WORDING_STRING_SYNC", 530);
      uxL = new a("USERINFO_WALLET_SET_PWD_TIP_INT_SYNC", 531);
      uxM = new a("USERINFO_WALLETLOCK_CURRENT_USED_TYPE_INT_SYNC", 532);
      uxN = new a("USERINFO_WALLETLOCK_FINGERPRINT_IS_OPENED_BOOLEAN_SYNC", 533);
      uxO = new a("USERINFO_WALLETLOCK_FINGERPRINT_FID_LIST_STRING_SYNC", 534);
      uxP = new a("USERINFO_WALLETLOCK_GESTURE_IS_OPENED_BOOLEAN_SYNC", 535);
      uxQ = new a("USERINFO_WALLETLOCK_FINGERPRINT_LAST_VERIFY_OK_TIME_STRING_SYNC", 536);
      uxR = new a("USERINFO_WALLETLOCK_FINGERPRINT_LAST_BLOCK_TIME_STRING_SYNC", 537);
      uxS = new a("USERINFO_WALLETLOCK_IS_AUTO_JUMP_TO_GESTURE_WHEN_NOT_SUPPORT_FINGERPRINT_BOOLEAN_SYNC", 538);
      uxT = new a("USERINFO_WALLETLOCK_FACEID_IS_OPENED_BOOLEAN_SYNC", 539);
      uxU = new a("USERINFO_WALLETLOCK_CURRENT_JSON_TYPE_STRING_SYNC", 540);
      uxV = new a("USERINFO_WALLET_USERINFO_UNREGTITLE_TYPE_STRING_SYNC", 541);
      uxW = new a("USERINFO_WALLET_USERINFO_UNREGURL_TYPE_STRING_SYNC", 542);
      uxX = new a("USERINFO_WCPAY_WALLET_BUFFER_CN_STRING_SYNC", 543);
      uxY = new a("USERINFO_WCPAY_WALLET_BUFFER_MY_STRING_SYNC", 544);
      uxZ = new a("USERINFO_WCPAY_WALLET_BUFFER_ZA_STRING_SYNC", 545);
      uya = new a("USERINFO_WCPAY_WALLET_BUFFER_HK_STRING_SYNC", 546);
      uyb = new a("USERINFO_WALLET_QR_REWARD_PHOTO_WIDTH_INT_SYNC", 547);
      uyc = new a("USERINFO_WALLET_QR_REWARD_ICON_WIDTH_INT_SYNC", 548);
      uyd = new a("USERINFO_WALLET_QR_REWARD_WORD_STRING_SYNC", 549);
      uye = new a("USERINFO_WALLET_QR_REWARD_DESC_STRING_SYNC", 550);
      uyf = new a("USERINFO_WALLET_QR_REWARD_TRUE_NAME_STRING_SYNC", 551);
      uyg = new a("USERINFO_WALLET_QR_REWARD_MAX_AMT_INT_SYNC", 552);
      uyh = new a("USERINFO_WALLET_QR_REWARD_AMT_LIST_STRING_SYNC", 553);
      uyi = new a("USERINFO_WALLET_QR_REWARD_BOTTOM_STR_STRING_SYNC", 554);
      uyj = new a("USERINFO_WALLET_QR_REWARD_BOTTOM_URL_STRING_SYNC", 555);
      uyk = new a("USERINFO_WALLET_QR_REWARD_LAST_PHOTO_URL_STRING_SYNC", 556);
      uyl = new a("USERINFO_SHOW_MSG_DELAY_BOOLEAN_SYNC", 557);
      uym = new a("USERINFO_WALLET_COLLECT_BUSITYPE_INT_SYNC", 558);
      uyn = new a("USERINFO_WALLET_COLLECT_BUSIURL_STRING_SYNC", 559);
      uyo = new a("USERINFO_SETTING_SWITCH_ACCOUNT_FIRST_CLICK_BOOLEAN_SYNC", 560);
      uyp = new a("GAME_FIND_MORE_FRIEND_MSG_ID_STRING_SYNC", 561);
      uyq = new a("NEW_BANDAGE_DATASOURCE_GROUP_PAY_STRING_SYNC", 562);
      uyr = new a("NEW_BANDAGE_DATASOURCE_F2F_COLLECT_STRING_SYNC", 563);
      uys = new a("NEW_BANDAGE_DATASOURCE_F2F_HB_STRING_SYNC", 564);
      uyt = new a("NEW_BANDAGE_DATASOURCE_QR_REWARD_STRING_SYNC", 565);
      uyu = new a("NEW_BANDAGE_DATASOURCE_BANK_REMIT_STRING_SYNC", 566);
      uyv = new a("USERINFO_PAY_OR_RECV_HAS_SHOW_RED_DOT_BOOLEAN_SYNC", 567);
      uyw = new a("USERINFO_WALLET_BANK_REMIT_MIN_POUNDAGE_INT_SYNC", 568);
      uyx = new a("USERINFO_WALLET_BANK_REMIT_MAX_TRANSFER_AMOUNT_INT_SYNC", 569);
      uyy = new a("USERINFO_WALLET_BANK_REMIT_PAYLIST_STRING_SYNC", 570);
      uyz = new a("USERINFO_WALLET_BANK_REMIT_OPEN_INT_SYNC", 571);
      uyA = new a("USERINFO_WALLET_BANK_REMIT_HAS_SHOWN_RED_DOT_INT_SYNC", 572);
      uyB = new a("USERINFO_WALLET_MENU_UI_REDDOT_CONFIG_STRING_SYNC", 573);
      uyC = new a("USERINFO_WALLET_MALL_MENU_UI_REDDOT_CONFIG_BOOLEAN_SYNC", 574);
      uyD = new a("USERINFO_WALLET_MALL_MENU_UI_REDDOT_CONFIG_EXPIRETIME_LONG_SYNC", 575);
      uyE = new a("USERINFO_CELLTEXTVIEW_CONFIG_BOOLEAN_SYNC", 576);
      uyF = new a("USERINFO_APPBRANDRECENTVIEW_CONFIG_BOOLEAN_SYNC", 577);
      uyG = new a("USERINFO_WALLET_BALANCE_MENU_INFO_STRING_SYNC", 578);
      uyH = new a("USERINFO_WALLET_ENTRY_WORDING_STRING_SYNC", 579);
      uyI = new a("USERINFO_WALLET_MY_ENTRY_TAB_REDDOT_BOOLEAN_SYNC", 580);
      uyJ = new a("USERINFO_WALLET_MY_ENTRY_TAB_REDDOT_EXPIRETIME_LONG_SYNC", 581);
      uyK = new a("USERINFO_WALLET_MY_ENTRY_REDDOT_BOOLEAN_SYNC", 582);
      uyL = new a("USERINFO_WALLET_MY_ENTRY_REDDOT_EXPIRETIME_LONG_SYNC", 583);
      uyM = new a("USERINFO_LQT_DEFAULTCARD_STRING_SYNC", 584);
      uyN = new a("USERINFO_LQT_DEFAULTCARD_SAVE_STRING_SYNC", 585);
      uyO = new a("USERINFO_LQT_DEFAULTCARD_FETCH_STRING_SYNC", 586);
      uyP = new a("USERINFO_HARDWARE_CPU_FREQUENCY_MHZ_INT_SYNC", 587);
      uyQ = new a("USERINFO_HARDWARE_MEMORY_IN_MB_INT_SYNC", 588);
      uyR = new a("USERINFO_TOP_STORY_REDDOT_TIMESTAMP_LONG", 589);
      uyS = new a("USERINFO_TOP_STORY_RED_XML_REC_STRING", 590);
      uyT = new a("NEW_BANDAGE_DATASOURCE_DEVICE_PROTECT_STRING_SYNC", 591);
      uyU = new a("NEW_BANDAGE_WATCHER_SETTINGS_MORE_SAFE_STRING_SYNC", 592);
      uyV = new a("USERINFO_DEVICE_PROTECT_SECURITY_STATUS_INT_SYNC", 593);
      uyW = new a("USERINFO_FTS_RECOMMEND_LOCAL_FILE_INDEX_LONG_SYNC", 594);
      uyX = new a("USERINFO_WALLET_F2F_RCV_VOICE_PLAYED_LIST_STRING_SYNC", 595);
      uyY = new a("USERINFO_WALLET_AGREE_PAY_BOOLEAN_SYNC", 596);
      uyZ = new a("USERINFO_MULTITALK_DISABLE_TIME_INT_SYNC", 597);
      uza = new a("USERINFO_MULTITALK_DISABLE_TIMESTAMP_LONG_SYNC", 598);
      uzb = new a("USERINFO_WALLET_INDEX_IS_SHOW_LQB_INT_SYNC", 599);
      uzc = new a("USERINFO_WALLET_INDEX_IS_LQB_OPEN_INT_SYNC", 600);
      uzd = new a("USERINFO_WALLET_INDEX_LQB_OPEN_URL_STRING_SYNC", 601);
      uze = new a("USERINFO_LAST_LOGIN_USERNAME_STRING", 602);
      uzf = new a("USERINFO_LAST_LOGIN_AVATAR_PATH_STRING", 603);
      uzg = new a("USERINFO_VOIP_MSG_SOUND_DIFF_STAT_BOOLEAN_SYNC", 604);
      uzh = new a("USERINFO_SEARCH_REDDOT_LONG", 605);
      uzi = new a("USERINFO_NEED_BIRTHDAY_BOOLEAN_SYNC", 606);
      uzj = new a("USERINFO_NEED_OPENPLATFORM_BOOLEAN_SYNC", 607);
      uzk = new a("USERINFO_NEED_CONFIRM_BOOLEAN_SYNC", 608);
      uzl = new a("USERINFO_READERAPP_REPORT_TIMESTAMP_LONG", 609);
      uzm = new a("USERINFO_GET_EXPT_INTERVAL_SEC_INT", 610);
      uzn = new a("USERINFO_GET_EXPT_LAST_TIME_SEC_INT", 611);
      uzo = new a("USERINOF_VOICE_INPUT_DEF_LANG_HISTORY_STRING", 612);
      uzp = new a("USERINFO_BIZ_TIME_LINE_GROUP_START_TIME_STRING_SYNC", 613);
      uzq = new a("USERINFO_BIZ_TIME_LINE_MIGRATE_DATA_INT_SYNC", 614);
      uzr = new a("USERINFO_BIZ_TIME_LINE_OFTEN_READ_STRING_SYNC", 615);
      uzs = new a("USERINFO_ROOM_EXPT_INFO_STRING", 616);
      uzt = new a("USERINFO_WEBVIEW_BAG_INFO_STRING_SYNC", 617);
      uzu = new a("USERINFO_WEBVIEW_BAG_TEST_INFO_STRING_SYNC", 618);
      uzv = new a("USERINFO_TOP_STORY_RED_DOT_RESULT_STRING", 619);
      uzw = new a("USERINFO_TOP_STORY_HOME_UI_TIMESTAMP_LONG", 620);
      uzx = new a("USERINFO_RECENT_SMILEY_STRING", 621);
      uzy = new a("USERINFO_SNS_MEDIA_COLLAPSE_STRING", 622);
      uzz = new a("USERINFO_SNS_MEDIA_COLLAPSE_SNS_ID_LONG", 623);
      uzA = new a("USERINFO_EMOJI_CAPTURE_OPENED_BOOLEAN", 624);
      uzB = new a("USERINFO_EMOJI_CAPTURE_IMITATE_SAVED_BOOLEAN", 625);
      wuP = new a("USERINFO_EMOJI_CAPTURE_TIP_SHOW_BOOLEAN", 626);
      wuQ = new a("USERINFO_EMOJI_CAPTURE_NEW_DOT_START_LONG", 627);
      wuR = new a("USERINFO_EMOJI_CAPTURE_NEW_DOT_CLICK_BOOLEAN", 628);
      wuS = new a("USERINFO_EMOJI_CAPTURE_CHANGE_CUSTOM_TAB_BOOLEAN", 629);
    }
    
    private a() {}
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes.jar
 * Qualified Name:     com.tencent.mm.storage.ac
 * JD-Core Version:    0.7.0.1
 */