package com.tencent.mm.plugin.appbrand.jsapi;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiAddDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiAddDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiAddDownloadTaskStraight;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiCancelDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiCancelDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiGetInstallState;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiGetInstallStateForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiInstallDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiInstallDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiJumpDownloaderWidgetForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiLaunchApplicationForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiPauseDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiPauseDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiQueryDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiQueryDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiResumeDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiGetBackgroundAudioState;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiGetMusicPlayerState;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiOperateMusicPlayer;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiPausePlayVoice;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiSetBackgroundAudioStateWC;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiStartPlayVoice;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiStartRecordVoice;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiStopPlayVoice;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiStopRecordVoice;
import com.tencent.mm.plugin.appbrand.jsapi.auth.JsApiAuthorize;
import com.tencent.mm.plugin.appbrand.jsapi.auth.JsApiLogin;
import com.tencent.mm.plugin.appbrand.jsapi.auth.JsApiOperateWXData;
import com.tencent.mm.plugin.appbrand.jsapi.backgroundfetch.JsApiSetBackgroundFetchToken;
import com.tencent.mm.plugin.appbrand.jsapi.backgroundfetch.JsApiTriggerBackgroundFetch;
import com.tencent.mm.plugin.appbrand.jsapi.bio.face.JsApiCheckIsSupportFaceDetect;
import com.tencent.mm.plugin.appbrand.jsapi.bio.soter.JsApiCheckBioEnrollment;
import com.tencent.mm.plugin.appbrand.jsapi.bio.soter.JsApiCheckIsSupportSoterAuthentication;
import com.tencent.mm.plugin.appbrand.jsapi.bizvideochannel.JsApiHandleMpChannelAction;
import com.tencent.mm.plugin.appbrand.jsapi.bizvideochannel.JsApiOpenWebViewUseFastLoad;
import com.tencent.mm.plugin.appbrand.jsapi.camera.AppBrandCameraView;
import com.tencent.mm.plugin.appbrand.jsapi.camera.SameLayerCameraView;
import com.tencent.mm.plugin.appbrand.jsapi.contact.JsApiChooseWeChatContact;
import com.tencent.mm.plugin.appbrand.jsapi.fakenative.JsApiRemoveSplashScreenshot;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiDeleteFinderDataItem;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiFetchSendingAndFailProfileFeed;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiFinderEndorsementFinished;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiGetFinderAccount;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiPostFinderDataItem;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiResendProfileFeed;
import com.tencent.mm.plugin.appbrand.jsapi.lab.JsApiGetLabInfo;
import com.tencent.mm.plugin.appbrand.jsapi.lab.JsApiSetLabInfo;
import com.tencent.mm.plugin.appbrand.jsapi.media.JsApiChooseImage;
import com.tencent.mm.plugin.appbrand.jsapi.media.JsApiChooseMedia;
import com.tencent.mm.plugin.appbrand.jsapi.media.JsApiChooseMultiMedia;
import com.tencent.mm.plugin.appbrand.jsapi.media.JsApiUploadEncryptedFileToCDN;
import com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.JsApiNavigateToDevMiniProgram;
import com.tencent.mm.plugin.appbrand.jsapi.msgsubscription.JsApiRequestSubscribeMessage;
import com.tencent.mm.plugin.appbrand.jsapi.nfc.hce.HCEService;
import com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.logic.c.a;
import com.tencent.mm.plugin.appbrand.jsapi.rencentusage.JsApiGetRecentUsageList;
import com.tencent.mm.plugin.appbrand.jsapi.rencentusage.JsApiOperateRecentUsageList;
import com.tencent.mm.plugin.appbrand.jsapi.scanner.JsApiScanCode;
import com.tencent.mm.plugin.appbrand.jsapi.scanner.JsApiScanItem;
import com.tencent.mm.plugin.appbrand.jsapi.share.JsApiShowUpdatableMessageSubscribeButton;
import com.tencent.mm.plugin.appbrand.widget.input.panel.e.b;
import com.tencent.mm.sdk.platformtools.BuildInfo;
import com.tencent.mm.sdk.platformtools.Log;
import com.tencent.mm.sdk.platformtools.Util;
import com.tencent.mm.sdk.platformtools.WeChatEnvironment;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class t
{
  private static final boolean lxT;
  private long lxU;
  private long lxV;
  private final Map<String, p> lxW;
  private final Map<String, p> lxX;
  
  static
  {
    AppMethodBeat.i(45430);
    com.tencent.mm.plugin.appbrand.x.a.bUd();
    com.tencent.mm.plugin.appbrand.jsapi.video.b.init();
    AppBrandCameraView.bFJ();
    SameLayerCameraView.bFJ();
    de.bEv();
    com.tencent.mm.plugin.appbrand.app.j.UJ("com.tencent.mm.plugin.soter.PluginSoter");
    com.tencent.mm.plugin.appbrand.app.j.UJ("com.tencent.mm.plugin.facedetect.PluginFace");
    c.a locala = com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.logic.c.miO;
    c.a.b(com.tencent.mm.plugin.appbrand.t.b.njP);
    com.tencent.mm.plugin.appbrand.jsapi.r.e.a(com.tencent.mm.plugin.appbrand.platform.window.h.nEx);
    com.tencent.luggage.xweb_ext.extendplugin.component.live.livepusher.r.a(com.tencent.mm.plugin.appbrand.xweb_ext.a.q.oHw);
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.s.o.class, new com.tencent.mm.plugin.appbrand.luggage.c.c());
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.utils.b.a.class, new com.tencent.mm.plugin.appbrand.jsapi.i.u());
    com.tencent.luggage.a.e.a(com.tencent.luggage.c.a.a.class, new com.tencent.mm.plugin.appbrand.luggage.b.g());
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.widget.input.a.b.class, com.tencent.mm.plugin.appbrand.luggage.b.d.nae);
    com.tencent.luggage.a.e.a(e.b.class, new com.tencent.mm.plugin.appbrand.luggage.b.e());
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.y.a.class, new com.tencent.mm.plugin.appbrand.jsapi.y.j());
    com.tencent.luggage.a.e.a(ag.class, new com.tencent.mm.plugin.appbrand.luggage.b.a());
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.ag.e.a.b.class, new com.tencent.mm.plugin.appbrand.utils.ab());
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.k.a.c.class, new com.tencent.mm.plugin.appbrand.luggage.b.o());
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.widget.b.b.class, new com.tencent.mm.plugin.appbrand.luggage.b.n());
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.ag.e.a.c.class, new com.tencent.mm.plugin.appbrand.report.n());
    com.tencent.luggage.a.e.a(ai.class, new com.tencent.mm.plugin.appbrand.utils.al());
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.u.a.class, com.tencent.mm.plugin.appbrand.utils.ak.ohK);
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.camera.e.class, new com.tencent.mm.plugin.appbrand.jsapi.ag.a.b());
    com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.nfc.c.class, com.tencent.mm.plugin.appbrand.utils.aj.ohH);
    if ((BuildInfo.IS_FLAVOR_RED) || (BuildInfo.IS_FLAVOR_PURPLE) || (!com.tencent.mm.protocal.d.KyP) || (WeChatEnvironment.hasDebugger())) {}
    for (boolean bool = true;; bool = false)
    {
      lxT = bool;
      AppMethodBeat.o(45430);
      return;
    }
  }
  
  private t()
  {
    AppMethodBeat.i(45422);
    this.lxW = new HashMap()
    {
      public final String toString()
      {
        AppMethodBeat.i(45420);
        String str = String.format(Locale.ENGLISH, "ServiceAPIs[%d]", new Object[] { Integer.valueOf(size()) });
        AppMethodBeat.o(45420);
        return str;
      }
    };
    this.lxX = new HashMap()
    {
      public final String toString()
      {
        AppMethodBeat.i(45421);
        String str = String.format(Locale.ENGLISH, "PageAPIs[%d]", new Object[] { Integer.valueOf(size()) });
        AppMethodBeat.o(45421);
        return str;
      }
    };
    AppMethodBeat.o(45422);
  }
  
  private void a(p paramp)
  {
    AppMethodBeat.i(45428);
    long l = Util.currentTicks() - this.lxV;
    if (l > 1L) {
      Log.e("MicroMsg.AppBrandJsApiPool", "addToPagePool api[%s] use[%dms]", new Object[] { paramp.getName(), Long.valueOf(l) });
    }
    if ((p)this.lxX.put(paramp.getName(), paramp) != null)
    {
      paramp = new IllegalAccessError("Duplicated api instance " + c(paramp));
      AppMethodBeat.o(45428);
      throw paramp;
    }
    paramp.lxO = lxT;
    this.lxV = Util.currentTicks();
    AppMethodBeat.o(45428);
  }
  
  private void b(p paramp)
  {
    AppMethodBeat.i(45426);
    long l = Util.currentTicks() - this.lxU;
    if (l > 1L) {
      Log.e("MicroMsg.AppBrandJsApiPool", "addToServicePool api[%s] use[%dms]", new Object[] { paramp.getName(), Long.valueOf(l) });
    }
    if ((p)this.lxW.put(paramp.getName(), paramp) != null)
    {
      paramp = new IllegalAccessError("Duplicated api instance " + c(paramp));
      AppMethodBeat.o(45426);
      throw paramp;
    }
    paramp.lxO = lxT;
    this.lxU = Util.currentTicks();
    AppMethodBeat.o(45426);
  }
  
  public static Map<String, p> bEk()
  {
    AppMethodBeat.i(45423);
    Object localObject = new t();
    ((t)localObject).lxU = Util.currentTicks();
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.ad.a.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.ad.a.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.ad.a.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.ad.a.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.ad.a.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.o());
    ((t)localObject).b(new JsApiLogin());
    ((t)localObject).b(new JsApiAuthorize());
    ((t)localObject).b(new JsApiOperateWXData());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.auth.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ab());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.r());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.s());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.i());
    ((t)localObject).b(new ci());
    ((t)localObject).b(new JsApiChooseImage());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.l());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.m());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.g());
    ((t)localObject).b(new JsApiStartRecordVoice());
    ((t)localObject).b(new JsApiStopRecordVoice());
    ((t)localObject).b(new JsApiStartPlayVoice());
    ((t)localObject).b(new JsApiPausePlayVoice());
    ((t)localObject).b(new JsApiStopPlayVoice());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.i.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.i.p());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.g());
    ((t)localObject).b(new JsApiGetMusicPlayerState());
    ((t)localObject).b(new JsApiOperateMusicPlayer());
    ((t)localObject).b(new JsApiScanCode());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.scanner.a());
    ((t)localObject).b(new JsApiScanItem());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.l());
    ((t)localObject).b(new bt());
    ((t)localObject).b(new bu());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.w.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.s());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.contact.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.contact.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.al());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ai());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ah());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.b.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.m());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.l());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.w.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.w.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.w.f());
    ((t)localObject).b(new cs());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.h.g());
    ((t)localObject).b(new bl());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.h.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.y.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.y.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.y.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.y.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.y.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.l());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.b.b.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.b.b.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.b.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.t.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.t.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.t.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.t.a());
    ((t)localObject).b(new be());
    ((t)localObject).b(new bp());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.i.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.i.q());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.j());
    ((t)localObject).b(new JsApiRefreshSession());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.am());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.o());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.o());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.af.h());
    ((t)localObject).b(new am());
    ((t)localObject).b(new bv());
    ((t)localObject).b(new JsApiMakeVoIPCall());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.e());
    ((t)localObject).b(new JsApiSetClipboardDataWC());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.l());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.o());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.p());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.m());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.q());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.q());
    ((t)localObject).b(new co());
    ((t)localObject).b(new bd());
    ((t)localObject).b(new JsApiChooseWeChatContact());
    ((t)localObject).b(new JsApiChooseMedia());
    ((t)localObject).b(new JsApiUploadEncryptedFileToCDN());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.d());
    ((t)localObject).b(new cb());
    ((t)localObject).b(new cu());
    ((t)localObject).b(new JsApiGetBackgroundAudioState());
    ((t)localObject).b(new JsApiSetBackgroundAudioStateWC());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.audio.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.p());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.b());
    ((t)localObject).b(new cc());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.r());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.contact.b());
    ((t)localObject).b(new JsApiOpenWeRunSetting());
    ((t)localObject).b(new JsApiUploadWeRunData());
    ((t)localObject).b(new aq());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.q());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.s());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.t());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.s());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.r());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.u());
    ((t)localObject).b(new JsApiShowUpdatableMessageSubscribeButton());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.g.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.g.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.g.d());
    ((t)localObject).b(new JsApiCheckIsSupportFaceDetect());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.live.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.live.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.o());
    ((t)localObject).b(new bn());
    ((t)localObject).b(new by());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.k());
    ((t)localObject).b(new ao());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.m());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.i());
    ((t)localObject).b(new ap());
    ((t)localObject).b(new an());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.channels.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.channels.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.channels.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.p());
    ((t)localObject).b(new ax());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.b.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.op_report.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.aa());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ao());
    ((t)localObject).b(new cr());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ad());
    ((t)localObject).b(new ct());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.z());
    ((t)localObject).b(new JsApiCheckIsSupportSoterAuthentication());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.bio.soter.c());
    ((t)localObject).b(new az());
    ((t)localObject).b(new ay());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.b.b(com.tencent.mm.plugin.appbrand.jsapi.o.b.a.mgg, com.tencent.mm.plugin.appbrand.bd.btx()));
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.b.c(com.tencent.mm.plugin.appbrand.jsapi.o.b.a.mgg, com.tencent.mm.plugin.appbrand.bd.btx()));
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.b.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.a.b(com.tencent.mm.plugin.appbrand.bd.bty()));
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.a.c(com.tencent.mm.plugin.appbrand.bd.bty()));
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.a.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.c.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.c.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.c.d());
    ((t)localObject).b(new cw());
    ((t)localObject).b(new at());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.camera.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ak());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.audio.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ad.a.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.audio.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.audio.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.audio.m());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.audio.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.audio.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.audio.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.audio.n());
    ((t)localObject).b(new JsApiNavigateBackApplication());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.i.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.i.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.i.f());
    ((t)localObject).b(new JsApiCheckBioEnrollment());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.a());
    ((t)localObject).b(new JsApiNavigateToDevMiniProgram());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.g(HCEService.class));
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.l());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.m());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.o());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ae());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ag());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.af());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.aj());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ui.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ui.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ui.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ui.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.r());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.an());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.e(com.tencent.mm.plugin.appbrand.jsapi.o.e.mgg, com.tencent.mm.plugin.appbrand.bd.btv()));
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.g(com.tencent.mm.plugin.appbrand.bd.btv()));
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.q());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.w());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.am());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.an());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.r());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.s());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.t());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ah());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ag());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.as());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.aa());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ae());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.al());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ap());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.v());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.q());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ab());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.af());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ar());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.z());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ad());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ak());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ao());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.u());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.p());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.aq());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.o());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ai());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.aj());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.l());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.m());
    ((t)localObject).b(new JsApiGetLabInfo());
    ((t)localObject).b(new JsApiSetLabInfo());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ab.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.b.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.b.c());
    ((t)localObject).b(new ca());
    ((t)localObject).b(new bw());
    ((t)localObject).b(new bx());
    ((t)localObject).b(new ce());
    ((t)localObject).b(new cf());
    ((t)localObject).b(new cg());
    ((t)localObject).b(new ch());
    ((t)localObject).b(new cj());
    ((t)localObject).b(new bo());
    ((t)localObject).b(new br());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.z.d());
    ((t)localObject).b(new JsApiLaunchApplication());
    ((t)localObject).b(new JsApiLaunchApplicationDirectly());
    ((t)localObject).b(new JsApiAddNativeDownloadTask());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.m());
    ((t)localObject).b(new JsApiAddDownloadTask());
    ((t)localObject).b(new JsApiAddDownloadTaskStraight());
    ((t)localObject).b(new JsApiQueryDownloadTask());
    ((t)localObject).b(new JsApiInstallDownloadTask());
    ((t)localObject).b(new JsApiPauseDownloadTask());
    ((t)localObject).b(new JsApiResumeDownloadTask());
    ((t)localObject).b(new JsApiGetInstallState());
    ((t)localObject).b(new JsApiCancelDownloadTask());
    ((t)localObject).b(new JsApiWriteCommData());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ui.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.u());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.v());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.j.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.j.b());
    ArrayList localArrayList = new ArrayList();
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.c());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ai());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.h());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.aa());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.g());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.z());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.d());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.i());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.l());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.v());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.af());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.u());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.p());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.n());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.o());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.q());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.m());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ac());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.j());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ab());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.e());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.y());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ad());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.s());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.f());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ah());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.w());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ae());
    localArrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.k());
    ((t)localObject).bv(localArrayList);
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.h5_interact.b());
    ((t)localObject).b(new JsApiOpenAdCanvas());
    ((t)localObject).b(new ba());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.storage.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.profile.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.profile.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.profile.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.l.a());
    ((t)localObject).b(new bi());
    ((t)localObject).b(new bj());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.offlinevoice.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.offlinevoice.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.f());
    ((t)localObject).b(new cd());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.p());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.j());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.h());
    ((t)localObject).b(new JsApiGetABTestConfig());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.o.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.x.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.x.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.x.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.r());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.n());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.p());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.l());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.q());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.m());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.i());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.d());
    ((t)localObject).b(new cl());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.ac());
    ((t)localObject).b(new JsApiPrivateAddContact());
    ((t)localObject).b(new al());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.o());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.k());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.media.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ap());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.ac());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.f());
    ((t)localObject).b(new JsApiChooseMultiMedia());
    ((t)localObject).b(new JsApiRequestSubscribeMessage());
    ((t)localObject).b(new bq());
    ((t)localObject).b(new JsApiSetBackgroundFetchToken());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.backgroundfetch.a());
    ((t)localObject).b(new JsApiTriggerBackgroundFetch());
    ((t)localObject).b(new JsApiAddDownloadTaskForNative());
    ((t)localObject).b(new JsApiPauseDownloadTaskForNative());
    ((t)localObject).b(new JsApiResumeDownloadTaskForNative());
    ((t)localObject).b(new JsApiQueryDownloadTaskForNative());
    ((t)localObject).b(new JsApiInstallDownloadTaskForNative());
    ((t)localObject).b(new JsApiGetInstallStateForNative());
    ((t)localObject).b(new JsApiLaunchApplicationForNative());
    ((t)localObject).b(new JsApiCancelDownloadTaskForNative());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.appdownload.f());
    ((t)localObject).b(new JsApiJumpDownloaderWidgetForNative());
    ((t)localObject).b(new cz());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.n.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.w.c());
    ((t)localObject).b(new cv());
    ((t)localObject).bv(com.tencent.mm.plugin.appbrand.jsapi.ui.launcher.d.bIV());
    ((t)localObject).b(new ck());
    ((t)localObject).b(new av());
    ((t)localObject).b(new JsApiGetFinderAccount());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.finder.b());
    ((t)localObject).b(new JsApiPostFinderDataItem());
    ((t)localObject).b(new JsApiDeleteFinderDataItem());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.finder.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.finder.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.finder.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.finder.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.finder.h());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.finder.i());
    ((t)localObject).b(new JsApiFetchSendingAndFailProfileFeed());
    ((t)localObject).b(new JsApiResendProfileFeed());
    ((t)localObject).b(new JsApiFinderEndorsementFinished());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.finder.d());
    ((t)localObject).b(new bh());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.d.a());
    ((t)localObject).b(new cq());
    ((t)localObject).b(new bs());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.x());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.p.y());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.h());
    ((t)localObject).b(new cp());
    ((t)localObject).b(new JsApiHandleMpChannelAction());
    ((t)localObject).b(new JsApiOpenWebViewUseFastLoad());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.camera.l());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.camera.p());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.camera.o());
    ((t)localObject).b(new JsApiAddToFavorites());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.l());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.q());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.share.t());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.e());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.a());
    ((t)localObject).b(new JsApiRemoveSplashScreenshot());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.pay.i());
    ((t)localObject).b(new JsApiOnWebPageUrlExposed());
    ((t)localObject).b(new JsApiGetRecentUsageList());
    ((t)localObject).b(new JsApiOperateRecentUsageList());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.e.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.e.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.e.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.q.b());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.aa.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.aa.d());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.aa.f());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.aa.g());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.aa.e());
    ((t)localObject).b(new ar());
    ((t)localObject).b(new as());
    ((t)localObject).b(new bb());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.x());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.file.y());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.f.c());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.f.b());
    ((t)localObject).b(new bm());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.a.a());
    ((t)localObject).b(new com.tencent.mm.plugin.appbrand.jsapi.i.d());
    ((t)localObject).b(new bf());
    localObject = ((t)localObject).lxW;
    AppMethodBeat.o(45423);
    return localObject;
  }
  
  public static Map<String, p> bEl()
  {
    AppMethodBeat.i(45424);
    Object localObject = new t();
    ((t)localObject).lxV = Util.currentTicks();
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.profile.c());
    ((t)localObject).a(new bz());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.z.m());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.z.l());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.z.j());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.h.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.h.c());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.h.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.h.i());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.h.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.h.j());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.h.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.h.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.o());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.n());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.m());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.w.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.w.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.w.g());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.w.f());
    ((t)localObject).a(new cn());
    ((t)localObject).a(new cs());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.r.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.r.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.c());
    ((t)localObject).a(new bl());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.a());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.c());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.live.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.live.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.live.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.live.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.live.a());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.live.g());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.live.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.live.c());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.i());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.i());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.c());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.g());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.j());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.l());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.contact.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.contact.f());
    ((t)localObject).a(new JsApiPrivateAddContact());
    ((t)localObject).a(new cm());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.g());
    ((t)localObject).a(new cu());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.z.t());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.container.a());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.container.c());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.container.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.r.g());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.r.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.r.i());
    ((t)localObject).a(new ct());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.i());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.r());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.n());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.g());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.p());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.l());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.camera.l());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.camera.p());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.camera.o());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.debugger.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.af.g());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.af.i());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.af.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.o());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.k());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.m());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.k());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.a.a.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.a.a.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.b.a.a.c());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.t());
    ((t)localObject).a(new cl());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.file.ac());
    ((t)localObject).a(new al());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.q());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.m());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.ab());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.z());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.ai());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.f());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.v());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.u());
    ((t)localObject).bw(com.tencent.mm.plugin.appbrand.jsapi.k.aj.bGR());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ui.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ui.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.ah());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ui.e());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ui.c());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.i());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.g());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.pay.n());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.pay.l());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.aa());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.af.h());
    ((t)localObject).a(new JsApiOperateWXData());
    ((t)localObject).a(new JsApiLogin());
    ((t)localObject).a(new JsApiAuthorize());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.z.h());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.z.q());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.z.n());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.z.r());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.an());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.storage.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.storage.j());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.storage.m());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.storage.e());
    ((t)localObject).a(new bt());
    ((t)localObject).a(new bu());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.d.a.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.d.a.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.d.a.c());
    ((t)localObject).a(new JsApiShowImageOperateSheet());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.a.a.b());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.a.a.d());
    ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ag.a.a.c());
    if (!com.tencent.mm.plugin.appbrand.xweb_ext.c.cdl()) {}
    for (boolean bool = true;; bool = false)
    {
      ((t)localObject).bw(com.tencent.mm.plugin.appbrand.jsapi.ag.b.d.hU(bool));
      ((t)localObject).bw(com.tencent.mm.plugin.appbrand.jsapi.ui.launcher.d.bIV());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.v.b());
      ((t)localObject).a(new ck());
      ((t)localObject).a(new bh());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.d.a());
      ((t)localObject).a(new cq());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.file.w());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.ap());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.ac());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.x.a());
      ((t)localObject).a(new JsApiOnWebPageUrlExposed());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.q.b());
      ((t)localObject).a(new ar());
      ((t)localObject).a(new as());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.y());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.a.a());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.share.k());
      ((t)localObject).a(new ao());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.share.m());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.share.i());
      ((t)localObject).a(new ap());
      ((t)localObject).a(new an());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.channels.d());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.channels.e());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.channels.b());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ae.c());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ae.d());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.ae.b());
      ((t)localObject).a(new com.tencent.mm.plugin.appbrand.jsapi.p.p());
      localObject = ((t)localObject).lxX;
      AppMethodBeat.o(45424);
      return localObject;
    }
  }
  
  private void bv(List<p> paramList)
  {
    AppMethodBeat.i(45425);
    if ((paramList == null) || (paramList.size() <= 0))
    {
      AppMethodBeat.o(45425);
      return;
    }
    paramList = paramList.iterator();
    while (paramList.hasNext()) {
      b((p)paramList.next());
    }
    AppMethodBeat.o(45425);
  }
  
  private void bw(List<p> paramList)
  {
    AppMethodBeat.i(45427);
    if ((paramList == null) || (paramList.size() <= 0))
    {
      AppMethodBeat.o(45427);
      return;
    }
    paramList = paramList.iterator();
    while (paramList.hasNext()) {
      a((p)paramList.next());
    }
    AppMethodBeat.o(45427);
  }
  
  private static String c(p paramp)
  {
    AppMethodBeat.i(45429);
    paramp = String.format(Locale.US, "[%s->%s]", new Object[] { paramp.getName(), paramp.getClass().getSimpleName() });
    AppMethodBeat.o(45429);
    return paramp;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes3.jar
 * Qualified Name:     com.tencent.mm.plugin.appbrand.jsapi.t
 * JD-Core Version:    0.7.0.1
 */