package com.tencent.mm.plugin.eggspring.b;

import com.tencent.matrix.trace.core.AppMethodBeat;
import d.g.b.p;
import d.l;
import d.n.n;

@l(gfx={1, 1, 16}, gfy={""}, gfz={"Lcom/tencent/mm/plugin/eggspring/model/Constants;", "", "()V", "Companion", "plugin-eggspring_release"})
public final class b
{
  public static final a pzh;
  
  static
  {
    AppMethodBeat.i(162210);
    pzh = new a((byte)0);
    AppMethodBeat.o(162210);
  }
  
  @l(gfx={1, 1, 16}, gfy={""}, gfz={"Lcom/tencent/mm/plugin/eggspring/model/Constants$Companion;", "", "()V", "BLESSING_MEDIA_SHOW_TYPE_RECTANGLE", "", "BLESSING_MEDIA_SHOW_TYPE_SQUARE", "BLESSING_MEDIA_TYPE_IMG", "BLESSING_MEDIA_TYPE_VIDEO", "CARD_TYPE_BLESSING", "CARD_TYPE_COUPON", "CARD_TYPE_RED_POCKET_COVER", "COUPON_RET_CODE_ERR_MKT_COUPON_SEQUENCE_CONFLICT", "", "COUPON_RET_CODE_ERR_MKT_COUPON_STOCK_PRESEND_FAIL_FOR_NOT_ENOUGH_DAYSTOCKAMOUNT", "COUPON_RET_CODE_ERR_MKT_COUPON_STOCK_PRESEND_FAIL_FOR_NOT_ENOUGH_STOCKAMOUNT", "COUPON_RET_CODE_ERR_MKT_COUPON_STOCK_PRESEND_FAIL_FOR_NOT_ENOUGH_STOCKNUM", "COUPON_RET_CODE_ERR_MKT_INSERT_UIN_COUPON_CHECK_BY_GOT_LIMIT_ERROR", "COUPON_RET_CODE_ERR_MKT_PAYGIFTAPPSVR_FREQ_CHECK_FAIL", "COUPON_RET_CODE_ERR_MKT_PAYGIFTAPPSVR_FREQ_CHECL_BY_USER_FAIL", "COUPON_RET_CODE_ERR_MKT_USER_MAX_QUOTA", "COUPON_RET_CODE_ERR_MMPAY_MKT_STOCKSVR_APPLY_TIMES_DAY_LIMIT", "COUPON_RET_CODE_ERR_MMY_MKT_BEYOND_THE_LIMIT_COLLAR", "COUPON_RET_CODE_OK", "KEY_APP_ID", "", "KEY_BRAND_BG_COLOR", "KEY_BRAND_BTM_IMG", "KEY_BRAND_COUPON_MAIN_TITLE", "KEY_BRAND_COUPON_SUB_TITLE", "KEY_BRAND_ICON", "KEY_BRAND_NAME", "KEY_BRAND_RED_POCKET_COVER_MAIN_TITLE", "KEY_BRAND_RED_POCKET_COVER_SUB_TITLE", "KEY_BTM_MAIN_TITLE", "KEY_BTM_MAIN_TITLE_COLOR", "KEY_BTM_SUB_TITLE", "KEY_BTM_SUB_TITLE_COLOR", "KEY_KEYWORD", "KEY_TRACE_ID", "REPORT_AD_EGG_ACTION_CLICK_LB", "REPORT_AD_EGG_ACTION_EGG", "REPORT_AD_EGG_ACTION_LUCKY_BAG", "REPORT_AD_EGG_ACTION_MATCH", "REPORT_LUCKY_BAG_ACTION_ACCEPT_COUPON_ERR", "REPORT_LUCKY_BAG_ACTION_ACCEPT_COUPON_SUCC", "REPORT_LUCKY_BAG_ACTION_CLICK_ACCEPT_COUPON", "REPORT_LUCKY_BAG_ACTION_CLICK_ACCEPT_RED_POCKET_COVER", "REPORT_LUCKY_BAG_ACTION_CLICK_CLICKABLE_TXT", "REPORT_LUCKY_BAG_ACTION_CLOSE_DETAIL", "REPORT_LUCKY_BAG_ACTION_SHOW_CARD_SUCC", "REPORT_LUCKY_BAG_ACTION_SHOW_CLICKABLE_TXT", "REPORT_LUCKY_BAG_ACTION_SHOW_COUPON", "REPORT_LUCKY_BAG_ACTION_SHOW_DETAIL", "REPORT_LUCKY_BAG_ACTION_SHOW_IMG_BLESSING_RECTANGLE", "REPORT_LUCKY_BAG_ACTION_SHOW_IMG_BLESSING_SQUARE", "REPORT_LUCKY_BAG_ACTION_SHOW_PLAN_B", "REPORT_LUCKY_BAG_ACTION_SHOW_RED_POCKET_COVER", "REPORT_LUCKY_BAG_ACTION_SHOW_VIDEO_BLESSING_RECTANGLE", "REPORT_LUCKY_BAG_ACTION_SHOW_VIDEO_BLESSING_SQUARE", "getEggDataPath", "getEmojiDataPath", "plugin-eggspring_release"})
  public static final class a
  {
    public static String cfG()
    {
      AppMethodBeat.i(162209);
      Object localObject = new StringBuilder();
      String str = com.tencent.mm.loader.j.b.arN();
      p.g(str, "CConstants.DATAROOT_PUBLIC_PATH()");
      localObject = n.h(str, "/data/user/0", "/data/data", false) + "/emoji/egg/";
      AppMethodBeat.o(162209);
      return localObject;
    }
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes.jar
 * Qualified Name:     com.tencent.mm.plugin.eggspring.b.b
 * JD-Core Version:    0.7.0.1
 */