package com.tencent.mobileqq.apollo.model;

import java.io.Serializable;
import java.util.concurrent.ConcurrentHashMap;

public class StartCheckParam
  implements Serializable
{
  public static final int COMMON_FLAG_BIT_SHOW_QUIT_TIPS = 1;
  public static final int COMMON_FLAG_BIT_SHOW_RED_PACKET_BTN = 2;
  public static final int COMMON_FLAG_BIT_SHOW_RED_PACKET_FLOAT_VIEW = 4;
  public static final int START_MODE_FROM_TIPBAR = 1;
  public static final int START_MODE_IN_GAME = 2;
  public static final int START_MODE_MAIN_LOADING = 3;
  public static final int START_MODE_NORMAL = 0;
  private static final long serialVersionUID = 1L;
  public long adDevUin;
  public String adForbidPosId;
  public int adShareRate;
  public int aioType;
  public String apolloGameSt;
  public String apolloGameStkey;
  public int apolloStatus;
  public int appIdSrc;
  public int commFlag;
  public int delayMs;
  public boolean disableMinGame;
  public boolean enableMenu = true;
  public int enter;
  public String extInfoFromSvr;
  public String extendJson;
  public String from;
  public ApolloGameData game;
  public int gameId;
  public int gameMode;
  public String gameName;
  public int gameTypeForRedPacket = 0;
  public int gender;
  public boolean isCreator;
  public boolean isEnableMSAA;
  public boolean isGameRscExist;
  public boolean isNeedConfInfo = false;
  public boolean isPatch;
  public boolean isRequestConf = false;
  public boolean isRunning;
  public boolean isWhiteUsr;
  public boolean launchNewGame;
  public long mCreateTs;
  public String mExtraStr;
  public String mFriendUin;
  public int mGameType;
  public boolean mIsTransGame;
  public boolean mLoadingOnMainProcess;
  public boolean mOpenTempAIOOnFinish;
  public String mRobotOpenId;
  public String mSSORule;
  public String mSendMsgUin;
  public int mStartType = 0;
  public String mTempAIONickName;
  public String mTempAIOUin;
  public boolean mUpdated;
  public int msgGameStatus;
  public boolean notFullScreen;
  public String openId;
  public String redUrl;
  public long requestCode;
  public long retCode;
  public long roomId;
  public String rpIconUrl;
  public String rpUrl;
  public String sessionOpenId;
  public int sessionType;
  public String sessionUin;
  public boolean showAlertTips;
  public int src;
  public long startCallEngine;
  public long startCheckGame;
  public long startT;
  public ConcurrentHashMap<String, Long> statMap = new ConcurrentHashMap();
  public String styleString;
  public String transInfo;
  public String version;
  public int viewMode;
  public String wordingV2;
  public String zipMD5;
  
  public StartCheckParam(int paramInt1, boolean paramBoolean, String paramString1, long paramLong, int paramInt2, int paramInt3, int paramInt4, int paramInt5, String paramString2, int paramInt6, String paramString3)
  {
    this.gameId = paramInt1;
    this.isCreator = paramBoolean;
    this.from = paramString1;
    this.enter = paramInt2;
    this.gameMode = paramInt3;
    this.sessionType = paramInt5;
    this.sessionUin = paramString2;
    this.src = paramInt6;
    this.aioType = paramInt4;
    this.roomId = paramLong;
    this.gameName = paramString3;
  }
  
  public String toString()
  {
    StringBuffer localStringBuffer = new StringBuffer("StartCheckParam{");
    localStringBuffer.append("game=");
    localStringBuffer.append(this.game);
    localStringBuffer.append(", mSendMsgUin='");
    localStringBuffer.append(this.mSendMsgUin);
    localStringBuffer.append('\'');
    localStringBuffer.append(", gameId=");
    localStringBuffer.append(this.gameId);
    localStringBuffer.append(", gameName='");
    localStringBuffer.append(this.gameName);
    localStringBuffer.append('\'');
    localStringBuffer.append(", isCreator=");
    localStringBuffer.append(this.isCreator);
    localStringBuffer.append(", from='");
    localStringBuffer.append(this.from);
    localStringBuffer.append('\'');
    localStringBuffer.append(", roomId=");
    localStringBuffer.append(this.roomId);
    localStringBuffer.append(", enter=");
    localStringBuffer.append(this.enter);
    localStringBuffer.append(", isRunning=");
    localStringBuffer.append(this.isRunning);
    localStringBuffer.append(", gameMode=");
    localStringBuffer.append(this.gameMode);
    localStringBuffer.append(", viewMode=");
    localStringBuffer.append(this.viewMode);
    localStringBuffer.append(", sessionType=");
    localStringBuffer.append(this.sessionType);
    localStringBuffer.append(", aioType=");
    localStringBuffer.append(this.aioType);
    localStringBuffer.append(", sessionUin='");
    localStringBuffer.append(this.sessionUin);
    localStringBuffer.append('\'');
    localStringBuffer.append(", src=");
    localStringBuffer.append(this.src);
    localStringBuffer.append(", requestCode=");
    localStringBuffer.append(this.requestCode);
    localStringBuffer.append(", extendJson='");
    localStringBuffer.append(this.extendJson);
    localStringBuffer.append('\'');
    localStringBuffer.append(", version='");
    localStringBuffer.append(this.version);
    localStringBuffer.append('\'');
    localStringBuffer.append(", isPatch=");
    localStringBuffer.append(this.isPatch);
    localStringBuffer.append(", zipMD5='");
    localStringBuffer.append(this.zipMD5);
    localStringBuffer.append('\'');
    localStringBuffer.append(", retCode=");
    localStringBuffer.append(this.retCode);
    localStringBuffer.append(", wordingV2='");
    localStringBuffer.append(this.wordingV2);
    localStringBuffer.append('\'');
    localStringBuffer.append(", apolloGameSt='");
    localStringBuffer.append(this.apolloGameSt);
    localStringBuffer.append('\'');
    localStringBuffer.append(", apolloGameStkey='");
    localStringBuffer.append(this.apolloGameStkey);
    localStringBuffer.append('\'');
    localStringBuffer.append(", openId='");
    localStringBuffer.append(this.openId);
    localStringBuffer.append('\'');
    localStringBuffer.append(", sessionOpenId='");
    localStringBuffer.append(this.sessionOpenId);
    localStringBuffer.append('\'');
    localStringBuffer.append(", extInfoFromSvr='");
    localStringBuffer.append(this.extInfoFromSvr);
    localStringBuffer.append('\'');
    localStringBuffer.append(", mExtraStr='");
    localStringBuffer.append(this.mExtraStr);
    localStringBuffer.append('\'');
    localStringBuffer.append(", mFriendUin='");
    localStringBuffer.append(this.mFriendUin);
    localStringBuffer.append('\'');
    localStringBuffer.append(", showAlertTips=");
    localStringBuffer.append(this.showAlertTips);
    localStringBuffer.append(", msgGameStatus=");
    localStringBuffer.append(this.msgGameStatus);
    localStringBuffer.append(", launchNewGame=");
    localStringBuffer.append(this.launchNewGame);
    localStringBuffer.append(", isWhiteUsr=");
    localStringBuffer.append(this.isWhiteUsr);
    localStringBuffer.append(", gender=");
    localStringBuffer.append(this.gender);
    localStringBuffer.append(", apolloStatus=");
    localStringBuffer.append(this.apolloStatus);
    localStringBuffer.append(", mGameType=");
    localStringBuffer.append(this.mGameType);
    localStringBuffer.append(", mUpdated=");
    localStringBuffer.append(this.mUpdated);
    localStringBuffer.append(", gameTypeForRedPacket=");
    localStringBuffer.append(this.gameTypeForRedPacket);
    localStringBuffer.append(", redUrl='");
    localStringBuffer.append(this.redUrl);
    localStringBuffer.append('\'');
    localStringBuffer.append(", startT=");
    localStringBuffer.append(this.startT);
    localStringBuffer.append(", startCheckGame=");
    localStringBuffer.append(this.startCheckGame);
    localStringBuffer.append(", startCallEngine=");
    localStringBuffer.append(this.startCallEngine);
    localStringBuffer.append(", appIdSrc=");
    localStringBuffer.append(this.appIdSrc);
    localStringBuffer.append(", commFlag=");
    localStringBuffer.append(this.commFlag);
    localStringBuffer.append(", enableMenu=");
    localStringBuffer.append(this.enableMenu);
    localStringBuffer.append(", disableMinGame=");
    localStringBuffer.append(this.disableMinGame);
    localStringBuffer.append(", mStartType=");
    localStringBuffer.append(this.mStartType);
    localStringBuffer.append(", mOpenTempAIOOnFinish=");
    localStringBuffer.append(this.mOpenTempAIOOnFinish);
    localStringBuffer.append(", mTempAIOUin='");
    localStringBuffer.append(this.mTempAIOUin);
    localStringBuffer.append('\'');
    localStringBuffer.append(", mTempAIONickName='");
    localStringBuffer.append(this.mTempAIONickName);
    localStringBuffer.append('\'');
    localStringBuffer.append(", adDevUin=");
    localStringBuffer.append(this.adDevUin);
    localStringBuffer.append(", adShareRate=");
    localStringBuffer.append(this.adShareRate);
    localStringBuffer.append(", adForbidPosId='");
    localStringBuffer.append(this.adForbidPosId);
    localStringBuffer.append('\'');
    localStringBuffer.append(", rpUrl='");
    localStringBuffer.append(this.rpUrl);
    localStringBuffer.append('\'');
    localStringBuffer.append(", rpIconUrl='");
    localStringBuffer.append(this.rpIconUrl);
    localStringBuffer.append('\'');
    localStringBuffer.append(", isNeedConfInfo=");
    localStringBuffer.append(this.isNeedConfInfo);
    localStringBuffer.append(", isRequestConf=");
    localStringBuffer.append(this.isRequestConf);
    localStringBuffer.append(", mRobotOpenId='");
    localStringBuffer.append(this.mRobotOpenId);
    localStringBuffer.append('\'');
    localStringBuffer.append(", isEnableMSAA=");
    localStringBuffer.append(this.isEnableMSAA);
    localStringBuffer.append(", mCreateTs=");
    localStringBuffer.append(this.mCreateTs);
    localStringBuffer.append(", mLoadingOnMainProcess=");
    localStringBuffer.append(this.mLoadingOnMainProcess);
    localStringBuffer.append(", mSSORule='");
    localStringBuffer.append(this.mSSORule);
    localStringBuffer.append('\'');
    localStringBuffer.append(", statMap=");
    localStringBuffer.append(this.statMap);
    localStringBuffer.append(", mIsTransGame=");
    localStringBuffer.append(this.mIsTransGame);
    localStringBuffer.append(", transInfo=");
    localStringBuffer.append(this.transInfo);
    localStringBuffer.append('}');
    return localStringBuffer.toString();
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes7.jar
 * Qualified Name:     com.tencent.mobileqq.apollo.model.StartCheckParam
 * JD-Core Version:    0.7.0.1
 */