package com.tencent.mobileqq.qqexpand.network;

import kotlin.Metadata;

@Metadata(bv={1, 0, 3}, d1={""}, d2={"Lcom/tencent/mobileqq/qqexpand/network/ExpandHandlerConstants;", "", "()V", "CMD_CERTIFICATE_CONFIRM_SCHOOL", "", "CMD_EDIT_EXTEND_FRIEND_INFO", "CMD_GET_CAMPUS_CERTIFICATE_STATUS", "CMD_GET_EXTEND_FRIEND_INFO", "CMD_GET_EXTEND_FRIEND_ONLINE_STATE", "CMD_GET_ME_IN_COLDPALACE", "CMD_GET_SIG_BY_0XB4C_CODE", "CMD_GET_SQUARE_STRANGER_LIST", "CMD_REQ_EXTEND_FRIEND_ENTER_AND_QUIT", "CMD_REQ_REPORT", "CMD_REQ_SETTING_FOR_PLUS", "CMD_REQ_THROW_TO_COLDPALACE", "CMD_REQ_UN_LIMIT", "CMD_UPDATE_EXTEND_FRIEND_CAMPUS_SCHOOL_INFO", "KEY_GET_SEQ", "KEY_NEED_GET_ONLINE_NUMBER", "KEY_NEED_GET_SEARCH_KEYWORDS", "KEY_ONLY_STRANGER_INFO", "MATCH_CHAT_TAG_ID_FOR_OPEN_SIGNAL_BOMB", "", "MATCH_CHAT_TAG_ID_FOR_VOICE_MATCH", "STATUS_UPDATE_SCENE_JSAPI", "STATUS_UPDATE_SCENE_SERVER_RSP", "TYPE_CANCLE_UNLIMIT_MATCH", "TYPE_CLOSE_SIGNAL_BOMB", "TYPE_EDIT_EXTEND_FRIEND_INFO", "TYPE_GET_COLDPALACE_DATA", "TYPE_GET_EXTEND_FRIEND_INFO", "TYPE_GET_EXTEND_FRIEND_ONLINE_STATE", "TYPE_GET_SIG_BY_0XB4C_CODE", "TYPE_GET_SQUARE_STRANGER_LIST", "TYPE_GET_STRANGER_INFO", "TYPE_GET_UNLIMIT_FRIEND_INFO", "TYPE_GET_UNLIMIT_MATCH", "TYPE_GET_UNLIMIT_MATCH_PUSH", "TYPE_GET_UNLIMIT_TAG", "TYPE_GET_USER_CATEGORY", "TYPE_OPEN_SIGNAL_BOMB", "TYPE_REQ_THROW_TO_COLDPALACE", "TYPE_SET_UNLIMIT_SWITCH", "TYPE_UPDATE_CAMPUS_CERTIFICATE_STATUS", "TYPE_UPDATE_EXTEND_FRIEND_CAMPUS_SCHOOL_INFO", "TYPE_UPDATE_EXTEND_FRIEND_LIMIT_CHAT_RESOURCE_STATE", "TYPE_UPDATE_EXTEND_FRIEND_RESOURCE_STATE", "TYPE_UPDATE_LIMIT_CHAT_SETTING", "TYPE_UPDATE_MATCHCHAT_ENTRANCE_CONFIG", "TYPE_UPDATE_MATCH_INFO", "TYPE_UPDATE_MATCH_PUSH", "TYPE_UPDATE_REDPOINT_DISPLAY", "TYPE_UPDATE_SIGNAL_BOMB_PUSH", "sexTypeBoy", "sexTypeCasual", "sexTypeGirl", "qqexpand-api_release"}, k=1, mv={1, 1, 16})
public final class ExpandHandlerConstants
{
  public static final ExpandHandlerConstants a = new ExpandHandlerConstants();
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes8.jar
 * Qualified Name:     com.tencent.mobileqq.qqexpand.network.ExpandHandlerConstants
 * JD-Core Version:    0.7.0.1
 */