package com.tencent.token;

public abstract interface tg
{
  @tm(a=tr.class)
  public static final String CMD_CHECK_UP_SMS = "mbtoken3_check_up_sms";
  @tm(a=tt.class)
  public static final String CMD_DEL_DEVICE = "mbtoken3_device_lock_del_device_v2";
  @tm(a=tu.class)
  public static final String CMD_DEL_MB_INFO = "mbtoken3_del_mbitem";
  @tm(a=tv.class)
  public static final String CMD_DEL_UNVERIFYUIN = "mbtoken3_del_unvfy_uin";
  @tm(a=tw.class)
  public static final String CMD_DEVICE_INFO_REPORT = "mbtoken3_device_info_report_encrypt";
  @tm(a=tx.class)
  public static final String CMD_DO_ACTIVETOKEN = "mbtoken3_activate_token";
  @tm(a=tp.class)
  public static final String CMD_DO_AUTO_IDCARD_DETECT = "mbtoken3_auto_idcard_detect";
  @tm(a=ty.class)
  public static final String CMD_DO_BINDTOKEN = "mbtoken3_bind_token_by_app_v3";
  @tm(a=tq.class)
  public static final String CMD_DO_BINDTOKENH5 = "mbtoken3_bind_token_h5";
  @tm(a=tz.class)
  public static final String CMD_DO_BINDTOKEN_BYREALNAME = "mbtoken3_bind_token_by_realname";
  @tm(a=ua.class)
  public static final String CMD_DO_BINDTOKEN_BYUNIVERIFY = "mbtoken3_bind_token_by_univerify";
  @tm(a=ts.class)
  public static final String CMD_DO_COPY_FACE = "mbtoken3_copy_face";
  @tm(a=ub.class)
  public static final String CMD_DO_EXCHANGEKEY = "mbtoken3_exchange_key_v3";
  @tm(a=ue.class)
  public static final String CMD_DO_FEEDBACK_COMMENT = "mbtoken3_feedback_v2";
  @tm(a=us.class)
  public static final String CMD_DO_FREEZE_UIN = "mbtoken3_freeze_action";
  @tm(a=uc.class)
  public static final String CMD_DO_GENERAL_BINDTOKEN = "mbtoken3_general_bind";
  @tm(a=ui.class)
  public static final String CMD_DO_GENERAL_VERIFY_FACTOR = "mbtoken3_verify_original_mobile";
  @tm(a=vt.class)
  public static final String CMD_DO_LIVE_VIDEO_DETECT = "mbtoken3_live_video_detect";
  @tm(a=ud.class)
  public static final String CMD_DO_LOGIN_V2 = "mbtoken3_login_v2";
  @tm(a=wd.class)
  public static final String CMD_DO_REALNAME_CARD_CHECK = "mbtoken3_card_check";
  @tm(a=wg.class)
  public static final String CMD_DO_REPORT_LOCATION = "mbtoken3_report_location";
  @tm(a=uf.class)
  public static final String CMD_DO_SEND_SMSCODE = "mbtoken3_get_mobile_code_v2";
  @tm(a=ug.class)
  public static final String CMD_DO_SESSIONINFO = "mbtoken3_session_info";
  @tm(a=uh.class)
  public static final String CMD_DO_UNBINDTOKEN = "mbtoken3_unbind_token";
  @tm(a=uj.class)
  public static final String CMD_DO_VERIFYQQTOKEN = "mbtoken3_verify_qqtoken_v2";
  @tm(a=uk.class)
  public static final String CMD_DO_VERIFYQUESTION = "mbtoken3_vry_ques_v2";
  @tm(a=ul.class)
  public static final String CMD_DO_VERIFY_SMSCODE = "mbtoken3_verify_mobile_code_v2";
  @tm(a=um.class)
  public static final String CMD_DO_WTLOGIN = "mbtoken3_vfy_wtlogin";
  @tm(a=uo.class)
  public static final String CMD_FACEPK = "mbtoken3_face_pk";
  @tm(a=un.class)
  public static final String CMD_FACERECOGNITION = "mbtoken3_face_reg_v2";
  @tm(a=uq.class)
  public static final String CMD_FEEDBACK_ABNORMAL_LOGIN = "mbtoken3_feedback_abnormal_login";
  @tm(a=ur.class)
  public static final String CMD_FEEDBACK_MOBILE_USING = "mbtoken3_feedback_mobile_using";
  @tm(a=ut.class)
  public static final String CMD_GENERAL_GET_MOBILE_CODE = "mbtoken3_general_get_mobile_code";
  @tm(a=uu.class)
  public static final String CMD_GENERAL_VRY_MOBILE_CODE = "mbtoken3_general_verify_mobile_code";
  @tm(a=uv.class)
  public static final String CMD_GET_ACCOUNT_LOCK_STATUS = "mbtoken3_get_ac_lock_status_v2";
  @tm(a=uw.class)
  public static final String CMD_GET_COMMON_IMG = "token.getcommonimg";
  @tm(a=ux.class)
  public static final String CMD_GET_CONFIG = "mbtoken3_get_config_v2";
  @tm(a=uy.class)
  public static final String CMD_GET_DETERMIN_VERIFY_FACTORS = "mbtoken3_determine_verify_factors";
  @tm(a=uz.class)
  public static final String CMD_GET_DEVICE_LOCK = "mbtoken3_get_device_lock_status_v2";
  @tm(a=va.class)
  public static final String CMD_GET_DOMAIN = "mbtoken3_get_domain";
  @tm(a=vb.class)
  public static final String CMD_GET_DUAL_MSG_LIST = "mbtoken3_get_dual_msg_list_v2";
  @tm(a=vc.class)
  public static final String CMD_GET_EVAL_ACCOUNT_RESULT = "mbtoken3_eval_account_v3";
  @tm(a=vd.class)
  public static final String CMD_GET_GAME_LOCK_STATUS = "mbtoken3_get_game_lock_status_v2";
  @tm(a=ve.class)
  public static final String CMD_GET_LOGIN_PROTECT = "mbtoken3_get_login_prot";
  @tm(a=vf.class)
  public static final String CMD_GET_MB_INFO = "mbtoken3_get_mbinfo";
  @tm(a=vg.class)
  public static final String CMD_GET_MB_MOBILE_CODE = "mbtoken3_mbop_get_mobile_code";
  @tm(a=vh.class)
  public static final String CMD_GET_MESSAGE = "mbtoken3_get_message_v2";
  @tm(a=vi.class)
  public static final String CMD_GET_OPERATEMSG = "mbtoken3_get_ads_info";
  @tm(a=vj.class)
  public static final String CMD_GET_QQFACEURL = "mbtoken3_get_photo_v3";
  @tm(a=vl.class)
  public static final String CMD_GET_REALNAME_VERIFY = "mbtoken3_realname_lip";
  @tm(a=vm.class)
  public static final String CMD_GET_REALUIN = "mbtoken3_query_real_uin_v2";
  @tm(a=vk.class)
  public static final String CMD_GET_REAL_NAME_STATUS = "mbtoken3_realname_status_v2";
  @tm(a=vo.class)
  public static final String CMD_GET_SAFE_PROTECTION = "mbtoken3_get_safe_protection_v2";
  @tm(a=vn.class)
  public static final String CMD_GET_SMS_CHANNEL = "mbtoken3_get_sms_port_v2";
  @tm(a=vp.class)
  public static final String CMD_GET_STARTUP_IMG = "token.getstartupimg";
  @tm(a=vq.class)
  public static final String CMD_GET_STR_CONFIG = "mbtoken3_get_key_value_conf";
  @tm(a=vr.class)
  public static final String CMD_GET_UIN_LIST = "mbtoken3_get_uin_list_v2";
  @tm(a=up.class)
  public static final String CMD_GET_VRY_ON_OFF = "mbtoken3_face_verify_on_off";
  @tm(a=vs.class)
  public static final String CMD_KICK_ONLINE_DEVICE_OFF = "mbtoken3_kickoff_v2";
  @tm(a=vv.class)
  public static final String CMD_MOD_QQ_PWD = "mbtoken3_modify_pwd";
  @tm(a=vu.class)
  public static final String CMD_MOD_SEED = "mbtoken3_mod_seed";
  @tm(a=vw.class)
  public static final String CMD_QRY_BIND_NOTIFY_MSG = "mbtoken3_qry_bind_notify_msg";
  @tm(a=vx.class)
  public static final String CMD_QUERY_CAPTCHA = "mbtoken3_query_captcha";
  @tm(a=vy.class)
  public static final String CMD_QUERY_FREEZE_STATUS = "mbtoken3_query_freeze_status";
  @tm(a=vz.class)
  public static final String CMD_QUERY_MALICIOUS_URL = "mbtoken3_query_malicious_url";
  @tm(a=wa.class)
  public static final String CMD_QUERY_REALNAME = "mbtoken3_realname_qry";
  @tm(a=wb.class)
  public static final String CMD_QUERY_SPE_VERIFY = "mbtoken3_qry_spec_verify";
  @tm(a=wc.class)
  public static final String CMD_QUERY_SUPER_CODE_INFO = "mbtoken3_qry_super_code_info";
  @tm(a=we.class)
  public static final String CMD_REAL_NAME_REG = "mbtoken3_realname_reg_v2";
  @tm(a=wf.class)
  public static final String CMD_REPORT_DNS_INFO = "mbtoken3_report_dns_v2";
  @tm(a=wh.class)
  public static final String CMD_SET_MB_MOBILE = "mbtoken3_set_mod_mobile";
  @tm(a=tj.class)
  public static final String CMD_SET_SERVICES_STATUS_V2 = "mbtoken3_set_service_status_v2";
  @tm(a=wi.class)
  public static final String CMD_SET_SUPER_CODE = "mbtoken3_set_super_code";
  @tm(a=wj.class)
  public static final String CMD_UPLOAD_LOGFILE = "mbtoken3_log_upload";
  @tm(a=wk.class)
  public static final String CMD_UPLOAD_REALNAME_FILE = "mbtoken3_realname_check";
  @tm(a=wl.class)
  public static final String CMD_VRY_CAPTCHA = "mbtoken3_verify_captcha_v3";
  @tm(a=wm.class)
  public static final String CMD_VRY_MB_MOBILE_CODE = "mbtoken3_mbop_verify_mobile_code";
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.token\classes.jar
 * Qualified Name:     com.tencent.token.tg
 * JD-Core Version:    0.7.0.1
 */