package com.tencent.mm.autogen.mmdata.rpt;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.report.a;

public final class hb
  extends a
{
  public String iAa = "";
  public String iAb = "";
  public long iCW;
  public long iIE;
  public long iLU;
  public long iLV;
  public long iLW;
  public long iLX;
  public long iLY;
  public long iLZ;
  public String iMA = "";
  public long iMB;
  public String iMC = "";
  public String iMD = "";
  public long iME;
  public long iMF;
  public String iMG = "";
  public long iMH;
  public int iMI;
  public long iMJ;
  public int iMK;
  public String iML = "";
  public String iMM = "";
  public int iMN;
  public int iMO;
  public int iMP;
  public String iMQ = "";
  private long iMR;
  private long iMS;
  private long iMT;
  public long iMU;
  public String iMV = "";
  public long iMW;
  public String iMX = "";
  public String iMY = "";
  public int iMZ;
  public long iMa;
  public long iMb;
  public long iMc;
  public long iMd;
  public long iMe;
  public long iMf;
  public long iMg;
  public long iMh;
  public long iMi;
  public long iMj;
  public long iMk;
  public long iMl;
  public long iMm;
  public long iMn;
  public String iMo = "";
  public long iMp;
  public long iMq;
  public String iMr = "";
  public long iMs;
  public long iMt;
  public long iMu;
  public long iMv;
  public long iMw;
  public String iMx = "";
  public long iMy;
  public String iMz = "";
  private int iNa;
  public int iNb;
  private String iNc = "";
  private String iNd = "";
  public String iNe = "";
  public String ijV = "";
  public String ijk = "";
  public String ikG = "";
  private String imU = "";
  public int ipK;
  public String ipT = "";
  public String ipU = "";
  public long ipV;
  public String iqp = "";
  private long iqr;
  public String iwJ = "";
  public String iwK = "";
  public long iwf;
  public String izY = "";
  
  public final String aIE()
  {
    AppMethodBeat.i(168932);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append(this.iLU);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ikG);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iqr);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iCW);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iLV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iLW);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iLX);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iIE);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iLY);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iLZ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMa);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMb);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMc);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMd);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ijV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ijk);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMe);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMf);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMg);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMh);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMi);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iwf);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMj);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMk);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMl);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMm);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMn);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMo);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMp);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMq);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMr);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMs);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMt);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMu);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMv);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMw);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMx);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMy);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMz);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.imU);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMB);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMC);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMD);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ipV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iME);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMF);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMG);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ipU);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ipT);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iqp);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMH);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ipK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMI);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMJ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iML);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMM);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMN);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMO);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMP);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMQ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iwJ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iwK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.izY);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMR);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMS);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMT);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMU);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMW);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMX);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMY);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iMZ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iNa);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iNb);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iNc);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iNd);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iNe);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iAa);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iAb);
    localObject = ((StringBuffer)localObject).toString();
    aUm((String)localObject);
    AppMethodBeat.o(168932);
    return localObject;
  }
  
  public final String aIF()
  {
    AppMethodBeat.i(168933);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append("FeedId:").append(this.iLU);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("MediaId:").append(this.ikG);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("Scene:").append(this.iqr);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("Duration:").append(this.iCW);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayTime:").append(this.iLV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("HitPreload:").append(this.iLW);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("HitPreloadPercent:").append(this.iLX);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileSize:").append(this.iIE);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FirstLoadTime:").append(this.iLY);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayPercent:").append(this.iLZ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("DownloadFinishTime:").append(this.iMa);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("MoovReadyTime:").append(this.iMb);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("MoovReadyOffset:").append(this.iMc);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("StartPlayTime:").append(this.iMd);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("NetType:").append(this.ijV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SessionId:").append(this.ijk);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("Position:").append(this.iMe);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PageIndex:").append(this.iMf);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("DownloadPercent:").append(this.iMg);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FirstPlay:").append(this.iMh);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ReplayCount:").append(this.iMi);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("InnerVersion:").append(this.iwf);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayStatus:").append(this.iMj);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("DownloadSpeed:").append(this.iMk);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PauseTotalTime:").append(this.iMl);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("RealPlayTime:").append(this.iMm);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FirstFrameTime:").append(this.iMn);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("NewFeedId:").append(this.iMo);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("WaittingCount:").append(this.iMp);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FetchTimestamp:").append(this.iMq);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("HistoryPlayInfo:").append(this.iMr);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FirstRequestDataOffset:").append(this.iMs);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayDownloadSpeed:").append(this.iMt);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("NetTypeInt:").append(this.iMu);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayWaittingCount:").append(this.iMv);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("RttMsg:").append(this.iMw);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SvrIp:").append(this.iMx);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SvrPort:").append(this.iMy);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("WaitingDetails:").append(this.iMz);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("Username:").append(this.imU);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PreloadStrategyId:").append(this.iMA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("useTPPlayer:").append(this.iMB);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayProgressInfo:").append(this.iMC);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("VoiceInfo:").append(this.iMD);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CommentScene:").append(this.ipV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsSeek:").append(this.iME);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsPause:").append(this.iMF);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayFormat:").append(this.iMG);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ClickTabContextId:").append(this.ipU);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ContextId:").append(this.ipT);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SessionBuffer:").append(this.iqp);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("VideoMode:").append(this.iMH);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ErrCode:").append(this.ipK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayerErrCode:").append(this.iMI);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TotalWaittingTime:").append(this.iMJ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("videoBitrate:").append(this.iMK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayCodeFormat:").append(this.iML);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayFileFormat:").append(this.iMM);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayAudioBitrate:").append(this.iMN);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FrameRate:").append(this.iMO);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("VideoResolution:").append(this.iMP);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayFormatJson:").append(this.iMQ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ExtraInfo:").append(this.iwJ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("enterSourceInfo:").append(this.iwK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LongVideoId:").append(this.izY);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsPlayUnifiedURL:").append(this.iMR);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PlayerResourceIsHLS:").append(this.iMS);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SvrRecallCount:").append(this.iMT);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TraceID:").append(this.iMU);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("VideoCdnMsg:").append(this.iMV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FirstRespCostTime:").append(this.iMW);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("NetConnInfo:").append(this.iMX);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FirstFrameDetail:").append(this.iMY);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("enableRendererSharpen:").append(this.iMZ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("hitPreCreatePlayer:").append(this.iNa);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("transportprotocol:").append(this.iNb);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("requestFormat:").append(this.iNc);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("svrDownloadFormat:").append(this.iNd);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("hdrInfo:").append(this.iNe);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("jump_id:").append(this.iAa);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("client_udf_kv:").append(this.iAb);
    localObject = ((StringBuffer)localObject).toString();
    AppMethodBeat.o(168933);
    return localObject;
  }
  
  public final int getId()
  {
    return 19059;
  }
  
  public final hb rp(String paramString)
  {
    AppMethodBeat.i(184194);
    this.imU = F("Username", paramString, true);
    AppMethodBeat.o(184194);
    return this;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes9.jar
 * Qualified Name:     com.tencent.mm.autogen.mmdata.rpt.hb
 * JD-Core Version:    0.7.0.1
 */