package com.tencent.mm.autogen.mmdata.rpt;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.report.a;

public final class ui
  extends a
{
  public long iFA;
  public String iFs = "";
  public long iQF;
  public String iSn = "";
  public String ilM = "";
  public int ioK;
  public String ipx = "";
  private String iqw = "";
  public long iuA;
  public long jAV;
  public long jFA;
  public long jFG;
  public long jFS;
  public long jFT;
  public long jFU;
  public long jFV;
  public long jFW;
  public long jFX;
  public long jFY;
  public String jFZ = "";
  public long jGA;
  private long jGB;
  public long jGC;
  public String jGD = "";
  public long jGE = 0L;
  public long jGF = 0L;
  public long jGG = 0L;
  public long jGH = 0L;
  public long jGa;
  public long jGb;
  public long jGc;
  public long jGd;
  public long jGe;
  public long jGf;
  public long jGg;
  public long jGh;
  public long jGi;
  public long jGj;
  public long jGk;
  public long jGl;
  public long jGm;
  public String jGn = "";
  public int jGo;
  public int jGp;
  public int jGq;
  public int jGr;
  public int jGs;
  public int jGt;
  public int jGu;
  public String jGv = "";
  public int jGw;
  public long jGx;
  public long jGy;
  public long jGz;
  
  public final String aIE()
  {
    AppMethodBeat.i(368135);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append(this.ilM);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ipx);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iFA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFG);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iQF);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iuA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFS);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFT);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iSn);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jAV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFU);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFW);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFX);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFY);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jFZ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iqw);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.iFs);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGa);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGb);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGc);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGd);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGe);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGf);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGg);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGh);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGi);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGj);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGk);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGl);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGm);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGn);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGo);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGp);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGq);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGr);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGs);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGt);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGu);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGv);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGw);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGx);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGy);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGz);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGB);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGC);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.ioK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGD);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGE);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGF);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGG);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.jGH);
    localObject = ((StringBuffer)localObject).toString();
    aUm((String)localObject);
    AppMethodBeat.o(368135);
    return localObject;
  }
  
  public final String aIF()
  {
    AppMethodBeat.i(368151);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append("InstanceId:").append(this.ilM);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("appid:").append(this.ipx);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("appversion:").append(this.iFA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("appstate:").append(this.jFA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("apptype:").append(this.jFG);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("costTime:").append(this.iQF);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("scene:").append(this.iuA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("startTimestamp:").append(this.jFS);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("endTimestamp:").append(this.jFT);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("moduleName:").append(this.iSn);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("packageType:").append(this.jAV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("localAppVersion:").append(this.jFU);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("downloadAppVersion:").append(this.jFV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("patchType:").append(this.jFW);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("compressType:").append(this.jFX);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("encryptVersion:").append(this.jFY);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("downloadUrl:").append(this.jFZ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("md5:").append(this.iqw);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("networktype:").append(this.iFs);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("redirectStart:").append(this.jGa);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("redirectEnd:").append(this.jGb);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("fetchStart:").append(this.jGc);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("domainLookUpStart:").append(this.jGd);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("domainLookUpEnd:").append(this.jGe);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("connectStart:").append(this.jGf);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("connectEnd:").append(this.jGg);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SSLconnectionStart:").append(this.jGh);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SSLconnectionEnd:").append(this.jGi);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("requestStart:").append(this.jGj);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("requestEnd:").append(this.jGk);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("responseStart:").append(this.jGl);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("responseEnd:").append(this.jGm);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("protocol:").append(this.jGn);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("rtt:").append(this.jGo);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("statusCode:").append(this.jGp);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("networkTypeEstimate:").append(this.jGq);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("httpRttEstimate:").append(this.jGr);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("transportRttEstimate:").append(this.jGs);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("downstreamThroughputKbpsEstimate:").append(this.jGt);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("throughputKbps:").append(this.jGu);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("peerIP:").append(this.jGv);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("port:").append(this.jGw);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("socketReused:").append(this.jGx);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("sendBytesCount:").append(this.jGy);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("receivedBytedCount:").append(this.jGz);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("downloadPkgSize:").append(this.jGA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("decompressTime:").append(this.jGB);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("decompressPkgSize:").append(this.jGC);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("errcode:").append(this.ioK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("finalPkgMd5:").append(this.jGD);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("isNewDNSUsed:").append(this.jGE);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("RequestSource_sync_type:").append(this.jGF);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("RequestSource_is_pre_hot:").append(this.jGG);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("RequestSource_launch_flag:").append(this.jGH);
    localObject = ((StringBuffer)localObject).toString();
    AppMethodBeat.o(368151);
    return localObject;
  }
  
  public final int getId()
  {
    return 19717;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes8.jar
 * Qualified Name:     com.tencent.mm.autogen.mmdata.rpt.ui
 * JD-Core Version:    0.7.0.1
 */