package com.tencent.mobileqq.search.util;

import java.util.ArrayList;
import java.util.HashMap;

public class SpellTool
{
  private static ArrayList<String> A;
  private static ArrayList<String> B;
  private static ArrayList<String> C;
  public static StringBuilder a = new StringBuilder();
  public static HashMap<String, Integer> b;
  public static HashMap<String, Integer> c;
  private static ArrayList<ArrayList<String>> d = new ArrayList();
  private static ArrayList<String> e = new ArrayList();
  private static ArrayList<String> f = new ArrayList();
  private static ArrayList<String> g = new ArrayList();
  private static ArrayList<String> h = new ArrayList();
  private static ArrayList<String> i = new ArrayList();
  private static ArrayList<String> j = new ArrayList();
  private static ArrayList<String> k = new ArrayList();
  private static ArrayList<String> l = new ArrayList();
  private static ArrayList<String> m = new ArrayList();
  private static ArrayList<String> n = new ArrayList();
  private static ArrayList<String> o = new ArrayList();
  private static ArrayList<String> p = new ArrayList();
  private static ArrayList<String> q = new ArrayList();
  private static ArrayList<String> r = new ArrayList();
  private static ArrayList<String> s = new ArrayList();
  private static ArrayList<String> t = new ArrayList();
  private static ArrayList<String> u = new ArrayList();
  private static ArrayList<String> v = new ArrayList();
  private static ArrayList<String> w = new ArrayList();
  private static ArrayList<String> x = new ArrayList();
  private static ArrayList<String> y = new ArrayList();
  private static ArrayList<String> z = new ArrayList();
  
  static
  {
    A = new ArrayList();
    B = new ArrayList();
    C = new ArrayList();
    e.add("b");
    e.add("c");
    e.add("d");
    e.add("f");
    e.add("g");
    e.add("h");
    e.add("j");
    e.add("k");
    e.add("l");
    e.add("m");
    e.add("n");
    e.add("p");
    e.add("q");
    e.add("r");
    e.add("s");
    e.add("t");
    e.add("w");
    e.add("x");
    e.add("y");
    e.add("z");
    e.add("ch");
    e.add("sh");
    e.add("zh");
    f.add("a");
    f.add("ai");
    f.add("an");
    f.add("ang");
    f.add("ao");
    f.add("e");
    f.add("en");
    f.add("eng");
    f.add("er");
    f.add("o");
    f.add("ou");
    f.add("ong");
    g.add("a");
    g.add("ai");
    g.add("an");
    g.add("ang");
    g.add("ao");
    g.add("ei");
    g.add("en");
    g.add("eng");
    g.add("i");
    g.add("ian");
    g.add("iao");
    g.add("ie");
    g.add("in");
    g.add("ing");
    g.add("o");
    g.add("u");
    h.add("a");
    h.add("ai");
    h.add("an");
    h.add("ang");
    h.add("ao");
    h.add("e");
    h.add("en");
    h.add("eng");
    h.add("i");
    h.add("ong");
    h.add("ou");
    h.add("u");
    h.add("uan");
    h.add("ui");
    h.add("un");
    h.add("uo");
    i.add("a");
    i.add("ai");
    i.add("an");
    i.add("ang");
    i.add("ao");
    i.add("e");
    i.add("ei");
    i.add("en");
    i.add("eng");
    i.add("i");
    i.add("ia");
    i.add("ian");
    i.add("iao");
    i.add("ie");
    i.add("ing");
    i.add("iu");
    i.add("ong");
    i.add("ou");
    i.add("u");
    i.add("uan");
    i.add("ui");
    i.add("un");
    i.add("uo");
    j.add("a");
    j.add("an");
    j.add("ang");
    j.add("ei");
    j.add("en");
    j.add("eng");
    j.add("iao");
    j.add("o");
    j.add("ou");
    j.add("u");
    k.add("a");
    k.add("ai");
    k.add("an");
    k.add("ang");
    k.add("ao");
    k.add("e");
    k.add("ei");
    k.add("en");
    k.add("eng");
    k.add("ong");
    k.add("ou");
    k.add("u");
    k.add("uai");
    k.add("uan");
    k.add("uang");
    k.add("ui");
    k.add("un");
    k.add("uo");
    l.add("a");
    l.add("ai");
    l.add("an");
    l.add("ang");
    l.add("ao");
    l.add("e");
    l.add("ei");
    l.add("en");
    l.add("eng");
    l.add("ong");
    l.add("ou");
    l.add("u");
    l.add("ua");
    l.add("uai");
    l.add("uan");
    l.add("uang");
    l.add("ui");
    l.add("un");
    l.add("uo");
    m.add("i");
    m.add("ia");
    m.add("ian");
    m.add("iang");
    m.add("iao");
    m.add("ie");
    m.add("in");
    m.add("ing");
    m.add("iong");
    m.add("iu");
    m.add("u");
    m.add("uan");
    m.add("ue");
    m.add("un");
    n.add("a");
    n.add("ai");
    n.add("an");
    n.add("ang");
    n.add("ao");
    n.add("e");
    n.add("en");
    n.add("eng");
    n.add("ong");
    n.add("ou");
    n.add("u");
    n.add("ui");
    n.add("un");
    n.add("uo");
    o.add("a");
    o.add("ai");
    o.add("an");
    o.add("ang");
    o.add("ao");
    o.add("e");
    o.add("ei");
    o.add("eng");
    o.add("i");
    o.add("ia");
    o.add("ian");
    o.add("iao");
    o.add("ie");
    o.add("in");
    o.add("ing");
    o.add("iu");
    o.add("o");
    o.add("ong");
    o.add("ou");
    o.add("u");
    o.add("uan");
    o.add("un");
    o.add("uo");
    o.add("v");
    o.add("ve");
    p.add("a");
    p.add("ai");
    p.add("an");
    p.add("ang");
    p.add("ao");
    p.add("e");
    p.add("ei");
    p.add("en");
    p.add("eng");
    p.add("i");
    p.add("ian");
    p.add("iao");
    p.add("ie");
    p.add("in");
    p.add("ing");
    p.add("iu");
    p.add("o");
    p.add("ou");
    p.add("u");
    q.add("a");
    q.add("ai");
    q.add("an");
    q.add("ang");
    q.add("ao");
    q.add("e");
    q.add("ei");
    q.add("en");
    q.add("eng");
    q.add("i");
    q.add("ian");
    q.add("iang");
    q.add("iao");
    q.add("ie");
    q.add("in");
    q.add("ing");
    q.add("iu");
    q.add("ong");
    q.add("ou");
    q.add("u");
    q.add("uan");
    q.add("un");
    q.add("uo");
    q.add("v");
    q.add("ve");
    r.add("a");
    r.add("ai");
    r.add("an");
    r.add("ang");
    r.add("ao");
    r.add("e");
    r.add("ei");
    r.add("en");
    r.add("eng");
    r.add("i");
    r.add("ian");
    r.add("iao");
    r.add("ie");
    r.add("in");
    r.add("ing");
    r.add("o");
    r.add("ou");
    r.add("u");
    s.add("i");
    s.add("ia");
    s.add("ian");
    s.add("iang");
    s.add("iao");
    s.add("ie");
    s.add("in");
    s.add("ing");
    s.add("iong");
    s.add("iu");
    s.add("u");
    s.add("uan");
    s.add("ue");
    s.add("un");
    t.add("an");
    t.add("ang");
    t.add("ao");
    t.add("e");
    t.add("en");
    t.add("eng");
    t.add("i");
    t.add("ong");
    t.add("ou");
    t.add("u");
    t.add("ua");
    t.add("uan");
    t.add("ui");
    t.add("un");
    t.add("uo");
    u.add("a");
    u.add("ai");
    u.add("an");
    u.add("ang");
    u.add("ao");
    u.add("e");
    u.add("en");
    u.add("eng");
    u.add("i");
    u.add("ong");
    u.add("ou");
    u.add("u");
    u.add("uan");
    u.add("ui");
    u.add("un");
    u.add("uo");
    v.add("a");
    v.add("ai");
    v.add("an");
    v.add("ang");
    v.add("ao");
    v.add("e");
    v.add("ei");
    v.add("eng");
    v.add("i");
    v.add("ian");
    v.add("iao");
    v.add("ie");
    v.add("ing");
    v.add("ong");
    v.add("ou");
    v.add("u");
    v.add("uan");
    v.add("ui");
    v.add("un");
    v.add("uo");
    w.add("a");
    w.add("ai");
    w.add("an");
    w.add("ang");
    w.add("ei");
    w.add("en");
    w.add("eng");
    w.add("o");
    w.add("u");
    x.add("i");
    x.add("ia");
    x.add("ian");
    x.add("iang");
    x.add("iao");
    x.add("ie");
    x.add("in");
    x.add("ing");
    x.add("iong");
    x.add("iu");
    x.add("u");
    x.add("uan");
    x.add("ue");
    x.add("un");
    y.add("a");
    y.add("an");
    y.add("ang");
    y.add("ao");
    y.add("e");
    y.add("i");
    y.add("in");
    y.add("ing");
    y.add("o");
    y.add("ong");
    y.add("ou");
    y.add("u");
    y.add("uan");
    y.add("ue");
    y.add("un");
    z.add("a");
    z.add("ai");
    z.add("an");
    z.add("ang");
    z.add("ao");
    z.add("e");
    z.add("ei");
    z.add("en");
    z.add("eng");
    z.add("i");
    z.add("ong");
    z.add("ou");
    z.add("u");
    z.add("uan");
    z.add("ui");
    z.add("un");
    z.add("uo");
    C.add("a");
    C.add("ai");
    C.add("an");
    C.add("ang");
    C.add("ao");
    C.add("e");
    C.add("en");
    C.add("eng");
    C.add("i");
    C.add("ong");
    C.add("ou");
    C.add("u");
    C.add("ua");
    C.add("uai");
    C.add("uan");
    C.add("uang");
    C.add("ui");
    C.add("un");
    C.add("uo");
    A.add("a");
    A.add("ai");
    A.add("an");
    A.add("ang");
    A.add("ao");
    A.add("e");
    A.add("ei");
    A.add("en");
    A.add("eng");
    A.add("i");
    A.add("ou");
    A.add("u");
    A.add("ua");
    A.add("uai");
    A.add("uan");
    A.add("uang");
    A.add("ui");
    A.add("un");
    A.add("uo");
    B.add("a");
    B.add("ai");
    B.add("an");
    B.add("ang");
    B.add("ao");
    B.add("e");
    B.add("ei");
    B.add("en");
    B.add("eng");
    B.add("i");
    B.add("ong");
    B.add("ou");
    B.add("u");
    B.add("ua");
    B.add("uai");
    B.add("uan");
    B.add("uang");
    B.add("ui");
    B.add("un");
    B.add("uo");
    d.add(f);
    d.add(g);
    d.add(h);
    d.add(i);
    d.add(j);
    d.add(k);
    d.add(l);
    d.add(m);
    d.add(n);
    d.add(o);
    d.add(p);
    d.add(q);
    d.add(r);
    d.add(s);
    d.add(t);
    d.add(u);
    d.add(v);
    d.add(w);
    d.add(x);
    d.add(y);
    d.add(z);
    d.add(C);
    d.add(A);
    d.add(B);
    b = new HashMap();
    c = new HashMap();
    b.put("a", Integer.valueOf(1));
    b.put("o", Integer.valueOf(2));
    b.put("e", Integer.valueOf(3));
    b.put("i", Integer.valueOf(4));
    b.put("u", Integer.valueOf(5));
    b.put("v", Integer.valueOf(6));
    b.put("ai", Integer.valueOf(7));
    b.put("ei", Integer.valueOf(7));
    b.put("ui", Integer.valueOf(8));
    b.put("ao", Integer.valueOf(9));
    b.put("ou", Integer.valueOf(10));
    b.put("iu", Integer.valueOf(11));
    b.put("ie", Integer.valueOf(12));
    b.put("ve", Integer.valueOf(13));
    b.put("er", Integer.valueOf(14));
    b.put("an", Integer.valueOf(15));
    b.put("en", Integer.valueOf(16));
    b.put("in", Integer.valueOf(17));
    b.put("un", Integer.valueOf(18));
    b.put("ven", Integer.valueOf(19));
    b.put("ang", Integer.valueOf(15));
    b.put("eng", Integer.valueOf(16));
    b.put("ing", Integer.valueOf(17));
    b.put("ong", Integer.valueOf(20));
    c.put("b", Integer.valueOf(1));
    c.put("p", Integer.valueOf(2));
    c.put("m", Integer.valueOf(3));
    c.put("f", Integer.valueOf(4));
    c.put("d", Integer.valueOf(5));
    c.put("t", Integer.valueOf(6));
    c.put("n", Integer.valueOf(7));
    c.put("l", Integer.valueOf(7));
    c.put("g", Integer.valueOf(8));
    c.put("k", Integer.valueOf(9));
    c.put("h", Integer.valueOf(10));
    c.put("j", Integer.valueOf(11));
    c.put("q", Integer.valueOf(12));
    c.put("x", Integer.valueOf(13));
    c.put("zh", Integer.valueOf(14));
    c.put("ch", Integer.valueOf(15));
    c.put("sh", Integer.valueOf(16));
    c.put("r", Integer.valueOf(17));
    c.put("z", Integer.valueOf(14));
    c.put("c", Integer.valueOf(15));
    c.put("s", Integer.valueOf(16));
    c.put("y", Integer.valueOf(18));
    c.put("w", Integer.valueOf(19));
  }
  
  public static int a(String paramString)
  {
    paramString = paramString.toCharArray();
    int i4 = 0;
    int i1 = 0;
    int i2 = 0;
    int i3 = 0;
    while (i1 < paramString.length)
    {
      if (a(paramString[i1])) {
        i2 = 1;
      } else {
        i3 = 1;
      }
      i1 += 1;
    }
    if ((i2 != 0) && (i3 == 0)) {
      return 2;
    }
    i1 = i4;
    if (i2 != 0) {
      i1 = 1;
    }
    return i1;
  }
  
  public static void a()
  {
    a = new StringBuilder();
  }
  
  public static final boolean a(char paramChar)
  {
    Character.UnicodeBlock localUnicodeBlock = Character.UnicodeBlock.of(paramChar);
    return (localUnicodeBlock == Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS) || (localUnicodeBlock == Character.UnicodeBlock.CJK_COMPATIBILITY_IDEOGRAPHS) || (localUnicodeBlock == Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A) || (localUnicodeBlock == Character.UnicodeBlock.GENERAL_PUNCTUATION) || (localUnicodeBlock == Character.UnicodeBlock.CJK_SYMBOLS_AND_PUNCTUATION) || (localUnicodeBlock == Character.UnicodeBlock.HALFWIDTH_AND_FULLWIDTH_FORMS);
  }
  
  public static boolean a(String paramString1, String paramString2)
  {
    return c.get(paramString1) == c.get(paramString2);
  }
  
  public static boolean b(String paramString1, String paramString2)
  {
    return b.get(paramString1) == b.get(paramString2);
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes11.jar
 * Qualified Name:     com.tencent.mobileqq.search.util.SpellTool
 * JD-Core Version:    0.7.0.1
 */