import android.os.Environment;
import com.tencent.common.app.BaseApplicationImpl;
import com.tencent.qphone.base.util.BaseApplication;
import java.io.File;

public abstract interface alof
{
  public static final String A;
  public static final String B;
  public static final String C;
  public static final String D;
  public static final String E;
  public static final String F;
  public static final String G;
  public static final String H;
  public static final String I;
  public static final String J;
  public static final String K;
  public static final String L;
  public static final String M;
  public static final String N;
  public static final String O;
  public static final String P;
  public static final String Q;
  public static final String R;
  public static final String S;
  public static final String T;
  public static final String U;
  public static final String V;
  public static final String W;
  public static final String X;
  public static final String Y;
  public static final String Z;
  public static final String aA;
  public static final String aB;
  public static final String aC;
  public static final String aD;
  public static final String aE;
  public static final String aF;
  public static final String aG;
  public static final String aH;
  public static final String aI;
  public static final String aJ;
  public static final String aK;
  public static final String aL;
  public static final String aM;
  public static final String aN;
  public static final String aO;
  public static final String aP;
  public static final String aQ;
  public static final String aR;
  public static final String aS;
  public static final String aT;
  public static final String aU;
  public static final String aV;
  public static final String aW;
  public static final String aX;
  public static final String aY;
  public static final String aZ;
  public static final String aa;
  public static final String ab;
  public static final String ac;
  public static final String ad;
  public static final String ae;
  public static final String af;
  public static final String ag;
  public static final String ah;
  public static final String ai;
  public static final String aj;
  public static final String ak;
  public static final String al;
  public static final String am;
  public static final String an;
  public static final String ao;
  public static final String ap;
  public static final String aq;
  public static final String ar;
  public static final String as;
  public static final String at;
  public static final String au;
  public static final String av;
  public static final String aw;
  public static final String ax;
  public static final String ay;
  public static final String az;
  public static final String bA;
  public static final String bB;
  public static final String bC;
  public static final String bD;
  public static final String bE;
  public static final String bF;
  public static final String bG;
  public static final String bH;
  public static final String bI;
  public static final String bJ;
  public static final String bK;
  public static final String bL;
  public static final String bM;
  public static final String bN;
  public static final String bO;
  public static final String bP;
  public static final String bQ;
  public static final String bR;
  public static final String bS;
  public static final String bT;
  public static final String bU;
  public static final String bV;
  public static final String bW;
  public static final String bX;
  public static final String bY;
  public static final String bZ;
  public static final String ba;
  public static final String bb;
  public static final String bc;
  public static final String bd;
  public static final String be;
  public static final String bf;
  public static final String bg;
  public static final String bh;
  public static final String bi;
  public static final String bj;
  public static final String bk;
  public static final String bl;
  public static final String bm;
  public static final String bn;
  public static final String bo;
  public static final String bp;
  public static final String bq;
  public static final String br;
  public static final String bs;
  public static final String bt;
  public static final String bu;
  public static final String bv;
  public static final String bw;
  public static final String bx;
  public static final String by;
  public static final String bz;
  public static final String[] c;
  public static final String cA;
  public static final String cB;
  public static final String cC;
  public static final String cD;
  public static final String cE;
  public static final String cF;
  public static final String cG;
  public static final String cH;
  public static final String cI;
  public static final String cJ;
  public static final String cK;
  public static final String cL;
  public static final String cM;
  public static final String cN;
  public static final String cO;
  public static final String cP;
  public static final String cQ;
  public static final String cR;
  public static final String cS;
  public static final String cT;
  public static final String cU;
  public static final String cV;
  public static final String cW;
  public static final String ca;
  public static final String cb;
  public static final String cc;
  public static final String cd;
  public static final String ce;
  public static final String cf;
  public static final String cg;
  public static final String ch;
  public static final String ci;
  public static final String cj;
  public static final String ck;
  public static final String cl;
  public static final String cm;
  public static final String cn;
  public static final String co;
  public static final String cp;
  public static final String cq;
  public static final String cr;
  public static final String cs;
  public static final String ct;
  public static final String cu;
  public static final String cv;
  public static final String cw;
  public static final String cx;
  public static final String cy;
  public static final String cz;
  public static final long l;
  public static final String u = String.valueOf(2068467417L);
  public static final String v;
  public static final String w;
  public static final String x;
  public static final String y;
  public static final String z;
  
  static
  {
    l = Math.pow(10.0D, 16.0D);
    v = String.valueOf(9990L);
    w = String.valueOf(9991L);
    x = String.valueOf(9992L);
    y = String.valueOf(9971L);
    z = String.valueOf(9993L);
    A = String.valueOf(9962L);
    B = String.valueOf(9978L);
    C = String.valueOf(9994L);
    D = String.valueOf(9995L);
    E = String.valueOf(9996L);
    F = String.valueOf(9997L);
    G = String.valueOf(9998L);
    H = String.valueOf(9999L);
    I = String.valueOf(9929L);
    J = String.valueOf(10000L);
    K = String.valueOf(9989L);
    L = String.valueOf(9988L);
    M = String.valueOf(9987L);
    N = String.valueOf(9986L);
    O = String.valueOf(9915L);
    P = String.valueOf(9985L);
    Q = String.valueOf(9914L);
    R = String.valueOf(9984L);
    S = String.valueOf(9983L);
    T = String.valueOf(9982L);
    U = String.valueOf(9981L);
    V = String.valueOf(9951L);
    W = String.valueOf(9980L);
    X = String.valueOf(9976L);
    Y = String.valueOf(9979L);
    Z = String.valueOf(9977L);
    aa = String.valueOf(9972L);
    ab = String.valueOf(9974L);
    ac = String.valueOf(9975L);
    ad = String.valueOf(9973L);
    ae = String.valueOf(9970L);
    af = String.valueOf(9969L);
    ag = String.valueOf(9921L);
    ah = String.valueOf(9968L);
    ai = String.valueOf(9967L);
    aj = String.valueOf(9966L);
    ak = String.valueOf(9965L);
    al = String.valueOf(9949L);
    am = String.valueOf(9950L);
    an = String.valueOf(9919L);
    ao = String.valueOf(9918L);
    ap = String.valueOf(9917L);
    aq = String.valueOf(9957L);
    ar = String.valueOf(9964L);
    as = String.valueOf(9963L);
    at = String.valueOf(9961L);
    au = String.valueOf(9960L);
    av = String.valueOf(9959L);
    aw = String.valueOf(9958L);
    ax = String.valueOf(9955L);
    ay = String.valueOf(3338705755L);
    az = String.valueOf(2171946401L);
    aA = String.valueOf(9954L);
    aB = String.valueOf(9953L);
    aC = String.valueOf(66600000L);
    aD = String.valueOf(13002L);
    aE = String.valueOf(9952L);
    aF = String.valueOf(9952L);
    aG = String.valueOf(9949L);
    aH = String.valueOf(1042L);
    aI = String.valueOf(1043L);
    aJ = String.valueOf(1044L);
    aK = String.valueOf(9948L);
    aL = String.valueOf(9946L);
    aM = String.valueOf(9947L);
    aN = String.valueOf(9945L);
    aO = String.valueOf(9944L);
    aP = String.valueOf(9930L);
    aQ = String.valueOf(2062433139L);
    aR = String.valueOf(2173223560L);
    aS = String.valueOf(3434959637L);
    aT = String.valueOf(9922L);
    aU = String.valueOf(9916L);
    aV = String.valueOf(3606676177L);
    aW = Environment.getExternalStorageDirectory().getAbsolutePath();
    aX = aW + "/Tencent/MobileQQ/";
    aY = aW + "/Tencent/MobileQQ/ChatRecord/";
    aZ = aX + "emoji/";
    ba = aX + "hotimage/";
    bb = aW + "/Tencent/blob/";
    bc = aX + "log/";
    bd = aW + "/Tencent/QQ_Images/";
    be = bd + "QQEditPic/OriginPic/";
    bf = aW + "/DCIM/QQPhoto/";
    bg = aW + "/Tencent/QQ_Shortvideos/";
    bh = aW + "/Tencent/AIO_FORWARD/";
    bi = bdzf.a(aW + "/Tencent/QQ_Favorite/");
    bj = bdzf.a(aW + "/Tencent/QQ_CameraEmo/");
    bk = aW + "/DCIM/Camera/";
    bl = bdzf.a(aW + "/Tencent/QQ_Collection/");
    bm = bdzf.a(aW + "/Tencent/QQfile_recv/");
    bn = bm + ".thumbnails/";
    bo = bm + ".tmp/";
    bp = bm + ".trooptmp/";
    bq = aW + "/Tencent/QQ_Secretfile/";
    br = bdzf.a(aW + "/Tencent/QQ_Video/");
    bs = aW + "/Tencent/QQfile_share/";
    bt = aW + "/Tencent/QQHomework_recv/";
    bu = aW + "/Tencent/QQHomework_attach/";
    bv = aX + "Troop_reward/";
    bw = bdzf.a(aX + "ar_cloud_img/");
    bx = bdzf.a(aX + "ar_cloud_marker_feature/");
    by = bdzf.a(aX + "ar_cloud_marker_config/");
    bz = bdzf.a(aX + "ar_cloud_marker_model/");
    bA = bdzf.a(aX + "ARRelationShip/");
    bB = bdzf.a(aX + "ar_cloud_transfer/");
    bC = bdzf.a(aX + "qqmusic/");
    bD = aX + "pe";
    bE = aX + "poke";
    bF = aX + "newpoke";
    if (BaseApplicationImpl.getContext().doesHasSDCardPermission()) {}
    for (String str = aX;; str = "/sdcard/Android/data/com.tencent.mobileqq/files/Tencent/MobileQQ/")
    {
      bG = str;
      bH = bdzf.a(bG + "head/");
      bI = bdzf.a(aX + "head/");
      bJ = bH + "_hd/";
      bK = bH + "_thd/";
      bL = bH + "_stranger/";
      bM = bH + "_st/";
      bN = bH + "_dhd/";
      bO = bH + "_SSOhd/";
      bP = bdzf.a(bG + ".starHead/");
      bQ = bdzf.a(bG + ".pendant/");
      bR = aX + ".secmsgPic/";
      bS = bdzf.a(aX + ".emotionsm/");
      bT = aX + ".emoQFace/";
      bU = bdzf.a(aX + ".diy/");
      bV = bdzf.a(aX + ".indivAnim/");
      bW = bdzf.a(new StringBuilder().append(aX).append("pddata/vas/").toString()) + "individual_sign/";
      bX = bW + "stickers/";
      bY = aX + "foward_urldrawable/";
      bZ = aX + ".billd_urldrawable/";
      ca = aX + ".map_roam/";
      cb = aX + "device/";
      cc = aX + "location/";
      cd = bdzf.a(aX + "system_background/");
      ce = cd + "QQPicConfig.xml";
      cf = aX + "lyric/";
      cg = aX + "/dynamic_profile/";
      ch = aX + "/audioCache/";
      ci = aX + ".mini_wangka/";
      cj = cd + "thumbnail/";
      ck = cd + "resource/";
      cl = aX + "turnbrand/";
      cm = bdzf.a(aX + "Scribble/");
      cn = bdzf.a(aX + ".profilecard" + "/");
      co = aX + "card/";
      cp = aX + "card/starfans/";
      cq = aX + "card/individbanners/";
      cr = aX + "data/";
      cs = aX + "troop/activity/";
      ct = aX + "photo/watermark_temp.jpg";
      cu = bdzf.a(aX + ".gift/");
      cv = aX + "robot/";
      cw = aX + ".nearby_lottie/";
      cx = aX + ".nearby_flower/";
      cy = aX + "pubaccount/";
      cz = cy + "screenshots/";
      cA = aX + "readinjoy/";
      cB = cA + "record/";
      cC = cB + "template/";
      cD = aX + "viola/template/";
      cE = cA + "offline/tmp/";
      cF = aW + "/Tencent/MobileQQ/.story/";
      cG = cF + "animation/";
      cH = bdzf.a(cy + "preload/");
      cI = bdzf.a(cy + "preimg/");
      cJ = aW + "/DCIM/Video/";
      cK = aW + alud.a(2131700994);
      cL = aW + alud.a(2131700995);
      cM = aW + "/Camera/Video/";
      cN = cy + "imagecollection/";
      cO = aX + "/newerGuide/";
      cP = aX + "/qim_theme_aio/";
      cQ = aX + "hotpic";
      cR = aX + "/nearby_profile_now_video/";
      cS = aX + "/tim_theme_aio/";
      cT = aX + "minirecog/";
      cU = aX + "troopphoto/";
      cV = aX + "subscribe_draft" + File.separator;
      cW = aX + "subscribe_draft_simple" + File.separator;
      c = new String[] { "NONE", "WIFI", "2G", "3G", "4G", "CABLE" };
      return;
    }
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes.jar
 * Qualified Name:     alof
 * JD-Core Version:    0.7.0.1
 */