package com.tencent.mobileqq.app;

import android.os.Environment;
import java.io.File;

public abstract interface AppConstants
{
  public static final String A;
  public static final String B;
  public static final String C;
  public static final String D;
  public static final String E;
  public static final String F;
  public static final String G;
  public static final String H;
  public static final String I;
  public static final String J;
  public static final String K;
  public static final String L;
  public static final String M;
  public static final String N;
  public static final String O;
  public static final String P;
  public static final String Q;
  public static final String R;
  public static final String S;
  public static final String T;
  public static final String U;
  public static final String V;
  public static final String W;
  public static final String X;
  public static final String Y;
  public static final String Z;
  public static final String aA;
  public static final String aB;
  public static final String aC;
  public static final String aD;
  public static final String aE;
  public static final String aF;
  public static final String aG;
  public static final String aH;
  public static final String aI;
  public static final String aJ;
  public static final String aK;
  public static final String aL;
  public static final String aM;
  public static final String aN;
  public static final String aO;
  public static final String aP;
  public static final String aQ;
  public static final String aR;
  public static final String aS;
  public static final String aT;
  public static final String aU;
  public static final String aV;
  public static final String aW;
  public static final String aX;
  public static final String aY;
  public static final String aZ;
  public static final String aa;
  public static final String ab;
  public static final String ac;
  public static final String ad;
  public static final String ae;
  public static final String af;
  public static final String ag;
  public static final String ah;
  public static final String ai;
  public static final String aj;
  public static final String ak;
  public static final String al;
  public static final String am;
  public static final String an;
  public static final String ao;
  public static final String ap;
  public static final String aq;
  public static final String ar;
  public static final String as;
  public static final String at;
  public static final String au;
  public static final String av;
  public static final String aw;
  public static final String ax;
  public static final String ay;
  public static final String az;
  public static final String bA;
  public static final String bB;
  public static final String bC;
  public static final String bD;
  public static final String bE;
  public static final String bF;
  public static final String bG;
  public static final String bH;
  public static final String bI;
  public static final String bJ;
  public static final String bK;
  public static final String bL;
  public static final String bM;
  public static final String bN;
  public static final String bO;
  public static final String bP;
  public static final String bQ;
  public static final String bR;
  public static final String bS;
  public static final String bT;
  public static final String bU;
  public static final String bV;
  public static final String bW;
  public static final String bX;
  public static final String bY;
  public static final String bZ;
  public static final String ba;
  public static final String bb;
  public static final String bc;
  public static final String bd;
  public static final String be;
  public static final String bf;
  public static final String bg;
  public static final String bh;
  public static final String bi;
  public static final String bj;
  public static final String bk;
  public static final String bl;
  public static final String bm;
  public static final String bn;
  public static final String bo;
  public static final String bp;
  public static final String bq;
  public static final String br;
  public static final String bs;
  public static final String bt;
  public static final String bu;
  public static final String bv;
  public static final String bw;
  public static final String bx;
  public static final String by;
  public static final String bz;
  public static final String[] c = { "NONE", "WIFI", "2G", "3G", "4G", "CABLE" };
  public static final String ca;
  public static final String cb;
  public static final String cc;
  public static final String cd;
  public static final String ce;
  public static final String cf;
  public static final String cg;
  public static final String ch;
  public static final String ci;
  public static final String cj;
  public static final String ck;
  public static final String cl;
  public static final String cm;
  public static final String cn;
  public static final String co;
  public static final String cp;
  public static final String cq;
  public static final String cr;
  public static final String cs;
  public static final String ct;
  public static final String cu;
  public static final String cv;
  public static final String cw;
  public static final String cx;
  public static final String cy;
  public static final long l;
  public static final String t = String.valueOf(2068467417L);
  public static final String u;
  public static final String v;
  public static final String w;
  public static final String x;
  public static final String y;
  public static final String z;
  
  static
  {
    l = Math.pow(10.0D, 16.0D);
    u = String.valueOf(9990L);
    v = String.valueOf(9991L);
    w = String.valueOf(9992L);
    x = String.valueOf(9971L);
    y = String.valueOf(9993L);
    z = String.valueOf(9962L);
    A = String.valueOf(9978L);
    B = String.valueOf(9994L);
    C = String.valueOf(9995L);
    D = String.valueOf(9996L);
    E = String.valueOf(9997L);
    F = String.valueOf(9998L);
    G = String.valueOf(9999L);
    H = String.valueOf(10000L);
    I = String.valueOf(9989L);
    J = String.valueOf(9988L);
    K = String.valueOf(9987L);
    L = String.valueOf(9986L);
    M = String.valueOf(9985L);
    N = String.valueOf(9984L);
    O = String.valueOf(9983L);
    P = String.valueOf(9982L);
    Q = String.valueOf(9981L);
    R = String.valueOf(9951L);
    S = String.valueOf(9980L);
    T = String.valueOf(9976L);
    U = String.valueOf(9979L);
    V = String.valueOf(9977L);
    W = String.valueOf(9972L);
    X = String.valueOf(9974L);
    Y = String.valueOf(9975L);
    Z = String.valueOf(9973L);
    aa = String.valueOf(9970L);
    ab = String.valueOf(9969L);
    ac = String.valueOf(9968L);
    ad = String.valueOf(9967L);
    ae = String.valueOf(9966L);
    af = String.valueOf(9965L);
    ag = String.valueOf(9949L);
    ah = String.valueOf(9950L);
    ai = String.valueOf(9957L);
    aj = String.valueOf(9964L);
    ak = String.valueOf(9963L);
    al = String.valueOf(9961L);
    am = String.valueOf(9960L);
    an = String.valueOf(9959L);
    ao = String.valueOf(9958L);
    ap = String.valueOf(9955L);
    aq = String.valueOf(3338705755L);
    ar = String.valueOf(2171946401L);
    as = String.valueOf(9954L);
    at = String.valueOf(9953L);
    au = String.valueOf(66600000L);
    av = String.valueOf(9952L);
    aw = String.valueOf(9952L);
    ax = String.valueOf(9949L);
    ay = String.valueOf(1042L);
    az = String.valueOf(1043L);
    aA = String.valueOf(1044L);
    aB = String.valueOf(9948L);
    aC = String.valueOf(9946L);
    aD = String.valueOf(9947L);
    aE = String.valueOf(9945L);
    aF = String.valueOf(9944L);
    aG = String.valueOf(9930L);
    aH = String.valueOf(2062433139L);
    aI = Environment.getExternalStorageDirectory().getAbsolutePath();
    aJ = aI + "/Tencent/MobileQQ/";
    aK = aI + "/Tencent/MobileQQ/ChatRecord/";
    aL = aJ + "emoji/";
    aM = aJ + "hotimage/";
    aN = aI + "/Tencent/blob/";
    aO = aJ + "log/";
    aP = aI + "/Tencent/QQ_Images/";
    aQ = aP + "QQEditPic/OriginPic/";
    aR = aI + "/DCIM/QQPhoto/";
    aS = aI + "/Tencent/QQ_Shortvideos/";
    aT = aI + "/Tencent/AIO_FORWARD/";
    aU = aI + "/Tencent/QQ_Favorite/";
    aV = aI + "/DCIM/Camera/";
    aW = aI + "/Tencent/QQ_Collection/";
    aX = aI + "/Tencent/QQfile_recv/";
    aY = aI + "/Tencent/QQfile_recv/.thumbnails/";
    aZ = aI + "/Tencent/QQfile_recv/.tmp/";
    ba = aI + "/Tencent/QQfile_recv/.trooptmp/";
    bb = aI + "/Tencent/QQ_Secretfile/";
    bc = aI + "/Tencent/QQ_Video/";
    bd = aI + "/Tencent/QQfile_share/";
    be = aI + "/Tencent/QQHomework_recv/";
    bf = aI + "/Tencent/QQHomework_attach/";
    bg = aJ + "Troop_reward/";
    bh = aJ + "ar_cloud_img/";
    bi = aJ + "ar_cloud_marker_feature/";
    bj = aJ + "ar_cloud_marker_config/";
    bk = aJ + "ar_cloud_marker_model/";
    bl = aJ + "ARRelationShip/";
    bm = aJ + "head/" + "_hd/";
    bn = aJ + "head/" + "_thd/";
    bo = aJ + "head/" + "_stranger/";
    bp = aJ + "head/" + "_st/";
    bq = aJ + ".secmsgPic/";
    br = aJ + ".emotionsm/";
    bs = aJ + ".emoQFace/";
    bt = aJ + ".diy/";
    bu = aJ + ".starHead/";
    bv = aJ + ".pendant/";
    bw = aJ + ".indivAnim/";
    bx = aJ + "pddata/vas/individual_sign/";
    by = bx + "stickers/";
    bz = aJ + "foward_urldrawable/";
    bA = aJ + ".billd_urldrawable/";
    bB = aJ + ".map_roam/";
    bC = aJ + "device/";
    bD = aJ + "head/" + "_SSOhd/";
    bE = aJ + "location/";
    bF = aJ + "system_background/";
    bG = bF + "QQPicConfig.xml";
    bH = aJ + "lyric/";
    bI = aJ + "/dynamic_profile/";
    bJ = bF + "thumbnail/";
    bK = bF + "resource/";
    bL = aJ + "turnbrand/";
    bM = aJ + "Scribble/";
    bN = aJ + "theme_pkg/";
    bO = bN + "QQThemePkg" + "/";
    bP = bO + "QQThemePkgConfig.xml";
    bQ = bO + "QQThemePkgTempConfig.xml";
    bR = bO + "QQThemePkgOldConfig.xml";
    bS = bO + "cover/";
    bT = bO + "pkg/";
    bU = aJ + ".profilecard" + "/";
    bV = aJ + "card/";
    bW = aJ + "card/starfans/";
    bX = aJ + "card/individbanners/";
    bY = aJ + "data/";
    bZ = aJ + "troop/activity/";
    ca = aJ + "photo/watermark_temp.jpg";
    cb = aJ + "head/" + "_dhd/";
    cc = aJ + ".gift/";
    cd = aJ + "robot/";
    ce = aJ + ".nearby_lottie/";
    cf = aJ + ".nearby_flower/";
    cg = aJ + "pubaccount/";
    ch = cg + "screenshots/";
    ci = aJ + "readinjoy/";
    cj = ci + "record/";
    ck = cj + "template/";
    cl = aI + "/Tencent/MobileQQ/.story/";
    cm = cl + "animation/";
    cn = cg + "preload/";
    co = cg + "preimg/";
    cp = aI + "/DCIM/Video/";
    cq = aI + "/照相机/Camera/";
    cr = aI + "/相机/";
    cs = aI + "/Camera/Video/";
    ct = cg + "imagecollection/";
    cu = aJ + "/newerGuide/";
    cv = aJ + "/qim_theme_aio/";
    cw = aJ + "hotpic";
    cx = aJ + "/nearby_profile_now_video/";
    cy = aJ + "/tim_theme_aio/";
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes.jar
 * Qualified Name:     com.tencent.mobileqq.app.AppConstants
 * JD-Core Version:    0.7.0.1
 */