package com.tencent.mobileqq.app;

import android.os.Environment;
import anvx;
import com.tencent.common.app.BaseApplicationImpl;
import com.tencent.mobileqq.vfs.VFSAssistantUtils;
import com.tencent.qphone.base.util.BaseApplication;
import java.io.File;

public abstract interface AppConstants
{
  public static final long ACTIVATE_FRIENDS_LONG_VALUE = 9973L;
  public static final String ACTIVATE_FRIENDS_UIN;
  public static final String AIO_PLUS_PANEL_RED_POINT_PREF = "aio_plus_panel_red_point";
  public static final long APP_ASSISTANT_UIN = 1787740092L;
  public static final String APP_NAME = "mobileQQ";
  public static final String APP_NAME_FOR_SUBSTITUTE = "QQ";
  public static final String APP_ROOT = "/sdcard/Android/data/com.tencent.mobileqq/files/";
  public static final int ARK_DEBUG_OPEN_CLICK_COUNT = 5;
  public static final String ARK_DEBUG_UIN;
  public static final long ARK_DEBUG_UIN_LONGVALUE = 9947L;
  public static final String AUDIO_ROOM_UIN;
  public static final String BABY_Q_UIN;
  public static final long BABY_Q_UIN_LONGVALUE = 66600000L;
  public static final String BANNER_AND_SPLASH = "banner_and_splash";
  public static final long C2C_FILE_SIZE_LIMIT = 16777216L;
  public static final String CALL_PREF = "free_call";
  public static final String CAMPUS_NOTICE_UIN;
  public static final long CAMPUS_NOTICE_UIN_LONGVALUE = 9948L;
  public static final String CHAT_BACKGOURND_CUSTOM = "custom";
  public static final String CHAT_BACKGOURND_DEFUALT = "null";
  public static final String CHAT_BACKGOURND_NICKNAME_COLOR = "chat_backgournd_nickname_color.";
  public static final String CHAT_BACKGROUND_BROADCAST = "chatbgBroadcast";
  public static final String CHAT_BACKGROUND_NULL = "none";
  public static final String CONFESS_FRD_REC_UIN;
  public static final long CONFESS_FRD_REC_UIN_LONGVALUE = 9944L;
  public static final String CONFESS_UIN;
  public static final long CONFESS_UIN_LONGVALUE = 9945L;
  public static final String CONVERSATION_CONTACTS_GUIDE_UIN;
  public static final long CONVERSATION_CONTACTS_GUIDE_UIN_LONGVALUE = 9922L;
  public static final String CONVERSATION_MAY_KNOW_FRIEND_UIN;
  public static final long CONVERSATION_MAY_KNOW_FRIEND_UIN_LONGVALUE = 9921L;
  public static final int CSPECIAL_FLAG_ENTERPRISEQQ = 1;
  public static final int CSPECIAL_FLAG_INVALID = -1;
  public static final int CSPECIAL_FLAG_QIDIAN_EXT = 4;
  public static final int CSPECIAL_FLAG_QIDIAN_MASTER = 16;
  public static final int CSPECIAL_FLAG_ROBOT = 2;
  public static final String DATALINE_IPAD_UIN;
  public static final long DATALINE_IPAD_UIN_LONGVALUE = 9962L;
  public static final String DATALINE_PC_UIN;
  public static final long DATALINE_PC_UIN_LONGVALUE = 9993L;
  public static final String DATALINE_PRINTER_UIN;
  public static final long DATALINE_PRINTER_UIN_LONGVALUE = 9978L;
  public static final String DATE_SAY_HELLO_LIST_UIN;
  public static final long DATE_SAY_HELLO_LIST_UIN_LONGVALUE = 9965L;
  public static final String DATE_UIN;
  public static final long DATE_UIN_LONGVALUE = 9974L;
  public static final int DEFAULT_SUB_VERSION = 5;
  public static final String DEVICE_HEAD_PATH;
  public static final String DEVICE_HEAD_PATH_SYSTEM = "head/_dhd/";
  public static final String DINGDONG_UIN;
  public static final long DINGDONG_UIN_LONGVALUE = 9961L;
  public static final int DOWNLOAD_BACKGROUND = 2;
  public static final int DOWNLOAD_THEME = 1;
  public static final String DYNAMIC_PROFILE;
  public static final String EC_SHOP_ASSISTANT_UIN;
  public static final long EC_SHOP_ASSISTANT_UIN_LONGVALUE = 9970L;
  public static final String EMOTION_URLDRAWABLE_DIR = ".emtion_urldrawable";
  public static final String EXTERNAL_THEME_DIR_NAME = "using_theme_res";
  public static final String EXTSDCARD_ROOT = "/mnt/extSdCard/";
  public static final long FANS_MSG_BOX_UIN_LONGVALUE = 1050L;
  public static final String FAVORITES_UIN;
  public static final long FAVORITES_UIN_LONGVALUE = 9988L;
  public static final String FILE_ASSISTANT_UIN;
  public static final long FILE_ASSISTANT_UIN_LONGVALUE = 3636666661L;
  public static final String FILTER_MSG_UIN;
  public static final long FILTER_MSG_UIN_LONGVALUE = 9911L;
  public static final String FM_EXTERNAL_SAVEFILE_UIN;
  public static final long FM_EXTERNAL_SAVEFILE_UIN_LONGVALUE = 9990L;
  public static final String FORGET_PWD_URL = "https://ti.qq.com/safe/forgetpw?source_id=2756";
  public static final long FRIEND_ANNIVER = 9952L;
  public static final String FRIEND_ANNIVER_UIN;
  public static final String FRIEND_LIST_LABEL_MSG_UIN;
  public static final long FRIEND_LIST_LABEL_MSG_UIN_LONGVALUE = 9985L;
  public static final String FRIEND_SYSTEM_MSG_UIN;
  public static final long FRIEND_SYSTEM_MSG_UIN_LONGVALUE = 9987L;
  public static final String FRIEND_SYSTEM_RIBBON_MSG_UIN;
  public static final long FRIEND_SYSTEM_RIBBON_MSG_UIN_LONGVALUE = 9984L;
  public static final String GOOGLEMAP_URL = "http://maps.google.com/maps?q=";
  public static final String GRAY_TIP_BUSI_ID = "1008";
  public static final int GROUP_BLACK_LIST_ID = -1002;
  public static final int GROUP_COMMONUSED_ID = 1005;
  public static final int GROUP_CUR_GROUP_ID = 1006;
  public static final int GROUP_DEFAULT_ID = -1;
  public static final long GROUP_FILE_SIZE_LIMIT = 16777216L;
  public static final int GROUP_MY_DEVICE_ID = 1001;
  public static final int GROUP_ONLY_UI = 1000;
  public static final String GROUP_PAD_PEMPLATE_NOTICE = "group_pad_template_notice";
  public static final int GROUP_PHONE_CONTACT_ID = 1002;
  public static final int GROUP_QCIRCLE_DOUBLE_FOLLOW = 1009;
  public static final int GROUP_RECENT_ID = 1003;
  public static final int GROUP_RELATIONFRIENDS = 1007;
  public static final int GROUP_RELATIONTROOPS = 1008;
  public static final int GROUP_SPECIAL_CARE_ID = 1004;
  public static final String HEAD_ROOT_PATH;
  public static final String HISTORY_CHAT_MSG_SEARCH_KEY_PREF = "history_chat_msg_search_key";
  public static final long HOTCHAT_CENTER_LONGVALUE = 9946L;
  public static final String HOTCHAT_CENTER_UIN;
  public static final long HTTP_HEADER_FIX_SIZE = 160L;
  public static final String HTTP_TYPE_MULTIMSG_CD = "multimsgCd";
  public static final String HTTP_TYPE_MULTIMSG_CU = "multimsgCu";
  public static final String HTTP_TYPE_MULTIMSG_DD = "multimsgDd";
  public static final String HTTP_TYPE_MULTIMSG_DU = "multimsgDu";
  public static final String HTTP_TYPE_MULTIMSG_GD = "multimsgGd";
  public static final String HTTP_TYPE_MULTIMSG_GU = "multimsgGu";
  public static final String HTTP_TYPE_PIC_CD = "picCd";
  public static final String HTTP_TYPE_PIC_CU = "picCu";
  public static final String HTTP_TYPE_PIC_DD = "picDd";
  public static final String HTTP_TYPE_PIC_DU = "picDu";
  public static final String HTTP_TYPE_PIC_GD = "picGd";
  public static final String HTTP_TYPE_PIC_GU = "picGu";
  public static final String HTTP_TYPE_PTT_CD = "pttCd";
  public static final String HTTP_TYPE_PTT_CU = "pttCu";
  public static final String HTTP_TYPE_PTT_DD = "pttDd";
  public static final String HTTP_TYPE_PTT_DU = "pttDu";
  public static final String HTTP_TYPE_PTT_GD = "pttGd";
  public static final String HTTP_TYPE_PTT_GU = "pttGu";
  public static final String HTTP_TYPE_QB_OFFLINE = "qb_offline";
  public static final String HTTP_TYPE_QB_QRCODE = "qb_qrcode";
  public static final String HTTP_TYPE_QB_SHARE = "qb_share";
  public static final String HTTP_TYPE_QB_TROOP_BAR = "qb_troop_bar";
  public static final String HTTP_TYPE_QB_TROOP_OTHER = "qb_other";
  public static final String HTTP_TYPE_QZONE_DOWNLOAD_AVATAR = "qzAvatar";
  public static final String HTTP_TYPE_QZONE_DOWNLOAD_BIG_PIC = "qzBigPicd";
  public static final String HTTP_TYPE_QZONE_DOWNLOAD_COVER_PIC = "qzCvPicd";
  public static final String HTTP_TYPE_QZONE_DOWNLOAD_EMO = "qzEmod";
  public static final String HTTP_TYPE_QZONE_DOWNLOAD_FEEDS_PIC = "qzFsPicd";
  public static final String HTTP_TYPE_QZONE_DOWNLOAD_PIC = "qzPicd";
  public static final String HTTP_TYPE_QZONE_DOWNLOAD_SIGN_PIC = "qzSignPicd";
  public static final String HTTP_TYPE_QZONE_DOWNLOAD_VIDEO = "qzViod";
  public static final String HTTP_TYPE_QZONE_UPLOAD_PIC = "qzPicu";
  public static final String HTTP_TYPE_VIDEO_CD = "videoCd";
  public static final String HTTP_TYPE_VIDEO_CF = "videoCf";
  public static final String HTTP_TYPE_VIDEO_CU = "videoCu";
  public static final String HTTP_TYPE_VIDEO_DD = "videoDd";
  public static final String HTTP_TYPE_VIDEO_DF = "videoDf";
  public static final String HTTP_TYPE_VIDEO_DU = "videoDu";
  public static final String HTTP_TYPE_VIDEO_GD = "videoGd";
  public static final String HTTP_TYPE_VIDEO_GF = "videoGf";
  public static final String HTTP_TYPE_VIDEO_GU = "videoGu";
  public static final String HTTP_TYPE_VIDEO_OD = "videoOd";
  public static final String HTTP_TYPE_VIDEO_OF = "videoOf";
  public static final String HTTP_TYPE_VIDEO_OU = "videoOu";
  public static final boolean INJECT_NET_WORK_ERROR = false;
  public static final String INTENT_ACCOUNT_INFO_UPDATE = "sc.account.info.update";
  public static final String INTERNAL_MEDIA = "/data/media/";
  public static final String INTERNAL_THEME_DIR_810 = "theme_810";
  public static final String INTERNAL_THEME_DIR_NAME = "mobileqq_theme";
  public static final String JOIN_TROOP_UIN;
  public static final long JOIN_TROOP_UIN_LONGVALUE = 9997L;
  public static final String KANDIAN_DAILY_UIN;
  public static final long KANDIAN_DAILY_UIN_LONGVALUE = 3434959637L;
  public static final String KANDIAN_LOCKSCREEN_INTERACT_MSG_UIN;
  public static final String KANDIAN_MERGE_UIN;
  public static final long KANDIAN_MERGE_UIN_LONGVALUE = 9954L;
  public static final long KANDIAN_MSG_LOCKSCREEN_INTERACT_UIN_LONGVALUE = 9914L;
  public static final String KANDIAN_SUBSCRIBE_UIN;
  public static final long KANDIAN_SUBSCRIBE_UIN_LONGVALUE = 2173223560L;
  public static final String KEY_RESEND_COUNT = "k_resend_cnt";
  public static final String KEY_TEAM_WORK_EXT_INFO_NEW_URL = "key_team_work_ext_info_new_url";
  public static final String KEY_TEAM_WORK_FILE_IMPORT_INFO = "key_team_work_file_import_info";
  public static final String LBS_HELLO_UIN;
  public static final long LBS_HELLO_UIN_LONGVALUE = 9999L;
  public static final int LBS_MAX_MSG_SIZE = 500;
  public static final String LBS_NEARBY_RECOMMEND_UIN;
  public static final long LBS_NEARBY_RECOMMEND_UIN_LONGVALUE = 9963L;
  public static final String LBS_SAY_HELLO_LIST_UIN;
  public static final long LBS_SAY_HELLO_LIST_UIN_LONGVALUE = 9966L;
  public static final int LIMIT_RESEND = 2;
  public static final String LOCAL_HTML_PREFERENCE = "local_html";
  public static final String LOCK_SCREEN_DATE_UIN;
  public static final long LOCK_SCREEN_DATE_UIN_LONGVALUE = 9967L;
  public static final String LOCK_SCREEN_LBS_HELLO_UIN;
  public static final long LOCK_SCREEN_LBS_HELLO_UIN_LONGVALUE = 9968L;
  public static final String LOG_PATH_SDCARD;
  public static final String LYRIC_PATH_SDCARD;
  public static final String MATCH_CHAT_UIN;
  public static final long MATCH_CHAT_UIN_LONGVALUE = 9916L;
  public static final long MAYKNOW_RECOMMEND = 9955L;
  public static final String MAYKNOW_RECOMMEND_UIN;
  public static final long MILLIS_PER_SECOND = 1000L;
  public static final String MINI_GAME_PUBLIC_ACCOUNT_UIN;
  public static final long MINI_GAME_PUBLIC_ACCOUNT_UIN_LONG_VALUE = 1983141935L;
  public static final long MSG_BOX_DAREN_ASSISTANT = 9918L;
  public static final String MSG_BOX_DAREN_ASSISTANT_UIN;
  public static final long MSG_BOX_FOLLOW_LONGVALUE = 9950L;
  public static final String MSG_BOX_FOLLOW_UIN;
  public static final long MSG_BOX_INTERACT_LONGVALUE = 9949L;
  public static final String MSG_BOX_INTERACT_UIN;
  public static final long MSG_BOX_MYMOMMENT_LONGVALUE = 9919L;
  public static final String MSG_BOX_MYMOMMENT_UIN;
  public static final long MSG_BOX_YANZHI = 9917L;
  public static final String MSG_BOX_YANZHI_UIN;
  public static final String NEARBY_LBS_HELLO_UIN;
  public static final long NEARBY_LBS_HELLO_UIN_LONGVALUE = 9929L;
  public static final String[] NET_TYPE_NAME;
  public static final String NEW_KANDIAN_UIN;
  public static final long NEW_KANDIAN_UIN_LONGVALUE = 2171946401L;
  public static final String NEW_MSG_NOTIFICATION_KEY = "new_msg_notification_key";
  public static final String NOTIFCATION_TAGET = "notifcation_taget";
  public static final long NOW_LIVE_TIP_UIN_BASE;
  public static final String OLD_KANDIAN_UIN;
  public static final long OLD_KANDIAN_UIN_LONGVALUE = 3338705755L;
  public static final String ONE_WAY_MSG_DATE_KEY = "_OneWayMsgDateRecentUinList";
  public static final String ONE_WAY_MSG_LBSFRIEND_KEY = "_OneWayMsgLBSFriendRecentUinList";
  public static final String ONE_WAY_MSG_RECENT_UIN_KEY = "OneWayMsgRecentUinList";
  public static final String PATH_BUSINESS_CARD_PHOTO = "business_card_photo/";
  public static final String PATH_CARD_INDIVID_BANNERS;
  public static final String PATH_CARD_QZONE;
  public static final String PATH_CARD_STARFANS;
  public static final String PATH_CRASH_INFO = "crashinfo/";
  public static final String PATH_CUSTOM_BACKGROUND = "custom_background/";
  public static final String PATH_CUSTOM_HEAD = "head/";
  public static final String PATH_CUSTOM_HEAD_ROOT;
  public static final String PATH_CUSTOM_HEAD_ROOT_SDCARD;
  public static final String PATH_DEVICE;
  public static final String PATH_DIY_SCREEN_SHOT = "data/diy_screenshot/";
  public static final String PATH_EMOTICON = ".emotionsm/";
  public static final String PATH_EMOTICON_QFACE = ".emoQFace/";
  public static final String PATH_GIFT = ".gift/";
  public static final String PATH_HEAD_APOLLO;
  public static final String PATH_HEAD_APOLLO_SYSTEM = "head/_apollo/";
  public static final String PATH_HEAD_HD;
  public static final String PATH_HEAD_HD_SYSTEM = "head/_hd/";
  public static final String PATH_HEAD_STORE;
  public static final String PATH_HEAD_STORE_SYSTEM = "head/_st/";
  public static final String PATH_HEAD_STRANGER;
  public static final String PATH_HEAD_STRANGER_SYSTEM = "head/_stranger/";
  public static final String PATH_HEAD_THD;
  public static final String PATH_HEAD_THD_SYSTEM = "head/_thd/";
  public static final String PATH_INDIVIDUATION_ANIMATION = ".indivAnim/";
  public static final String PATH_LOCATION_IMG;
  public static final String PATH_MOBILEQQ_CACHE = "mqq";
  public static final String PATH_NEARBY_FLOWER = ".nearby_flower/";
  public static final String PATH_NEARBY_LOTTIE = ".nearby_lottie/";
  public static final String PATH_NEARBY_PEOPLE_PHOTO = "nearby_people_photo/";
  public static final String PATH_NEWER_GUIDE_DIR_NAME;
  public static final String PATH_NIGHT_THEME_XML_JSON = "data/theme_night/";
  public static final String PATH_NOW_TEMP = ".now_temp/";
  public static final String PATH_NOW_VIDEO = ".now_video/";
  public static final String PATH_PENDANT = ".pendant/";
  public static final String PATH_READINJ0Y_AVATAR_UPLOAD = "readinjoy_avatar_upload/";
  public static final String PATH_ROBOT = "robot/";
  public static final String PATH_SECMSG_PIC_TEMPLATE = ".secmsgPic/";
  public static final String PATH_SSO_HEAD_HD;
  public static final String PATH_STAR_HEAD = ".starHead/";
  public static final String PATH_SYSTEM_BACKGROUND;
  public static final String PATH_SYSTEM_BACKGROUND_CONFIG;
  public static final String PATH_SYSTEM_BACKGROUND_RESOURCE;
  public static final String PATH_SYSTEM_BACKGROUND_THUMBNAIL;
  public static final String PATH_TROOP_ACTIVITY;
  public static final String PATH_TURNBRAND;
  public static final String PATH_TURNBRAND_SYSTEM = "turnbrand/";
  public static final String PATH_UNIFORM_BACKGROUND = "uniform_background.jpg";
  public static final String PATH_URLDRAWABLE_DISKCACHE = "diskcache";
  public static final String PCACTIVE_CONFIG = "pcactive_config";
  public static final String PCACTIVE_HAS_NOTICE_KEY = "pcactive_has_notice";
  public static final String PCACTIVE_NOTICE_KEY = "pcactive_notice_key";
  public static final String PHONE_CONTACT_UIN;
  public static final long PHONE_CONTACT_UIN_LONGVALUE = 9949L;
  public static final int PIC_SUB_VERSION_BIG_PIC_PREDOWN = 5;
  public static final int PIC_SUB_VERSION_PBSTRUCT = 3;
  public static final int PIC_SUB_VERSION_URLREFACTOR = 4;
  public static final String PKG_NAME_FOR_REQ_THEME = "QQThemePkg";
  public static final String PLUGIN_IS_SHOW_MENGBAN = "plugin_is_show_mengban";
  public static final String PREF_SCREEN_SHOT = "screen_shot";
  public static final String PROFILE_CARD_BACKGROUND_DIR;
  public static final String PUBLIC_ACCOUNT_QQ_MAIL = "2010741172";
  public static final String PUBLIC_ACCOUNT_READINJOY_FOLLOW_UIN = "2173223560";
  public static final int PUBLIC_ACCOUNT_TYPE_EQQ = 2;
  public static final int PUBLIC_ACCOUNT_TYPE_LOOKER = 1;
  public static final int PUBLIC_ACCOUNT_TYPE_NORMAL = 0;
  public static final int PUBLIC_ACCOUNT_TYPE_SEC_MSG = 3;
  public static final String PUBLIC_ACCOUNT_WPA_ASSISTANT_UIN;
  public static final long PUBLIC_ACCOUNT_WPA_ASSISTANT_UIN_LONGVALUE = 9981L;
  public static final long PULL_ACTIVE_PUSH = 9958L;
  public static final String PULL_ACTIVE_PUSH_UIN;
  public static final String QCIRCLE_CHAT_UIN;
  public static final long QCIRCLE_CHAT_UIN_LONGVALUE = 9913L;
  public static final String QQBROADCAST_MSG_UIN;
  public static final long QQBROADCAST_MSG_UIN_LONGVALUE = 10000L;
  public static final String QQSETTING_ALLOW_KANDIAN_PUSH = "qqsetting_kandian_key";
  public static final String QQSETTING_ALL_CONTACTS_KEY = "qqsetting_all_contacts_key";
  public static final String QQSETTING_ANTILOST_KEY = "qqsetting_antilost_key";
  public static final String QQSETTING_AUTO_RECEIVE_MAGIC_FACE_KEY = "qqsetting_auto_receive_magic_face_key";
  public static final String QQSETTING_AUTO_RECEIVE_PIC_KEY = "qqsetting_auto_receive_pic_key";
  public static final String QQSETTING_AVCALL_NOTIFY_KEY = "qqsetting_avcall_notify_key";
  public static final String QQSETTING_BOTHONLINE_KEY = "qqsetting_bothonline_key";
  public static final String QQSETTING_CALLTAB_SHOW_KEY = "qqsetting_calltab_show_key";
  public static final String QQSETTING_CALLTAB_SHOW_KEY_VERSION = "qqsetting_calltab_show_key_version";
  public static final String QQSETTING_CLEAR_MEMORY_KEY = "qqsetting_clear_memory_key";
  public static final String QQSETTING_DEVICE_PLUGIN_AUTOLOAD_KEY = "qqsetting_deviceplugin_bind_flag";
  public static final String QQSETTING_ENTER_SENDMSG_KEY = "qqsetting_enter_sendmsg_key";
  public static final String QQSETTING_HELLO_LIVE_MESSAGE = "qqsetting_hello_live_message";
  public static final String QQSETTING_KANDIAN_DOWNLOAD_PIC_IN_WIFI_ONLY = "qqsetting_kandian_download_pic_flag";
  public static final String QQSETTING_KANDIAN_VIDEO_AUTO = "qqsetting_kandian_video_auto_flag";
  public static final String QQSETTING_LOCALE_ID = "qqsetting_locale_id";
  public static final String QQSETTING_LOCKSCREENMSG_WHENEXIST_KEY = "qqsetting_lock_screen_whenexit_key";
  public static final String QQSETTING_MUSICGENE_CANSHOW_KEY = "qqsetting_musicgene_canshow_key";
  public static final String QQSETTING_MUSICGENE_EXIST_KEY = "qqsetting_musicgene_exist_key";
  public static final String QQSETTING_NODISTURB_MODE_KEY = "qqsetting_nodisturb_mode_key";
  public static final String QQSETTING_NOTIFY_BLNCONTROL_KEY = "qqsetting_notify_blncontrol_key";
  public static final String QQSETTING_NOTIFY_ICON_KEY = "qqsetting_notify_icon_key";
  public static final String QQSETTING_NOTIFY_MYFEEDPUSH_KEY = "qqsetting_notify_myfeedpush_key";
  public static final String QQSETTING_NOTIFY_SHOWCONTENT_KEY = "qqsetting_notify_showcontent_key";
  public static final String QQSETTING_NOTIFY_SOUNDTYPE_KEY = "qqsetting_notify_soundtype_key";
  public static final String QQSETTING_PCACTIVE_KEY = "qqsetting_pcactive_key";
  public static final String QQSETTING_QRLOGIN_SET_MUTE = "qqsetting_qrlogin_set_mute";
  public static final String QQSETTING_RECEIVEMSG_WHENEXIST_KEY = "qqsetting_receivemsg_whenexit_key";
  public static final String QQSETTING_SCREENSHOT_KEY = "qqsetting_screenshot_key";
  public static final String QQSETTING_SECURITY_SCAN_KEY = "qqsetting_security_scan_key";
  public static final String QQSETTING_SHAREDPREF_NAME = "qqsetting_sharedpref";
  public static final String QQSETTING_SHOW_PUSH_MESSAGE = "qqsetting_show_push_message";
  public static final String QQSETTING_SPECIAL_CARE_BAR = "qqsetting_special_care_bar";
  public static final String QQSETTING_SUBACCOUNT_NOTIFY = "qqsetting_subaccount_notify";
  public static final long QQSTORY_PIAZZA_UIN_LONGVALUE = 1044L;
  public static final String QQSTORY_UIN;
  public static final long QQSTORY_UIN_LONGVALUE = 1043L;
  public static final String QQSTORY_UIN_PIAZZA;
  public static final String QQ_KICKED_LOGIN_OTHER_DEVICE = "com.tencent.mobileqq.kickedLogin.otherDevice";
  public static final String QQ_VIP_UIN;
  public static final long QQ_VIP_UIN_LONGVALUE = 2659464438L;
  public static final String QZONE_PHOTO_ASSISTANT_UIN;
  public static final long QZONE_PHOTO_ASSISTANT_UIN_LONGVALUE = 9982L;
  public static final String QZONE_UIN;
  public static final long QZONE_UIN_LONGVALUE = 1042L;
  public static final String READINJOY_UIN;
  public static final long READINJOY_UIN_LONGVALUE = 9964L;
  public static final String RECOMMEND_CONTACT_UIN;
  public static final long RECOMMEND_CONTACT_UIN_LONGVALUE = 9995L;
  public static final String RECOMMEND_TROOP_UIN;
  public static final long RECOMMEND_TROOP_UIN_LONGVALUE = 9979L;
  public static final String REMINDER_UIN = String.valueOf(2068467417L);
  public static final long REMINDER_UIN_LONGVALUE = 2068467417L;
  public static final String REQ_PB_PROTOCOL_FLAG = "req_pb_protocol_flag";
  public static final boolean RICH_MEDIA_INJECT_ERROR = false;
  public static final int RICH_MEDIA_STEP_HTTP_ERROR_POBABILITY = 90;
  public static final int RICH_MEDIA_STEP_SEND_MSG_ERROR_PROBABILITY = 20;
  public static final int RICH_MEDIA_STEP_URL_ERROR_POBABILITY = 40;
  public static final String SAME_STATE_BOX_UIN;
  public static final long SAME_STATE_BOX_UIN_LONGVALUE = 9991L;
  public static final String SCHEDULE_NOTIFY_UIN;
  public static final long SCHEDULE_NOTIFY_UIN_LONGVALUE = 9957L;
  public static final String SCRIBBLE_FILE_DIR;
  public static final String SDCARD_AIO_FORWARD;
  public static final String SDCARD_AIO_QIM_THEME_DIR;
  public static final String SDCARD_AIO_TIM_THEME_DIR;
  public static final String SDCARD_AR_CONFIG;
  public static final String SDCARD_AR_FEATURE;
  public static final String SDCARD_AR_IMG;
  public static final String SDCARD_AR_MODEL;
  public static final String SDCARD_AR_RELATIONSHIP;
  public static final String SDCARD_AR_TRANSFER;
  public static final String SDCARD_AUDIO_CACHE;
  public static final String SDCARD_BILLD_URLDRAWABLE;
  public static final String SDCARD_BOLB_PATH;
  public static final String SDCARD_DATABASE;
  public static final String SDCARD_EMOTICON_QFACE;
  public static final String SDCARD_EMOTICON_SAVE;
  public static final String SDCARD_EMOTIOCN_DIY;
  public static final String SDCARD_FILE_SAVE_PATH;
  public static final String SDCARD_FILE_SAVE_THUMB_PATH;
  public static final String SDCARD_FILE_SAVE_TMP_PATH;
  public static final String SDCARD_FILE_SAVE_TROOPTMP_PATH;
  public static final String SDCARD_GIFT_SAVE;
  public static final String SDCARD_HOMEWORK_ATTACH;
  public static final String SDCARD_HOMEWORK_AUDIO;
  public static final String SDCARD_HOT_PIC_PATH;
  public static final String SDCARD_IMG_CAMERA;
  public static final String SDCARD_IMG_CAMERA_EMO;
  public static final String SDCARD_IMG_FAVORITE;
  public static final String SDCARD_IMG_FLOW_CAMERA;
  public static final String SDCARD_IMG_FORWARD_URLDRAWABLE;
  public static final String SDCARD_IMG_ORIGIN_SAVE;
  public static final String SDCARD_IMG_SAVE;
  public static final String SDCARD_IMG_VIDEO;
  public static final String SDCARD_IMG_VIDEO_GN9000L;
  public static final String SDCARD_IMG_VIDEO_RUBBISH_MX040;
  public static final String SDCARD_IMG_VIDEO_VIVO_X7;
  public static final String SDCARD_INDIV_ANIM_ROOT;
  public static final String SDCARD_MAP_ROAM_SAVE;
  public static final String SDCARD_MINIAPP_WANGKA_PATH;
  public static final String SDCARD_MUSIC;
  public static final String SDCARD_NEARBY_FLOWER;
  public static final String SDCARD_NEARBY_LOTTIE;
  public static final String SDCARD_NEARBY_PROFILE_NOW_VIDEO_DIR;
  public static final String SDCARD_NEW_POKE;
  public static final String SDCARD_PATH;
  public static final String SDCARD_PATH_CHATRECORD;
  public static final String SDCARD_PATH_EMOJIS;
  public static final String SDCARD_PATH_HOMEWORK_TROOP = "homework_troop";
  public static final String SDCARD_PATH_HOTFRIEND_IMG;
  public static final String SDCARD_PATH_MINICODERECOG;
  public static final String SDCARD_PATH_PUBLIC_ACCOUNT;
  public static final String SDCARD_PATH_PUBLIC_ACCOUNT_IMAGE_COLLECTION_PRELOAD;
  public static final String SDCARD_PATH_PUBLIC_ACCOUNT_PRELOAD;
  public static final String SDCARD_PATH_PUBLIC_ACCOUNT_PRELOAD_IMAGE;
  public static final String SDCARD_PATH_PUBLIC_ACCOUNT_SCREENSHOTS;
  public static final String SDCARD_PATH_READINJOY;
  public static final String SDCARD_PATH_READINJOY_CAMERA_CAPTURE_FOLDER;
  public static final String SDCARD_PATH_READINJOY_OFFLINE_TEMP_FOLDER;
  public static final String SDCARD_PATH_READINJOY_TEMPLATE_VIDEO_PATH;
  public static final String SDCARD_PATH_READINJOY_VIOLA_JS_SOURCE_PATH;
  public static final String SDCARD_PATH_STORY;
  public static final String SDCARD_PATH_STORY_ANIMATION;
  public static final String SDCARD_PATH_TROOPPHOTO;
  public static final String SDCARD_PATH_ZHITU = "zhitu";
  public static final String SDCARD_PE;
  public static final String SDCARD_PENDANT_ROOT;
  public static final String SDCARD_POKE;
  public static final String SDCARD_ROBOT_SAVE;
  public static final String SDCARD_ROOT;
  public static final String SDCARD_SECMSG_PIC_ROOT;
  public static final String SDCARD_SECRETFILE_SAVE;
  public static final String SDCARD_SHARE_VCARD;
  public static final String SDCARD_SHORTVIDEO_SAVE;
  public static final String SDCARD_SIGNATURE_STICKER_DIR;
  public static final String SDCARD_SIGNATURE_TEMPLATE_ROOT;
  public static final String SDCARD_STAR_HEAD;
  public static final String SDCARD_TROOP_REWARD;
  public static final String SDCARD_VIDEO;
  public static final String SEC_MSG_UIN;
  public static final long SEC_MSG_UIN_LONGVALUE = 9977L;
  public static final String SEND_BLESS_UIN;
  public static final long SEND_BLESS_UIN_LONGVALUE = 9960L;
  public static final String SERVICE_ACCOUNT_FOLDER_UIN;
  public static final long SERVICE_ACCOUNT_FOLDER_UIN_LONGVALUE = 9953L;
  public static final String SERVICE_ID = "mobileqq.service";
  public static final String SERVICE_ID_QC = "qcenter.service";
  public static final String SHARE_PREFERENCE_NAME = "share";
  public static final String SHARE_REQ_BIZNAME_STAR_BLESS_LINK = "StarBlessLink";
  public static final String SMARTDEVICE_SEARCH_UIN;
  public static final long SMARTDEVICE_SEARCH_UIN_LONGVALUE = 9971L;
  public static final String SMARTDEVICE_UIN;
  public static final long SMARTDEVICE_UIN_LONGVALUE = 9972L;
  public static final String SP_STATISTIC = "statistic";
  public static final String SUBACCOUNT_ASSISTANT_UIN;
  public static final long SUBACCOUNT_ASSISTANT_UIN_LONGVALUE = 9992L;
  public static final String SUBACCOUNT_TROOP_UIN;
  public static final long SUBACCOUNT_TROOP_UIN_LONGVALUE = 13002L;
  public static final String SUBSCRIBE_DRAFT;
  public static final String SUBSCRIBE_DRAFT_SIMPLE;
  public static final String SYNCWEB = "mobileqq.web";
  public static final String SYSTEM_MSG_UIN;
  public static final long SYSTEM_MSG_UIN_LONGVALUE = 9998L;
  public static final String SYSTEM_NOTIFICATION_ENABLED_KEY = "system_notification_enabled_key";
  public static final String S_DCARD_COLLECTION;
  public static final String TAG_RAW_PHOTO = "raw_photo";
  public static final String TAG_RAW_PHOTO_4_TEST = "raw_photo_4_test";
  public static final String TAG_RAW_SHORT_VIDEO = "short_video";
  public static final String TEAM_WORK_WORD_UIN;
  public static final long TEAM_WORK_WORD_UIN_LONMGVALUE = 9951L;
  public static final String TEMP_MSG_BOX_UIN;
  public static final long TEMP_MSG_BOX_UIN_LONGVALUE = 9912L;
  public static final String TENCENT_DOCS_ASSISTANT_UIN;
  public static final long TENCENT_DOCS_ASSISTANT_UIN_LONGVALUE = 9930L;
  public static final long TIME_30_DAYS = 2592000000L;
  public static final String TIM_KICKED_LOGIN_OTHER_DEVICE = "com.tencent.tim.kickedLogin.otherDevice";
  public static final String TIM_PACKAGE_NAME = "com.tencent.tim";
  public static final String TIM_SIG_MD5 = "775E696D09856872FDD8AB4F3F06B1E0";
  public static final String TIM_TEAM_UIN;
  public static final long TIM_TEAM_UIN_LONGVALUE = 3606676177L;
  public static final String TOP_MSG_NOTIFICATION_KEY = "top_msg_notification_key";
  public static final String TROOP_ASSISTANT_UIN;
  public static final long TROOP_ASSISTANT_UIN_LONGVALUE = 9994L;
  public static final String TROOP_BAR_ASSISTANT_UIN;
  public static final long TROOP_BAR_ASSISTANT_UIN_LONGVALUE = 9975L;
  public static final String TROOP_FILE_UIN;
  public static final long TROOP_FILE_UIN_LONGVALUE = 9989L;
  public static final String TROOP_KEY_NEARBY_MEM_LIST = "troop_key_nearby_mem_list";
  public static final String TROOP_NEARBY_MEM_LIST = "troop_nearby_list";
  public static final String TROOP_NEW_GUIDE = "troop_new_guid";
  public static final String TROOP_NOTIFICATION_UIN;
  public static final long TROOP_NOTIFICATION_UIN_LONGVALUE = 9980L;
  public static final String TROOP_SUSPICIOUS_MSG_UIN;
  public static final long TROOP_SUSPICIOUS_MSG_UIN_LONGVALUE = 9915L;
  public static final String TROOP_SYSTEM_MSG_UIN;
  public static final long TROOP_SYSTEM_MSG_UIN_LONGVALUE = 9986L;
  public static final String TROOP_SYSTEM_RIBBON_MSG_UIN;
  public static final long TROOP_SYSTEM_RIBBON_MSG_UIN_LONGVALUE = 9983L;
  public static final long TYPE_TRIBE_CONTACT_LONGVALUE = 9956L;
  public static final long UINT2_LONG = 4294967295L;
  public static final String VOTE_MSG_UIN;
  public static final long VOTE_MSG_UIN_LONGVALUE = 9996L;
  public static final String VOTE_UIN;
  public static final long VOTE_UIN_LONGVALUE = 9969L;
  public static final String WATER_MARK_TEMP_PATH;
  public static final String WEISHI_UIN;
  public static final long WEISHI_UIN_LONGVALUE = 2062433139L;
  public static final String WIFI_HOTSPOT_UIN;
  public static final long WIFI_HOTSPOT_UIN_LONGVALUE = 9959L;
  public static final String WIFI_HOT_CHAT_UIN;
  public static final long WIFI_HOT_CHAT_UIN_LONGVALUE = 9976L;
  public static final long WORD_DOC_FILE_SIZE_LIMIT = 6291456L;
  
  static
  {
    NOW_LIVE_TIP_UIN_BASE = Math.pow(10.0D, 16.0D);
    FM_EXTERNAL_SAVEFILE_UIN = String.valueOf(9990L);
    SAME_STATE_BOX_UIN = String.valueOf(9991L);
    SUBACCOUNT_ASSISTANT_UIN = String.valueOf(9992L);
    SMARTDEVICE_SEARCH_UIN = String.valueOf(9971L);
    DATALINE_PC_UIN = String.valueOf(9993L);
    DATALINE_IPAD_UIN = String.valueOf(9962L);
    DATALINE_PRINTER_UIN = String.valueOf(9978L);
    FILE_ASSISTANT_UIN = String.valueOf(3636666661L);
    TROOP_ASSISTANT_UIN = String.valueOf(9994L);
    RECOMMEND_CONTACT_UIN = String.valueOf(9995L);
    VOTE_MSG_UIN = String.valueOf(9996L);
    JOIN_TROOP_UIN = String.valueOf(9997L);
    SYSTEM_MSG_UIN = String.valueOf(9998L);
    LBS_HELLO_UIN = String.valueOf(9999L);
    NEARBY_LBS_HELLO_UIN = String.valueOf(9929L);
    QQBROADCAST_MSG_UIN = String.valueOf(10000L);
    TROOP_FILE_UIN = String.valueOf(9989L);
    FAVORITES_UIN = String.valueOf(9988L);
    FRIEND_SYSTEM_MSG_UIN = String.valueOf(9987L);
    TROOP_SYSTEM_MSG_UIN = String.valueOf(9986L);
    TROOP_SUSPICIOUS_MSG_UIN = String.valueOf(9915L);
    FRIEND_LIST_LABEL_MSG_UIN = String.valueOf(9985L);
    KANDIAN_LOCKSCREEN_INTERACT_MSG_UIN = String.valueOf(9914L);
    FRIEND_SYSTEM_RIBBON_MSG_UIN = String.valueOf(9984L);
    TROOP_SYSTEM_RIBBON_MSG_UIN = String.valueOf(9983L);
    QZONE_PHOTO_ASSISTANT_UIN = String.valueOf(9982L);
    PUBLIC_ACCOUNT_WPA_ASSISTANT_UIN = String.valueOf(9981L);
    TEAM_WORK_WORD_UIN = String.valueOf(9951L);
    TROOP_NOTIFICATION_UIN = String.valueOf(9980L);
    WIFI_HOT_CHAT_UIN = String.valueOf(9976L);
    RECOMMEND_TROOP_UIN = String.valueOf(9979L);
    SEC_MSG_UIN = String.valueOf(9977L);
    SMARTDEVICE_UIN = String.valueOf(9972L);
    DATE_UIN = String.valueOf(9974L);
    TROOP_BAR_ASSISTANT_UIN = String.valueOf(9975L);
    ACTIVATE_FRIENDS_UIN = String.valueOf(9973L);
    EC_SHOP_ASSISTANT_UIN = String.valueOf(9970L);
    VOTE_UIN = String.valueOf(9969L);
    CONVERSATION_MAY_KNOW_FRIEND_UIN = String.valueOf(9921L);
    LOCK_SCREEN_LBS_HELLO_UIN = String.valueOf(9968L);
    LOCK_SCREEN_DATE_UIN = String.valueOf(9967L);
    LBS_SAY_HELLO_LIST_UIN = String.valueOf(9966L);
    DATE_SAY_HELLO_LIST_UIN = String.valueOf(9965L);
    MSG_BOX_INTERACT_UIN = String.valueOf(9949L);
    MSG_BOX_FOLLOW_UIN = String.valueOf(9950L);
    MSG_BOX_MYMOMMENT_UIN = String.valueOf(9919L);
    MSG_BOX_DAREN_ASSISTANT_UIN = String.valueOf(9918L);
    MSG_BOX_YANZHI_UIN = String.valueOf(9917L);
    SCHEDULE_NOTIFY_UIN = String.valueOf(9957L);
    READINJOY_UIN = String.valueOf(9964L);
    LBS_NEARBY_RECOMMEND_UIN = String.valueOf(9963L);
    DINGDONG_UIN = String.valueOf(9961L);
    SEND_BLESS_UIN = String.valueOf(9960L);
    WIFI_HOTSPOT_UIN = String.valueOf(9959L);
    PULL_ACTIVE_PUSH_UIN = String.valueOf(9958L);
    MAYKNOW_RECOMMEND_UIN = String.valueOf(9955L);
    OLD_KANDIAN_UIN = String.valueOf(3338705755L);
    NEW_KANDIAN_UIN = String.valueOf(2171946401L);
    KANDIAN_MERGE_UIN = String.valueOf(9954L);
    SERVICE_ACCOUNT_FOLDER_UIN = String.valueOf(9953L);
    BABY_Q_UIN = String.valueOf(66600000L);
    SUBACCOUNT_TROOP_UIN = String.valueOf(13002L);
    FRIEND_ANNIVER_UIN = String.valueOf(9952L);
    PHONE_CONTACT_UIN = String.valueOf(9949L);
    QZONE_UIN = String.valueOf(1042L);
    QQSTORY_UIN = String.valueOf(1043L);
    QQSTORY_UIN_PIAZZA = String.valueOf(1044L);
    CAMPUS_NOTICE_UIN = String.valueOf(9948L);
    HOTCHAT_CENTER_UIN = String.valueOf(9946L);
    ARK_DEBUG_UIN = String.valueOf(9947L);
    CONFESS_UIN = String.valueOf(9945L);
    CONFESS_FRD_REC_UIN = String.valueOf(9944L);
    TENCENT_DOCS_ASSISTANT_UIN = String.valueOf(9930L);
    WEISHI_UIN = String.valueOf(2062433139L);
    KANDIAN_SUBSCRIBE_UIN = String.valueOf(2173223560L);
    KANDIAN_DAILY_UIN = String.valueOf(3434959637L);
    CONVERSATION_CONTACTS_GUIDE_UIN = String.valueOf(9922L);
    MATCH_CHAT_UIN = String.valueOf(9916L);
    QCIRCLE_CHAT_UIN = String.valueOf(9913L);
    TIM_TEAM_UIN = String.valueOf(3606676177L);
    MINI_GAME_PUBLIC_ACCOUNT_UIN = String.valueOf(1983141935L);
    QQ_VIP_UIN = String.valueOf(2659464438L);
    AUDIO_ROOM_UIN = String.valueOf(3606676177L);
    TEMP_MSG_BOX_UIN = String.valueOf(9912L);
    FILTER_MSG_UIN = String.valueOf(9911L);
    SDCARD_ROOT = Environment.getExternalStorageDirectory().getAbsolutePath();
    SDCARD_PATH = SDCARD_ROOT + "/Tencent/MobileQQ/";
    SDCARD_PATH_CHATRECORD = SDCARD_ROOT + "/Tencent/MobileQQ/ChatRecord/";
    SDCARD_PATH_EMOJIS = SDCARD_PATH + "emoji/";
    SDCARD_PATH_HOTFRIEND_IMG = SDCARD_PATH + "hotimage/";
    SDCARD_BOLB_PATH = SDCARD_ROOT + "/Tencent/blob/";
    LOG_PATH_SDCARD = SDCARD_PATH + "log/";
    SDCARD_IMG_SAVE = SDCARD_ROOT + "/Tencent/QQ_Images/";
    SDCARD_IMG_ORIGIN_SAVE = SDCARD_IMG_SAVE + "QQEditPic/OriginPic/";
    SDCARD_IMG_FLOW_CAMERA = SDCARD_ROOT + "/DCIM/QQPhoto/";
    SDCARD_SHORTVIDEO_SAVE = SDCARD_ROOT + "/Tencent/QQ_Shortvideos/";
    SDCARD_AIO_FORWARD = SDCARD_ROOT + "/Tencent/AIO_FORWARD/";
    SDCARD_IMG_FAVORITE = VFSAssistantUtils.getSDKPrivatePath(SDCARD_ROOT + "/Tencent/QQ_Favorite/");
    SDCARD_IMG_CAMERA_EMO = VFSAssistantUtils.getSDKPrivatePath(SDCARD_ROOT + "/Tencent/QQ_CameraEmo/");
    SDCARD_IMG_CAMERA = SDCARD_ROOT + "/DCIM/Camera/";
    S_DCARD_COLLECTION = VFSAssistantUtils.getSDKPrivatePath(SDCARD_ROOT + "/Tencent/QQ_Collection/");
    SDCARD_FILE_SAVE_PATH = VFSAssistantUtils.getSDKPrivatePath(SDCARD_ROOT + "/Tencent/QQfile_recv/");
    SDCARD_FILE_SAVE_THUMB_PATH = SDCARD_FILE_SAVE_PATH + ".thumbnails/";
    SDCARD_FILE_SAVE_TMP_PATH = SDCARD_FILE_SAVE_PATH + ".tmp/";
    SDCARD_FILE_SAVE_TROOPTMP_PATH = SDCARD_FILE_SAVE_PATH + ".trooptmp/";
    SDCARD_SECRETFILE_SAVE = SDCARD_ROOT + "/Tencent/QQ_Secretfile/";
    SDCARD_VIDEO = VFSAssistantUtils.getSDKPrivatePath(SDCARD_ROOT + "/Tencent/QQ_Video/");
    SDCARD_SHARE_VCARD = SDCARD_ROOT + "/Tencent/QQfile_share/";
    SDCARD_HOMEWORK_AUDIO = SDCARD_ROOT + "/Tencent/QQHomework_recv/";
    SDCARD_HOMEWORK_ATTACH = SDCARD_ROOT + "/Tencent/QQHomework_attach/";
    SDCARD_TROOP_REWARD = SDCARD_PATH + "Troop_reward/";
    SDCARD_AR_IMG = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "ar_cloud_img/");
    SDCARD_AR_FEATURE = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "ar_cloud_marker_feature/");
    SDCARD_AR_CONFIG = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "ar_cloud_marker_config/");
    SDCARD_AR_MODEL = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "ar_cloud_marker_model/");
    SDCARD_AR_RELATIONSHIP = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "ARRelationShip/");
    SDCARD_AR_TRANSFER = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "ar_cloud_transfer/");
    SDCARD_MUSIC = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "qqmusic/");
    SDCARD_PE = SDCARD_PATH + "pe";
    SDCARD_POKE = SDCARD_PATH + "poke";
    SDCARD_NEW_POKE = SDCARD_PATH + "newpoke";
    if (BaseApplicationImpl.getContext().doesHasSDCardPermission()) {}
    for (String str = SDCARD_PATH;; str = "/sdcard/Android/data/com.tencent.mobileqq/files/Tencent/MobileQQ/")
    {
      HEAD_ROOT_PATH = str;
      PATH_CUSTOM_HEAD_ROOT = VFSAssistantUtils.getSDKPrivatePath(HEAD_ROOT_PATH + "head/");
      PATH_CUSTOM_HEAD_ROOT_SDCARD = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "head/");
      PATH_HEAD_HD = PATH_CUSTOM_HEAD_ROOT + "_hd/";
      PATH_HEAD_THD = PATH_CUSTOM_HEAD_ROOT + "_thd/";
      PATH_HEAD_STRANGER = PATH_CUSTOM_HEAD_ROOT + "_stranger/";
      PATH_HEAD_APOLLO = PATH_CUSTOM_HEAD_ROOT + "_apollo/";
      PATH_HEAD_STORE = PATH_CUSTOM_HEAD_ROOT + "_st/";
      DEVICE_HEAD_PATH = PATH_CUSTOM_HEAD_ROOT + "_dhd/";
      PATH_SSO_HEAD_HD = PATH_CUSTOM_HEAD_ROOT + "_SSOhd/";
      SDCARD_STAR_HEAD = VFSAssistantUtils.getSDKPrivatePath(HEAD_ROOT_PATH + ".starHead/");
      SDCARD_PENDANT_ROOT = VFSAssistantUtils.getSDKPrivatePath(HEAD_ROOT_PATH + ".pendant/");
      SDCARD_SECMSG_PIC_ROOT = SDCARD_PATH + ".secmsgPic/";
      SDCARD_EMOTICON_SAVE = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + ".emotionsm/");
      SDCARD_EMOTICON_QFACE = SDCARD_PATH + ".emoQFace/";
      SDCARD_EMOTIOCN_DIY = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + ".diy/");
      SDCARD_INDIV_ANIM_ROOT = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + ".indivAnim/");
      SDCARD_SIGNATURE_TEMPLATE_ROOT = VFSAssistantUtils.getSDKPrivatePath(new StringBuilder().append(SDCARD_PATH).append("pddata/vas/").toString()) + "individual_sign/";
      SDCARD_SIGNATURE_STICKER_DIR = SDCARD_SIGNATURE_TEMPLATE_ROOT + "stickers/";
      SDCARD_IMG_FORWARD_URLDRAWABLE = SDCARD_PATH + "foward_urldrawable/";
      SDCARD_BILLD_URLDRAWABLE = SDCARD_PATH + ".billd_urldrawable/";
      SDCARD_MAP_ROAM_SAVE = SDCARD_PATH + ".map_roam/";
      PATH_DEVICE = SDCARD_PATH + "device/";
      PATH_LOCATION_IMG = SDCARD_PATH + "location/";
      PATH_SYSTEM_BACKGROUND = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "system_background/");
      PATH_SYSTEM_BACKGROUND_CONFIG = PATH_SYSTEM_BACKGROUND + "QQPicConfig.xml";
      LYRIC_PATH_SDCARD = SDCARD_PATH + "lyric/";
      DYNAMIC_PROFILE = SDCARD_PATH + "/dynamic_profile/";
      SDCARD_AUDIO_CACHE = SDCARD_PATH + "/audioCache/";
      SDCARD_MINIAPP_WANGKA_PATH = SDCARD_PATH + ".mini_wangka/";
      PATH_SYSTEM_BACKGROUND_THUMBNAIL = PATH_SYSTEM_BACKGROUND + "thumbnail/";
      PATH_SYSTEM_BACKGROUND_RESOURCE = PATH_SYSTEM_BACKGROUND + "resource/";
      PATH_TURNBRAND = SDCARD_PATH + "turnbrand/";
      SCRIBBLE_FILE_DIR = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + "Scribble/");
      PROFILE_CARD_BACKGROUND_DIR = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + ".profilecard" + "/");
      PATH_CARD_QZONE = SDCARD_PATH + "card/";
      PATH_CARD_STARFANS = SDCARD_PATH + "card/starfans/";
      PATH_CARD_INDIVID_BANNERS = SDCARD_PATH + "card/individbanners/";
      SDCARD_DATABASE = SDCARD_PATH + "data/";
      PATH_TROOP_ACTIVITY = SDCARD_PATH + "troop/activity/";
      WATER_MARK_TEMP_PATH = SDCARD_PATH + "photo/watermark_temp.jpg";
      SDCARD_GIFT_SAVE = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH + ".gift/");
      SDCARD_ROBOT_SAVE = SDCARD_PATH + "robot/";
      SDCARD_NEARBY_LOTTIE = SDCARD_PATH + ".nearby_lottie/";
      SDCARD_NEARBY_FLOWER = SDCARD_PATH + ".nearby_flower/";
      SDCARD_PATH_PUBLIC_ACCOUNT = SDCARD_PATH + "pubaccount/";
      SDCARD_PATH_PUBLIC_ACCOUNT_SCREENSHOTS = SDCARD_PATH_PUBLIC_ACCOUNT + "screenshots/";
      SDCARD_PATH_READINJOY = SDCARD_PATH + "readinjoy/";
      SDCARD_PATH_READINJOY_CAMERA_CAPTURE_FOLDER = SDCARD_PATH_READINJOY + "record/";
      SDCARD_PATH_READINJOY_TEMPLATE_VIDEO_PATH = SDCARD_PATH_READINJOY_CAMERA_CAPTURE_FOLDER + "template/";
      SDCARD_PATH_READINJOY_VIOLA_JS_SOURCE_PATH = SDCARD_PATH + "viola/template/";
      SDCARD_PATH_READINJOY_OFFLINE_TEMP_FOLDER = SDCARD_PATH_READINJOY + "offline/tmp/";
      SDCARD_PATH_STORY = SDCARD_ROOT + "/Tencent/MobileQQ/.story/";
      SDCARD_PATH_STORY_ANIMATION = SDCARD_PATH_STORY + "animation/";
      SDCARD_PATH_PUBLIC_ACCOUNT_PRELOAD = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH_PUBLIC_ACCOUNT + "preload/");
      SDCARD_PATH_PUBLIC_ACCOUNT_PRELOAD_IMAGE = VFSAssistantUtils.getSDKPrivatePath(SDCARD_PATH_PUBLIC_ACCOUNT + "preimg/");
      SDCARD_IMG_VIDEO = SDCARD_ROOT + "/DCIM/Video/";
      SDCARD_IMG_VIDEO_GN9000L = SDCARD_ROOT + anvx.a(2131700112);
      SDCARD_IMG_VIDEO_VIVO_X7 = SDCARD_ROOT + anvx.a(2131700113);
      SDCARD_IMG_VIDEO_RUBBISH_MX040 = SDCARD_ROOT + "/Camera/Video/";
      SDCARD_PATH_PUBLIC_ACCOUNT_IMAGE_COLLECTION_PRELOAD = SDCARD_PATH_PUBLIC_ACCOUNT + "imagecollection/";
      PATH_NEWER_GUIDE_DIR_NAME = SDCARD_PATH + "/newerGuide/";
      SDCARD_AIO_QIM_THEME_DIR = SDCARD_PATH + "/qim_theme_aio/";
      SDCARD_HOT_PIC_PATH = SDCARD_PATH + "hotpic";
      SDCARD_NEARBY_PROFILE_NOW_VIDEO_DIR = SDCARD_PATH + "/nearby_profile_now_video/";
      SDCARD_AIO_TIM_THEME_DIR = SDCARD_PATH + "/tim_theme_aio/";
      SDCARD_PATH_MINICODERECOG = SDCARD_PATH + "minirecog/";
      SDCARD_PATH_TROOPPHOTO = SDCARD_PATH + "troopphoto/";
      SUBSCRIBE_DRAFT = SDCARD_PATH + "subscribe_draft" + File.separator;
      SUBSCRIBE_DRAFT_SIMPLE = SDCARD_PATH + "subscribe_draft_simple" + File.separator;
      NET_TYPE_NAME = new String[] { "NONE", "WIFI", "2G", "3G", "4G", "CABLE" };
      return;
    }
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes.jar
 * Qualified Name:     com.tencent.mobileqq.app.AppConstants
 * JD-Core Version:    0.7.0.1
 */