package com.tencent.mobileqq.app;

import com.immersion.stickersampleapp.ImmersionHandler;
import com.tencent.av.utils.VideoC2CHandler;
import com.tencent.av.wtogether.handler.WatchTogetherHandler;
import com.tencent.biz.TroopRedpoint.TroopRedTouchHandler;
import com.tencent.biz.bmqq.app.BmqqBusinessHandler;
import com.tencent.biz.now.NowRecordInfo;
import com.tencent.biz.pubaccount.EncryptUinHandler;
import com.tencent.biz.pubaccount.ecshopassit.EcShopHandler;
import com.tencent.biz.pubaccount.ecshopassit.EcshopReportHandler;
import com.tencent.biz.pubaccount.subscript.SubscriptHandler;
import com.tencent.biz.pubaccount.util.PublicAccountClassApi;
import com.tencent.biz.qqstory.base.QQStoryHandler;
import com.tencent.device.devicemgr.SmartDeviceProxyMgr;
import com.tencent.device.file.DeviceFileHandler;
import com.tencent.device.msg.data.DeviceMsgHandle;
import com.tencent.mobileqq.activity.contact.addcontact.face2face.Face2FaceAddContactHandler;
import com.tencent.mobileqq.activity.miniaio.MiniMsgHandler;
import com.tencent.mobileqq.activity.recent.guidebanner.NewerGuideBannerHandler;
import com.tencent.mobileqq.activity.recent.msgbox.api.ITempMsgBoxService;
import com.tencent.mobileqq.addon.DiyPendantHandler;
import com.tencent.mobileqq.apollo.utils.ApolloClassFactoryApi;
import com.tencent.mobileqq.app.qqdaily.QQDailyHandler;
import com.tencent.mobileqq.app.utils.MessageRoamHandler;
import com.tencent.mobileqq.app.utils.PokeBigResHandler;
import com.tencent.mobileqq.applets.AppletsHandler;
import com.tencent.mobileqq.armap.ArMapHandler;
import com.tencent.mobileqq.avatar.api.IQQAvatarHandlerApi;
import com.tencent.mobileqq.avatar.dynamicavatar.DynamicAvatarInfoHandler;
import com.tencent.mobileqq.avatar.handler.DiscussionAvatarHandler;
import com.tencent.mobileqq.bubble.BubbleDiyHandler;
import com.tencent.mobileqq.c2cshortcutbar.C2CShortcutBarHandler;
import com.tencent.mobileqq.colornote.data.ColorNoteHandler;
import com.tencent.mobileqq.confess.ConfessHandler;
import com.tencent.mobileqq.ecshop.ad.api.IEcshopAdApi;
import com.tencent.mobileqq.emosm.api.IEmoticonBusinessProxyApi;
import com.tencent.mobileqq.filemanager.fileassistant.top.FileAssistTopHandler;
import com.tencent.mobileqq.flashchat.FlashChatHanlder;
import com.tencent.mobileqq.friends.intimate.IntimateInfoHandler;
import com.tencent.mobileqq.gamecenter.api.IGameMsgHandlerNameApi;
import com.tencent.mobileqq.inputstatus.InputStatusHandler;
import com.tencent.mobileqq.kandian.ad.api.IRIJSuperMaskService;
import com.tencent.mobileqq.kandian.glue.businesshandler.api.IRIJHandlerNameApi;
import com.tencent.mobileqq.leba.ILebaHandler;
import com.tencent.mobileqq.listentogether.ListenTogetherHandler;
import com.tencent.mobileqq.location.api.ILocationUtilApi;
import com.tencent.mobileqq.loginwelcome.LoginWelcomeHandler;
import com.tencent.mobileqq.mini.api.QQMiniManager;
import com.tencent.mobileqq.msgbackup.authentication.MsgBackupAuthHandler;
import com.tencent.mobileqq.multicard.manager.TroopMemberRecommendHandler;
import com.tencent.mobileqq.musicgene.MusicPlayerHandler;
import com.tencent.mobileqq.nearby.QQNearbyManager;
import com.tencent.mobileqq.nearby.now.NowSmallVideoHandler;
import com.tencent.mobileqq.nearby.redtouch.RedtouchHandler;
import com.tencent.mobileqq.paiyipai.PaiYiPaiHandler;
import com.tencent.mobileqq.participle.ParticipleHandler;
import com.tencent.mobileqq.phonecontact.handler.ContactBindHandler;
import com.tencent.mobileqq.profile.PersonalityLabel.PersonalityLabelHandler;
import com.tencent.mobileqq.profilecard.bussiness.anonymous.handler.AnonymousHandler;
import com.tencent.mobileqq.profilesetting.CardSettingHandler;
import com.tencent.mobileqq.qcall.QCallCardHandler;
import com.tencent.mobileqq.qcircle.api.IQCircleClassApi;
import com.tencent.mobileqq.qqexpand.ExpandClassManager;
import com.tencent.mobileqq.qroute.QRoute;
import com.tencent.mobileqq.quicklogin.business.QuickLoginHandler;
import com.tencent.mobileqq.relationx.onewayfriend.OneWayFriendHandler;
import com.tencent.mobileqq.security.business.ModifyPwdTopBarHandler;
import com.tencent.mobileqq.simpleui.SimpleUIHandler;
import com.tencent.mobileqq.studymode.AlphabeticFontHandler;
import com.tencent.mobileqq.teamwork.TenDocOCRExportHandler;
import com.tencent.mobileqq.teamwork.api.ITeamWorkFacadeCreator;
import com.tencent.mobileqq.tofumsg.TofuHandler;
import com.tencent.mobileqq.together.TogetherOperationHandler;
import com.tencent.mobileqq.troop.api.ITroopHandlerNameApi;
import com.tencent.mobileqq.troop.shortcutbar.TroopShortcutBarHandler;
import com.tencent.mobileqq.vas.VasMonitorHandler;
import com.tencent.mobileqq.vas.svip.api.ISVIPHandlerProxy;
import com.tencent.mobileqq.vipav.VipSetFunCallHandler;
import com.tencent.mobileqq.werewolves.WerewolvesHandler;
import com.tencent.mobileqq.writetogether.api.IWTHandlerClassName;
import com.tencent.msfmqpsdkbridge.MSFNetTransportProvider;
import com.tencent.open.manager.OpenAgentHandler;
import com.tencent.qidian.controller.BigDataGetIpHandler;
import com.tencent.qidian.controller.QidianHandler;
import com.tencent.qidian.controller.QidianPubAccountBigDataHandler;
import com.tencent.util.notification.NotificationController;
import cooperation.ilive.group.IliveCommonHandler;
import cooperation.qqfav.forward.QfavFileForwardHandler;

public class BusinessHandlerFactory
{
  public static final String ANONYMOUS_ANSWER_HANDLER;
  public static final String APOLLO_CONTENT_UPDATE_HANDLER;
  public static final String APOLLO_EXTENSION_HANDLER;
  public static final String APPLET_PUSH_HANDLER;
  public static final String ARMAP_HANDLER;
  public static final String AVATAR_HANDLER;
  public static final String BABY_Q_HANDLER;
  public static final String BIG_DATA_GET_IP_HANDLER;
  public static final String BMQQ_BUSINESS_HANDLER;
  public static final String BUBBLE_DIYTEXT_HANDLER;
  public static final String C2C_SHORTCUT_BAR_HANDLER;
  public static final String CAMERA_EMOTICON_HANDLER;
  public static final String CAMERA_HANDLER = "com.tencent.aelight.camera.ae.config.CameraDataServiceHandler";
  public static final String CARD_HANLDER;
  public static final String CARD_SETTING_HANDLER;
  public static final String CHANGE_VOICE_HANDLER;
  public static final String CHATBG_AUTH;
  public static final String CLUBCONTENTUPDATE_HANDLER;
  public static final String COLOR_NOTE_HANDLER;
  public static final String COLUMN_SUBSCRIBE_HANDLER;
  public static final String COMMPLGUGIN_HANDLER;
  public static final String CONFESS_HANDLER;
  public static final String CONFIG_HANDLER;
  public static final String CONTACT_BIND_HANDLER;
  public static final String DATALINE_HANDLER;
  public static final String DEVICEFILE_HANDLER;
  public static final String DEVICEMSG_HANDLER;
  public static final String DEVICEPROXYMGR_HANDLER;
  public static final String DISCUSSION_AVATAR_HANDLER;
  public static final String DISCUSSION_HANDLER;
  public static final String DIY_PENDANT_HANDLER;
  public static final String DYNAMIC_AVATAR_HANDLER;
  public static final String ECSHOP_HANDLER;
  public static final String EC_SHOP_REPORT_HANDLER;
  public static final String ENCRYPT_UIN_HANDLER;
  public static final String ENTERPRISEQQ_HANDLER;
  public static final String ESHOP_AD_HANDLER;
  public static final String EXTEND_FRIEND_HANDLER;
  public static final String FACE2FACE_ADD_FRIEND_HANDLER;
  public static final String FAVEMO_ROAMING_HANDLER;
  public static final String FAV_ONLINE_FILE_FORWARD_HANDLER;
  public static final String FILE_ASSIST_TOP;
  public static final String FILTER_MSG_BOX_HANDLER;
  public static final String FLASH_CHAT_HANDLER;
  public static final String FRIENDLIST_HANDLER;
  public static final String FUN_CALL_HANDLER;
  public static final String GAME_CENTER_UNISSO_HANDLER;
  public static final String GET_RED_POINT_EX_HANDLER;
  public static final String GET_ROAMMESSAGE_HANDLER;
  public static final String GLOBAL_SEARCH_HANDLER;
  public static final String GROUP_TEAM_WORK_HANDLER;
  public static final String GVIDEO_HANDLER;
  public static final String HANDLER_EMOSM;
  public static final String HANDLER_PUBLIC_ACCOUNT;
  public static final String ILIVE_COMMON_HANDLER;
  public static final String IMMERSION_HANDLER;
  public static final String INPUT_STATUS_HANDLER;
  public static final String INTIMATE_INFO_HANDLER;
  public static final String LBS_HANDLER;
  public static final String LEBA_SETTING_HANDLER;
  public static final String LISTEN_TOGETHER_HANDLER;
  public static final String LOCATION_HANDLER;
  public static final String LOGIN_WELCOME_HANDLER;
  public static final String LOVE_STATE_CHANGE_HANDLER;
  public static final String MESSAGE_HANDLER = MessageHandler.class.getName();
  public static final String MINIMSG_HANDLER;
  public static final String MINI_APP_ENTRY_HANDLER;
  public static final String MQQ_COMIC_HANDLER;
  public static final String MSF_NET_TRANSPORT_PROVIDER_HANDLER;
  public static final String MSG_BACK_UP_HANDLER;
  public static final String MUSIC_PLAYER_HANDLER;
  public static final String NEARBY_CARD_HANDLER;
  public static final String NEARBY_HANDLER;
  public static final String NEARBY_RELEVANT_HANDLER;
  public static final String NEARFIELD_DISCUSS_HANDLER;
  public static final String NEARFIELD_TROOP_HANDLER;
  public static final String NEWER_GUIDE_BANNER_HANDLER;
  public static final String NOTIFICATION_CONTROLLER_HANDLER;
  public static final String NOW_CHANNEL_HANDLER_V2;
  public static final String NOW_PROXY_HANDLER;
  public static final String NOW_SMALL_VIDEO_HANDLER;
  public static final String NUMREDMSG_HANDLER;
  public static final String ONE_WAY_FRIEND_HANDLER;
  public static final String OPEN_AGENT_HANDLER;
  public static final String PAI_YI_PAI_HANDLER;
  public static final String PARTICIPLE_HANDLER;
  public static final String POKE_BIG_RES_HANDLER;
  public static final String PPC_LOGIN_AUTH;
  public static final String PRINTER_STATUS_HANDLER;
  public static final String PROFILE_PERSONALITY_LABEL;
  public static final String PUBLIC_ACCOUNT_VIDEO_DIANZAN;
  public static final String PUBLIC_ACCOUNT_VIDEO_HANDLER;
  public static final String QAV_C2C_HANDLER;
  public static final String QAV_HANDLER;
  public static final String QAV_WT_HANDLER;
  public static final String QCALLCARD_HANDLER;
  public static final String QCIRCLE_HANDLER;
  public static final String QIDIAN_HANDLER;
  public static final String QIDIAN_PA_BIG_DATA_HANDLER;
  public static final String QPAY_HANDLER;
  public static final String QQSTORY_HANDLER;
  public static final String QQ_DAILY_HANDLER;
  public static final String QUICK_LOGIN;
  public static final String QWALLET_AUTH_HANDLER;
  public static final String QZONENOTIFY_HANDLER;
  public static final String READINJOY_AD_MATERIAL_HANDLER;
  public static final String READINJOY_HANDLER;
  public static final String READ_INJOY_SKIN_HANDLER;
  public static final String REDPOINT_HANDER;
  public static final String REDTOUCH_HANDLER;
  public static final String REGPRXYSVCPACK_HANDLER;
  public static final String RELATED_EMOTION_HANDLER;
  public static final String REPORT_HANDLER;
  public static final String ROUTER_HANDLER;
  public static final String SAFECENTER_PUSH_HANDLER;
  public static final String SECURITY_TOP_BAR;
  public static final String SEC_SVC_HANDLER;
  public static final String SHIELD_LIST_HANDLER;
  public static final String SIGNATURE_HANDLER;
  public static final String SIMPLE_UI_HANDLER;
  public static final String SPECIAL_CARE_HANDLER;
  public static final String STARTAPPCHECK_HANDLER;
  public static final String SUBSCRIPT_HANDLER;
  public static final String SVIP_HANDLER;
  public static final String TEAM_WORK_FILE_EXPORT_HANDLER;
  public static final String TEAM_WORK_FILE_IMPORT_HANDLER;
  public static final String TEAM_WORK_HANDLER;
  public static final String TEAM_WORK_OCR_EXPORT_HANDLER;
  public static final String TEENS_MODE_ALPHABETIC_FONT_HANDLER;
  public static final String THEME_HANDLER;
  public static final String TOFUMSG_HANDLER;
  public static final String TOGETHER_OPERATOR_HANDLER;
  public static final String TROOP_ADD_FRIEND_HANDLER;
  public static final String TROOP_AIO_NOTIFY_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopAioNotifyHandlerName();
  public static final String TROOP_ANNOUNCEMENT_HANDLER;
  public static final String TROOP_ANONYMOUS_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopAnonymousHandlerName();
  public static final String TROOP_APP_HANDLER;
  public static final String TROOP_ASSOCIATION_HANDLER;
  public static final String TROOP_AUDIT_HANDLER;
  public static final String TROOP_AVATAR_HANDLER;
  public static final String TROOP_BATCH_INFO_HANDLER;
  public static final String TROOP_CLOCKIN_HANDLER;
  public static final String TROOP_COMMONLY_USED_HANDLER;
  public static final String TROOP_CONFIG_HANDLER;
  public static final String TROOP_ESSENCE_MSG_HANDLER;
  public static final String TROOP_FANS_HANDLER;
  public static final String TROOP_FEE_HANDLER;
  public static final String TROOP_FILE_HANDLER;
  public static final String TROOP_GAG_HANDLER;
  public static final String TROOP_GAME_HANDLER;
  public static final String TROOP_HONOR_HANDLER;
  public static final String TROOP_INFO_EXT_HANDLER;
  public static final String TROOP_INFO_HANDLER;
  public static final String TROOP_LIST_HANDLER;
  public static final String TROOP_LUCKY_CHARACTER_HANDLER;
  public static final String TROOP_MANAGER_BIZ_HANDLER;
  public static final String TROOP_MEMBER_CARD_HANDLER;
  public static final String TROOP_MEMBER_INFO_HANDLER;
  public static final String TROOP_MEMBER_LEVEL_HANDLER;
  public static final String TROOP_MEMBER_LIST_HANDLER;
  public static final String TROOP_MEMBER_MNG_HANDLER;
  public static final String TROOP_MEMBER_RECOMMED_HANDLER;
  public static final String TROOP_MESSAGE_HANDLER;
  public static final String TROOP_MNG_HANDLER;
  public static final String TROOP_MODIFY_HANDLER;
  public static final String TROOP_NOTIFICATION_HANDLER;
  public static final String TROOP_ONLINE_MEMBER_HANDLER;
  public static final String TROOP_ONLINE_PUSH_HANDLER;
  public static final String TROOP_PHOTO_HANDLER;
  public static final String TROOP_PUSH_HANDLER;
  public static final String TROOP_QZONE_UPLOAD_ALBUM_PROGRESS_HANDLER;
  public static final String TROOP_RECOMMEND_HANDLER;
  public static final String TROOP_RED_DOT_HANDLER;
  public static final String TROOP_ROAMSETTING_HANDLER;
  public static final String TROOP_ROBOT_HANDLER;
  public static final String TROOP_SETTING_HANDLER;
  public static final String TROOP_SHORTCUTBAR_HANDLE;
  public static final String TROOP_SHOW_EXTERNAL_HANDLER;
  public static final String TROOP_SURVEY_HANDLER;
  public static final String TROOP_TOKEN_HANDLER;
  public static final String UNIFY_SEARCH_UNITE_HANDLER;
  public static final String UNITE_SEARCH_HANDLER;
  public static final String UNI_PAY_HANDLER;
  public static final String VAS_MONITOR_HANDLER;
  public static final String VIDEOPLAYCOUNT_HANDLER;
  public static final String VIDEOPLAYRECOMMEND_HANDLER;
  public static final String VIDEO_FEEDS_BARRAGE_HANDLER;
  public static final String VIDEO_FEEDS_LIKE_ANIMATION_CONFIG;
  public static final String VIPINFO_HANDLER;
  public static final String VIPRECOMMENDPAY_HANDLER;
  public static final String VIP_AIO_SEND_HANDLER;
  public static final String WEREWOLVES_HANDLER;
  public static final String WIFI_SDK_HANDLER;
  public static final String WRITE_TOGETHER_HANDLER;
  
  static
  {
    FRIENDLIST_HANDLER = FriendListHandler.class.getName();
    CARD_HANLDER = CardHandler.class.getName();
    LBS_HANDLER = LBSHandler.class.getName();
    CONFIG_HANDLER = ConfigHandler.class.getName();
    REPORT_HANDLER = ReportHandler.class.getName();
    DISCUSSION_HANDLER = DiscussionHandler.class.getName();
    QZONENOTIFY_HANDLER = QZoneNotifyHandler.class.getName();
    DATALINE_HANDLER = DataLineHandler_210.class.getName();
    REGPRXYSVCPACK_HANDLER = RegisterProxySvcPackHandler.class.getName();
    HANDLER_PUBLIC_ACCOUNT = PublicAccountClassApi.a();
    HANDLER_EMOSM = ((IEmoticonBusinessProxyApi)QRoute.api(IEmoticonBusinessProxyApi.class)).getEmoticonHandlerImplClassName();
    SVIP_HANDLER = ((ISVIPHandlerProxy)QRoute.api(ISVIPHandlerProxy.class)).getImplClassName();
    THEME_HANDLER = ThemeHandler.class.getName();
    SPECIAL_CARE_HANDLER = QvipSpecialCareHandler.class.getName();
    CLUBCONTENTUPDATE_HANDLER = ClubContentUpdateHandler.class.getName();
    SHIELD_LIST_HANDLER = ShieldListHandler.class.getName();
    GVIDEO_HANDLER = GVideoHandler.class.getName();
    ENTERPRISEQQ_HANDLER = EnterpriseQQHandler.class.getName();
    TROOP_FILE_HANDLER = TroopFileHandler.class.getName();
    STARTAPPCHECK_HANDLER = StartAppCheckHandler.class.getName();
    FILE_ASSIST_TOP = FileAssistTopHandler.class.getName();
    SAFECENTER_PUSH_HANDLER = SafeCenterPushHandler.class.getName();
    VIPINFO_HANDLER = VipInfoHandler.class.getName();
    TROOP_QZONE_UPLOAD_ALBUM_PROGRESS_HANDLER = TroopQZoneUploadAlbumHandler.class.getName();
    LEBA_SETTING_HANDLER = ((ILebaHandler)QRoute.api(ILebaHandler.class)).getLebaSettingHandlerClassName();
    NEARFIELD_DISCUSS_HANDLER = NearFieldDiscussHandler.class.getName();
    SEC_SVC_HANDLER = SecSvcHandler.class.getName();
    BMQQ_BUSINESS_HANDLER = BmqqBusinessHandler.class.getName();
    QAV_C2C_HANDLER = VideoC2CHandler.class.getName();
    SIGNATURE_HANDLER = SignatureHandler.class.getName();
    QWALLET_AUTH_HANDLER = QWalletAuthHandler.class.getName();
    GET_RED_POINT_EX_HANDLER = TroopRedTouchHandler.class.getName();
    UNI_PAY_HANDLER = UniPayHandler.class.getName();
    FUN_CALL_HANDLER = VipSetFunCallHandler.class.getName();
    QPAY_HANDLER = QPayHandler.class.getName();
    ROUTER_HANDLER = RouterHandler.class.getName();
    DEVICEMSG_HANDLER = DeviceMsgHandle.class.getName();
    DEVICEFILE_HANDLER = DeviceFileHandler.class.getName();
    DEVICEPROXYMGR_HANDLER = SmartDeviceProxyMgr.class.getName();
    QAV_HANDLER = com.tencent.av.business.handler.MessageHandler.class.getName();
    BABY_Q_HANDLER = BabyQHandler.class.getName();
    CHATBG_AUTH = ChatBackgroundAuthHandler.class.getName();
    NUMREDMSG_HANDLER = NumRedMsgHandler.class.getName();
    NEARFIELD_TROOP_HANDLER = NearFieldTroopHandler.class.getName();
    PPC_LOGIN_AUTH = PPCLoginAuthHandler.class.getName();
    GET_ROAMMESSAGE_HANDLER = MessageRoamHandler.class.getName();
    NEARBY_CARD_HANDLER = QQNearbyManager.r();
    READINJOY_HANDLER = ((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getReadInJoyHandlerName();
    MSF_NET_TRANSPORT_PROVIDER_HANDLER = MSFNetTransportProvider.class.getName();
    SUBSCRIPT_HANDLER = SubscriptHandler.class.getName();
    NEARBY_RELEVANT_HANDLER = QQNearbyManager.q();
    ECSHOP_HANDLER = EcShopHandler.class.getName();
    BUBBLE_DIYTEXT_HANDLER = BubbleDiyHandler.class.getName();
    APOLLO_EXTENSION_HANDLER = ApolloClassFactoryApi.h();
    FAVEMO_ROAMING_HANDLER = ((IEmoticonBusinessProxyApi)QRoute.api(IEmoticonBusinessProxyApi.class)).getFavEmoHandlerImplClassName();
    VIPRECOMMENDPAY_HANDLER = VIPRecommendPayHandler.class.getName();
    PRINTER_STATUS_HANDLER = PrinterStatusHandler.class.getName();
    QCALLCARD_HANDLER = QCallCardHandler.class.getName();
    MQQ_COMIC_HANDLER = ((IEmoticonBusinessProxyApi)QRoute.api(IEmoticonBusinessProxyApi.class)).getVipComicMqqHandlerImplClassName();
    GLOBAL_SEARCH_HANDLER = GlobalSearchHandler.class.getName();
    LOGIN_WELCOME_HANDLER = LoginWelcomeHandler.class.getName();
    QIDIAN_HANDLER = QidianHandler.class.getName();
    VIP_AIO_SEND_HANDLER = VIPAioSendHandler.class.getName();
    REDPOINT_HANDER = RedpointHandler.class.getName();
    EC_SHOP_REPORT_HANDLER = EcshopReportHandler.class.getName();
    NEARBY_HANDLER = NearbyHandler.class.getName();
    VIDEOPLAYRECOMMEND_HANDLER = ((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getVideoPlayRecommendHandlerName();
    REDTOUCH_HANDLER = RedtouchHandler.class.getName();
    MUSIC_PLAYER_HANDLER = MusicPlayerHandler.class.getName();
    PUBLIC_ACCOUNT_VIDEO_HANDLER = PublicAccountClassApi.b();
    CHANGE_VOICE_HANDLER = VoiceChangeHandler.class.getName();
    DYNAMIC_AVATAR_HANDLER = DynamicAvatarInfoHandler.class.getName();
    QQSTORY_HANDLER = QQStoryHandler.class.getName();
    VIDEOPLAYCOUNT_HANDLER = ((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getVideoPlayCountHandlerName();
    ARMAP_HANDLER = ArMapHandler.class.getName();
    VAS_MONITOR_HANDLER = VasMonitorHandler.class.getName();
    BIG_DATA_GET_IP_HANDLER = BigDataGetIpHandler.class.getName();
    QIDIAN_PA_BIG_DATA_HANDLER = QidianPubAccountBigDataHandler.class.getName();
    WEREWOLVES_HANDLER = WerewolvesHandler.class.getName();
    FLASH_CHAT_HANDLER = FlashChatHanlder.class.getName();
    UNITE_SEARCH_HANDLER = UniteSearchHandler.class.getName();
    PROFILE_PERSONALITY_LABEL = PersonalityLabelHandler.class.getName();
    DIY_PENDANT_HANDLER = DiyPendantHandler.class.getName();
    APOLLO_CONTENT_UPDATE_HANDLER = ApolloClassFactoryApi.g();
    IMMERSION_HANDLER = ImmersionHandler.class.getName();
    POKE_BIG_RES_HANDLER = PokeBigResHandler.class.getName();
    NOW_SMALL_VIDEO_HANDLER = NowSmallVideoHandler.class.getName();
    TEAM_WORK_FILE_IMPORT_HANDLER = ((ITeamWorkFacadeCreator)QRoute.api(ITeamWorkFacadeCreator.class)).getImportHandlerName();
    READ_INJOY_SKIN_HANDLER = ((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getReadInJoySkinHandlerName();
    TEAM_WORK_HANDLER = ((ITeamWorkFacadeCreator)QRoute.api(ITeamWorkFacadeCreator.class)).getTeamWorkHandlerName();
    CONFESS_HANDLER = ConfessHandler.class.getName();
    PUBLIC_ACCOUNT_VIDEO_DIANZAN = ((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getVideoPlayDianZanHandler();
    EXTEND_FRIEND_HANDLER = ExpandClassManager.b();
    COMMPLGUGIN_HANDLER = ((ILebaHandler)QRoute.api(ILebaHandler.class)).getCommPluginHandlerClassName();
    NOW_PROXY_HANDLER = NowRecordInfo.class.getName();
    CONTACT_BIND_HANDLER = ContactBindHandler.class.getName();
    WIFI_SDK_HANDLER = WifiSdkHandler.class.getName();
    ENCRYPT_UIN_HANDLER = EncryptUinHandler.class.getName();
    VIDEO_FEEDS_BARRAGE_HANDLER = ((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getBarrageHandlerName();
    VIDEO_FEEDS_LIKE_ANIMATION_CONFIG = ((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getVideoFeedsLikeAnimateHandlerName();
    ESHOP_AD_HANDLER = ((IEcshopAdApi)QRoute.api(IEcshopAdApi.class)).getEcshopAdHandlerClassName();
    TEAM_WORK_FILE_EXPORT_HANDLER = ((ITeamWorkFacadeCreator)QRoute.api(ITeamWorkFacadeCreator.class)).getExportHandlerName();
    GROUP_TEAM_WORK_HANDLER = ((ITeamWorkFacadeCreator)QRoute.api(ITeamWorkFacadeCreator.class)).getGroupTeamWorkHandlerName();
    NOW_CHANNEL_HANDLER_V2 = QQNearbyManager.u();
    NOTIFICATION_CONTROLLER_HANDLER = NotificationController.class.getName();
    MINIMSG_HANDLER = MiniMsgHandler.class.getName();
    APPLET_PUSH_HANDLER = AppletsHandler.class.getName();
    MINI_APP_ENTRY_HANDLER = QQMiniManager.getMiniAppEntryHandlerClassName();
    INPUT_STATUS_HANDLER = InputStatusHandler.class.getName();
    OPEN_AGENT_HANDLER = OpenAgentHandler.class.getName();
    UNIFY_SEARCH_UNITE_HANDLER = UnifySearchHandler.class.getName();
    INTIMATE_INFO_HANDLER = IntimateInfoHandler.class.getName();
    SIMPLE_UI_HANDLER = SimpleUIHandler.class.getName();
    COLUMN_SUBSCRIBE_HANDLER = ((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getVideoColumnSubscribeHandlerName();
    LISTEN_TOGETHER_HANDLER = ListenTogetherHandler.class.getName();
    TEAM_WORK_OCR_EXPORT_HANDLER = TenDocOCRExportHandler.class.getName();
    CAMERA_EMOTICON_HANDLER = ((IEmoticonBusinessProxyApi)QRoute.api(IEmoticonBusinessProxyApi.class)).getCameraEmoHandlerImplClassName();
    PARTICIPLE_HANDLER = ParticipleHandler.class.getName();
    MSG_BACK_UP_HANDLER = MsgBackupAuthHandler.class.getName();
    READINJOY_AD_MATERIAL_HANDLER = ((IRIJSuperMaskService)QRoute.api(IRIJSuperMaskService.class)).getAdMaterialHandlerClassName();
    LOCATION_HANDLER = ((ILocationUtilApi)QRoute.api(ILocationUtilApi.class)).getClassName();
    TOGETHER_OPERATOR_HANDLER = TogetherOperationHandler.class.getName();
    TROOP_HONOR_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopHonorHandlerName();
    TROOP_MEMBER_RECOMMED_HANDLER = TroopMemberRecommendHandler.class.getName();
    COLOR_NOTE_HANDLER = ColorNoteHandler.class.getName();
    FACE2FACE_ADD_FRIEND_HANDLER = Face2FaceAddContactHandler.class.getName();
    TROOP_SHORTCUTBAR_HANDLE = TroopShortcutBarHandler.class.getName();
    LOVE_STATE_CHANGE_HANDLER = LoveZoneInfoHandler.class.getName();
    QQ_DAILY_HANDLER = QQDailyHandler.class.getName();
    GAME_CENTER_UNISSO_HANDLER = ((IGameMsgHandlerNameApi)QRoute.api(IGameMsgHandlerNameApi.class)).getGameMsgHandlerName();
    FAV_ONLINE_FILE_FORWARD_HANDLER = QfavFileForwardHandler.class.getName();
    TOFUMSG_HANDLER = TofuHandler.class.getName();
    ONE_WAY_FRIEND_HANDLER = OneWayFriendHandler.class.getName();
    RELATED_EMOTION_HANDLER = ((IEmoticonBusinessProxyApi)QRoute.api(IEmoticonBusinessProxyApi.class)).getRelatedEmoHandlerImplClassName();
    QUICK_LOGIN = QuickLoginHandler.class.getName();
    NEWER_GUIDE_BANNER_HANDLER = NewerGuideBannerHandler.class.getName();
    CARD_SETTING_HANDLER = CardSettingHandler.class.getName();
    QCIRCLE_HANDLER = ((IQCircleClassApi)QRoute.api(IQCircleClassApi.class)).getQCircleHandlerClass().getName();
    WRITE_TOGETHER_HANDLER = ((IWTHandlerClassName)QRoute.api(IWTHandlerClassName.class)).getClassName();
    C2C_SHORTCUT_BAR_HANDLER = C2CShortcutBarHandler.class.getName();
    SECURITY_TOP_BAR = ModifyPwdTopBarHandler.class.getName();
    TROOP_NOTIFICATION_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopNotificationHandlerName();
    ANONYMOUS_ANSWER_HANDLER = AnonymousHandler.class.getName();
    TEENS_MODE_ALPHABETIC_FONT_HANDLER = AlphabeticFontHandler.class.getName();
    ILIVE_COMMON_HANDLER = IliveCommonHandler.class.getName();
    FILTER_MSG_BOX_HANDLER = ((ITempMsgBoxService)QRoute.api(ITempMsgBoxService.class)).getFilterMsgBoxHandlerName();
    PAI_YI_PAI_HANDLER = PaiYiPaiHandler.class.getName();
    QAV_WT_HANDLER = WatchTogetherHandler.class.getName();
    AVATAR_HANDLER = ((IQQAvatarHandlerApi)QRoute.api(IQQAvatarHandlerApi.class)).getClassName();
    DISCUSSION_AVATAR_HANDLER = DiscussionAvatarHandler.class.getName();
    TROOP_INFO_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopInfoHandlerName();
    TROOP_BATCH_INFO_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopBatchInfoHandlerName();
    TROOP_LIST_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopListHandlerName();
    TROOP_INFO_EXT_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopInfoExtHandlerName();
    TROOP_MODIFY_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopModifyHandlerName();
    TROOP_MEMBER_INFO_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopMemberInfoHandlerName();
    TROOP_MEMBER_LIST_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopMemberListHandlerName();
    TROOP_MEMBER_CARD_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopMemberCardHandlerName();
    TROOP_AVATAR_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopAvatarHandlerName();
    TROOP_PUSH_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopPushHandlerName();
    TROOP_MNG_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopMngHandlerName();
    TROOP_MANAGER_BIZ_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopManagerBizHandlerName();
    TROOP_SETTING_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopSettingHandlerName();
    TROOP_GAG_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopGagHandlerName();
    TROOP_PHOTO_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopPhotoHandlerName();
    TROOP_ROBOT_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopRobotHandlerName();
    TROOP_ESSENCE_MSG_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopEssenceHandlerName();
    TROOP_APP_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopAppHandlerName();
    TROOP_ADD_FRIEND_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopAddFriendHandlerName();
    TROOP_GAME_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopGameHandlerName();
    TROOP_MEMBER_MNG_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopMemberMngHandlerName();
    TROOP_MEMBER_LEVEL_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopMemberLevelHandlerName();
    TROOP_ONLINE_MEMBER_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopOnlineMemberHandlerName();
    TROOP_RECOMMEND_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopRecommendHandlerName();
    TROOP_CLOCKIN_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopClockInHandlerName();
    TROOP_LUCKY_CHARACTER_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopLuckyCharacterHandlerName();
    TROOP_TOKEN_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopTokenHandlerName();
    TROOP_ANNOUNCEMENT_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopAnnouncementHandlerName();
    TROOP_ASSOCIATION_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopAssociationHandlerName();
    TROOP_FANS_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopFansHandlerName();
    TROOP_ROAMSETTING_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopRoamSettingHandlerName();
    TROOP_COMMONLY_USED_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopCommonlyUsedHandlerName();
    TROOP_RED_DOT_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopRedDotHandlerName();
    TROOP_ONLINE_PUSH_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopOnlinePushHandlerName();
    TROOP_SURVEY_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopSurveyHandlerName();
    TROOP_SHOW_EXTERNAL_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopShowExternalHandlerName();
    TROOP_MESSAGE_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopMessageHandlerName();
    TROOP_FEE_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopFeeHandlerName();
    TROOP_AUDIT_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopAuditHandlerName();
    TROOP_CONFIG_HANDLER = ((ITroopHandlerNameApi)QRoute.api(ITroopHandlerNameApi.class)).getTroopConfigHandlerName();
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes7.jar
 * Qualified Name:     com.tencent.mobileqq.app.BusinessHandlerFactory
 * JD-Core Version:    0.7.0.1
 */