package com.tencent.mobileqq.app;

import android.text.TextUtils;
import com.tencent.avgame.util.AVGameCmdUtil;
import com.tencent.biz.qqstory.base.QQStoryHandler;
import com.tencent.common.app.BaseApplicationImpl;
import com.tencent.mobileqq.armap.ArMapConstant;
import com.tencent.mobileqq.kandian.glue.businesshandler.api.IRIJHandlerNameApi;
import com.tencent.mobileqq.nearby.NearbyConstants;
import com.tencent.mobileqq.pushdialog.SafeBlowHandler;
import com.tencent.mobileqq.qroute.QRoute;
import com.tencent.mobileqq.service.message.MessageConstants;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

public class Cmd2HandlerMap
{
  private static Object jdField_a_of_type_JavaLangObject = new Object();
  public static final String a = "com.tencent.mobileqq.app.Cmd2HandlerMap";
  private static Map<String, String[]> jdField_a_of_type_JavaUtilMap;
  private static Map<String, String[]> b;
  
  public static Map<String, String[]> a()
  {
    if (jdField_a_of_type_JavaUtilMap == null) {
      synchronized (jdField_a_of_type_JavaLangObject)
      {
        if (jdField_a_of_type_JavaUtilMap == null)
        {
          jdField_a_of_type_JavaUtilMap = new ConcurrentHashMap();
          if ((BaseApplicationImpl.sProcessId != 5) && (BaseApplicationImpl.sProcessId != 7))
          {
            if (BaseApplicationImpl.sProcessId == 12) {
              AVGameCmdUtil.a(jdField_a_of_type_JavaUtilMap);
            } else {
              e();
            }
          }
          else
          {
            c();
            a();
            b();
          }
        }
      }
    }
    return jdField_a_of_type_JavaUtilMap;
  }
  
  private static void a()
  {
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x95a", new String[] { ArMapConstant.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xb49", new String[] { ArMapConstant.b });
  }
  
  public static Map<String, String[]> b()
  {
    if (b == null) {
      synchronized (jdField_a_of_type_JavaLangObject)
      {
        if (b == null)
        {
          b = new ConcurrentHashMap();
          d();
        }
      }
    }
    return b;
  }
  
  private static void b()
  {
    jdField_a_of_type_JavaUtilMap.put(((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getVideoPlayRecommendHandlerCmd(), new String[] { "VideoPlayRecommendHandler" });
    jdField_a_of_type_JavaUtilMap.put(((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getVideoPlayCountHandlerCmd(), new String[] { "VideoPlayCountHandler." });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.CheckArticleLike", new String[] { "PublicAccountArticleHandler" });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.GetArticleLikeCount", new String[] { "PublicAccountArticleHandler" });
  }
  
  private static void c()
  {
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8dd", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("EncounterSvc.ReqGetEncounter", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("RoamClientSvr.GetQualify", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x66b", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("NeighborSvc.ReqGetPoint", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x686", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9c7_0", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4f0_0", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x6be", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xafc_1", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xafc_2", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xafc_3", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xada_0", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("MQ_nearby_sso_proxy.0x667_1", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("MQ_nearby_sso_proxy.0x3e8_1", new String[] { NearbyConstants.a });
    jdField_a_of_type_JavaUtilMap.put("MultibusidURLSvr.HeadUrlReq", new String[] { NearbyConstants.b });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x74b", new String[] { BusinessHandlerFactory.DYNAMIC_AVATAR_HANDLER });
  }
  
  private static void d()
  {
    b.put("ShadowBackendSvc.GetRecommandTextByEmotion", new String[] { PeakAppInterface.d });
    b.put("ShadowBackendSvc.GetTextValidStatus", new String[] { PeakAppInterface.d });
    b.put("ShadowBackendSvc.GetCategoryMaterial", new String[] { PeakAppInterface.d });
    b.put("ShadowBackendSvc.GetPlayShowCatMatTree", new String[] { PeakAppInterface.d });
    b.put("ShadowBackendSvc.GetCameraConfig", new String[] { PeakAppInterface.d });
    b.put("ShadowBackendSvc.GetOnlineUserNum", new String[] { PeakAppInterface.d });
    b.put("ShadowBackendSvc.GetFontData", new String[] { PeakAppInterface.d });
    b.put("ShadowBackendSvc.GetImgValidStatus", new String[] { PeakAppInterface.d });
    b.put("ShadowBackendSvc.GetBulkImageClassify", new String[] { PeakAppInterface.d });
    b.put("ShadowBackendSvc.GetCircleCatMatTree", new String[] { PeakAppInterface.e });
    b.put("ShadowBackendSvc.GetBigShowRecommend", new String[] { PeakAppInterface.e });
  }
  
  private static void e()
  {
    jdField_a_of_type_JavaUtilMap.put("ShadowBackendSvc.GetCategoryMaterial", new String[] { "com.tencent.aelight.camera.ae.config.CameraDataServiceHandler" });
    jdField_a_of_type_JavaUtilMap.put("ShadowBackendSvc.GetPlayShowCatMatTree", new String[] { "com.tencent.aelight.camera.ae.config.CameraDataServiceHandler" });
    jdField_a_of_type_JavaUtilMap.put("ShadowBackendSvc.GetCameraConfig", new String[] { "com.tencent.aelight.camera.ae.config.CameraDataServiceHandler" });
    jdField_a_of_type_JavaUtilMap.put("AccostSvc.SvrMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER, BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("AccostSvc.ClientMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER, BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("AccostSvc.ReqDeleteBlackList", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("AccostSvc.ReqInsertBlackList", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9db", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("AccostSvc.ReqGetBlackList", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ff_42024", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("TransService.ReqGetSign", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SharpSvr.s2c", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PbGetRoamMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.DelRoamMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PbMessageSvc.PbSearchRoamMsgInCloud", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SharpSvr.c2sack", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.RequestPushStatus", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StatSvc.SvcReqMSFLoginNotify", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ADMsgSvc.PushMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StreamSvr.PushStreamMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OnlinePush.ReqPush", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OnlinePush.PbPushTransMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OnlinePush.PbC2CMsgSync", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PbBindUinGetMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PbMessageSvc.PbBindUinMsgReadedConfirm", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5d0_1", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OnlinePush.PbPushDisMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PullGroupMsgSeq", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PbMessageSvc.PbUnReadMsgSeq", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PbGetOneDayRoamMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StreamSvr.RespUploadStreamMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("TransService.ReqOffFilePack", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PbGetGroupMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PbGetDiscussMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.DelMsgV2", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.SetRoamMsgAllUser", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OnlinePush.PbPushGroupMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OnlinePush.PbPushBindUinGroupMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OnlinePush.PbPushC2CMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("VideoCCSvc.Adaptation", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StreamSvr.UploadStreamMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MultiVideo.s2c", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearFieldTranFileSvr.NotifyList", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PbSendMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER, BusinessHandlerFactory.DATALINE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xa89", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PbMultiMsgSend", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SecSvcBlessingHelper.blessing_helper", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PushReaded", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OnlinePush.RespPush", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("TransService.ReqTmpChatPicDownload", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PbGetMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MultiVideo.c2sack", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PbMessageSvc.PbDelOneRoamMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PbMessageSvc.PbMsgWithDraw", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PushNotify", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.GetMsgV4", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.PullDisMsgSeq", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.PbGetMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.GetMsgV2", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.PbGetDiscussMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.PbGetGroupMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.PullDisGroupSeq", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.NoticeEnd", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.infoLogin", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.PullGroupMsgSeq", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.getOffMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.infoSync", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.PbSyncMsg", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.GetBoxFilter", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.Pb.ReqSystemMsgRead", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.Pb.ReqSystemMsgNew", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.Pb.ReqSystemMsgNew.Friend", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.Pb.ReqSystemMsgNew.Group", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.Pb.ReqSystemMsgAction", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PbMessageSvc.PbMsgReadedReport", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MessageSvc.PbReceiptRead", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xb31", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQRTCSvc.group_video_create_share_url", new String[] { BusinessHandlerFactory.QAV_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQRTCSvc.push_share_ark", new String[] { BusinessHandlerFactory.QAV_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQRTCSvc.share_backflow_check_group_can_join", new String[] { BusinessHandlerFactory.QAV_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQRTCSvc.group_video_share_backflow_verify", new String[] { BusinessHandlerFactory.QAV_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQRTCSvc.group_video_terminate_msg", new String[] { BusinessHandlerFactory.QAV_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("friendlist.delFriend", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("friendlist.SetGroupReq", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("friendlist.GetLastLoginInfoReq", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("friendlist.getFriendGroupList", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xaed_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("friendlist.MovGroupMemReq", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("friendlist.GetSimpleOnlineFriendInfoReq", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("BumpSvc.ReqComfirmContactFriend", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x777", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc34_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc34_1", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc83", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc85", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.GetSimpleInfo", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER, BusinessHandlerFactory.WEREWOLVES_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5d1_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4fc_30", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("DevLockAuthSvc.RecommendAuth", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("DevLockAuthSvc.ConfirmAuth", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xcf0_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SummaryCard.ReqSearch", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SummaryCard.ReqCondSearch", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x972_5", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("AvatarInfoSvr.QQHeadUrlReq", new String[] { "com.tencent.mobileqq.avatar.handler.AvatarHandler" });
    jdField_a_of_type_JavaUtilMap.put("StatSvc.register", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.GetRichSig", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StatSvc.DelDevLoginInfo", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StatSvc.BindUin", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StatSvc.SvcReqKikOut", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.CheckUpdateReq", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.ChangeFriendName", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.SetRichSig", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("IncreaseURLSvr.QQHeadUrlReq", new String[] { BusinessHandlerFactory.AVATAR_HANDLER, BusinessHandlerFactory.QCIRCLE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MultibusidURLSvr.HeadUrlReq", new String[] { BusinessHandlerFactory.AVATAR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MultibusidURLSvr.HeadUrlReq", new String[] { BusinessHandlerFactory.AVATAR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xedb", new String[] { BusinessHandlerFactory.AVATAR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StatSvc.GetDevLoginInfo", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("friendlist.GetOnlineInfoReq", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x49d_107", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x476_146", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x491_107", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x490_107", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x7c4_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4f4_5", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x7c6_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x7c7_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x847_3", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x53b_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x6c9_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x7df_3", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5d6_7", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5d6_18", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5d6_19", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x77c", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5d6_21", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc26_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc36_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc35_0", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5d6_21", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc26_1", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8b4", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("VisitorSvc.ReqFavorite", new String[] { BusinessHandlerFactory.CARD_HANLDER, BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8e6_1", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8e7_1", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x491_100", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("VisitorSvc.ReqGetVoterList", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("VisitorSvc.ReqGetFavoriteList", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("SummaryCard.ReqSummaryCard", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MCardSvc.ReqDelFace", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("MCardSvc.ReqGetCardSwitch", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("MCardSvc.ReqPicSafetyCheck", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("MCardSvc.ReqSetCard", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("MCardSvc.ReqSetCardSwitch", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x490_100", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("SummaryCard.SetLabel", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("SummaryCard.LikeIt", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("SQQzoneSvc.getCover", new String[] { BusinessHandlerFactory.CARD_HANLDER, BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x480_9", new String[] { BusinessHandlerFactory.QQSTORY_HANDLER, BusinessHandlerFactory.NEARBY_RELEVANT_HANDLER, BusinessHandlerFactory.GET_ROAMMESSAGE_HANDLER, BusinessHandlerFactory.REDTOUCH_HANDLER, BusinessHandlerFactory.FLASH_CHAT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ff_9", new String[] { BusinessHandlerFactory.QQSTORY_HANDLER, BusinessHandlerFactory.CARD_HANLDER, BusinessHandlerFactory.NEARBY_RELEVANT_HANDLER, BusinessHandlerFactory.GET_ROAMMESSAGE_HANDLER, BusinessHandlerFactory.FLASH_CHAT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5ea_2", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x82f_0", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x82f_0", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9ae_2", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_42092", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_40350", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x7ba", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("VisitorSvc.ReqDeleteVisitorRecord", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xd2d", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_42326", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("MusicSongInfoMatchSvc.songquery", new String[] { BusinessHandlerFactory.MUSIC_PLAYER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xb4b", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xb4b_6", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xb4c", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xb51", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xcb5", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xdb1", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xdb1_2", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe52_3", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe03", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe09", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe51", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe67", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xeae", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xeaf", new String[] { BusinessHandlerFactory.EXTEND_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xec9", new String[] { BusinessHandlerFactory.ANONYMOUS_ANSWER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xee5", new String[] { BusinessHandlerFactory.ANONYMOUS_ANSWER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xecf", new String[] { BusinessHandlerFactory.ANONYMOUS_ANSWER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xf15", new String[] { BusinessHandlerFactory.ANONYMOUS_ANSWER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearbyGroup.GetGroupList", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NeighborRecommender.ReqGetRecommender", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NeighborSvc.ReqGetSwitches", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NeighborSvc.ReqSetStateSwitch", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NeighborSvc.ReqGetPoint", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearbyGroup.ReqGetAreaList", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x7f5_1", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("LbsShareSvr.nearby_shops", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("LbsShareSvr.location", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("LbsShareSvr.get_shops_by_ids", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9c0_0", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9c1_0", new String[] { BusinessHandlerFactory.LBS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ConfigService.ClientReq", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ResourceConfig.GetResourceReq", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MobileTipsSvc.TipsReport", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MAAControl.CheckSinglePkgSig", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MAAControl.GetSinglePkgSig", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQServiceDiscussSvc.ReqGetDiscussInteRemark", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QRCodeSvc.discuss_geturl", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x58a", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQServiceDiscussSvc.ReqCreateDiscuss", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QRCodeSvc.discuss_decode", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQServiceDiscussSvc.ReqJoinDiscuss", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQServiceDiscussSvc.ReqSetDiscussFlag", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQServiceDiscussSvc.ReqChangeDiscussName", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQServiceDiscussSvc.ReqAddDiscussMember", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQServiceDiscussSvc.ReqSetDiscussAttr", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQServiceDiscussSvc.ReqGetDiscussInfo", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x58b_0", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQServiceDiscussSvc.ReqQuitDiscuss", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x865_3", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x870_4", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x870_5", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x921_0", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x751", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x44c", new String[] { BusinessHandlerFactory.DISCUSSION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QzoneService.GetNewAndUnread", new String[] { BusinessHandlerFactory.QZONENOTIFY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.PushParam", new String[] { BusinessHandlerFactory.REGPRXYSVCPACK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.infoAndroid", new String[] { BusinessHandlerFactory.REGPRXYSVCPACK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StatSvc.GetOnlineStatus", new String[] { BusinessHandlerFactory.REGPRXYSVCPACK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RegPrxySvc.QueryIpwdStat", new String[] { BusinessHandlerFactory.REGPRXYSVCPACK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("StatSvc.SetMute", new String[] { BusinessHandlerFactory.REGPRXYSVCPACK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("wtlogin_device.trans_emp", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("wtlogin_device.trans_reg", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_status.stat_reg", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_status.stat_hello", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_pullstatus.pull_status", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_msg.device_sharp", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_msg.multi_video", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_status.stat_forceoffline", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_msg.msg_send", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_push.msg_push", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_status.stat_queryhb", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x634", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x633", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x632", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x582", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x631", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x630", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x61e", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x61d", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x61f", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_msg.device_dataline", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_msg.openserver_req", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x60f", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x60d", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_msg.device_report", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_msg.get_bluetooth_info", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ConfigService.DeviceUp", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0x5e6", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("im_msg.open_smart_c2s", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ConfigPushSvc.RTOSReq", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0xac7", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QFindSvc.ReqReportMyDev", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QFindSvc.ReqClearTrack", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QFindSvc.ReqLostStatus", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc_device.0xa11", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QFindSvc.ReqReportDevs", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ConfigPushSvc.RTOSReq", new String[] { BusinessHandlerFactory.DEVICEPROXYMGR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PubAccountSvc.ReportLbs", new String[] { BusinessHandlerFactory.HANDLER_PUBLIC_ACCOUNT });
    jdField_a_of_type_JavaUtilMap.put("QQWeatherReport.getWeatherInfo", new String[] { BusinessHandlerFactory.HANDLER_PUBLIC_ACCOUNT });
    jdField_a_of_type_JavaUtilMap.put("BQMallSvc.TabOpReq", new String[] { BusinessHandlerFactory.HANDLER_EMOSM });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x490_92", new String[] { BusinessHandlerFactory.HANDLER_EMOSM });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_99", new String[] { BusinessHandlerFactory.HANDLER_EMOSM });
    jdField_a_of_type_JavaUtilMap.put("gxzbIpsit.ipsite", new String[] { BusinessHandlerFactory.HANDLER_EMOSM });
    jdField_a_of_type_JavaUtilMap.put("AvatarUpdate.checkUpdate", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("Font.fresh", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("FriendClone.CloneAuthStatus", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("groupnick.readitem", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("profilelogic.readUserInfo", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("profilelogic.setUserFlag", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("profilelogic.setUserProfile", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("FontBubbleRecommend.getFontRecommend", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("FontBubbleRecommend.getBubbleRecommend", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("GroupCare.getMessageRemindInfo", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("FontBubbleRecommend.setFontBubble", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RoamWrap.GetRoamToast", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("Face.setFace", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QCUniBusinessLogin.check", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileMusicBox.getMusicList", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileMusicBox.getQzoneMusicInfo", new String[] { BusinessHandlerFactory.SVIP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("FunCallSvr.call", new String[] { BusinessHandlerFactory.FUN_CALL_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("voiceChange.Auth", new String[] { BusinessHandlerFactory.CHANGE_VOICE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("AuthSvr.ThemeAuth", new String[] { BusinessHandlerFactory.THEME_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SpecialRemind.Service", new String[] { BusinessHandlerFactory.SPECIAL_CARE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ClubContentUpdate.Req", new String[] { BusinessHandlerFactory.CLUBCONTENTUPDATE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("apollo_content_update.Req", new String[] { BusinessHandlerFactory.APOLLO_CONTENT_UPDATE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SsoSnsSession.Cmd0x3_SubCmd0x3_FuncDelBlockList", new String[] { BusinessHandlerFactory.SHIELD_LIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SsoSnsSession.Cmd0x3_SubCmd0x1_FuncGetBlockList", new String[] { BusinessHandlerFactory.SHIELD_LIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SsoSnsSession.Cmd0x3_SubCmd0x2_FuncAddBlockList", new String[] { BusinessHandlerFactory.SHIELD_LIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("mq_crm.get_menu", new String[] { BusinessHandlerFactory.ENTERPRISEQQ_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("mq_crm.send_key", new String[] { BusinessHandlerFactory.ENTERPRISEQQ_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("EqqAccountSvc.get_eqq_list", new String[] { BusinessHandlerFactory.ENTERPRISEQQ_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("CrmSvcEx.ReportLbs", new String[] { BusinessHandlerFactory.ENTERPRISEQQ_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("GroupFileAppSvr.DelFile", new String[] { BusinessHandlerFactory.TROOP_FILE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("GroupFileAppSvr.GetFileInfo", new String[] { BusinessHandlerFactory.TROOP_FILE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("GroupFileAppSvr.GetFileSearch", new String[] { BusinessHandlerFactory.TROOP_FILE_HANDLER, BusinessHandlerFactory.QAV_WT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("GroupFileAppSvr.GetFileList", new String[] { BusinessHandlerFactory.TROOP_FILE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("GroupFileAppSvr.GetFileListV2", new String[] { BusinessHandlerFactory.TROOP_FILE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ClubInfoSvc.queryPrivExt", new String[] { BusinessHandlerFactory.VIPINFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ClubInfoSvc.guanjiaReport", new String[] { BusinessHandlerFactory.VIPINFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("VipCustom.GetCustomOnlineStatus", new String[] { BusinessHandlerFactory.VIPINFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QCUniBusinessLogic.uniSet", new String[] { BusinessHandlerFactory.VIPINFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QCUniBusinessLogic.uniGet", new String[] { BusinessHandlerFactory.VIPINFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RedTouchSvc.EntranceSetting", new String[] { BusinessHandlerFactory.LEBA_SETTING_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SecuritySvc.GetConfig", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("DevLockAuthSvc.WxMsgOpt", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("DevLockSecSvc.DevLockQuery", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x614_1", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xa13", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ad", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SecuritySvc.AlertReport", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MobileQQprotect.QPUpdate", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MobileQQprotect.QSecCb", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QSec.AVEng", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xeb8", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xebd", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xec0", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MamonoSvc.Pa", new String[] { BusinessHandlerFactory.SEC_SVC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SecCheckSigSvc.UploadReq", new String[] { BusinessHandlerFactory.STARTAPPCHECK_HANDLER, BusinessHandlerFactory.MSF_NET_TRANSPORT_PROVIDER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SecSafeChkSvc.MainCmd", new String[] { BusinessHandlerFactory.MSF_NET_TRANSPORT_PROVIDER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SecIntChkSvc.MainCmd", new String[] { BusinessHandlerFactory.MSF_NET_TRANSPORT_PROVIDER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearFieldDiscussSvr.ReqJoinDiscuss", new String[] { BusinessHandlerFactory.NEARFIELD_DISCUSS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearFieldDiscussSvr.ReqGetList", new String[] { BusinessHandlerFactory.NEARFIELD_DISCUSS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearFieldDiscussSvr.ReqExit", new String[] { BusinessHandlerFactory.NEARFIELD_DISCUSS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearFieldDiscussSvr.NotifyList", new String[] { BusinessHandlerFactory.NEARFIELD_DISCUSS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("hrtxformqq.getUsrSimpleInfo", new String[] { BusinessHandlerFactory.BMQQ_BUSINESS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQWalletPayAuthServer.checkChangePwdAuth", new String[] { BusinessHandlerFactory.QWALLET_AUTH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("WalletGestureSvc.GetPassword", new String[] { BusinessHandlerFactory.QWALLET_AUTH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("VacThirdCodeSvc.fetchCodes", new String[] { BusinessHandlerFactory.QWALLET_AUTH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QWalletPfa.RecFriend", new String[] { BusinessHandlerFactory.QWALLET_AUTH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("VipSTCheckServer.UinPay", new String[] { BusinessHandlerFactory.UNI_PAY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ComicProtoConvSvr.tunnel", new String[] { BusinessHandlerFactory.MQQ_COMIC_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QcallOidbSvc.0x5e3_1", new String[] { BusinessHandlerFactory.QCALLCARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("Background.checkAuth", new String[] { BusinessHandlerFactory.CHATBG_AUTH });
    jdField_a_of_type_JavaUtilMap.put("red_touch_num_svr.get_num_msg", new String[] { BusinessHandlerFactory.NUMREDMSG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(MessageConstants.D, new String[] { BusinessHandlerFactory.REDPOINT_HANDER });
    jdField_a_of_type_JavaUtilMap.put("VipPayLogicServer.getCommPayInfo ", new String[] { BusinessHandlerFactory.VIPRECOMMENDPAY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QPayReminderSvc.query_over_due_info", new String[] { BusinessHandlerFactory.QPAY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearfieldGroupSvr.ReqGetGroupList", new String[] { BusinessHandlerFactory.NEARFIELD_TROOP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearfieldGroupSvr.ReqExit", new String[] { BusinessHandlerFactory.NEARFIELD_TROOP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearfieldGroupSvr.ReqJoinGroup", new String[] { BusinessHandlerFactory.NEARFIELD_TROOP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("Loginauth.1", new String[] { BusinessHandlerFactory.PPC_LOGIN_AUTH });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x42e_3", new String[] { BusinessHandlerFactory.GET_ROAMMESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5cf_0", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5cf_1", new String[] { BusinessHandlerFactory.MESSAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9c9_0", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9c9_1", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xb5b", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9c5_0", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9c8_0", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9c7_0", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x9e4_22", new String[] { BusinessHandlerFactory.NEARBY_RELEVANT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x682", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.1081", new String[] { BusinessHandlerFactory.SUBSCRIPT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x472", new String[] { BusinessHandlerFactory.SUBSCRIPT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ff_41993", new String[] { BusinessHandlerFactory.NEARBY_RELEVANT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5fc_0", new String[] { BusinessHandlerFactory.NEARBY_RELEVANT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("bubble.1", new String[] { BusinessHandlerFactory.BUBBLE_DIYTEXT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("Faceroam.OpReq", new String[] { BusinessHandlerFactory.FAVEMO_ROAMING_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xdc4", new String[] { BusinessHandlerFactory.FAVEMO_ROAMING_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xdcf", new String[] { BusinessHandlerFactory.FAVEMO_ROAMING_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SelfGif.Op", new String[] { BusinessHandlerFactory.CAMERA_EMOTICON_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x438", new String[] { BusinessHandlerFactory.QWALLET_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x66b", new String[] { BusinessHandlerFactory.CARD_HANLDER, BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x682", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x686", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5ea_1", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5ea_3", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5ea_4", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5ea_6", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5ea_7", new String[] { BusinessHandlerFactory.NEARBY_CARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("MQKanDianSvc.0x001", new String[] { BusinessHandlerFactory.GLOBAL_SEARCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(VIPAioSendHandler.a, new String[] { BusinessHandlerFactory.VIP_AIO_SEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(VIPAioSendHandler.b, new String[] { BusinessHandlerFactory.VIP_AIO_SEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x59f", new String[] { BusinessHandlerFactory.LOGIN_WELCOME_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.WpaAssignKfext", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.clickReplyCmd", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.getUserDetailInfo", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.verifyWpaAndKey", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.getShieldStatus", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.blockBulkMsg", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.getCustomerTransferInfo", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.getNavigationConfig", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.corpUinWpaReport", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.fetchCorpDetailInfo", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x7e7_0", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.emanClickReport", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.closeAIOSessionReport", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.WpaGenSigMsg", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.webimAddFriend", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QidianSsoProto.getQidianGroupInfo", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x782", new String[] { BusinessHandlerFactory.QIDIAN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SQQShopCliLog.RtReport", new String[] { BusinessHandlerFactory.EC_SHOP_REPORT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SQQShopMsgSvc.GetRichMsgInfo", new String[] { BusinessHandlerFactory.EC_SHOP_REPORT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("SQQShopCliLog.AdFeedback", new String[] { BusinessHandlerFactory.EC_SHOP_REPORT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("EncounterSvc.ReqGetEncounter", new String[] { BusinessHandlerFactory.NEARBY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8dd", new String[] { BusinessHandlerFactory.NEARBY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x6cf", new String[] { BusinessHandlerFactory.VIDEOPLAYRECOMMEND_HANDLER, BusinessHandlerFactory.READINJOY_AD_MATERIAL_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x6a6", new String[] { BusinessHandlerFactory.VIDEOPLAYCOUNT_HANDLER, BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8c8", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_DIANZAN });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x83e", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_DIANZAN });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc13", new String[] { BusinessHandlerFactory.ENCRYPT_UIN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xb73", new String[] { BusinessHandlerFactory.VIDEO_FEEDS_LIKE_ANIMATION_CONFIG });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc15", new String[] { BusinessHandlerFactory.VIDEO_FEEDS_BARRAGE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.ArticleLike", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.CheckArticleLike", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.GetArticleLikeCount", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.CreateArticleComment", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.GetArticleCommentCount", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.PictureInfo", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.GetRecommendInfo", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PubAccountArticleCenter.GalleryReport", new String[] { BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.cmd0x6cd", new String[] { BusinessHandlerFactory.REDTOUCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.cmd0x6ce", new String[] { BusinessHandlerFactory.REDTOUCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.cmd0x6f5", new String[] { BusinessHandlerFactory.REDTOUCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x77d_0", new String[] { BusinessHandlerFactory.BABY_Q_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8db_0", new String[] { BusinessHandlerFactory.BABY_Q_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x74b", new String[] { BusinessHandlerFactory.DYNAMIC_AVATAR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8f0", new String[] { BusinessHandlerFactory.PROFILE_PERSONALITY_LABEL });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x91d", new String[] { BusinessHandlerFactory.PROFILE_PERSONALITY_LABEL });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x909", new String[] { BusinessHandlerFactory.PROFILE_PERSONALITY_LABEL });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x90c", new String[] { BusinessHandlerFactory.PROFILE_PERSONALITY_LABEL });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8f3", new String[] { BusinessHandlerFactory.PROFILE_PERSONALITY_LABEL });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x8f1", new String[] { BusinessHandlerFactory.PROFILE_PERSONALITY_LABEL });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.a, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.c, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.e, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.b, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.d, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.f, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.h, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.i, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.j, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.k, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.l, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.m, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ff_42073", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_42073", new String[] { BusinessHandlerFactory.CONFIG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("gxhreport.report", new String[] { BusinessHandlerFactory.VAS_MONITOR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("HttpConn.0x6ff_501", new String[] { BusinessHandlerFactory.BIG_DATA_GET_IP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x922", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe26", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xa28", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xac6", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x7a8", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("trpc.qqshop.adpush.PushService.GetAd", new String[] { BusinessHandlerFactory.ESHOP_AD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("trpc.qqshop.adreport.ReportService.AdReport", new String[] { BusinessHandlerFactory.ESHOP_AD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("dynamic_tab_search.1", new String[] { BusinessHandlerFactory.UNIFY_SEARCH_UNITE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("UnifySearch.BusiHotWord", new String[] { BusinessHandlerFactory.UNIFY_SEARCH_UNITE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("UnifySearch.Unite", new String[] { BusinessHandlerFactory.UNIFY_SEARCH_UNITE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("UnifySearch.AssociationWord", new String[] { BusinessHandlerFactory.UNIFY_SEARCH_UNITE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("UnifySearch.Tab", new String[] { BusinessHandlerFactory.UNIFY_SEARCH_UNITE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("UnifySearch.Discovery", new String[] { BusinessHandlerFactory.UNIFY_SEARCH_UNITE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("dynamic_tab_search.1", new String[] { BusinessHandlerFactory.UNITE_SEARCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("dynamic_busi_hot_word.1", new String[] { BusinessHandlerFactory.UNITE_SEARCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("dynamic_unite_search.1", new String[] { BusinessHandlerFactory.UNITE_SEARCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("dynamic_association_word.1", new String[] { BusinessHandlerFactory.UNITE_SEARCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("qb_association_word.1", new String[] { BusinessHandlerFactory.UNITE_SEARCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("DynamicScDiscovery.1", new String[] { BusinessHandlerFactory.UNITE_SEARCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("qb_discovery.1", new String[] { BusinessHandlerFactory.UNITE_SEARCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xd78_0", new String[] { BusinessHandlerFactory.UNITE_SEARCH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ReadDiyAddonInfo.1", new String[] { BusinessHandlerFactory.DIY_PENDANT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put(QQStoryHandler.n, new String[] { BusinessHandlerFactory.QQSTORY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("TimDocSvc.GetPadRightInfo", new String[] { BusinessHandlerFactory.TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("TimDocSvc.SetPadRightInfo", new String[] { BusinessHandlerFactory.TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("TimDocSvc.GetSharedPadList", new String[] { BusinessHandlerFactory.TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xbab_1", new String[] { BusinessHandlerFactory.TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xbab_2", new String[] { BusinessHandlerFactory.TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xbab_3", new String[] { BusinessHandlerFactory.TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xbab_4", new String[] { BusinessHandlerFactory.TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.cmd0xb67", new String[] { BusinessHandlerFactory.CONFESS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NowGetRecordInfoSvr.get_record_info", new String[] { BusinessHandlerFactory.NOW_PROXY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.cmd0xbc3", new String[] { BusinessHandlerFactory.CONFESS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xbe8", new String[] { BusinessHandlerFactory.CONTACT_BIND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xbf2", new String[] { BusinessHandlerFactory.CONTACT_BIND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("WifiCloudCheckSvc.req", new String[] { BusinessHandlerFactory.WIFI_SDK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc33_42220", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_22", new String[] { BusinessHandlerFactory.CARD_HANLDER, BusinessHandlerFactory.CARD_SETTING_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_15", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xae9_1", new String[] { BusinessHandlerFactory.GROUP_TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xaef_1", new String[] { BusinessHandlerFactory.GROUP_TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xaee", new String[] { BusinessHandlerFactory.GROUP_TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xaea_1", new String[] { BusinessHandlerFactory.GROUP_TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xaf3_1", new String[] { BusinessHandlerFactory.GROUP_TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xaf3_2", new String[] { BusinessHandlerFactory.GROUP_TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xae9_2", new String[] { BusinessHandlerFactory.GROUP_TEAM_WORK_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc7a", new String[] { BusinessHandlerFactory.APPLET_PUSH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc76", new String[] { BusinessHandlerFactory.APPLET_PUSH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc96", new String[] { BusinessHandlerFactory.APPLET_PUSH_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xcd4", new String[] { BusinessHandlerFactory.INPUT_STATUS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_42261", new String[] { BusinessHandlerFactory.INPUT_STATUS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ff_42261", new String[] { BusinessHandlerFactory.INPUT_STATUS_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xcd5", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xc05", new String[] { BusinessHandlerFactory.OPEN_AGENT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xccd", new String[] { BusinessHandlerFactory.OPEN_AGENT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xf26", new String[] { BusinessHandlerFactory.OPEN_AGENT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xcf3", new String[] { BusinessHandlerFactory.INTIMATE_INFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xcf4", new String[] { BusinessHandlerFactory.INTIMATE_INFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe3e", new String[] { BusinessHandlerFactory.INTIMATE_INFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("PluginConfig.dynamic_plugin", new String[] { BusinessHandlerFactory.COMMPLGUGIN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xd8a", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ff_42315", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_SimpleUI", new String[] { BusinessHandlerFactory.SIMPLE_UI_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xed1_SimpleUI", new String[] { BusinessHandlerFactory.SIMPLE_UI_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xd45", new String[] { BusinessHandlerFactory.INTIMATE_INFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xcf4_1", new String[] { BusinessHandlerFactory.INTIMATE_INFO_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xd4a", new String[] { BusinessHandlerFactory.INTIMATE_INFO_HANDLER });
    String str = ((IRIJHandlerNameApi)QRoute.api(IRIJHandlerNameApi.class)).getVideoColumnSubscribeHandlerCmd();
    if (!TextUtils.isEmpty(str)) {
      jdField_a_of_type_JavaUtilMap.put(str, new String[] { BusinessHandlerFactory.COLUMN_SUBSCRIBE_HANDLER });
    }
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.get_latest_playing_state", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER, BusinessHandlerFactory.TOGETHER_OPERATOR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.create_room", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER, BusinessHandlerFactory.TOGETHER_OPERATOR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.heartbeat", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER, BusinessHandlerFactory.TOGETHER_OPERATOR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.get_song_extended_info", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.media_operation", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.room_operation", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.get_play_show_info", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.share_trans_check", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.share_trans", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.report_download_fail", new String[] { BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQLBSShareSvc.room_operation", new String[] { BusinessHandlerFactory.LOCATION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQLBSShareSvc.report_location", new String[] { BusinessHandlerFactory.LOCATION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQLBSShareSvc.assembly_point_operation", new String[] { BusinessHandlerFactory.LOCATION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQLBSShareSvc.room_query", new String[] { BusinessHandlerFactory.LOCATION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xd79", new String[] { BusinessHandlerFactory.PARTICIPLE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xd69", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xd72", new String[] { BusinessHandlerFactory.FRIENDLIST_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xcdd", new String[] { BusinessHandlerFactory.MSG_BACK_UP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xcde", new String[] { BusinessHandlerFactory.MSG_BACK_UP_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_15(2)", new String[] { BusinessHandlerFactory.CARD_HANLDER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xdc9", new String[] { BusinessHandlerFactory.TROOP_HONOR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.oidb_0xdcc", new String[] { BusinessHandlerFactory.TROOP_MEMBER_RECOMMED_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.get_dynamic_info", new String[] { BusinessHandlerFactory.TOGETHER_OPERATOR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQAIOMediaSvc.VideoWrite", new String[] { BusinessHandlerFactory.TOGETHER_OPERATOR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_cn_switch", new String[] { BusinessHandlerFactory.COLOR_NOTE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ff_cn_switch", new String[] { BusinessHandlerFactory.COLOR_NOTE_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearFieldFriendSvr.ReqEnter", new String[] { BusinessHandlerFactory.FACE2FACE_ADD_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearFieldFriendSvr.ReqExit", new String[] { BusinessHandlerFactory.FACE2FACE_ADD_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("NearFieldFriendSvr.ReqHeartBeat", new String[] { BusinessHandlerFactory.FACE2FACE_ADD_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe82", new String[] { BusinessHandlerFactory.TROOP_SHORTCUTBAR_HANDLE });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe0e", new String[] { BusinessHandlerFactory.TROOP_SHORTCUTBAR_HANDLE });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe27", new String[] { BusinessHandlerFactory.QQ_DAILY_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xd68", new String[] { BusinessHandlerFactory.FAV_ONLINE_FILE_FORWARD_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("DynamicPluginSvc.GetList", new String[] { BusinessHandlerFactory.COMMPLGUGIN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("DynamicPluginSvc.SetList", new String[] { BusinessHandlerFactory.COMMPLGUGIN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x6e1_1", new String[] { BusinessHandlerFactory.TOFUMSG_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x587_74", new String[] { BusinessHandlerFactory.CARD_SETTING_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe8c", new String[] { BusinessHandlerFactory.ONE_WAY_FRIEND_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe9c_1", new String[] { BusinessHandlerFactory.RELATED_EMOTION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x484_15", new String[] { BusinessHandlerFactory.QUICK_LOGIN });
    jdField_a_of_type_JavaUtilMap.put("OidbSvcTcp.0xea3", new String[] { BusinessHandlerFactory.TROOP_SHORTCUTBAR_HANDLE });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.oidb_0xeb5", new String[] { BusinessHandlerFactory.C2C_SHORTCUT_BAR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.oidb_0xd51", new String[] { BusinessHandlerFactory.C2C_SHORTCUT_BAR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.oidb_0x587", new String[] { BusinessHandlerFactory.C2C_SHORTCUT_BAR_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_42483", new String[] { BusinessHandlerFactory.TEENS_MODE_ALPHABETIC_FONT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ff_42483", new String[] { BusinessHandlerFactory.TEENS_MODE_ALPHABETIC_FONT_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_42482", new String[] { BusinessHandlerFactory.COMMPLGUGIN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x4ff_42482", new String[] { BusinessHandlerFactory.COMMPLGUGIN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("RedTouchSvc.BatchSetSetting", new String[] { BusinessHandlerFactory.COMMPLGUGIN_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_troopnotifycation", new String[] { BusinessHandlerFactory.TROOP_NOTIFICATION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x668", new String[] { BusinessHandlerFactory.TROOP_NOTIFICATION_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvcTcp.0xe89_0", new String[] { BusinessHandlerFactory.WRITE_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvcTcp.0xe89_1", new String[] { BusinessHandlerFactory.WRITE_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvcTcp.0xe89_2", new String[] { BusinessHandlerFactory.WRITE_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe95", new String[] { BusinessHandlerFactory.WRITE_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xe94", new String[] { BusinessHandlerFactory.WRITE_TOGETHER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xed3", new String[] { BusinessHandlerFactory.PAI_YI_PAI_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xf51", new String[] { BusinessHandlerFactory.PAI_YI_PAI_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x5eb_fst", new String[] { BusinessHandlerFactory.FILE_ASSIST_TOP });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.oidb_0x587_fst", new String[] { BusinessHandlerFactory.FILE_ASSIST_TOP });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xecc_0", new String[] { BusinessHandlerFactory.SECURITY_TOP_BAR });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0x59f_newer_guide_banner", new String[] { BusinessHandlerFactory.NEWER_GUIDE_BANNER_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("QQLive.GetLiveGroupTips", new String[] { BusinessHandlerFactory.ILIVE_COMMON_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("OidbSvc.0xefe", new String[] { BusinessHandlerFactory.FILTER_MSG_BOX_HANDLER, SafeBlowHandler.a });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.ReqGetSettings", new String[] { BusinessHandlerFactory.TROOP_ROAMSETTING_HANDLER });
    jdField_a_of_type_JavaUtilMap.put("ProfileService.ReqSetSettings", new String[] { BusinessHandlerFactory.TROOP_ROAMSETTING_HANDLER });
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes5.jar
 * Qualified Name:     com.tencent.mobileqq.app.Cmd2HandlerMap
 * JD-Core Version:    0.7.0.1
 */