package com.tencent.mobileqq.app;

import aalt;
import aclo;
import afno;
import afsl;
import afza;
import ahqp;
import ahud;
import aiin;
import aimn;
import aioi;
import aipw;
import ajco;
import akqe;
import akqv;
import akrc;
import aktz;
import akyj;
import alkd;
import alku;
import amee;
import amma;
import ammz;
import amnd;
import amog;
import anch;
import android.util.SparseArray;
import ankc;
import anly;
import anrz;
import ansj;
import anty;
import anui;
import anvk;
import anwv;
import anxc;
import anxs;
import anzc;
import anzp;
import aobp;
import aocd;
import aoce;
import aode;
import aodf;
import aodp;
import aoke;
import aokt;
import aoxx;
import aozl;
import aozr;
import apbf;
import apcq;
import apgi;
import aqdg;
import aqgh;
import aqjm;
import aqlp;
import aqnd;
import aqni;
import arpr;
import arqo;
import arxv;
import asaa;
import aseg;
import asen;
import aseo;
import asey;
import asfk;
import asfl;
import asgo;
import asih;
import atix;
import aumk;
import auuc;
import auzd;
import avaq;
import avds;
import avhf;
import avhp;
import avji;
import avkh;
import avmh;
import avqv;
import avrk;
import avuq;
import avux;
import avwp;
import avwq;
import avxv;
import awnx;
import awra;
import awtc;
import awtl;
import awtn;
import awto;
import awtp;
import awtq;
import awtu;
import awxj;
import awyg;
import awyq;
import awyr;
import awzf;
import axel;
import axgu;
import axia;
import axig;
import axii;
import axjk;
import axlz;
import axnt;
import axny;
import axoe;
import axpb;
import axpp;
import axtf;
import aydj;
import ayks;
import ayow;
import ayrg;
import azaz;
import azcb;
import azil;
import azod;
import azph;
import azvc;
import azzr;
import bahk;
import bahy;
import baif;
import baki;
import bakx;
import bapa;
import baql;
import bazf;
import bazk;
import bbbl;
import bbcx;
import bbdh;
import bben;
import bbob;
import bboo;
import bbvn;
import bbyl;
import bbzs;
import bcha;
import bcpl;
import bdjw;
import bdjy;
import bdts;
import bdvz;
import becf;
import bedr;
import beed;
import befl;
import beim;
import bejk;
import benm;
import bfbz;
import bfge;
import bfgz;
import bfkw;
import bflc;
import bfox;
import bfyc;
import bgbg;
import bgbv;
import bgfr;
import bgfx;
import bggl;
import bghm;
import bghx;
import bgie;
import bgig;
import bgko;
import bglo;
import bgmk;
import bgth;
import bgwd;
import bhml;
import bhnl;
import bhom;
import bhon;
import bhou;
import bhwz;
import bibh;
import bicd;
import bidm;
import bkvt;
import blqh;
import blrh;
import blsk;
import bluc;
import blvf;
import blvy;
import bmeh;
import bmfv;
import com.tencent.biz.qqstory.takevideo.artfilter.ArtFilterManager;
import com.tencent.common.app.AppInterface;
import com.tencent.mobileqq.activity.aio.AudioDeviceManager;
import com.tencent.mobileqq.activity.aio.MediaPlayerManager;
import com.tencent.mobileqq.activity.aio.stickerrecommended.scenesrecommend.ScenesRecommendManager;
import com.tencent.mobileqq.activity.qwallet.preload.PreloadManager;
import com.tencent.mobileqq.apollo.ApolloResManager;
import com.tencent.mobileqq.ark.ArkAppCenter;
import com.tencent.mobileqq.business.sougou.WordMatchManager;
import com.tencent.mobileqq.data.MsgBoxInterFollowManager;
import com.tencent.mobileqq.data.QQEntityManagerFactory;
import com.tencent.mobileqq.emoticonview.CommonUsedSystemEmojiManager;
import com.tencent.mobileqq.jsp.FaceDetectForThirdPartyManager;
import com.tencent.mobileqq.medalwall.MedalWallMng;
import com.tencent.mobileqq.microapp.apkg.UsedAppListManager;
import com.tencent.mobileqq.mini.apkgEntity.MiniAppEntityManager;
import com.tencent.mobileqq.mini.entry.MiniAppLocalSearchManager;
import com.tencent.mobileqq.mini.entry.MiniAppUserAppInfoListManager;
import com.tencent.mobileqq.mini.entry.search.data.MiniAppSearchDataManager;
import com.tencent.mobileqq.olympic.OlympicManager;
import com.tencent.mobileqq.portal.PortalManager;
import com.tencent.mobileqq.profile.like.PraiseManager;
import com.tencent.mobileqq.shortvideo.ShortVideoResourceManager;
import com.tencent.mobileqq.troop.widget.UsingTimeReportManager;
import com.tencent.mobileqq.upgrade.UpgradeTIMManager;
import com.tencent.mobileqq.utils.BusinessCommonConfig;
import com.tencent.mobileqq.vas.AvatarPendantManager;
import com.tencent.mobileqq.webprocess.WebProcessManager;
import com.tencent.qphone.base.util.QLog;
import cooperation.photoplus.PhotoPlusManager;
import cooperation.qqcircle.lbs.QcircleLbsService;
import cooperation.qzone.contentbox.QZoneMsgManager;
import cooperation.qzone.plugin.QZonePluginManager;
import cooperation.troop.TroopPluginManager;
import gb;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import lui;
import mqq.app.AccountManagerImpl;
import mqq.app.AppRuntime;
import mqq.app.ProxyIpManagerImpl;
import mqq.manager.Manager;
import ntw;
import oay;
import ofd;
import oht;
import opx;
import pmy;
import pvp;
import rmt;
import rmu;
import rna;
import sad;
import sqm;
import uhx;
import uic;
import use;
import vzt;
import wmr;
import zcj;
import zmv;

public final class QQManagerFactory
{
  public static final int ACCOUNTDPC_MANAGER;
  public static final int ACCOUNT_DETAIL_DYNAMIC_DATA_MANAGER;
  public static final int ACT_DAU_REPORT_MANAGER;
  public static final int ADDCONTACT_TROOP_SEARCH_POP_MANAGE;
  public static final int AIO_ANIMATION_MANAGER;
  public static final int AIO_GROUP_APPS_MANAGER;
  public static final int AIO_INPUT_STATUS_MANAGER;
  public static final int AIO_MULTI_WINDOW_MANAGER;
  public static final int AIO_PANEL_MINI_APP_MANAGER;
  public static final int ANONYMOUS_ANSWER_MANAGER;
  public static final int APKG_CONFIG_MANAGER;
  public static final int APOLLO_GAME_MANAGER;
  public static final int APOLLO_MANAGER;
  public static final int APOLLO_NATIVE_SSO_MANAGER;
  public static final int APOLLO_PUSH_MANAGER;
  public static final int APOLLO_RECENTMANAGER;
  public static final int APOLLO_RESPONSE_MANAGER;
  public static final int APOLLO_RES_MANAGER;
  public static final int APOOLO_DAO_MANAGER;
  public static final int APPLETS_ACCOUNT_MANAGER;
  public static final int APP_GUIDE_TIPS_MANAGER;
  public static final int ARK_APP_CENTER_MANAGER;
  public static final int ARMAP_RES_DOWNLOAD;
  public static final int ARPROMOTION_MANAGER;
  public static final int ART_FILTER_MANAGER;
  public static final int AR_CLOBAL_CONFIG_MANAGER;
  public static final int AR_RESOURCE_MANAGER;
  public static final int AUDIO_DEVICE_MANAGER;
  public static final int AUTO_REPLY_MANAGER;
  public static final int AV_GAME_MANAGER;
  public static final int AV_REDPACKET_CONFIG_MGR;
  public static final int BANNER_LISTENER_MANAGER;
  public static final int BEANCURD_MANAGER;
  public static final int BUSINESS_CARD_MANAGER;
  public static final int BUSINESS_COMMON_CONFIG_MANAGER;
  public static final int BUSINESS_WORD_MATCH_MANAGER;
  public static final int C2C_SHORTCUT_BAR_MANAGER;
  public static final int CACHE_MANAGER;
  public static final int CAMERA_EMOTION_DB_MANAGER;
  public static final int CAMERA_EMOTION_MANAGER;
  public static final int CAMPUS_NOTICE_MANAGER;
  public static final int CHAT_AVATAR_PENDANT_MANAGER;
  public static final int CHAT_BACKGROUND_MANAGER;
  public static final int CHAT_BUBBLE_MANAGER;
  public static final int CHAT_EMOTION_MANAGER;
  public static final int CHAT_FONT_MANAGER;
  public static final int CHECK_FORWARD_MANAGER;
  public static final int CLASSIC_HEAD_ACIVITY_MANAGER;
  public static final int COLOR_RING_MANAGER;
  public static final int COMIC_RED_TOUCH_MANAGER;
  public static final int COMMERCIAL_DRAINAGE_MANAGER;
  public static final int COMMONUSED_SYSTEM_EMOJI_MANAGERT;
  public static final int CONDITION_SEARCH_MANAGER;
  public static final int CONFESS_MANAGER;
  public static final int CONTACT_FACADE;
  public static final int CONTACT_MANAGER;
  public static final int CONVS_FACADE;
  public static final int COPY_PROMPT_MANAGER;
  public static final int COUNT_MANAGER;
  public static final int CTENTRY_MNG;
  public static final int CUSTOMIZE_GRAY_TIPS;
  public static final int CU_OPEN_CARD_GUIDE_MANAGER;
  public static final int DATING_PROXY_MANAGER;
  public static final int DB_FIX_MANAGER;
  public static final int DISCUSSION_MANAGER;
  public static final int DOUTU_MAGAGER;
  public static final int DOWNLOADER_FACTORY;
  public static final int DYNAMIC_AVATAR_MANAGER;
  public static final int EARLY_DOWNLOAD_MANAGER;
  public static final int EC_SHOP_ASSISTANT_MANAGER;
  public static final int EMOFROMGROUP_DB_MANAGER;
  public static final int EMOTICON_MANAGER;
  public static final int EMOTION_SEARCH_MANAGER;
  public static final int EQQ_DETAIL_DATA_MANAGER;
  public static final int EXTEND_FRIEND_LIMIT_CHAT_MANAGER;
  public static final int EXTEND_FRIEND_MANAGER;
  public static final int FACE_MANAGER;
  public static final int FACE_SCORE_MANAGER;
  public static final int FAVROAMING_DB_MANAGER;
  public static final int FAV_ROAMING_MANAGER;
  public static final int FETCH_OPENID_MANAGER;
  public static final int FLASH_CHAT_MANAGER;
  public static final int FOREGROUND_NOTIFY_MANAGER;
  public static final int FORWARD_MSG_MANAGER;
  public static final int FRIENDS_MANAGER;
  public static final int FRIEND_CLUE_MANAGER;
  public static final int FRONT_BACK_REPORT_MANAGER;
  public static final int FTSDB_MANAGER;
  public static final int FULL_MESSAGE_SEARCH_MANAGER;
  public static final int FUNCTION_MODULE_MANAGER;
  public static final int GAMECENTER_MANAGER;
  public static final int GAME_CENTER_MSG_MANAGER;
  public static final int GAME_PARTY_MANAGER;
  public static final int GROUP_TEAM_WORK_MANAGER;
  public static final int GROUP_VIDEO_PLUGIN_MANAGER;
  public static final int HCE_PLUGIN_MANAGER;
  public static final int HIBOOM_MANAGER;
  public static final int HIDDENCHAT_MANAGER;
  public static final int HOTCHAT_CENTER_MANAGER;
  public static final int HOTCHAT_PKACTIVITY_MANAGER;
  public static final int HOTCHAT_SCENE_CONFIG_MANAGER;
  public static final int HOT_CHAT_MANAGER;
  public static final int HOT_PIC_MANAGER;
  public static final int ICE_BREAKING_MNG;
  public static final int ILIVE_GROUP_TIPS_MANAGER;
  public static final int IMAGE_UPLOAD_MANAGER;
  public static final int IMAX_AD_VIDEO_PRELOAD_MANAGER;
  public static final int INDIVIDUAL_RED_PACKET_MANAGER;
  public static final int INDIVIDUATION_ABTEST_MANAGER;
  public static final int INTIMATE_INFO_MANAGER;
  public static final int KANDIAN_AD_EXPOSURE_MANAGER;
  public static final int KANDIAN_DAILY_MANAGER;
  public static final int KANDIAN_MERGE_MANAGER;
  public static final int KANDIAN_NATIVE_AD_PRELOAD_MANAGER;
  public static final int KANDIAN_SUBSCRIBE_MANAGER;
  public static final int LBS_REPORT_MANAGER;
  public static final int LIGHT_VIDEO_MANAGER;
  public static final int LIKE_RANKING_LIST_MANAGER;
  public static final int LISTEN_TOGETHER_MANAGER;
  public static final int LOCAL_REDTOUCH_MANAGER;
  public static final int LOCATION_FLOAT_WINDOW_MANAGER;
  public static final int LOGIN_DEVICES_MANAGER;
  public static final int LOGIN_WELCOME_MANAGER;
  public static final int LONG_ARK_MSG_MANAGER;
  public static final int LONG_TEXT_MSG_MANAGER;
  public static final int MAYKNOW_RECOMMEND_MANAGER;
  public static final int MEDAL_WALL_MNG;
  public static final int MEDIA_MSG_ORDER_SEND_MANAGER;
  public static final int MESSAGE_NOTIFICATION_SETTING_MANAGER;
  public static final int MESSAGE_ROAM_MANAGER;
  public static final int MGR_ACTVATE_FRIENDS;
  public static final int MGR_FILE_TRANS;
  public static final int MGR_MEDIA_PLAYER;
  public static final int MGR_MSG_FACADE;
  public static final int MGR_NET_ENGINE;
  public static final int MGR_PIC_PREDOWNLOAD;
  public static final int MGR_PLUGIN;
  public static final int MGR_PORTAL;
  public static final int MGR_RED_TOUCH;
  public static final int MGR_RED_TOUCH_EX;
  public static final int MGR_SUB_ACNT;
  public static final int MGR_SYNC_CONTACT;
  public static final int MGR_TROOP_CREATE;
  public static final int MGR_TROOP_FILTER;
  public static final int MINI_APKG_CONFIG_MANAGER;
  public static final int MINI_APP_DESKTOP_MANAGER;
  public static final int MINI_APP_ENTITY_MANAGER;
  public static final int MINI_APP_EXPOSURE_MANAGER;
  public static final int MINI_APP_ITEM_MANAGER;
  public static final int MINI_APP_LOCAL_SEARCH;
  public static final int MINI_APP_SEARCH_MANAGER;
  public static final int MINI_CARD_MANAGER;
  public static final int MIXED_MSG_MANAGER;
  public static final int MOST_USE_SEARCH_MANAGER;
  public static final int MQQ_COMIC_MANAGER;
  public static final int MSG_BOX_INTERACT_MANAGER;
  public static final int MSG_TAB_STORY_CONFIG_MANAGER;
  public static final int MSG_TAB_STORY_MANAGER;
  public static final int MULTI_CHOOSE_SAVE_MANAGER;
  public static final int MUTUAL_MARK_MANAGER;
  public static final int NEARBY_BANNER_MANAGER;
  public static final int NEARBY_CARD_MANAGER;
  public static final int NEARBY_FLOWER_MANAGER;
  public static final int NEARBY_GENERAL_MANAGER;
  public static final int NEARBY_GRAY_TIPS_MANAGER;
  public static final int NEARBY_LIKE_LIMIT_MANAGER;
  public static final int NEARBY_MOMENT_MANAGER;
  public static final int NEARBY_PROXY_MANAGER;
  public static final int NEARBY_VIDEO_CHAT;
  public static final int NEWER_GUIDE_BANNER_MANAGER;
  public static final int NEW_FRIEND_MANAGER;
  public static final int NEW_FRIEND_VERIFICATION_MANAGER;
  public static final int NEW_MSG_NOTIFICATION_MANAGER;
  public static final int NOTIFICATION_BANNER_MANAGER;
  public static final int NOTIFY_ID_MANAGER;
  public static final int NOW_DOWNLOAD_ENGINE_MANAGER;
  public static final int NOW_DYNAMIC_MANAGER;
  public static final int NOW_HONG_BAO_PUSH_MANAGER;
  public static final int NOW_LIVE_MANAGER;
  public static final int NUMREDMSG_MANAGER;
  public static final int OCR_MANAGER;
  public static final int ODPROXY_MGR;
  public static final int OLYMPIC_MANAGER;
  public static final int ONLINE_STATUS_MANAGER;
  public static final int ONLINE_STATUS_PERMISSION_MANAGER;
  public static final int PAI_YI_PAI_MANAGER;
  public static final int PASSWD_RED_BAG_MANAGER;
  public static final int PATCH_DOWNLOAD_MANAGER;
  public static final int PATH_TRACE_MANAGER;
  public static final int PA_REPORT_MANAGER;
  public static final int PERSONALITY_LABELS_UPLOAD_MGR;
  public static final int PERSONAL_PRAISE_MANAGER;
  public static final int PHONE_UNITY_MANAGER;
  public static final int PHOTOLIST_CONFIG_MANAGER;
  public static final int PHOTO_PLUS_MANAGER;
  public static final int PICTURE_STATISTICS_MANAGER;
  public static final int PIC_OCR_MANAGER;
  public static final int PNG_FRAME_DRAWABLE_MANAGER;
  public static final int PRECOVER_MANAGER;
  public static final int PRELOAD_MANAGER;
  public static final int PRE_DOWNLOAD_CONTROLLER_2;
  public static final int PRE_DOWNLOAD_SCHEDULER_MANAGER;
  public static final int PROXY_MANAGER;
  public static final int PTT_CFG_MANAGER;
  public static final int PTT_PRE_DOWNLOAD_MANAGER;
  public static final int PTT_PRE_SEND_MANAGER;
  public static final int PUBLICACCOUNTDATA_MANAGER;
  public static final int PUBLIC_ACCOUNT_ENTITY_HELPER;
  public static final int PUBLIC_ACCOUNT_VIDEO_PRELOAD_MANAGER;
  public static final int PUBLIC_QUICK_PAY_MANAGER;
  public static final int PULL_ACTIVE_MANAGER;
  public static final int PUSH_NOTICE_MANAGER;
  public static final int PUSH_NOTIFICATION_MANAGER;
  public static final int QASSISTANT_MANAGER;
  public static final int QCALLCARD_MANAGER;
  public static final int QCIRCLE_LBS_MANAGER;
  public static final int QCIRCLE_MGR_RED_TOUCH;
  public static final int QFILE_CONFIG_MANAGER;
  public static final int QIDIAN_MANAGER;
  public static final int QIM_NEW_FRIEND_MANAGER;
  public static final int QQCOMIC_PRELOAD_MANAGER;
  public static final int QQCOMIC_UPLOAD_MANAGER;
  public static final int QQLS_DATA_MANAGER;
  public static final int QQPROTECT_UPDATE_MANAGER;
  public static final int QQSTORY_MANAGER;
  public static final int QQ_NOTIFY_MANAGER;
  public static final int QQ_REMINDER_ALARM_MANAGER;
  public static final int QQ_STORY_FEED_MANAGER;
  public static final int QQ_VAS_UPDATE_MANAGER;
  public static final int QR_MAIN_PROC_MANAGER;
  public static final int QR_PROCESS_MANAGER;
  public static final int QWALLET_CONFIG_MANAGER;
  public static final int QWALLET_GDT_AD_MANAGER;
  public static final int QWALLET_RED_MANAGER;
  public static final int QZONE_ALBUM_RED_TOUCH;
  public static final int QZONE_CONTACTS_FEED_MANAGER;
  public static final int QZONE_GIFT_MANAGER;
  public static final int QZONE_MANAGER;
  public static final int QZONE_MSG_MANAGER;
  public static final int QZONE_NEW_STATUS_MANAGER;
  public static final int QZONE_PLUGIN_MANAGER;
  public static final int READER_RED_TOUCH_MANAGER;
  public static final int READINJOY_ACT_DAU_REPORT_MANAGER;
  public static final int READINJOY_AD_MATERIAL_MANAGER;
  public static final int READINJOY_LOGIC_MANAGER;
  public static final int READINJOY_MANAGER;
  public static final int READINJOY_VIDEO_UPLOAD_MANAGER;
  public static final int READ_INJOY_REFRESH_MANAGER;
  public static final int READ_INJOY_SKIN_MANAGER;
  public static final int READ_IN_JOY_OPERATION_MANAGER;
  public static final int RECENT_CALL_FACADE;
  public static final int RECENT_MANAGER_FOR_3RDPART;
  public static final int RECENT_USER;
  public static final int RECOMMEND_TROOP_MANAGER;
  public static final int RICH_TEXT_CHAT_MANAGER;
  public static final int RIJ_UGC_VIDEO_PUBLISH_MANAGER;
  public static final int ROAM_SETTING_MANAGER;
  public static final int ROCK_DOWNLOADER_MANAGER;
  public static final int SCENES_REC_EMO_MANAGER;
  public static final int SCHOOL_TROOP_KEYWORD_MANAGER;
  public static final int SCRIBBLE_DOWNLOAD_MANAGER;
  public static final int SDK_SHARE;
  public static final int SEARCHHISTORY_MANAGER;
  public static final int SEARCH_WEB_HISTORY_MANAGER;
  public static final int SEARCH_WORD_HISTORY_MANAGER;
  public static final int SEC_SPY_FILEMANAGER;
  public static final int SEND_BLESS_CONFIG_MANAGER;
  public static final int SHIELD_LIST_MANAGER;
  public static final int SHORT_VIDEO_PREDOWNLOAD_MANAGER;
  public static final int SHORT_VIDEO_RESOURCE_MANAGER;
  public static final int SHORT_VIDEO_TRANS_MANAGER;
  public static final int SIGNATURE_MANAGER;
  public static final int SLOW_TABLE_MANAGER;
  private static final Object SMALL_LOCK;
  public static final int SONIC_FILE_DISCARD_MANAGER;
  public static final int SPORT_MANAGER;
  public static final int SPRITE_SCRIPT_MANAGER;
  public static final int STATUS_MANAGER;
  public static final int STICKER_RECOMMEND_MANAGER;
  public static final int STORY_HALO_MANAGER;
  public static final int STT_MANAGER;
  public static final int STUDY_MODE_SWITCHER_MANAGER;
  public static final int STUDY_ROOM_MANAGER;
  public static final int SUB_ACCOUNT_CONTROLL;
  public static final int SUB_ACCOUNT_MANAGER;
  private static final String TAG = "QQInitHandler.QQManagerFactory";
  public static final int TEAMWORK_MANAGER;
  public static final int TEAMWORK_SPREAD_MANAGER;
  public static final int TEAMWORK_SPREAD_MANAGER_DATALINE;
  public static final int TEMP_MSG_BOX;
  public static final int TEMP_MSG_SETTTING_MANAGER;
  public static final int THEME_MANAGER;
  public static final int THIRD_PARTY_FACE_DETECT_MANAGER;
  public static final int TIM_JUMP_LOGIN_MANAGER;
  public static final int TIM_UPGRADE_DOWNLOAD_MANAGER;
  public static final int TIM_UPGRADE_HONGDIAN_MANAGER;
  public static final int TOFUMSG_MANAGER;
  public static final int TOGETHER_CONTROLLER_MANAGER;
  public static final int TROOPAPP_SHORTCUT_MANAGER;
  public static final int TROOPINFO_MANAGER;
  public static final int TROOP_AIO_AD_MANAGER;
  public static final int TROOP_AIO_KEYWORD_TIP_MANAGER;
  public static final int TROOP_AIO_MULTI_CARD_MANAGER;
  public static final int TROOP_AIO_NAVIGATE_BAR;
  public static final int TROOP_APP_MGR;
  public static final int TROOP_BIND_PUBACCOUNT_MANAGER;
  public static final int TROOP_CLASS_CONTROLLER_MANAGER;
  public static final int TROOP_ENTER_EFFECT_MANAGER;
  public static final int TROOP_ESSENCE_MSG_MANAGER;
  public static final int TROOP_GAG_MANAGER;
  public static final int TROOP_GAME_CARD_MANAGER;
  public static final int TROOP_GIFT_MANAGER;
  public static final int TROOP_HONOR_MANAGER;
  public static final int TROOP_IMPORTANT_MSG_MANAGER;
  public static final int TROOP_LUCKY_CHARACTER_MANAGER;
  public static final int TROOP_MANAGER;
  public static final int TROOP_MEMBER_RECOMMEND_MANAGER;
  public static final int TROOP_NOTIFICATION_MANAGER;
  public static final int TROOP_ONLINE_MEMBER_MANAGER;
  public static final int TROOP_PLUGIN_MANAGER;
  public static final int TROOP_REWARD_MGR;
  public static final int TROOP_ROBOT_MANAGER;
  public static final int TROOP_SHORTCUTBAR_MANAGER;
  public static final int TROOP_STORY_MANAGER;
  public static final int TROOP_TIPS_MSG_MANAGER;
  public static final int TROOP_VIDEO_MANAGER;
  public static final int UPCOMING_MSG_PRE_MANAGER;
  public static final int UPGRADE_MANAGER;
  public static final int URL_INTECEPT_MANAGER;
  public static final int URL_SECURITY_CHECK_MANAGER;
  public static final int USED_APP_LIST_MANAGER;
  public static final int USING_TIME_REPORT_MANAGER;
  public static final int VACD_REPORT_MANAGER;
  public static final int VAS_EXTENSION_MANAGER;
  public static final int VAS_QUICKUPDATE_MANAGER;
  public static final int VIDEO_STORY_MANAGER;
  public static final int VIP_FUNCALL_MANAGER;
  public static final int VIP_GIF_MANAGER;
  public static final int VOICE_ASSISTANT_MANAGER;
  public static final int VOICE_CHANGE_MANAGER;
  public static final int WATCH_LIVE_TOGETHER;
  public static final int WEATHER_MANAGER;
  public static final int WEBPROCESS_MANAGER;
  public static final int WEISHI_MANAGER;
  public static final int WEREWOLVES_MANAGER;
  public static final int WRITE_TOGETHER_MANAGER;
  public static final int ZHITU_MANAGER;
  private static AtomicBoolean hasLazyLoad;
  private static ArrayList<Integer> sAppInterfaceConstructorList = new QQManagerFactory.3();
  private static ArrayList<Integer> sAppRuntimeConstructorList;
  private static SparseArray<Class<? extends Manager>> sManagerArrays;
  private static int sManagerStart = 9;
  private static ArrayList<Integer> sNoConstructorList;
  
  static
  {
    int i = sManagerStart;
    sManagerStart = i + 1;
    QZONE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CONTACT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    GAMECENTER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    WEBPROCESS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    EMOTICON_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    STATUS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SHIELD_LIST_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    STT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PROXY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CACHE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_MSG_FACADE = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_NET_ENGINE = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    RECOMMEND_TROOP_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_FILE_TRANS = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_MEDIA_PLAYER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_PLUGIN = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_SUB_ACNT = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CONVS_FACADE = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_TROOP_FILTER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_TROOP_CREATE = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    RECENT_MANAGER_FOR_3RDPART = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEW_FRIEND_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    VIDEO_STORY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_RED_TOUCH = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOPINFO_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    RECENT_CALL_FACADE = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_PIC_PREDOWNLOAD = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ROAM_SETTING_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_SYNC_CONTACT = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CHAT_FONT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CHAT_EMOTION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CHAT_BUBBLE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    COLOR_RING_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CHAT_AVATAR_PENDANT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    DOWNLOADER_FACTORY = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_GAG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FRIENDS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    DISCUSSION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CONTACT_FACADE = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SEARCHHISTORY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PUBLICACCOUNTDATA_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SIGNATURE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CONDITION_SEARCH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    HOT_CHAT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SUB_ACCOUNT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SUB_ACCOUNT_CONTROLL = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CHAT_BACKGROUND_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NUMREDMSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SHORT_VIDEO_TRANS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ACCOUNTDPC_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    EQQ_DETAIL_DATA_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_RED_TOUCH_EX = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    DATING_PROXY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QQLS_DATA_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PICTURE_STATISTICS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEARBY_BANNER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    VIP_GIF_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    EARLY_DOWNLOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_PORTAL = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ADDCONTACT_TROOP_SEARCH_POP_MANAGE = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_TIPS_MSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    BUSINESS_WORD_MATCH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PNG_FRAME_DRAWABLE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    VIP_FUNCALL_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MGR_ACTVATE_FRIENDS = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    EC_SHOP_ASSISTANT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PTT_CFG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    IMAGE_UPLOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QZONE_CONTACTS_FEED_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MESSAGE_ROAM_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEARBY_GRAY_TIPS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SEC_SPY_FILEMANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SHORT_VIDEO_PREDOWNLOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    READINJOY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PA_REPORT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PHONE_UNITY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FAV_ROAMING_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QZONE_ALBUM_RED_TOUCH = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FULL_MESSAGE_SEARCH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEARBY_CARD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ODPROXY_MGR = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_APP_MGR = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    BUSINESS_CARD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_GIFT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    WEATHER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEARBY_PROXY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_PLUGIN_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PATCH_DOWNLOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ARK_APP_CENTER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    HOTCHAT_PKACTIVITY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    HOTCHAT_SCENE_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEARBY_FLOWER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PASSWD_RED_BAG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LBS_REPORT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PTT_PRE_DOWNLOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PTT_PRE_SEND_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QR_PROCESS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FTSDB_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    INDIVIDUAL_RED_PACKET_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_BIND_PUBACCOUNT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_AIO_AD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ACT_DAU_REPORT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PUBLIC_QUICK_PAY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SCRIBBLE_DOWNLOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SEND_BLESS_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QCALLCARD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MQQ_COMIC_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QQCOMIC_PRELOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LOCATION_FLOAT_WINDOW_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PULL_ACTIVE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LOGIN_WELCOME_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QQCOMIC_UPLOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    VACD_REPORT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FAVROAMING_DB_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    URL_INTECEPT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PRELOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_REWARD_MGR = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APOLLO_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APOLLO_RECENTMANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APOOLO_DAO_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    GAME_PARTY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NOTIFICATION_BANNER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    READINJOY_ACT_DAU_REPORT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MAYKNOW_RECOMMEND_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LOCAL_REDTOUCH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEARBY_GENERAL_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    KANDIAN_MERGE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    READINJOY_LOGIC_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_VIDEO_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QIDIAN_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LONG_TEXT_MSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    OLYMPIC_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AR_RESOURCE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PHOTO_PLUS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FACE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NOW_LIVE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    COMMONUSED_SYSTEM_EMOJI_MANAGERT = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ACCOUNT_DETAIL_DYNAMIC_DATA_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MIXED_MSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QZONE_PLUGIN_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    VOICE_CHANGE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    INDIVIDUATION_ABTEST_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PRECOVER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    DYNAMIC_AVATAR_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QQSTORY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    VAS_QUICKUPDATE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    THEME_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LIKE_RANKING_LIST_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ART_FILTER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    UPGRADE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ARMAP_RES_DOWNLOAD = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SONIC_FILE_DISCARD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PRE_DOWNLOAD_CONTROLLER_2 = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QQPROTECT_UPDATE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APOLLO_NATIVE_SSO_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AIO_GROUP_APPS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    STORY_HALO_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MESSAGE_NOTIFICATION_SETTING_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CLASSIC_HEAD_ACIVITY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    COMMERCIAL_DRAINAGE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SLOW_TABLE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MSG_BOX_INTERACT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_ROBOT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FACE_SCORE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    DB_FIX_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    HOT_PIC_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEARBY_LIKE_LIMIT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_STORY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PERSONAL_PRAISE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PATH_TRACE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APOLLO_GAME_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    COMIC_RED_TOUCH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    DOUTU_MAGAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PHOTOLIST_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FLASH_CHAT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APP_GUIDE_TIPS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    HIBOOM_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AR_CLOBAL_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CU_OPEN_CARD_GUIDE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FUNCTION_MODULE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AIO_ANIMATION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEARBY_VIDEO_CHAT = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_AIO_KEYWORD_TIP_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    READINJOY_VIDEO_UPLOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APOLLO_PUSH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    OCR_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SHORT_VIDEO_RESOURCE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PERSONALITY_LABELS_UPLOAD_MGR = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_ENTER_EFFECT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APOLLO_RESPONSE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PRE_DOWNLOAD_SCHEDULER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_ONLINE_MEMBER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    VAS_EXTENSION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    GROUP_VIDEO_PLUGIN_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PUBLIC_ACCOUNT_ENTITY_HELPER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PUBLIC_ACCOUNT_VIDEO_PRELOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CAMPUS_NOTICE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    USING_TIME_REPORT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TIM_JUMP_LOGIN_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QR_MAIN_PROC_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TIM_UPGRADE_HONGDIAN_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QWALLET_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SEARCH_WEB_HISTORY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    WEREWOLVES_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    KANDIAN_NATIVE_AD_PRELOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SPRITE_SCRIPT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MEDAL_WALL_MNG = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MSG_TAB_STORY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MSG_TAB_STORY_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QQ_STORY_FEED_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AV_REDPACKET_CONFIG_MGR = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    HOTCHAT_CENTER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TIM_UPGRADE_DOWNLOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QIM_NEW_FRIEND_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ZHITU_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    EMOFROMGROUP_DB_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SPORT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    READ_INJOY_SKIN_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SCHOOL_TROOP_KEYWORD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEARBY_MOMENT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    EXTEND_FRIEND_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NOW_HONG_BAO_PUSH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NOW_DOWNLOAD_ENGINE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    IMAX_AD_VIDEO_PRELOAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CONFESS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    READ_INJOY_REFRESH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    READ_IN_JOY_OPERATION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TEAMWORK_SPREAD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QWALLET_RED_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    WEISHI_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QZONE_NEW_STATUS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    HIDDENCHAT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    BUSINESS_COMMON_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ARPROMOTION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    KANDIAN_SUBSCRIBE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    BANNER_LISTENER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    BEANCURD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TEAMWORK_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PUSH_NOTICE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ICE_BREAKING_MNG = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    RICH_TEXT_CHAT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APKG_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    USED_APP_LIST_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_CLASS_CONTROLLER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    URL_SECURITY_CHECK_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    HCE_PLUGIN_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    EXTEND_FRIEND_LIMIT_CHAT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QZONE_MSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LIGHT_VIDEO_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CTENTRY_MNG = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    KANDIAN_DAILY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SEARCH_WORD_HISTORY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    THIRD_PARTY_FACE_DETECT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MINI_APKG_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TEMP_MSG_SETTTING_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    GROUP_TEAM_WORK_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TEAMWORK_SPREAD_MANAGER_DATALINE = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NOW_DYNAMIC_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    KANDIAN_AD_EXPOSURE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PUSH_NOTIFICATION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MINI_APP_ITEM_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MINI_APP_LOCAL_SEARCH = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CHECK_FORWARD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QZONE_GIFT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NOTIFY_ID_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    STICKER_RECOMMEND_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APPLETS_ACCOUNT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AIO_INPUT_STATUS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QFILE_CONFIG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MOST_USE_SEARCH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AUTO_REPLY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    COPY_PROMPT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QQ_REMINDER_ALARM_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MINI_APP_EXPOSURE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    INTIMATE_INFO_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MULTI_CHOOSE_SAVE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AIO_MULTI_WINDOW_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MEDIA_MSG_ORDER_SEND_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AIO_PANEL_MINI_APP_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ROCK_DOWNLOADER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_AIO_MULTI_CARD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MINI_APP_ENTITY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LISTEN_TOGETHER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEW_FRIEND_VERIFICATION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CAMERA_EMOTION_DB_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CAMERA_EMOTION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LOGIN_DEVICES_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MINI_APP_DESKTOP_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    READINJOY_AD_MATERIAL_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    WATCH_LIVE_TOGETHER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TOGETHER_CONTROLLER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FORWARD_MSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QWALLET_GDT_AD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MUTUAL_MARK_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_HONOR_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_MEMBER_RECOMMEND_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FETCH_OPENID_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEW_MSG_NOTIFICATION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SDK_SHARE = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    READER_RED_TOUCH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QASSISTANT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PIC_OCR_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AUDIO_DEVICE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_SHORTCUTBAR_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    RIJ_UGC_VIDEO_PUBLISH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOPAPP_SHORTCUT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    GAME_CENTER_MSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FRONT_BACK_REPORT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MINI_APP_SEARCH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    STUDY_MODE_SWITCHER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    STUDY_ROOM_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_AIO_NAVIGATE_BAR = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    SCENES_REC_EMO_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    UPCOMING_MSG_PRE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    RECENT_USER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    EMOTION_SEARCH_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TOFUMSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ONLINE_STATUS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ONLINE_STATUS_PERMISSION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FOREGROUND_NOTIFY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    LONG_ARK_MSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    AV_GAME_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TEMP_MSG_BOX = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    NEWER_GUIDE_BANNER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QQ_VAS_UPDATE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_IMPORTANT_MSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QCIRCLE_MGR_RED_TOUCH = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    WRITE_TOGETHER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QQ_NOTIFY_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    CUSTOMIZE_GRAY_TIPS = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    C2C_SHORTCUT_BAR_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_ESSENCE_MSG_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    FRIEND_CLUE_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_NOTIFICATION_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ANONYMOUS_ANSWER_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    QCIRCLE_LBS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    ILIVE_GROUP_TIPS_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    VOICE_ASSISTANT_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    PAI_YI_PAI_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    APOLLO_RES_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    MINI_CARD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_GAME_CARD_MANAGER = i;
    i = sManagerStart;
    sManagerStart = i + 1;
    TROOP_LUCKY_CHARACTER_MANAGER = i;
    COUNT_MANAGER = sManagerStart;
    SMALL_LOCK = new Object();
    hasLazyLoad = new AtomicBoolean(false);
    sManagerArrays = new SparseArray(512);
    aobp.a(sManagerArrays);
    sNoConstructorList = new QQManagerFactory.1();
    sAppRuntimeConstructorList = new QQManagerFactory.2();
  }
  
  private QQManagerFactory()
  {
    throw new IllegalStateException("Factory class can not be instance");
  }
  
  protected static Manager createManager(int paramInt, QQAppInterface paramQQAppInterface)
  {
    Manager localManager = createManagerForDeprecatedLogic(paramInt, paramQQAppInterface);
    if (localManager != null) {
      return localManager;
    }
    for (;;)
    {
      Class localClass;
      synchronized (SMALL_LOCK)
      {
        if ((sManagerArrays.indexOfKey(paramInt) < 0) && (!hasLazyLoad.get()))
        {
          QLog.e("QQInitHandler.QQManagerFactory", 1, "First trigger lazyLoad, name=" + paramInt);
          if (QLog.isColorLevel()) {
            QLog.d("QQInitHandler.QQManagerFactory", 2, "First trigger stack=", new RuntimeException("First trigger manager lazyLoad"));
          }
          lazyLoadManager();
          hasLazyLoad.set(true);
        }
        localClass = (Class)sManagerArrays.get(paramInt);
        if (localClass == null)
        {
          QLog.e("QQInitHandler.QQManagerFactory", 1, "Not Found Manager, name=" + paramInt);
          paramQQAppInterface = localManager;
          return paramQQAppInterface;
        }
      }
      try
      {
        if (sNoConstructorList.contains(Integer.valueOf(paramInt)))
        {
          paramQQAppInterface = (Manager)localClass.newInstance();
        }
        else if (sAppRuntimeConstructorList.contains(Integer.valueOf(paramInt)))
        {
          ??? = localClass.getDeclaredConstructor(new Class[] { AppRuntime.class });
          ((Constructor)???).setAccessible(true);
          paramQQAppInterface = (Manager)((Constructor)???).newInstance(new Object[] { paramQQAppInterface });
        }
        else if (sAppInterfaceConstructorList.contains(Integer.valueOf(paramInt)))
        {
          ??? = localClass.getDeclaredConstructor(new Class[] { AppInterface.class });
          ((Constructor)???).setAccessible(true);
          paramQQAppInterface = (Manager)((Constructor)???).newInstance(new Object[] { paramQQAppInterface });
        }
        else
        {
          ??? = localClass.getDeclaredConstructor(new Class[] { QQAppInterface.class });
          ((Constructor)???).setAccessible(true);
          paramQQAppInterface = (Manager)((Constructor)???).newInstance(new Object[] { paramQQAppInterface });
        }
      }
      catch (Exception paramQQAppInterface)
      {
        QLog.e("QQInitHandler.QQManagerFactory", 1, paramQQAppInterface, new Object[0]);
        if ((paramQQAppInterface instanceof InvocationTargetException))
        {
          QLog.e("QQInitHandler.QQManagerFactory", 1, ((InvocationTargetException)paramQQAppInterface).getTargetException(), new Object[0]);
          bdjw.a(((InvocationTargetException)paramQQAppInterface).getTargetException());
        }
        paramQQAppInterface = localManager;
      }
    }
  }
  
  private static Manager createManagerForDeprecatedLogic(int paramInt, QQAppInterface paramQQAppInterface)
  {
    if (paramInt == MGR_PLUGIN) {
      return blvy.a(paramQQAppInterface);
    }
    if (paramInt == STATUS_MANAGER) {
      return bbvn.a(paramQQAppInterface);
    }
    if (paramInt == FRIENDS_MANAGER) {
      return new anvk(paramQQAppInterface, paramQQAppInterface.getEntityManagerFactory().createEntityManager());
    }
    if (paramInt == MINI_APP_ENTITY_MANAGER) {
      return new MiniAppEntityManager(paramQQAppInterface.getCurrentUin());
    }
    return null;
  }
  
  private static void lazyLoadManager()
  {
    sManagerArrays.put(0, AccountManagerImpl.class);
    sManagerArrays.put(3, ProxyIpManagerImpl.class);
    sManagerArrays.put(WEBPROCESS_MANAGER, WebProcessManager.class);
    sManagerArrays.put(EMOTICON_MANAGER, awyr.class);
    sManagerArrays.put(SHIELD_LIST_MANAGER, awtp.class);
    sManagerArrays.put(STT_MANAGER, bdts.class);
    sManagerArrays.put(RECOMMEND_TROOP_MANAGER, aoce.class);
    sManagerArrays.put(MGR_FILE_TRANS, afsl.class);
    sManagerArrays.put(MGR_MEDIA_PLAYER, MediaPlayerManager.class);
    sManagerArrays.put(MGR_TROOP_CREATE, bfgz.class);
    sManagerArrays.put(RECENT_MANAGER_FOR_3RDPART, aocd.class);
    sManagerArrays.put(VIDEO_STORY_MANAGER, aalt.class);
    sManagerArrays.put(TROOPINFO_MANAGER, awzf.class);
    sManagerArrays.put(CHAT_FONT_MANAGER, gb.class);
    sManagerArrays.put(CHAT_EMOTION_MANAGER, asih.class);
    sManagerArrays.put(COLOR_RING_MANAGER, bhml.class);
    sManagerArrays.put(CHAT_AVATAR_PENDANT_MANAGER, AvatarPendantManager.class);
    sManagerArrays.put(CONTACT_FACADE, ansj.class);
    sManagerArrays.put(SEARCHHISTORY_MANAGER, aode.class);
    sManagerArrays.put(ACCOUNT_DETAIL_DYNAMIC_DATA_MANAGER, oay.class);
    sManagerArrays.put(SIGNATURE_MANAGER, SignatureManager.class);
    sManagerArrays.put(CONDITION_SEARCH_MANAGER, anrz.class);
    sManagerArrays.put(NUMREDMSG_MANAGER, bbbl.class);
    sManagerArrays.put(SHORT_VIDEO_TRANS_MANAGER, aodp.class);
    sManagerArrays.put(EQQ_DETAIL_DATA_MANAGER, anty.class);
    sManagerArrays.put(DATING_PROXY_MANAGER, arxv.class);
    sManagerArrays.put(QQLS_DATA_MANAGER, awto.class);
    sManagerArrays.put(NEARBY_BANNER_MANAGER, arpr.class);
    sManagerArrays.put(MGR_PORTAL, PortalManager.class);
    sManagerArrays.put(OLYMPIC_MANAGER, OlympicManager.class);
    sManagerArrays.put(AR_RESOURCE_MANAGER, apgi.class);
    sManagerArrays.put(ADDCONTACT_TROOP_SEARCH_POP_MANAGE, ntw.class);
    sManagerArrays.put(BUSINESS_WORD_MATCH_MANAGER, WordMatchManager.class);
    sManagerArrays.put(PNG_FRAME_DRAWABLE_MANAGER, awra.class);
    sManagerArrays.put(VIP_FUNCALL_MANAGER, bibh.class);
    sManagerArrays.put(PTT_CFG_MANAGER, bahk.class);
    sManagerArrays.put(IMAGE_UPLOAD_MANAGER, azvc.class);
    sManagerArrays.put(QZONE_CONTACTS_FEED_MANAGER, bazf.class);
    sManagerArrays.put(MESSAGE_ROAM_MANAGER, anzc.class);
    sManagerArrays.put(NEARBY_GRAY_TIPS_MANAGER, NearbyGrayTipsManager.class);
    sManagerArrays.put(SEC_SPY_FILEMANAGER, bcpl.class);
    sManagerArrays.put(PA_REPORT_MANAGER, use.class);
    sManagerArrays.put(PHONE_UNITY_MANAGER, ajco.class);
    sManagerArrays.put(FAV_ROAMING_MANAGER, asfl.class);
    sManagerArrays.put(FULL_MESSAGE_SEARCH_MANAGER, aokt.class);
    sManagerArrays.put(QZONE_ALBUM_RED_TOUCH, baql.class);
    sManagerArrays.put(TROOP_APP_MGR, bgig.class);
    sManagerArrays.put(TROOP_AIO_AD_MANAGER, bgie.class);
    sManagerArrays.put(COMMONUSED_SYSTEM_EMOJI_MANAGERT, CommonUsedSystemEmojiManager.class);
    sManagerArrays.put(NEARBY_CARD_MANAGER, axny.class);
    sManagerArrays.put(ODPROXY_MGR, avwp.class);
    sManagerArrays.put(TROOP_GIFT_MANAGER, bgko.class);
    sManagerArrays.put(WEATHER_MANAGER, amee.class);
    sManagerArrays.put(NEARBY_PROXY_MANAGER, axpp.class);
    sManagerArrays.put(PATCH_DOWNLOAD_MANAGER, aclo.class);
    sManagerArrays.put(TROOP_PLUGIN_MANAGER, TroopPluginManager.class);
    sManagerArrays.put(PTT_PRE_SEND_MANAGER, baif.class);
    sManagerArrays.put(PTT_PRE_DOWNLOAD_MANAGER, bahy.class);
    sManagerArrays.put(ARK_APP_CENTER_MANAGER, ArkAppCenter.class);
    sManagerArrays.put(PASSWD_RED_BAG_MANAGER, akqe.class);
    sManagerArrays.put(HOTCHAT_SCENE_CONFIG_MANAGER, anwv.class);
    sManagerArrays.put(BUSINESS_CARD_MANAGER, aqjm.class);
    sManagerArrays.put(FTSDB_MANAGER, aoxx.class);
    sManagerArrays.put(QR_PROCESS_MANAGER, bmeh.class);
    sManagerArrays.put(NEARBY_FLOWER_MANAGER, anzp.class);
    sManagerArrays.put(INDIVIDUAL_RED_PACKET_MANAGER, anxc.class);
    sManagerArrays.put(SEND_BLESS_CONFIG_MANAGER, aipw.class);
    sManagerArrays.put(ACT_DAU_REPORT_MANAGER, bdjy.class);
    sManagerArrays.put(PUBLIC_QUICK_PAY_MANAGER, akqv.class);
    sManagerArrays.put(LBS_REPORT_MANAGER, aozl.class);
    sManagerArrays.put(APOLLO_RECENTMANAGER, anly.class);
    sManagerArrays.put(APOOLO_DAO_MANAGER, ankc.class);
    sManagerArrays.put(QCALLCARD_MANAGER, bapa.class);
    sManagerArrays.put(MQQ_COMIC_MANAGER, asgo.class);
    sManagerArrays.put(QQCOMIC_PRELOAD_MANAGER, blqh.class);
    sManagerArrays.put(TROOP_REWARD_MGR, bglo.class);
    sManagerArrays.put(FAVROAMING_DB_MANAGER, asfk.class);
    sManagerArrays.put(CAMERA_EMOTION_DB_MANAGER, asen.class);
    sManagerArrays.put(EMOFROMGROUP_DB_MANAGER, asey.class);
    sManagerArrays.put(LOCATION_FLOAT_WINDOW_MANAGER, awnx.class);
    sManagerArrays.put(PULL_ACTIVE_MANAGER, awtl.class);
    sManagerArrays.put(NEARBY_GENERAL_MANAGER, axnt.class);
    sManagerArrays.put(QQCOMIC_UPLOAD_MANAGER, blrh.class);
    sManagerArrays.put(URL_INTECEPT_MANAGER, bhon.class);
    sManagerArrays.put(PRELOAD_MANAGER, PreloadManager.class);
    sManagerArrays.put(GAME_PARTY_MANAGER, avhf.class);
    sManagerArrays.put(NOTIFICATION_BANNER_MANAGER, aqni.class);
    sManagerArrays.put(READINJOY_ACT_DAU_REPORT_MANAGER, pmy.class);
    sManagerArrays.put(READINJOY_LOGIC_MANAGER, pvp.class);
    sManagerArrays.put(TROOP_VIDEO_MANAGER, bgmk.class);
    sManagerArrays.put(SCHOOL_TROOP_KEYWORD_MANAGER, bghx.class);
    sManagerArrays.put(LONG_TEXT_MSG_MANAGER, axii.class);
    sManagerArrays.put(PHOTO_PLUS_MANAGER, PhotoPlusManager.class);
    sManagerArrays.put(FACE_MANAGER, aoke.class);
    sManagerArrays.put(NEW_MSG_NOTIFICATION_MANAGER, awxj.class);
    sManagerArrays.put(MIXED_MSG_MANAGER, awyg.class);
    sManagerArrays.put(FORWARD_MSG_MANAGER, bben.class);
    sManagerArrays.put(FETCH_OPENID_MANAGER, avwq.class);
    sManagerArrays.put(ONLINE_STATUS_PERMISSION_MANAGER, azcb.class);
    sManagerArrays.put(QZONE_PLUGIN_MANAGER, QZonePluginManager.class);
    sManagerArrays.put(VOICE_CHANGE_MANAGER, bicd.class);
    sManagerArrays.put(INDIVIDUATION_ABTEST_MANAGER, bhnl.class);
    sManagerArrays.put(FUNCTION_MODULE_MANAGER, bbyl.class);
    sManagerArrays.put(PRECOVER_MANAGER, azod.class);
    sManagerArrays.put(THEME_MANAGER, beim.class);
    sManagerArrays.put(LIKE_RANKING_LIST_MANAGER, anxs.class);
    sManagerArrays.put(QQPROTECT_UPDATE_MANAGER, bkvt.class);
    sManagerArrays.put(ART_FILTER_MANAGER, ArtFilterManager.class);
    sManagerArrays.put(UPGRADE_MANAGER, bgwd.class);
    sManagerArrays.put(APOLLO_NATIVE_SSO_MANAGER, ammz.class);
    sManagerArrays.put(AIO_GROUP_APPS_MANAGER, bfbz.class);
    sManagerArrays.put(ARMAP_RES_DOWNLOAD, aqdg.class);
    sManagerArrays.put(SONIC_FILE_DISCARD_MANAGER, bhom.class);
    sManagerArrays.put(MSG_BOX_INTERACT_MANAGER, MsgBoxInterFollowManager.class);
    sManagerArrays.put(AR_CLOBAL_CONFIG_MANAGER, apbf.class);
    sManagerArrays.put(COMMERCIAL_DRAINAGE_MANAGER, awyq.class);
    sManagerArrays.put(CLASSIC_HEAD_ACIVITY_MANAGER, aozr.class);
    sManagerArrays.put(SLOW_TABLE_MANAGER, azil.class);
    sManagerArrays.put(FACE_SCORE_MANAGER, axoe.class);
    sManagerArrays.put(HOT_PIC_MANAGER, avmh.class);
    sManagerArrays.put(EMOTION_SEARCH_MANAGER, aseo.class);
    sManagerArrays.put(NEARBY_LIKE_LIMIT_MANAGER, axpb.class);
    sManagerArrays.put(PERSONAL_PRAISE_MANAGER, PraiseManager.class);
    sManagerArrays.put(TROOP_STORY_MANAGER, zcj.class);
    sManagerArrays.put(APOLLO_GAME_MANAGER, amma.class);
    sManagerArrays.put(COMIC_RED_TOUCH_MANAGER, blsk.class);
    sManagerArrays.put(DOUTU_MAGAGER, asaa.class);
    sManagerArrays.put(PHOTOLIST_CONFIG_MANAGER, ahud.class);
    sManagerArrays.put(NEARBY_VIDEO_CHAT, bghm.class);
    sManagerArrays.put(HIBOOM_MANAGER, avkh.class);
    sManagerArrays.put(CU_OPEN_CARD_GUIDE_MANAGER, awtc.class);
    sManagerArrays.put(AIO_ANIMATION_MANAGER, bggl.class);
    sManagerArrays.put(TROOP_AIO_KEYWORD_TIP_MANAGER, bfge.class);
    sManagerArrays.put(READINJOY_VIDEO_UPLOAD_MANAGER, sqm.class);
    sManagerArrays.put(APOLLO_PUSH_MANAGER, amnd.class);
    sManagerArrays.put(OCR_MANAGER, ayrg.class);
    sManagerArrays.put(SHORT_VIDEO_RESOURCE_MANAGER, ShortVideoResourceManager.class);
    sManagerArrays.put(PERSONALITY_LABELS_UPLOAD_MGR, azph.class);
    sManagerArrays.put(TROOP_ENTER_EFFECT_MANAGER, bfkw.class);
    sManagerArrays.put(VAS_EXTENSION_MANAGER, bhou.class);
    sManagerArrays.put(APOLLO_RESPONSE_MANAGER, amog.class);
    sManagerArrays.put(TROOP_ONLINE_MEMBER_MANAGER, bgth.class);
    sManagerArrays.put(PUBLIC_ACCOUNT_ENTITY_HELPER, opx.class);
    sManagerArrays.put(PUBLIC_ACCOUNT_VIDEO_PRELOAD_MANAGER, ofd.class);
    sManagerArrays.put(IMAX_AD_VIDEO_PRELOAD_MANAGER, avqv.class);
    sManagerArrays.put(SEARCH_WEB_HISTORY_MANAGER, bbzs.class);
    sManagerArrays.put(CAMPUS_NOTICE_MANAGER, aqnd.class);
    sManagerArrays.put(USING_TIME_REPORT_MANAGER, UsingTimeReportManager.class);
    sManagerArrays.put(TIM_JUMP_LOGIN_MANAGER, awtu.class);
    sManagerArrays.put(SPRITE_SCRIPT_MANAGER, anch.class);
    sManagerArrays.put(QR_MAIN_PROC_MANAGER, zmv.class);
    sManagerArrays.put(WEREWOLVES_MANAGER, axtf.class);
    sManagerArrays.put(AV_REDPACKET_CONFIG_MGR, lui.class);
    sManagerArrays.put(BUSINESS_COMMON_CONFIG_MANAGER, BusinessCommonConfig.class);
    sManagerArrays.put(QWALLET_CONFIG_MANAGER, aktz.class);
    sManagerArrays.put(KANDIAN_NATIVE_AD_PRELOAD_MANAGER, oht.class);
    sManagerArrays.put(MEDAL_WALL_MNG, MedalWallMng.class);
    sManagerArrays.put(MSG_TAB_STORY_MANAGER, wmr.class);
    sManagerArrays.put(QQ_STORY_FEED_MANAGER, vzt.class);
    sManagerArrays.put(SPORT_MANAGER, bhwz.class);
    sManagerArrays.put(TIM_UPGRADE_DOWNLOAD_MANAGER, UpgradeTIMManager.class);
    sManagerArrays.put(ZHITU_MANAGER, aioi.class);
    sManagerArrays.put(READ_INJOY_SKIN_MANAGER, rna.class);
    sManagerArrays.put(NEARBY_MOMENT_MANAGER, ayks.class);
    sManagerArrays.put(NOW_HONG_BAO_PUSH_MANAGER, ayow.class);
    sManagerArrays.put(NOW_DOWNLOAD_ENGINE_MANAGER, avuq.class);
    sManagerArrays.put(READ_INJOY_REFRESH_MANAGER, rmu.class);
    sManagerArrays.put(READ_IN_JOY_OPERATION_MANAGER, rmt.class);
    sManagerArrays.put(TEAMWORK_SPREAD_MANAGER, bedr.class);
    sManagerArrays.put(TEAMWORK_SPREAD_MANAGER_DATALINE, beed.class);
    sManagerArrays.put(QWALLET_RED_MANAGER, akyj.class);
    sManagerArrays.put(RICH_TEXT_CHAT_MANAGER, aumk.class);
    sManagerArrays.put(TEAMWORK_MANAGER, becf.class);
    sManagerArrays.put(TROOP_CLASS_CONTROLLER_MANAGER, bfox.class);
    sManagerArrays.put(URL_SECURITY_CHECK_MANAGER, bidm.class);
    sManagerArrays.put(HCE_PLUGIN_MANAGER, bluc.class);
    sManagerArrays.put(APKG_CONFIG_MANAGER, com.tencent.mobileqq.microapp.apkg.ApkgConfigManager.class);
    sManagerArrays.put(MINI_APKG_CONFIG_MANAGER, com.tencent.mobileqq.mini.apkg.ApkgConfigManager.class);
    sManagerArrays.put(USED_APP_LIST_MANAGER, UsedAppListManager.class);
    sManagerArrays.put(ICE_BREAKING_MNG, bbdh.class);
    sManagerArrays.put(QZONE_MSG_MANAGER, QZoneMsgManager.class);
    sManagerArrays.put(LIGHT_VIDEO_MANAGER, bboo.class);
    sManagerArrays.put(SEARCH_WORD_HISTORY_MANAGER, aodf.class);
    sManagerArrays.put(THIRD_PARTY_FACE_DETECT_MANAGER, FaceDetectForThirdPartyManager.class);
    sManagerArrays.put(TEMP_MSG_SETTTING_MANAGER, awtq.class);
    sManagerArrays.put(ARPROMOTION_MANAGER, apcq.class);
    sManagerArrays.put(GROUP_TEAM_WORK_MANAGER, befl.class);
    sManagerArrays.put(NOW_DYNAMIC_MANAGER, avux.class);
    sManagerArrays.put(PUSH_NOTIFICATION_MANAGER, awtn.class);
    sManagerArrays.put(KANDIAN_AD_EXPOSURE_MANAGER, uhx.class);
    sManagerArrays.put(MINI_APP_ITEM_MANAGER, MiniAppUserAppInfoListManager.class);
    sManagerArrays.put(MINI_APP_LOCAL_SEARCH, MiniAppLocalSearchManager.class);
    sManagerArrays.put(CHECK_FORWARD_MANAGER, avji.class);
    sManagerArrays.put(QZONE_GIFT_MANAGER, bazk.class);
    sManagerArrays.put(STICKER_RECOMMEND_MANAGER, aiin.class);
    sManagerArrays.put(MOST_USE_SEARCH_MANAGER, bcha.class);
    sManagerArrays.put(AIO_INPUT_STATUS_MANAGER, avrk.class);
    sManagerArrays.put(QFILE_CONFIG_MANAGER, atix.class);
    sManagerArrays.put(AUTO_REPLY_MANAGER, azaz.class);
    sManagerArrays.put(MULTI_CHOOSE_SAVE_MANAGER, axjk.class);
    sManagerArrays.put(MEDIA_MSG_ORDER_SEND_MANAGER, bbob.class);
    sManagerArrays.put(COPY_PROMPT_MANAGER, arqo.class);
    sManagerArrays.put(INTIMATE_INFO_MANAGER, auzd.class);
    sManagerArrays.put(AIO_PANEL_MINI_APP_MANAGER, ahqp.class);
    sManagerArrays.put(AIO_MULTI_WINDOW_MANAGER, axel.class);
    sManagerArrays.put(ROCK_DOWNLOADER_MANAGER, aqgh.class);
    sManagerArrays.put(TROOP_AIO_MULTI_CARD_MANAGER, axgu.class);
    sManagerArrays.put(CAMERA_EMOTION_MANAGER, aseg.class);
    sManagerArrays.put(READINJOY_AD_MATERIAL_MANAGER, uic.class);
    sManagerArrays.put(QASSISTANT_MANAGER, baki.class);
    sManagerArrays.put(WATCH_LIVE_TOGETHER, avxv.class);
    sManagerArrays.put(READER_RED_TOUCH_MANAGER, bmfv.class);
    sManagerArrays.put(MUTUAL_MARK_MANAGER, axlz.class);
    sManagerArrays.put(TROOP_MEMBER_RECOMMEND_MANAGER, axia.class);
    sManagerArrays.put(SDK_SHARE, auuc.class);
    sManagerArrays.put(PIC_OCR_MANAGER, avaq.class);
    sManagerArrays.put(TROOP_SHORTCUTBAR_MANAGER, bgbg.class);
    sManagerArrays.put(STUDY_ROOM_MANAGER, bdvz.class);
    sManagerArrays.put(AUDIO_DEVICE_MANAGER, AudioDeviceManager.class);
    sManagerArrays.put(RIJ_UGC_VIDEO_PUBLISH_MANAGER, sad.class);
    sManagerArrays.put(FOREGROUND_NOTIFY_MANAGER, anui.class);
    sManagerArrays.put(MINI_APP_SEARCH_MANAGER, MiniAppSearchDataManager.class);
    sManagerArrays.put(TROOPAPP_SHORTCUT_MANAGER, bgfr.class);
    sManagerArrays.put(GAME_CENTER_MSG_MANAGER, avds.class);
    sManagerArrays.put(QWALLET_GDT_AD_MANAGER, akrc.class);
    sManagerArrays.put(SCENES_REC_EMO_MANAGER, ScenesRecommendManager.class);
    sManagerArrays.put(UPCOMING_MSG_PRE_MANAGER, aimn.class);
    sManagerArrays.put(RECENT_USER, alku.class);
    sManagerArrays.put(TOFUMSG_MANAGER, bejk.class);
    sManagerArrays.put(LONG_ARK_MSG_MANAGER, axig.class);
    sManagerArrays.put(TROOP_IMPORTANT_MSG_MANAGER, bgbv.class);
    sManagerArrays.put(WRITE_TOGETHER_MANAGER, benm.class);
    sManagerArrays.put(QQ_NOTIFY_MANAGER, afno.class);
    sManagerArrays.put(CUSTOMIZE_GRAY_TIPS, avhp.class);
    sManagerArrays.put(C2C_SHORTCUT_BAR_MANAGER, aqlp.class);
    sManagerArrays.put(TROOP_ESSENCE_MSG_MANAGER, bflc.class);
    sManagerArrays.put(PAI_YI_PAI_MANAGER, afza.class);
    sManagerArrays.put(NEWER_GUIDE_BANNER_MANAGER, alkd.class);
    sManagerArrays.put(FRIEND_CLUE_MANAGER, bbcx.class);
    sManagerArrays.put(VOICE_ASSISTANT_MANAGER, bakx.class);
    sManagerArrays.put(ANONYMOUS_ANSWER_MANAGER, azzr.class);
    sManagerArrays.put(ILIVE_GROUP_TIPS_MANAGER, blvf.class);
    sManagerArrays.put(QCIRCLE_LBS_MANAGER, QcircleLbsService.class);
    sManagerArrays.put(APOLLO_RES_MANAGER, ApolloResManager.class);
    sManagerArrays.put(MINI_CARD_MANAGER, aydj.class);
    sManagerArrays.put(TROOP_GAME_CARD_MANAGER, bgfx.class);
    sManagerArrays.put(TROOP_LUCKY_CHARACTER_MANAGER, bfyc.class);
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes8.jar
 * Qualified Name:     com.tencent.mobileqq.app.QQManagerFactory
 * JD-Core Version:    0.7.0.1
 */