package com.tencent.mobileqq.kandian.biz.hippy.module;

import kotlin.Metadata;

@Metadata(bv={1, 0, 3}, d1={""}, d2={"Lcom/tencent/mobileqq/kandian/biz/hippy/module/TKDCommentBizModule$Companion;", "", "()V", "ARG_ANCHOR_ID", "", "ARG_ANONYMOUS", "ARG_ARTICLE_ID", "ARG_COMMENT", "ARG_COMMENT_ID", "ARG_COMMENT_INFO", "ARG_COMMENT_NUM", "ARG_COMMENT_TYPE", "ARG_CONTENT_SRC", "ARG_DEFAULT_TEXT", "ARG_ERROR_CODE", "ARG_EXTRA_PARAMS", "ARG_FIRST_COMMENT_ID", "ARG_FORBID", "ARG_FORBIDDEN", "ARG_HINT", "ARG_IS_LIKE", "ARG_IS_PGC_AUTHOR", "ARG_MAX_TEXT_LIMIT", "ARG_MINI_APP_URL", "ARG_PUBLISHER_CONFIG", "ARG_READ_TIME", "ARG_REPLIED_COMMENT_ID", "ARG_REPLIED_SUB_AUTHOR_ID", "ARG_REPLIED_SUB_COMMENT_ID", "ARG_REPLY_HAS_LINK", "ARG_RESULT_CODE", "ARG_ROW_KEY", "ARG_SCENE", "ARG_SHOW_AT_ICON", "ARG_SHOW_BIU_ICON", "ARG_SOURCE_TYPE", "ARG_STATUS", "ARG_SUB_COMMENT", "ARG_SUB_COMMENT_ID", "EVENT_CLOSECOMMENT", "EVENT_CLOSECOMMENT_DIRECTION_RIGHT", "EVENT_CLOSECOMMENT_KEY_DIRECTION", "EVENT_DELETE_SUB_COMMENT", "EVENT_DEL_MAIN_COMMENT", "EVENT_FONTSCALE", "EVENT_FONTSCALE_SCALEFACTOR", "EVENT_INSERT_SUB_COMMENT", "EVENT_LIFECYCLE", "EVENT_LIFECYCLE_KEY", "EVENT_LIKE_MAIN_COMMENT", "EVENT_ONACTIVE", "EVENT_ONDEACTIVE", "EVENT_ONDESTROY", "EVENT_ONSTART", "EVENT_OPEN_PUBLISHER", "EVENT_REFRESH_NEW_HOT", "EVENT_REPORT_COMMENT_READ_TIME", "EVENT_UPDATE_FOLLOW_UI", "REQ_CODE_COMMENT_EDITOR_NATIVE", "", "RET_CODE_CANCELED", "RET_CODE_FAILED", "RET_CODE_SUCCEED", "TAG", "kandian_feature_impl_release"}, k=1, mv={1, 1, 16})
public final class TKDCommentBizModule$Companion {}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes16.jar
 * Qualified Name:     com.tencent.mobileqq.kandian.biz.hippy.module.TKDCommentBizModule.Companion
 * JD-Core Version:    0.7.0.1
 */