package com.android.dx.io;

import com.android.dx.io.instructions.InstructionCodec;
import com.android.dx.util.Hex;

public final class OpcodeInfo
{
  public static final OpcodeInfo.Info ADD_DOUBLE;
  public static final OpcodeInfo.Info ADD_DOUBLE_2ADDR;
  public static final OpcodeInfo.Info ADD_FLOAT;
  public static final OpcodeInfo.Info ADD_FLOAT_2ADDR;
  public static final OpcodeInfo.Info ADD_INT;
  public static final OpcodeInfo.Info ADD_INT_2ADDR;
  public static final OpcodeInfo.Info ADD_INT_LIT16;
  public static final OpcodeInfo.Info ADD_INT_LIT8;
  public static final OpcodeInfo.Info ADD_LONG;
  public static final OpcodeInfo.Info ADD_LONG_2ADDR;
  public static final OpcodeInfo.Info AGET;
  public static final OpcodeInfo.Info AGET_BOOLEAN;
  public static final OpcodeInfo.Info AGET_BYTE;
  public static final OpcodeInfo.Info AGET_CHAR;
  public static final OpcodeInfo.Info AGET_OBJECT;
  public static final OpcodeInfo.Info AGET_SHORT;
  public static final OpcodeInfo.Info AGET_WIDE;
  public static final OpcodeInfo.Info AND_INT;
  public static final OpcodeInfo.Info AND_INT_2ADDR;
  public static final OpcodeInfo.Info AND_INT_LIT16;
  public static final OpcodeInfo.Info AND_INT_LIT8;
  public static final OpcodeInfo.Info AND_LONG;
  public static final OpcodeInfo.Info AND_LONG_2ADDR;
  public static final OpcodeInfo.Info APUT;
  public static final OpcodeInfo.Info APUT_BOOLEAN;
  public static final OpcodeInfo.Info APUT_BYTE;
  public static final OpcodeInfo.Info APUT_CHAR;
  public static final OpcodeInfo.Info APUT_OBJECT;
  public static final OpcodeInfo.Info APUT_SHORT;
  public static final OpcodeInfo.Info APUT_WIDE;
  public static final OpcodeInfo.Info ARRAY_LENGTH;
  public static final OpcodeInfo.Info CHECK_CAST;
  public static final OpcodeInfo.Info CMPG_DOUBLE;
  public static final OpcodeInfo.Info CMPG_FLOAT;
  public static final OpcodeInfo.Info CMPL_DOUBLE;
  public static final OpcodeInfo.Info CMPL_FLOAT;
  public static final OpcodeInfo.Info CMP_LONG;
  public static final OpcodeInfo.Info CONST;
  public static final OpcodeInfo.Info CONST_16;
  public static final OpcodeInfo.Info CONST_4;
  public static final OpcodeInfo.Info CONST_CLASS;
  public static final OpcodeInfo.Info CONST_HIGH16;
  public static final OpcodeInfo.Info CONST_STRING;
  public static final OpcodeInfo.Info CONST_STRING_JUMBO;
  public static final OpcodeInfo.Info CONST_WIDE;
  public static final OpcodeInfo.Info CONST_WIDE_16;
  public static final OpcodeInfo.Info CONST_WIDE_32;
  public static final OpcodeInfo.Info CONST_WIDE_HIGH16;
  public static final OpcodeInfo.Info DIV_DOUBLE;
  public static final OpcodeInfo.Info DIV_DOUBLE_2ADDR;
  public static final OpcodeInfo.Info DIV_FLOAT;
  public static final OpcodeInfo.Info DIV_FLOAT_2ADDR;
  public static final OpcodeInfo.Info DIV_INT;
  public static final OpcodeInfo.Info DIV_INT_2ADDR;
  public static final OpcodeInfo.Info DIV_INT_LIT16;
  public static final OpcodeInfo.Info DIV_INT_LIT8;
  public static final OpcodeInfo.Info DIV_LONG;
  public static final OpcodeInfo.Info DIV_LONG_2ADDR;
  public static final OpcodeInfo.Info DOUBLE_TO_FLOAT;
  public static final OpcodeInfo.Info DOUBLE_TO_INT;
  public static final OpcodeInfo.Info DOUBLE_TO_LONG;
  public static final OpcodeInfo.Info FILLED_NEW_ARRAY;
  public static final OpcodeInfo.Info FILLED_NEW_ARRAY_RANGE;
  public static final OpcodeInfo.Info FILL_ARRAY_DATA;
  public static final OpcodeInfo.Info FILL_ARRAY_DATA_PAYLOAD;
  public static final OpcodeInfo.Info FLOAT_TO_DOUBLE;
  public static final OpcodeInfo.Info FLOAT_TO_INT;
  public static final OpcodeInfo.Info FLOAT_TO_LONG;
  public static final OpcodeInfo.Info GOTO;
  public static final OpcodeInfo.Info GOTO_16;
  public static final OpcodeInfo.Info GOTO_32;
  public static final OpcodeInfo.Info IF_EQ;
  public static final OpcodeInfo.Info IF_EQZ;
  public static final OpcodeInfo.Info IF_GE;
  public static final OpcodeInfo.Info IF_GEZ;
  public static final OpcodeInfo.Info IF_GT;
  public static final OpcodeInfo.Info IF_GTZ;
  public static final OpcodeInfo.Info IF_LE;
  public static final OpcodeInfo.Info IF_LEZ;
  public static final OpcodeInfo.Info IF_LT;
  public static final OpcodeInfo.Info IF_LTZ;
  public static final OpcodeInfo.Info IF_NE;
  public static final OpcodeInfo.Info IF_NEZ;
  public static final OpcodeInfo.Info IGET;
  public static final OpcodeInfo.Info IGET_BOOLEAN;
  public static final OpcodeInfo.Info IGET_BYTE;
  public static final OpcodeInfo.Info IGET_CHAR;
  public static final OpcodeInfo.Info IGET_OBJECT;
  public static final OpcodeInfo.Info IGET_SHORT;
  public static final OpcodeInfo.Info IGET_WIDE;
  private static final OpcodeInfo.Info[] INFO;
  public static final OpcodeInfo.Info INSTANCE_OF;
  public static final OpcodeInfo.Info INT_TO_BYTE;
  public static final OpcodeInfo.Info INT_TO_CHAR;
  public static final OpcodeInfo.Info INT_TO_DOUBLE;
  public static final OpcodeInfo.Info INT_TO_FLOAT;
  public static final OpcodeInfo.Info INT_TO_LONG;
  public static final OpcodeInfo.Info INT_TO_SHORT;
  public static final OpcodeInfo.Info INVOKE_DIRECT;
  public static final OpcodeInfo.Info INVOKE_DIRECT_RANGE;
  public static final OpcodeInfo.Info INVOKE_INTERFACE;
  public static final OpcodeInfo.Info INVOKE_INTERFACE_RANGE;
  public static final OpcodeInfo.Info INVOKE_STATIC;
  public static final OpcodeInfo.Info INVOKE_STATIC_RANGE;
  public static final OpcodeInfo.Info INVOKE_SUPER;
  public static final OpcodeInfo.Info INVOKE_SUPER_RANGE;
  public static final OpcodeInfo.Info INVOKE_VIRTUAL;
  public static final OpcodeInfo.Info INVOKE_VIRTUAL_RANGE;
  public static final OpcodeInfo.Info IPUT;
  public static final OpcodeInfo.Info IPUT_BOOLEAN;
  public static final OpcodeInfo.Info IPUT_BYTE;
  public static final OpcodeInfo.Info IPUT_CHAR;
  public static final OpcodeInfo.Info IPUT_OBJECT;
  public static final OpcodeInfo.Info IPUT_SHORT;
  public static final OpcodeInfo.Info IPUT_WIDE;
  public static final OpcodeInfo.Info LONG_TO_DOUBLE;
  public static final OpcodeInfo.Info LONG_TO_FLOAT;
  public static final OpcodeInfo.Info LONG_TO_INT;
  public static final OpcodeInfo.Info MONITOR_ENTER;
  public static final OpcodeInfo.Info MONITOR_EXIT;
  public static final OpcodeInfo.Info MOVE;
  public static final OpcodeInfo.Info MOVE_16;
  public static final OpcodeInfo.Info MOVE_EXCEPTION;
  public static final OpcodeInfo.Info MOVE_FROM16;
  public static final OpcodeInfo.Info MOVE_OBJECT;
  public static final OpcodeInfo.Info MOVE_OBJECT_16;
  public static final OpcodeInfo.Info MOVE_OBJECT_FROM16;
  public static final OpcodeInfo.Info MOVE_RESULT;
  public static final OpcodeInfo.Info MOVE_RESULT_OBJECT;
  public static final OpcodeInfo.Info MOVE_RESULT_WIDE;
  public static final OpcodeInfo.Info MOVE_WIDE;
  public static final OpcodeInfo.Info MOVE_WIDE_16;
  public static final OpcodeInfo.Info MOVE_WIDE_FROM16;
  public static final OpcodeInfo.Info MUL_DOUBLE;
  public static final OpcodeInfo.Info MUL_DOUBLE_2ADDR;
  public static final OpcodeInfo.Info MUL_FLOAT;
  public static final OpcodeInfo.Info MUL_FLOAT_2ADDR;
  public static final OpcodeInfo.Info MUL_INT;
  public static final OpcodeInfo.Info MUL_INT_2ADDR;
  public static final OpcodeInfo.Info MUL_INT_LIT16;
  public static final OpcodeInfo.Info MUL_INT_LIT8;
  public static final OpcodeInfo.Info MUL_LONG;
  public static final OpcodeInfo.Info MUL_LONG_2ADDR;
  public static final OpcodeInfo.Info NEG_DOUBLE;
  public static final OpcodeInfo.Info NEG_FLOAT;
  public static final OpcodeInfo.Info NEG_INT;
  public static final OpcodeInfo.Info NEG_LONG;
  public static final OpcodeInfo.Info NEW_ARRAY;
  public static final OpcodeInfo.Info NEW_INSTANCE;
  public static final OpcodeInfo.Info NOP;
  public static final OpcodeInfo.Info NOT_INT;
  public static final OpcodeInfo.Info NOT_LONG;
  public static final OpcodeInfo.Info OR_INT;
  public static final OpcodeInfo.Info OR_INT_2ADDR;
  public static final OpcodeInfo.Info OR_INT_LIT16;
  public static final OpcodeInfo.Info OR_INT_LIT8;
  public static final OpcodeInfo.Info OR_LONG;
  public static final OpcodeInfo.Info OR_LONG_2ADDR;
  public static final OpcodeInfo.Info PACKED_SWITCH;
  public static final OpcodeInfo.Info PACKED_SWITCH_PAYLOAD;
  public static final OpcodeInfo.Info REM_DOUBLE;
  public static final OpcodeInfo.Info REM_DOUBLE_2ADDR;
  public static final OpcodeInfo.Info REM_FLOAT;
  public static final OpcodeInfo.Info REM_FLOAT_2ADDR;
  public static final OpcodeInfo.Info REM_INT;
  public static final OpcodeInfo.Info REM_INT_2ADDR;
  public static final OpcodeInfo.Info REM_INT_LIT16;
  public static final OpcodeInfo.Info REM_INT_LIT8;
  public static final OpcodeInfo.Info REM_LONG;
  public static final OpcodeInfo.Info REM_LONG_2ADDR;
  public static final OpcodeInfo.Info RETURN;
  public static final OpcodeInfo.Info RETURN_OBJECT;
  public static final OpcodeInfo.Info RETURN_VOID;
  public static final OpcodeInfo.Info RETURN_WIDE;
  public static final OpcodeInfo.Info RSUB_INT;
  public static final OpcodeInfo.Info RSUB_INT_LIT8;
  public static final OpcodeInfo.Info SGET;
  public static final OpcodeInfo.Info SGET_BOOLEAN;
  public static final OpcodeInfo.Info SGET_BYTE;
  public static final OpcodeInfo.Info SGET_CHAR;
  public static final OpcodeInfo.Info SGET_OBJECT;
  public static final OpcodeInfo.Info SGET_SHORT;
  public static final OpcodeInfo.Info SGET_WIDE;
  public static final OpcodeInfo.Info SHL_INT;
  public static final OpcodeInfo.Info SHL_INT_2ADDR;
  public static final OpcodeInfo.Info SHL_INT_LIT8;
  public static final OpcodeInfo.Info SHL_LONG;
  public static final OpcodeInfo.Info SHL_LONG_2ADDR;
  public static final OpcodeInfo.Info SHR_INT;
  public static final OpcodeInfo.Info SHR_INT_2ADDR;
  public static final OpcodeInfo.Info SHR_INT_LIT8;
  public static final OpcodeInfo.Info SHR_LONG;
  public static final OpcodeInfo.Info SHR_LONG_2ADDR;
  public static final OpcodeInfo.Info SPARSE_SWITCH;
  public static final OpcodeInfo.Info SPARSE_SWITCH_PAYLOAD;
  public static final OpcodeInfo.Info SPECIAL_FORMAT = new OpcodeInfo.Info(-1, "<special>", InstructionCodec.FORMAT_00X, IndexType.NONE);
  public static final OpcodeInfo.Info SPUT;
  public static final OpcodeInfo.Info SPUT_BOOLEAN;
  public static final OpcodeInfo.Info SPUT_BYTE;
  public static final OpcodeInfo.Info SPUT_CHAR;
  public static final OpcodeInfo.Info SPUT_OBJECT;
  public static final OpcodeInfo.Info SPUT_SHORT;
  public static final OpcodeInfo.Info SPUT_WIDE;
  public static final OpcodeInfo.Info SUB_DOUBLE;
  public static final OpcodeInfo.Info SUB_DOUBLE_2ADDR;
  public static final OpcodeInfo.Info SUB_FLOAT;
  public static final OpcodeInfo.Info SUB_FLOAT_2ADDR;
  public static final OpcodeInfo.Info SUB_INT;
  public static final OpcodeInfo.Info SUB_INT_2ADDR;
  public static final OpcodeInfo.Info SUB_LONG;
  public static final OpcodeInfo.Info SUB_LONG_2ADDR;
  public static final OpcodeInfo.Info THROW;
  public static final OpcodeInfo.Info USHR_INT;
  public static final OpcodeInfo.Info USHR_INT_2ADDR;
  public static final OpcodeInfo.Info USHR_INT_LIT8;
  public static final OpcodeInfo.Info USHR_LONG;
  public static final OpcodeInfo.Info USHR_LONG_2ADDR;
  public static final OpcodeInfo.Info XOR_INT;
  public static final OpcodeInfo.Info XOR_INT_2ADDR;
  public static final OpcodeInfo.Info XOR_INT_LIT16;
  public static final OpcodeInfo.Info XOR_INT_LIT8;
  public static final OpcodeInfo.Info XOR_LONG;
  public static final OpcodeInfo.Info XOR_LONG_2ADDR;
  
  static
  {
    PACKED_SWITCH_PAYLOAD = new OpcodeInfo.Info(256, "packed-switch-payload", InstructionCodec.FORMAT_PACKED_SWITCH_PAYLOAD, IndexType.NONE);
    SPARSE_SWITCH_PAYLOAD = new OpcodeInfo.Info(512, "sparse-switch-payload", InstructionCodec.FORMAT_SPARSE_SWITCH_PAYLOAD, IndexType.NONE);
    FILL_ARRAY_DATA_PAYLOAD = new OpcodeInfo.Info(768, "fill-array-data-payload", InstructionCodec.FORMAT_FILL_ARRAY_DATA_PAYLOAD, IndexType.NONE);
    NOP = new OpcodeInfo.Info(0, "nop", InstructionCodec.FORMAT_10X, IndexType.NONE);
    MOVE = new OpcodeInfo.Info(1, "move", InstructionCodec.FORMAT_12X, IndexType.NONE);
    MOVE_FROM16 = new OpcodeInfo.Info(2, "move/from16", InstructionCodec.FORMAT_22X, IndexType.NONE);
    MOVE_16 = new OpcodeInfo.Info(3, "move/16", InstructionCodec.FORMAT_32X, IndexType.NONE);
    MOVE_WIDE = new OpcodeInfo.Info(4, "move-wide", InstructionCodec.FORMAT_12X, IndexType.NONE);
    MOVE_WIDE_FROM16 = new OpcodeInfo.Info(5, "move-wide/from16", InstructionCodec.FORMAT_22X, IndexType.NONE);
    MOVE_WIDE_16 = new OpcodeInfo.Info(6, "move-wide/16", InstructionCodec.FORMAT_32X, IndexType.NONE);
    MOVE_OBJECT = new OpcodeInfo.Info(7, "move-object", InstructionCodec.FORMAT_12X, IndexType.NONE);
    MOVE_OBJECT_FROM16 = new OpcodeInfo.Info(8, "move-object/from16", InstructionCodec.FORMAT_22X, IndexType.NONE);
    MOVE_OBJECT_16 = new OpcodeInfo.Info(9, "move-object/16", InstructionCodec.FORMAT_32X, IndexType.NONE);
    MOVE_RESULT = new OpcodeInfo.Info(10, "move-result", InstructionCodec.FORMAT_11X, IndexType.NONE);
    MOVE_RESULT_WIDE = new OpcodeInfo.Info(11, "move-result-wide", InstructionCodec.FORMAT_11X, IndexType.NONE);
    MOVE_RESULT_OBJECT = new OpcodeInfo.Info(12, "move-result-object", InstructionCodec.FORMAT_11X, IndexType.NONE);
    MOVE_EXCEPTION = new OpcodeInfo.Info(13, "move-exception", InstructionCodec.FORMAT_11X, IndexType.NONE);
    RETURN_VOID = new OpcodeInfo.Info(14, "return-void", InstructionCodec.FORMAT_10X, IndexType.NONE);
    RETURN = new OpcodeInfo.Info(15, "return", InstructionCodec.FORMAT_11X, IndexType.NONE);
    RETURN_WIDE = new OpcodeInfo.Info(16, "return-wide", InstructionCodec.FORMAT_11X, IndexType.NONE);
    RETURN_OBJECT = new OpcodeInfo.Info(17, "return-object", InstructionCodec.FORMAT_11X, IndexType.NONE);
    CONST_4 = new OpcodeInfo.Info(18, "const/4", InstructionCodec.FORMAT_11N, IndexType.NONE);
    CONST_16 = new OpcodeInfo.Info(19, "const/16", InstructionCodec.FORMAT_21S, IndexType.NONE);
    CONST = new OpcodeInfo.Info(20, "const", InstructionCodec.FORMAT_31I, IndexType.NONE);
    CONST_HIGH16 = new OpcodeInfo.Info(21, "const/high16", InstructionCodec.FORMAT_21H, IndexType.NONE);
    CONST_WIDE_16 = new OpcodeInfo.Info(22, "const-wide/16", InstructionCodec.FORMAT_21S, IndexType.NONE);
    CONST_WIDE_32 = new OpcodeInfo.Info(23, "const-wide/32", InstructionCodec.FORMAT_31I, IndexType.NONE);
    CONST_WIDE = new OpcodeInfo.Info(24, "const-wide", InstructionCodec.FORMAT_51L, IndexType.NONE);
    CONST_WIDE_HIGH16 = new OpcodeInfo.Info(25, "const-wide/high16", InstructionCodec.FORMAT_21H, IndexType.NONE);
    CONST_STRING = new OpcodeInfo.Info(26, "const-string", InstructionCodec.FORMAT_21C, IndexType.STRING_REF);
    CONST_STRING_JUMBO = new OpcodeInfo.Info(27, "const-string/jumbo", InstructionCodec.FORMAT_31C, IndexType.STRING_REF);
    CONST_CLASS = new OpcodeInfo.Info(28, "const-class", InstructionCodec.FORMAT_21C, IndexType.TYPE_REF);
    MONITOR_ENTER = new OpcodeInfo.Info(29, "monitor-enter", InstructionCodec.FORMAT_11X, IndexType.NONE);
    MONITOR_EXIT = new OpcodeInfo.Info(30, "monitor-exit", InstructionCodec.FORMAT_11X, IndexType.NONE);
    CHECK_CAST = new OpcodeInfo.Info(31, "check-cast", InstructionCodec.FORMAT_21C, IndexType.TYPE_REF);
    INSTANCE_OF = new OpcodeInfo.Info(32, "instance-of", InstructionCodec.FORMAT_22C, IndexType.TYPE_REF);
    ARRAY_LENGTH = new OpcodeInfo.Info(33, "array-length", InstructionCodec.FORMAT_12X, IndexType.NONE);
    NEW_INSTANCE = new OpcodeInfo.Info(34, "new-instance", InstructionCodec.FORMAT_21C, IndexType.TYPE_REF);
    NEW_ARRAY = new OpcodeInfo.Info(35, "new-array", InstructionCodec.FORMAT_22C, IndexType.TYPE_REF);
    FILLED_NEW_ARRAY = new OpcodeInfo.Info(36, "filled-new-array", InstructionCodec.FORMAT_35C, IndexType.TYPE_REF);
    FILLED_NEW_ARRAY_RANGE = new OpcodeInfo.Info(37, "filled-new-array/range", InstructionCodec.FORMAT_3RC, IndexType.TYPE_REF);
    FILL_ARRAY_DATA = new OpcodeInfo.Info(38, "fill-array-data", InstructionCodec.FORMAT_31T, IndexType.NONE);
    THROW = new OpcodeInfo.Info(39, "throw", InstructionCodec.FORMAT_11X, IndexType.NONE);
    GOTO = new OpcodeInfo.Info(40, "goto", InstructionCodec.FORMAT_10T, IndexType.NONE);
    GOTO_16 = new OpcodeInfo.Info(41, "goto/16", InstructionCodec.FORMAT_20T, IndexType.NONE);
    GOTO_32 = new OpcodeInfo.Info(42, "goto/32", InstructionCodec.FORMAT_30T, IndexType.NONE);
    PACKED_SWITCH = new OpcodeInfo.Info(43, "packed-switch", InstructionCodec.FORMAT_31T, IndexType.NONE);
    SPARSE_SWITCH = new OpcodeInfo.Info(44, "sparse-switch", InstructionCodec.FORMAT_31T, IndexType.NONE);
    CMPL_FLOAT = new OpcodeInfo.Info(45, "cmpl-float", InstructionCodec.FORMAT_23X, IndexType.NONE);
    CMPG_FLOAT = new OpcodeInfo.Info(46, "cmpg-float", InstructionCodec.FORMAT_23X, IndexType.NONE);
    CMPL_DOUBLE = new OpcodeInfo.Info(47, "cmpl-double", InstructionCodec.FORMAT_23X, IndexType.NONE);
    CMPG_DOUBLE = new OpcodeInfo.Info(48, "cmpg-double", InstructionCodec.FORMAT_23X, IndexType.NONE);
    CMP_LONG = new OpcodeInfo.Info(49, "cmp-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    IF_EQ = new OpcodeInfo.Info(50, "if-eq", InstructionCodec.FORMAT_22T, IndexType.NONE);
    IF_NE = new OpcodeInfo.Info(51, "if-ne", InstructionCodec.FORMAT_22T, IndexType.NONE);
    IF_LT = new OpcodeInfo.Info(52, "if-lt", InstructionCodec.FORMAT_22T, IndexType.NONE);
    IF_GE = new OpcodeInfo.Info(53, "if-ge", InstructionCodec.FORMAT_22T, IndexType.NONE);
    IF_GT = new OpcodeInfo.Info(54, "if-gt", InstructionCodec.FORMAT_22T, IndexType.NONE);
    IF_LE = new OpcodeInfo.Info(55, "if-le", InstructionCodec.FORMAT_22T, IndexType.NONE);
    IF_EQZ = new OpcodeInfo.Info(56, "if-eqz", InstructionCodec.FORMAT_21T, IndexType.NONE);
    IF_NEZ = new OpcodeInfo.Info(57, "if-nez", InstructionCodec.FORMAT_21T, IndexType.NONE);
    IF_LTZ = new OpcodeInfo.Info(58, "if-ltz", InstructionCodec.FORMAT_21T, IndexType.NONE);
    IF_GEZ = new OpcodeInfo.Info(59, "if-gez", InstructionCodec.FORMAT_21T, IndexType.NONE);
    IF_GTZ = new OpcodeInfo.Info(60, "if-gtz", InstructionCodec.FORMAT_21T, IndexType.NONE);
    IF_LEZ = new OpcodeInfo.Info(61, "if-lez", InstructionCodec.FORMAT_21T, IndexType.NONE);
    AGET = new OpcodeInfo.Info(68, "aget", InstructionCodec.FORMAT_23X, IndexType.NONE);
    AGET_WIDE = new OpcodeInfo.Info(69, "aget-wide", InstructionCodec.FORMAT_23X, IndexType.NONE);
    AGET_OBJECT = new OpcodeInfo.Info(70, "aget-object", InstructionCodec.FORMAT_23X, IndexType.NONE);
    AGET_BOOLEAN = new OpcodeInfo.Info(71, "aget-boolean", InstructionCodec.FORMAT_23X, IndexType.NONE);
    AGET_BYTE = new OpcodeInfo.Info(72, "aget-byte", InstructionCodec.FORMAT_23X, IndexType.NONE);
    AGET_CHAR = new OpcodeInfo.Info(73, "aget-char", InstructionCodec.FORMAT_23X, IndexType.NONE);
    AGET_SHORT = new OpcodeInfo.Info(74, "aget-short", InstructionCodec.FORMAT_23X, IndexType.NONE);
    APUT = new OpcodeInfo.Info(75, "aput", InstructionCodec.FORMAT_23X, IndexType.NONE);
    APUT_WIDE = new OpcodeInfo.Info(76, "aput-wide", InstructionCodec.FORMAT_23X, IndexType.NONE);
    APUT_OBJECT = new OpcodeInfo.Info(77, "aput-object", InstructionCodec.FORMAT_23X, IndexType.NONE);
    APUT_BOOLEAN = new OpcodeInfo.Info(78, "aput-boolean", InstructionCodec.FORMAT_23X, IndexType.NONE);
    APUT_BYTE = new OpcodeInfo.Info(79, "aput-byte", InstructionCodec.FORMAT_23X, IndexType.NONE);
    APUT_CHAR = new OpcodeInfo.Info(80, "aput-char", InstructionCodec.FORMAT_23X, IndexType.NONE);
    APUT_SHORT = new OpcodeInfo.Info(81, "aput-short", InstructionCodec.FORMAT_23X, IndexType.NONE);
    IGET = new OpcodeInfo.Info(82, "iget", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IGET_WIDE = new OpcodeInfo.Info(83, "iget-wide", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IGET_OBJECT = new OpcodeInfo.Info(84, "iget-object", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IGET_BOOLEAN = new OpcodeInfo.Info(85, "iget-boolean", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IGET_BYTE = new OpcodeInfo.Info(86, "iget-byte", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IGET_CHAR = new OpcodeInfo.Info(87, "iget-char", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IGET_SHORT = new OpcodeInfo.Info(88, "iget-short", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IPUT = new OpcodeInfo.Info(89, "iput", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IPUT_WIDE = new OpcodeInfo.Info(90, "iput-wide", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IPUT_OBJECT = new OpcodeInfo.Info(91, "iput-object", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IPUT_BOOLEAN = new OpcodeInfo.Info(92, "iput-boolean", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IPUT_BYTE = new OpcodeInfo.Info(93, "iput-byte", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IPUT_CHAR = new OpcodeInfo.Info(94, "iput-char", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    IPUT_SHORT = new OpcodeInfo.Info(95, "iput-short", InstructionCodec.FORMAT_22C, IndexType.FIELD_REF);
    SGET = new OpcodeInfo.Info(96, "sget", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SGET_WIDE = new OpcodeInfo.Info(97, "sget-wide", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SGET_OBJECT = new OpcodeInfo.Info(98, "sget-object", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SGET_BOOLEAN = new OpcodeInfo.Info(99, "sget-boolean", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SGET_BYTE = new OpcodeInfo.Info(100, "sget-byte", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SGET_CHAR = new OpcodeInfo.Info(101, "sget-char", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SGET_SHORT = new OpcodeInfo.Info(102, "sget-short", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SPUT = new OpcodeInfo.Info(103, "sput", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SPUT_WIDE = new OpcodeInfo.Info(104, "sput-wide", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SPUT_OBJECT = new OpcodeInfo.Info(105, "sput-object", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SPUT_BOOLEAN = new OpcodeInfo.Info(106, "sput-boolean", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SPUT_BYTE = new OpcodeInfo.Info(107, "sput-byte", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SPUT_CHAR = new OpcodeInfo.Info(108, "sput-char", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    SPUT_SHORT = new OpcodeInfo.Info(109, "sput-short", InstructionCodec.FORMAT_21C, IndexType.FIELD_REF);
    INVOKE_VIRTUAL = new OpcodeInfo.Info(110, "invoke-virtual", InstructionCodec.FORMAT_35C, IndexType.METHOD_REF);
    INVOKE_SUPER = new OpcodeInfo.Info(111, "invoke-super", InstructionCodec.FORMAT_35C, IndexType.METHOD_REF);
    INVOKE_DIRECT = new OpcodeInfo.Info(112, "invoke-direct", InstructionCodec.FORMAT_35C, IndexType.METHOD_REF);
    INVOKE_STATIC = new OpcodeInfo.Info(113, "invoke-static", InstructionCodec.FORMAT_35C, IndexType.METHOD_REF);
    INVOKE_INTERFACE = new OpcodeInfo.Info(114, "invoke-interface", InstructionCodec.FORMAT_35C, IndexType.METHOD_REF);
    INVOKE_VIRTUAL_RANGE = new OpcodeInfo.Info(116, "invoke-virtual/range", InstructionCodec.FORMAT_3RC, IndexType.METHOD_REF);
    INVOKE_SUPER_RANGE = new OpcodeInfo.Info(117, "invoke-super/range", InstructionCodec.FORMAT_3RC, IndexType.METHOD_REF);
    INVOKE_DIRECT_RANGE = new OpcodeInfo.Info(118, "invoke-direct/range", InstructionCodec.FORMAT_3RC, IndexType.METHOD_REF);
    INVOKE_STATIC_RANGE = new OpcodeInfo.Info(119, "invoke-static/range", InstructionCodec.FORMAT_3RC, IndexType.METHOD_REF);
    INVOKE_INTERFACE_RANGE = new OpcodeInfo.Info(120, "invoke-interface/range", InstructionCodec.FORMAT_3RC, IndexType.METHOD_REF);
    NEG_INT = new OpcodeInfo.Info(123, "neg-int", InstructionCodec.FORMAT_12X, IndexType.NONE);
    NOT_INT = new OpcodeInfo.Info(124, "not-int", InstructionCodec.FORMAT_12X, IndexType.NONE);
    NEG_LONG = new OpcodeInfo.Info(125, "neg-long", InstructionCodec.FORMAT_12X, IndexType.NONE);
    NOT_LONG = new OpcodeInfo.Info(126, "not-long", InstructionCodec.FORMAT_12X, IndexType.NONE);
    NEG_FLOAT = new OpcodeInfo.Info(127, "neg-float", InstructionCodec.FORMAT_12X, IndexType.NONE);
    NEG_DOUBLE = new OpcodeInfo.Info(128, "neg-double", InstructionCodec.FORMAT_12X, IndexType.NONE);
    INT_TO_LONG = new OpcodeInfo.Info(129, "int-to-long", InstructionCodec.FORMAT_12X, IndexType.NONE);
    INT_TO_FLOAT = new OpcodeInfo.Info(130, "int-to-float", InstructionCodec.FORMAT_12X, IndexType.NONE);
    INT_TO_DOUBLE = new OpcodeInfo.Info(131, "int-to-double", InstructionCodec.FORMAT_12X, IndexType.NONE);
    LONG_TO_INT = new OpcodeInfo.Info(132, "long-to-int", InstructionCodec.FORMAT_12X, IndexType.NONE);
    LONG_TO_FLOAT = new OpcodeInfo.Info(133, "long-to-float", InstructionCodec.FORMAT_12X, IndexType.NONE);
    LONG_TO_DOUBLE = new OpcodeInfo.Info(134, "long-to-double", InstructionCodec.FORMAT_12X, IndexType.NONE);
    FLOAT_TO_INT = new OpcodeInfo.Info(135, "float-to-int", InstructionCodec.FORMAT_12X, IndexType.NONE);
    FLOAT_TO_LONG = new OpcodeInfo.Info(136, "float-to-long", InstructionCodec.FORMAT_12X, IndexType.NONE);
    FLOAT_TO_DOUBLE = new OpcodeInfo.Info(137, "float-to-double", InstructionCodec.FORMAT_12X, IndexType.NONE);
    DOUBLE_TO_INT = new OpcodeInfo.Info(138, "double-to-int", InstructionCodec.FORMAT_12X, IndexType.NONE);
    DOUBLE_TO_LONG = new OpcodeInfo.Info(139, "double-to-long", InstructionCodec.FORMAT_12X, IndexType.NONE);
    DOUBLE_TO_FLOAT = new OpcodeInfo.Info(140, "double-to-float", InstructionCodec.FORMAT_12X, IndexType.NONE);
    INT_TO_BYTE = new OpcodeInfo.Info(141, "int-to-byte", InstructionCodec.FORMAT_12X, IndexType.NONE);
    INT_TO_CHAR = new OpcodeInfo.Info(142, "int-to-char", InstructionCodec.FORMAT_12X, IndexType.NONE);
    INT_TO_SHORT = new OpcodeInfo.Info(143, "int-to-short", InstructionCodec.FORMAT_12X, IndexType.NONE);
    ADD_INT = new OpcodeInfo.Info(144, "add-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    SUB_INT = new OpcodeInfo.Info(145, "sub-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    MUL_INT = new OpcodeInfo.Info(146, "mul-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    DIV_INT = new OpcodeInfo.Info(147, "div-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    REM_INT = new OpcodeInfo.Info(148, "rem-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    AND_INT = new OpcodeInfo.Info(149, "and-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    OR_INT = new OpcodeInfo.Info(150, "or-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    XOR_INT = new OpcodeInfo.Info(151, "xor-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    SHL_INT = new OpcodeInfo.Info(152, "shl-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    SHR_INT = new OpcodeInfo.Info(153, "shr-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    USHR_INT = new OpcodeInfo.Info(154, "ushr-int", InstructionCodec.FORMAT_23X, IndexType.NONE);
    ADD_LONG = new OpcodeInfo.Info(155, "add-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    SUB_LONG = new OpcodeInfo.Info(156, "sub-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    MUL_LONG = new OpcodeInfo.Info(157, "mul-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    DIV_LONG = new OpcodeInfo.Info(158, "div-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    REM_LONG = new OpcodeInfo.Info(159, "rem-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    AND_LONG = new OpcodeInfo.Info(160, "and-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    OR_LONG = new OpcodeInfo.Info(161, "or-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    XOR_LONG = new OpcodeInfo.Info(162, "xor-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    SHL_LONG = new OpcodeInfo.Info(163, "shl-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    SHR_LONG = new OpcodeInfo.Info(164, "shr-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    USHR_LONG = new OpcodeInfo.Info(165, "ushr-long", InstructionCodec.FORMAT_23X, IndexType.NONE);
    ADD_FLOAT = new OpcodeInfo.Info(166, "add-float", InstructionCodec.FORMAT_23X, IndexType.NONE);
    SUB_FLOAT = new OpcodeInfo.Info(167, "sub-float", InstructionCodec.FORMAT_23X, IndexType.NONE);
    MUL_FLOAT = new OpcodeInfo.Info(168, "mul-float", InstructionCodec.FORMAT_23X, IndexType.NONE);
    DIV_FLOAT = new OpcodeInfo.Info(169, "div-float", InstructionCodec.FORMAT_23X, IndexType.NONE);
    REM_FLOAT = new OpcodeInfo.Info(170, "rem-float", InstructionCodec.FORMAT_23X, IndexType.NONE);
    ADD_DOUBLE = new OpcodeInfo.Info(171, "add-double", InstructionCodec.FORMAT_23X, IndexType.NONE);
    SUB_DOUBLE = new OpcodeInfo.Info(172, "sub-double", InstructionCodec.FORMAT_23X, IndexType.NONE);
    MUL_DOUBLE = new OpcodeInfo.Info(173, "mul-double", InstructionCodec.FORMAT_23X, IndexType.NONE);
    DIV_DOUBLE = new OpcodeInfo.Info(174, "div-double", InstructionCodec.FORMAT_23X, IndexType.NONE);
    REM_DOUBLE = new OpcodeInfo.Info(175, "rem-double", InstructionCodec.FORMAT_23X, IndexType.NONE);
    ADD_INT_2ADDR = new OpcodeInfo.Info(176, "add-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    SUB_INT_2ADDR = new OpcodeInfo.Info(177, "sub-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    MUL_INT_2ADDR = new OpcodeInfo.Info(178, "mul-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    DIV_INT_2ADDR = new OpcodeInfo.Info(179, "div-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    REM_INT_2ADDR = new OpcodeInfo.Info(180, "rem-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    AND_INT_2ADDR = new OpcodeInfo.Info(181, "and-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    OR_INT_2ADDR = new OpcodeInfo.Info(182, "or-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    XOR_INT_2ADDR = new OpcodeInfo.Info(183, "xor-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    SHL_INT_2ADDR = new OpcodeInfo.Info(184, "shl-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    SHR_INT_2ADDR = new OpcodeInfo.Info(185, "shr-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    USHR_INT_2ADDR = new OpcodeInfo.Info(186, "ushr-int/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    ADD_LONG_2ADDR = new OpcodeInfo.Info(187, "add-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    SUB_LONG_2ADDR = new OpcodeInfo.Info(188, "sub-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    MUL_LONG_2ADDR = new OpcodeInfo.Info(189, "mul-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    DIV_LONG_2ADDR = new OpcodeInfo.Info(190, "div-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    REM_LONG_2ADDR = new OpcodeInfo.Info(191, "rem-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    AND_LONG_2ADDR = new OpcodeInfo.Info(192, "and-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    OR_LONG_2ADDR = new OpcodeInfo.Info(193, "or-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    XOR_LONG_2ADDR = new OpcodeInfo.Info(194, "xor-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    SHL_LONG_2ADDR = new OpcodeInfo.Info(195, "shl-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    SHR_LONG_2ADDR = new OpcodeInfo.Info(196, "shr-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    USHR_LONG_2ADDR = new OpcodeInfo.Info(197, "ushr-long/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    ADD_FLOAT_2ADDR = new OpcodeInfo.Info(198, "add-float/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    SUB_FLOAT_2ADDR = new OpcodeInfo.Info(199, "sub-float/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    MUL_FLOAT_2ADDR = new OpcodeInfo.Info(200, "mul-float/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    DIV_FLOAT_2ADDR = new OpcodeInfo.Info(201, "div-float/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    REM_FLOAT_2ADDR = new OpcodeInfo.Info(202, "rem-float/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    ADD_DOUBLE_2ADDR = new OpcodeInfo.Info(203, "add-double/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    SUB_DOUBLE_2ADDR = new OpcodeInfo.Info(204, "sub-double/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    MUL_DOUBLE_2ADDR = new OpcodeInfo.Info(205, "mul-double/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    DIV_DOUBLE_2ADDR = new OpcodeInfo.Info(206, "div-double/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    REM_DOUBLE_2ADDR = new OpcodeInfo.Info(207, "rem-double/2addr", InstructionCodec.FORMAT_12X, IndexType.NONE);
    ADD_INT_LIT16 = new OpcodeInfo.Info(208, "add-int/lit16", InstructionCodec.FORMAT_22S, IndexType.NONE);
    RSUB_INT = new OpcodeInfo.Info(209, "rsub-int", InstructionCodec.FORMAT_22S, IndexType.NONE);
    MUL_INT_LIT16 = new OpcodeInfo.Info(210, "mul-int/lit16", InstructionCodec.FORMAT_22S, IndexType.NONE);
    DIV_INT_LIT16 = new OpcodeInfo.Info(211, "div-int/lit16", InstructionCodec.FORMAT_22S, IndexType.NONE);
    REM_INT_LIT16 = new OpcodeInfo.Info(212, "rem-int/lit16", InstructionCodec.FORMAT_22S, IndexType.NONE);
    AND_INT_LIT16 = new OpcodeInfo.Info(213, "and-int/lit16", InstructionCodec.FORMAT_22S, IndexType.NONE);
    OR_INT_LIT16 = new OpcodeInfo.Info(214, "or-int/lit16", InstructionCodec.FORMAT_22S, IndexType.NONE);
    XOR_INT_LIT16 = new OpcodeInfo.Info(215, "xor-int/lit16", InstructionCodec.FORMAT_22S, IndexType.NONE);
    ADD_INT_LIT8 = new OpcodeInfo.Info(216, "add-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    RSUB_INT_LIT8 = new OpcodeInfo.Info(217, "rsub-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    MUL_INT_LIT8 = new OpcodeInfo.Info(218, "mul-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    DIV_INT_LIT8 = new OpcodeInfo.Info(219, "div-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    REM_INT_LIT8 = new OpcodeInfo.Info(220, "rem-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    AND_INT_LIT8 = new OpcodeInfo.Info(221, "and-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    OR_INT_LIT8 = new OpcodeInfo.Info(222, "or-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    XOR_INT_LIT8 = new OpcodeInfo.Info(223, "xor-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    SHL_INT_LIT8 = new OpcodeInfo.Info(224, "shl-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    SHR_INT_LIT8 = new OpcodeInfo.Info(225, "shr-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    USHR_INT_LIT8 = new OpcodeInfo.Info(226, "ushr-int/lit8", InstructionCodec.FORMAT_22B, IndexType.NONE);
    INFO = new OpcodeInfo.Info[65537];
    set(SPECIAL_FORMAT);
    set(PACKED_SWITCH_PAYLOAD);
    set(SPARSE_SWITCH_PAYLOAD);
    set(FILL_ARRAY_DATA_PAYLOAD);
    set(NOP);
    set(MOVE);
    set(MOVE_FROM16);
    set(MOVE_16);
    set(MOVE_WIDE);
    set(MOVE_WIDE_FROM16);
    set(MOVE_WIDE_16);
    set(MOVE_OBJECT);
    set(MOVE_OBJECT_FROM16);
    set(MOVE_OBJECT_16);
    set(MOVE_RESULT);
    set(MOVE_RESULT_WIDE);
    set(MOVE_RESULT_OBJECT);
    set(MOVE_EXCEPTION);
    set(RETURN_VOID);
    set(RETURN);
    set(RETURN_WIDE);
    set(RETURN_OBJECT);
    set(CONST_4);
    set(CONST_16);
    set(CONST);
    set(CONST_HIGH16);
    set(CONST_WIDE_16);
    set(CONST_WIDE_32);
    set(CONST_WIDE);
    set(CONST_WIDE_HIGH16);
    set(CONST_STRING);
    set(CONST_STRING_JUMBO);
    set(CONST_CLASS);
    set(MONITOR_ENTER);
    set(MONITOR_EXIT);
    set(CHECK_CAST);
    set(INSTANCE_OF);
    set(ARRAY_LENGTH);
    set(NEW_INSTANCE);
    set(NEW_ARRAY);
    set(FILLED_NEW_ARRAY);
    set(FILLED_NEW_ARRAY_RANGE);
    set(FILL_ARRAY_DATA);
    set(THROW);
    set(GOTO);
    set(GOTO_16);
    set(GOTO_32);
    set(PACKED_SWITCH);
    set(SPARSE_SWITCH);
    set(CMPL_FLOAT);
    set(CMPG_FLOAT);
    set(CMPL_DOUBLE);
    set(CMPG_DOUBLE);
    set(CMP_LONG);
    set(IF_EQ);
    set(IF_NE);
    set(IF_LT);
    set(IF_GE);
    set(IF_GT);
    set(IF_LE);
    set(IF_EQZ);
    set(IF_NEZ);
    set(IF_LTZ);
    set(IF_GEZ);
    set(IF_GTZ);
    set(IF_LEZ);
    set(AGET);
    set(AGET_WIDE);
    set(AGET_OBJECT);
    set(AGET_BOOLEAN);
    set(AGET_BYTE);
    set(AGET_CHAR);
    set(AGET_SHORT);
    set(APUT);
    set(APUT_WIDE);
    set(APUT_OBJECT);
    set(APUT_BOOLEAN);
    set(APUT_BYTE);
    set(APUT_CHAR);
    set(APUT_SHORT);
    set(IGET);
    set(IGET_WIDE);
    set(IGET_OBJECT);
    set(IGET_BOOLEAN);
    set(IGET_BYTE);
    set(IGET_CHAR);
    set(IGET_SHORT);
    set(IPUT);
    set(IPUT_WIDE);
    set(IPUT_OBJECT);
    set(IPUT_BOOLEAN);
    set(IPUT_BYTE);
    set(IPUT_CHAR);
    set(IPUT_SHORT);
    set(SGET);
    set(SGET_WIDE);
    set(SGET_OBJECT);
    set(SGET_BOOLEAN);
    set(SGET_BYTE);
    set(SGET_CHAR);
    set(SGET_SHORT);
    set(SPUT);
    set(SPUT_WIDE);
    set(SPUT_OBJECT);
    set(SPUT_BOOLEAN);
    set(SPUT_BYTE);
    set(SPUT_CHAR);
    set(SPUT_SHORT);
    set(INVOKE_VIRTUAL);
    set(INVOKE_SUPER);
    set(INVOKE_DIRECT);
    set(INVOKE_STATIC);
    set(INVOKE_INTERFACE);
    set(INVOKE_VIRTUAL_RANGE);
    set(INVOKE_SUPER_RANGE);
    set(INVOKE_DIRECT_RANGE);
    set(INVOKE_STATIC_RANGE);
    set(INVOKE_INTERFACE_RANGE);
    set(NEG_INT);
    set(NOT_INT);
    set(NEG_LONG);
    set(NOT_LONG);
    set(NEG_FLOAT);
    set(NEG_DOUBLE);
    set(INT_TO_LONG);
    set(INT_TO_FLOAT);
    set(INT_TO_DOUBLE);
    set(LONG_TO_INT);
    set(LONG_TO_FLOAT);
    set(LONG_TO_DOUBLE);
    set(FLOAT_TO_INT);
    set(FLOAT_TO_LONG);
    set(FLOAT_TO_DOUBLE);
    set(DOUBLE_TO_INT);
    set(DOUBLE_TO_LONG);
    set(DOUBLE_TO_FLOAT);
    set(INT_TO_BYTE);
    set(INT_TO_CHAR);
    set(INT_TO_SHORT);
    set(ADD_INT);
    set(SUB_INT);
    set(MUL_INT);
    set(DIV_INT);
    set(REM_INT);
    set(AND_INT);
    set(OR_INT);
    set(XOR_INT);
    set(SHL_INT);
    set(SHR_INT);
    set(USHR_INT);
    set(ADD_LONG);
    set(SUB_LONG);
    set(MUL_LONG);
    set(DIV_LONG);
    set(REM_LONG);
    set(AND_LONG);
    set(OR_LONG);
    set(XOR_LONG);
    set(SHL_LONG);
    set(SHR_LONG);
    set(USHR_LONG);
    set(ADD_FLOAT);
    set(SUB_FLOAT);
    set(MUL_FLOAT);
    set(DIV_FLOAT);
    set(REM_FLOAT);
    set(ADD_DOUBLE);
    set(SUB_DOUBLE);
    set(MUL_DOUBLE);
    set(DIV_DOUBLE);
    set(REM_DOUBLE);
    set(ADD_INT_2ADDR);
    set(SUB_INT_2ADDR);
    set(MUL_INT_2ADDR);
    set(DIV_INT_2ADDR);
    set(REM_INT_2ADDR);
    set(AND_INT_2ADDR);
    set(OR_INT_2ADDR);
    set(XOR_INT_2ADDR);
    set(SHL_INT_2ADDR);
    set(SHR_INT_2ADDR);
    set(USHR_INT_2ADDR);
    set(ADD_LONG_2ADDR);
    set(SUB_LONG_2ADDR);
    set(MUL_LONG_2ADDR);
    set(DIV_LONG_2ADDR);
    set(REM_LONG_2ADDR);
    set(AND_LONG_2ADDR);
    set(OR_LONG_2ADDR);
    set(XOR_LONG_2ADDR);
    set(SHL_LONG_2ADDR);
    set(SHR_LONG_2ADDR);
    set(USHR_LONG_2ADDR);
    set(ADD_FLOAT_2ADDR);
    set(SUB_FLOAT_2ADDR);
    set(MUL_FLOAT_2ADDR);
    set(DIV_FLOAT_2ADDR);
    set(REM_FLOAT_2ADDR);
    set(ADD_DOUBLE_2ADDR);
    set(SUB_DOUBLE_2ADDR);
    set(MUL_DOUBLE_2ADDR);
    set(DIV_DOUBLE_2ADDR);
    set(REM_DOUBLE_2ADDR);
    set(ADD_INT_LIT16);
    set(RSUB_INT);
    set(MUL_INT_LIT16);
    set(DIV_INT_LIT16);
    set(REM_INT_LIT16);
    set(AND_INT_LIT16);
    set(OR_INT_LIT16);
    set(XOR_INT_LIT16);
    set(ADD_INT_LIT8);
    set(RSUB_INT_LIT8);
    set(MUL_INT_LIT8);
    set(DIV_INT_LIT8);
    set(REM_INT_LIT8);
    set(AND_INT_LIT8);
    set(OR_INT_LIT8);
    set(XOR_INT_LIT8);
    set(SHL_INT_LIT8);
    set(SHR_INT_LIT8);
    set(USHR_INT_LIT8);
  }
  
  public static OpcodeInfo.Info get(int paramInt)
  {
    try
    {
      OpcodeInfo.Info localInfo = INFO[(paramInt + 1)];
      if (localInfo != null) {
        return localInfo;
      }
    }
    catch (ArrayIndexOutOfBoundsException localArrayIndexOutOfBoundsException)
    {
      throw new IllegalArgumentException("bogus opcode: " + Hex.u2or4(paramInt));
    }
  }
  
  public static InstructionCodec getFormat(int paramInt)
  {
    return get(paramInt).getFormat();
  }
  
  public static IndexType getIndexType(int paramInt)
  {
    return get(paramInt).getIndexType();
  }
  
  public static String getName(int paramInt)
  {
    return get(paramInt).getName();
  }
  
  private static void set(OpcodeInfo.Info paramInfo)
  {
    int i = paramInfo.getOpcode();
    INFO[(i + 1)] = paramInfo;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mobileqq\classes6.jar
 * Qualified Name:     com.android.dx.io.OpcodeInfo
 * JD-Core Version:    0.7.0.1
 */