package com.tencent.liteav.basic.datareport;

public class a
{
  public static String A;
  public static String B;
  public static String C;
  public static int D;
  public static int E;
  public static int F;
  public static int G;
  public static int H;
  public static int I;
  public static int J;
  public static int K;
  public static int L;
  public static int M;
  public static int N;
  public static int O;
  public static int P;
  public static int Q;
  public static int R;
  public static int S;
  public static int T;
  public static int U;
  public static int V;
  public static int W;
  public static int X;
  public static int Y;
  public static int Z;
  public static String a = "u32_module_id";
  public static int aA;
  public static int aB;
  public static int aC;
  public static int aD;
  public static int aE;
  public static int aF;
  public static int aG;
  public static int aH;
  public static int aI;
  public static int aJ;
  public static int aK;
  public static int aL;
  public static int aM;
  public static int aN;
  public static int aO;
  public static int aP;
  public static int aQ;
  public static int aR;
  public static int aS;
  public static int aT;
  public static int aU;
  public static int aV;
  public static int aW;
  public static int aX;
  public static int aY;
  public static int aZ;
  public static int aa;
  public static int ab;
  public static int ac;
  public static int ad;
  public static int ae;
  public static int af;
  public static int ag;
  public static int ah;
  public static int ai;
  public static int aj;
  public static int ak;
  public static int al;
  public static int am;
  public static int an;
  public static int ao;
  public static int ap;
  public static int aq;
  public static int ar;
  public static int as;
  public static int at;
  public static int au;
  public static int av;
  public static int aw;
  public static int ax;
  public static int ay;
  public static int az;
  public static String b = "str_stream_url";
  public static int bA = 1552;
  public static int bB = 1553;
  public static int bC = 1554;
  public static int bD = 1555;
  public static int bE = 1556;
  public static int bF = 1557;
  public static int bG = 1601;
  public static int bH = 1602;
  public static int bI = 1603;
  public static int bJ = 1;
  public static int bK = 1;
  public static int bL = 2;
  public static int bM = 3;
  public static int ba;
  public static int bb;
  public static int bc;
  public static int bd;
  public static int be;
  public static int bf;
  public static int bg;
  public static int bh;
  public static int bi;
  public static int bj;
  public static int bk;
  public static int bl;
  public static int bm;
  public static int bn;
  public static int bo;
  public static int bp;
  public static int bq;
  public static int br;
  public static int bs;
  public static int bt;
  public static int bu;
  public static int bv;
  public static int bw;
  public static int bx;
  public static int by;
  public static int bz;
  public static String c = "platform";
  public static String d = "biz_id";
  public static String e = "app_id";
  public static String f = "dev_type";
  public static String g = "net_type";
  public static String h = "dev_id";
  public static String i = "dev_uuid";
  public static String j = "app_name";
  public static String k = "app_version";
  public static String l = "sys_version";
  public static String m = "mac_addr";
  public static String n = "evt_comm";
  public static String o = "event_id";
  public static String p = "err_code";
  public static String q = "err_info";
  public static String r = "ext";
  public static String s = "event_id";
  public static String t = "err_code";
  public static String u = "err_info";
  public static String v = "file_size";
  public static String w = "up_usetime";
  public static String x = "up_ip";
  public static String y = "ugc_upload";
  public static String z = "DAU";
  
  static
  {
    A = "u32_error_code";
    B = "str_error_msg";
    C = "str_msg_more";
    D = 1000;
    E = 1001;
    F = 1002;
    G = 2001;
    H = 2002;
    I = 2003;
    J = 2004;
    K = 2005;
    L = 2006;
    M = 2007;
    N = 2008;
    O = 2009;
    P = 40001;
    Q = 40000;
    R = 40002;
    S = 40003;
    T = 40005;
    U = 40101;
    V = 40100;
    W = 40102;
    X = 40501;
    Y = 40500;
    Z = 40502;
    aa = 40201;
    ab = 40200;
    ac = 40202;
    ad = 40301;
    ae = 40302;
    af = 40401;
    ag = 40402;
    ah = 49999;
    ai = 1000;
    aj = 1001;
    ak = 1002;
    al = 1003;
    am = 1004;
    an = 1005;
    ao = 1006;
    ap = 1007;
    aq = 1008;
    ar = 1009;
    as = 1010;
    at = 1011;
    au = 1001;
    av = 1002;
    aw = 1003;
    ax = 1004;
    ay = 1005;
    az = 1006;
    aA = 1007;
    aB = 1008;
    aC = 1009;
    aD = 1010;
    aE = 1011;
    aF = 1012;
    aG = 1013;
    aH = 1014;
    aI = 1015;
    aJ = 1016;
    aK = 1017;
    aL = 1018;
    aM = 1019;
    aN = 1020;
    aO = 1021;
    aP = 1022;
    aQ = 1023;
    aR = 1024;
    aS = 1025;
    aT = 1026;
    aU = 1027;
    aV = 1028;
    aW = 1029;
    aX = 1030;
    aY = 1031;
    aZ = 1032;
    ba = 1033;
    bb = 1034;
    bc = 1041;
    bd = 1042;
    be = 1043;
    bf = 1044;
    bg = 1045;
    bh = 1046;
    bi = 1047;
    bj = 1048;
    bk = 1049;
    bl = 1050;
    bm = 1051;
    bn = 1052;
    bo = 1053;
    bp = 1054;
    bq = 1055;
    br = 1056;
    bs = 1099;
    bt = 1997;
    bu = 1998;
    bv = 1999;
    bw = 1301;
    bx = 1501;
    by = 1502;
    bz = 1551;
  }
}


/* Location:           L:\local\mybackup\temp\qq_apk\com.tencent.mm\classes7.jar
 * Qualified Name:     com.tencent.liteav.basic.datareport.a
 * JD-Core Version:    0.7.0.1
 */